### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by tanaka-jp** [OpenNMT/OpenNMT-py#1003]
I got this error when I run the Example of Summarization.
    http://opennmt.net/OpenNMT-py/Summarization.html

python preprocess.py -train_src data/cnndm/train.txt.src -train_tgt data/cnndm/train.txt.tgt -valid_src data/cnndm/val.txt.src -valid_tgt data/cnndm/val.txt.tgt -save_data data/cnndm/CNNDM -src_seq_length 10000 -tgt_seq_length 10000 -src_seq_length_trunc 400 -tgt_seq_length_trunc 100 -dynamic_dict -share_vocab -max_shard_size 10485760

python train.py -data data/cnndm/CNNDM -save_model models/cnndm -layers 3 -rnn_size 8 -word_vec_size 8 -max_grad_norm 0 -optim adam -encoder_type transformer -decoder_type transformer -position_encoding -dropout 0.1 -param_init 0 -warmup_steps 8000 -learning_rate 2 -decay_method noam -label_smoothing 0.1 -adam_beta2 0.998 -batch_size 2 -batch_type tokens -normalization tokens -max_generator_batches 2 -train_steps=10000 -valid_steps=100000 -save_checkpoint_steps=2000 -accum_count 2 -share_embeddings -param_init_glorot

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.1\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.1\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.1\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/workspace_aa/train.py", line 40, in <module>
    main(opt)
  File "C:/workspace_aa/train.py", line 27, in main
    single_main(opt)
  File "C:\workspace_aa\onmt\train_single.py", line 147, in main
    opt.valid_steps)
  File "C:\workspace_aa\onmt\trainer.py", line 143, in train
    for i, batch in enumerate(train_iter):
  File "C:\workspace_aa\onmt\inputters\inputter.py", line 432, in __iter__
    for batch in self.cur_iter:
  File "C:\Anaconda3_5_2\lib\site-packages\torchtext\data\iterator.py", line 157, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "C:\Anaconda3_5_2\lib\site-packages\torchtext\data\batch.py", line 34, in __init__
    setattr(self, name, field.process(batch, device=device))
  File "C:\Anaconda3_5_2\lib\site-packages\torchtext\data\field.py", line 200, in process
    padded = self.pad(batch)
  File "C:\Anaconda3_5_2\lib\site-packages\torchtext\data\field.py", line 218, in pad
    max_len = max(len(x) for x in minibatch)
ValueError: max() arg is an empty sequence

I tried OpenNmt0.2 and OpenNmt0.2.1.
Is it the problem of CNNDM dataset ?

**Comment by tanaka-jp** [comment]
https://github.com/OpenNMT/OpenNMT-py/blob/e723f2aa70edb6920c0f0fe311b19aff0dcdf552/onmt/inputters/inputter.py#L393-L394

I found where this error comes from.
When len(b) == 0, it occurs. 

Is it a bug ?

**Comment by vince62s** [comment]
What version of torchtext do you have ? I can't replicate.

**Comment by tanaka-jp** [comment]
torch 0.4.0
torchtext  0.4.0

I installed torchtext by "pip install git+https://github.com/pytorch/text"
I am using Windows 7 (Japanese)

**Comment by vince62s** [comment]
Can you please pull to be on master and reprocess. use the shard_size option (number of ex) instead of the max_shard_size which is deprecated.
thanks. I don't have a windows set up so it will be difficult for me to replicate.

**Comment by tanaka-jp** [comment]
I tried the master version.
The preprocess used all of the PC memory , and my PC freezed.
So I just ran the train command by the preprocess result which created by OpenNmt 0.2.

python train.py -data data/cnndm/CNNDM -save_model models/cnndm -layers 3 -rnn_size 8 -word_vec_size 8 -max_grad_norm 0 -optim adam -encoder_type transformer -decoder_type transformer -position_encoding -dropout 0.1 -param_init 0 -warmup_steps 8000 -learning_rate 2 -decay_method noam -label_smoothing 0.1 -adam_beta2 0.998 -batch_size 2 -batch_type tokens -normalization tokens -max_generator_batches 2 -train_steps=10000 -valid_steps=100000 -save_checkpoint_steps=2000 -accum_count 2 -share_embeddings -param_init_glorot


[2018-10-29 11:43:05,440 INFO] encoder: 505480
[2018-10-29 11:43:05,440 INFO] decoder: 556396
[2018-10-29 11:43:05,440 INFO] * number of parameters: 1061876
[2018-10-29 11:43:05,469 INFO] Start training...
[2018-10-29 11:43:05,617 INFO] Loading train dataset from data/cnndm\CNNDM.train
.1.pt, number of examples: 2803
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    main(opt)
  File "train.py", line 53, in main
    single_main(opt, -1)
  File "C:\tmp\test_opennmt_master\OpenNMT-py-master\onmt\train_single.py", line
 141, in main
    opt.valid_steps)
  File "C:\tmp\test_opennmt_master\OpenNMT-py-master\onmt\trainer.py", line 148,
 in train
    for i, batch in enumerate(train_iter):
  File "C:\tmp\test_opennmt_master\OpenNMT-py-master\onmt\inputters\inputter.py"
, line 463, in __iter__
    for batch in self.cur_iter:
  File "C:\Anaconda3_5_2\lib\site-packages\torchtext\data\iterator.py", line 156
, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "C:\Anaconda3_5_2\lib\site-packages\torchtext\data\batch.py", line 34, in
 __init__
    setattr(self, name, field.process(batch, device=device))
  File "C:\Anaconda3_5_2\lib\site-packages\torchtext\data\field.py", line 236, i
n process
    padded = self.pad(batch)
  File "C:\Anaconda3_5_2\lib\site-packages\torchtext\data\field.py", line 254, i
n pad
    max_len = max(len(x) for x in minibatch)

ValueError: max() arg is an empty sequence

**Comment by tanaka-jp** [comment]
I added this modify to the inputter.py and it workes.
if len(b) == 0: continue

https://github.com/OpenNMT/OpenNMT-py/blob/e723f2aa70edb6920c0f0fe311b19aff0dcdf552/onmt/inputters/inputter.py#L393-L394

**Comment by vince62s** [comment]
What shard_size did you use to go OOM ? does not make sense, use -shard_size 1000000 or less if you don't have much memory.

**Comment by tanaka-jp** [comment]
I tried this command in which the shard_size is only 262144 (1024*256).
But nothing changed .
I stopped it when it used the memory over 9GB.

python preprocess.py -train_src data/cnndm/train.txt.src -train_tgt data/cnndm/train.txt.tgt -valid_src data/cnndm/val.txt.src -valid_tgt data/cnndm/val.txt.tgt -save_data data/cnndm/CNNDM -src_seq_length 10000 -tgt_seq_length 10000 -src_seq_length_trunc 400 -tgt_seq_length_trunc 100 -dynamic_dict -share_vocab -shard_size 262144

**Comment by vince62s** [comment]
what is the RAM size of your computer ?

**Comment by tanaka-jp** [comment]
12GB.

**Comment by vince62s** [comment]
wow you won't go very far with this. Maybe try with a shard_size of 10000 instead.

**Comment by worksking** [comment]
> I added this modify to the inputter.py and it workes.
> if len(b) == 0: continue
> 
> [OpenNMT-py/onmt/inputters/inputter.py](https://github.com/OpenNMT/OpenNMT-py/blob/e723f2aa70edb6920c0f0fe311b19aff0dcdf552/onmt/inputters/inputter.py#L393-L394)
> 
> Lines 393 to 394 in [e723f2a](/OpenNMT/OpenNMT-py/commit/e723f2aa70edb6920c0f0fe311b19aff0dcdf552)
> 
>  for b in random_shuffler(list(p_batch)): 
>      yield b

you means your code is 👍
    for b in random_shuffler(list(p_batch)): 
            if (len(b)) == 0:
               continue
            else : 
                yield b


>      yield b

**Comment by lipingbj** [comment]
I found it is the problem that you set the batch_size =2 and batch_type=tokens.The batch_size should be 4096 or some values are bigger enough.The same error occurs when i set the batch_size=32 and batch_type=tokens.

**Comment by lipingbj** [comment]
I found it is the problem that you set the batch_size =2 and batch_type=tokens.The batch_size should be 4096 or some values is bigger enough.The same error occurs when i set the batch_size=32 and batch_type=tokens.

**Comment by lipingbj** [comment]
I found it is the problem that you set the batch_size =2 and batch_type=tokens.The batch_size should be 4096 or some values are bigger enough.The same error occurs when i set the batch_size=32 and batch_type=tokens.
