### ISSUE TITLE
RuntimeError: cuda runtime error (59) during translation

### ISSUE THREAD

**Issue by Sumith1896** [OpenNMT/OpenNMT-py#1008]
Trained a basic seq2seq model with the copying mechanism flags on and received the following runtime error while translating tests. Same params without copying mechanism successfully translated the test source. Any help?

```
Traceback (most recent call last):
  File "translate.py", line 36, in <module>
    main(opt)
  File "translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 222, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 326, in translate_batch
    return self._translate_batch(batch, data)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 627, in _translate_batch
    beam_attn.data[:, j, :memory_lengths[j]])
  File "/home/users/sumith/OpenNMT-py/onmt/translate/beam.py", line 142, in advance
    if self.next_ys[-1][i] == self._eos:
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCStorage.cpp:36
```

**Comment by vince62s** [comment]
please post you train command and the translate command you used.

**Comment by Sumith1896** [comment]
Preprocess:
```
python preprocess.py -train_src /scratch/users/sumith/naps/trainA-full/naps.trainA.1.0.jsonl-src-train.txt -train_tgt /scratch/users/sumith/naps/trainA-full/naps.trainA.1.0.jsonl-tgt-train.txt -valid_src /scratch/users/sumith/naps/trainA-full/naps.trainA.1.0.jsonl-src-val.txt -valid_tgt /scratch/users/sumith/naps/trainA-full/naps.trainA.1.0.jsonl-tgt-val.txt -src_seq_length 1000 -tgt_seq_length 1000  -save_data /scratch/users/sumith/naps/trainA-full/trainA -dynamic_dict
```

Train:
```
python train.py -data /scratch/users/sumith/naps/trainA-full/trainA -save_model ftrainA-model -world_size 2 -gpu_ranks 0 1 -save_checkpoint_steps 1000 -valid_steps 30000 -train_steps 10000 -copy_attn -copy_attn_force
```

Translate:
```
python translate.py -model ftrainA-model_step_25000.pt -src /scratch/users/sumith/naps/test/naps.test.1.0.jsonl-src-test.txt -output /scratch/users/sumith/naps/test/trainA-pred.txt -max_length 1000 -replace_unk -verbose -gpu 1
```

Also I didn't want to incorporate any validation set, hence passed empty files as validation files and also set the validation step a value that's not attained, let me know if there is a better way or this is the source of the problem (I'm hoping it's not)

**Comment by vince62s** [comment]
I have never seen this error.
Since a CUDA error and this is asynchronous, you have to run it again while prefixing with
CUDA_LAUNCH_BLOCKING=1
Then it may trigger the error at another step in trace.

also try to reduce the batch_size to 8

**Comment by Sumith1896** [comment]
```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCTensorCopy.cu line=102 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "../translate.py", line 36, in <module>
    main(opt)
  File "../translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 222, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 326, in translate_batch
    return self._translate_batch(batch, data)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 627, in _translate_batch
    beam_attn.data[:, j, :memory_lengths[j]])
  File "/home/users/sumith/OpenNMT-py/onmt/translate/beam.py", line 139, in advance
    self.global_scorer.update_global_state(self)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/beam.py", line 231, in update_global_state
    beam.global_state["prev_penalty"] = beam.scores.clone().fill_(0.0)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/THCTensorCopy.cu:102
```
on prefixing with CUDA_LAUNCH_BLOCKING=1 (I don't still understand).

Will try reducing the batch size too!

**Comment by Sumith1896** [comment]
On the latest master (line numbers dont match in the above logs):
```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCTensorCopy.cu line=102 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "../../../translate.py", line 36, in <module>
    main(opt)
  File "../../../translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 222, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 326, in translate_batch
    return self._translate_batch(batch, data)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 642, in _translate_batch
    beam_attn.data[:, j, :memory_lengths[j]])
  File "/home/users/sumith/OpenNMT-py/onmt/translate/beam.py", line 139, in advance
    self.global_scorer.update_global_state(self)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/beam.py", line 231, in update_global_state
    beam.global_state["prev_penalty"] = beam.scores.clone().fill_(0.0)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/THCTensorCopy.cu:102
```

**Comment by Sumith1896** [comment]
Removing `-gpu 1` eliminates this error and translation starts! (the translation however is not good, that may be a mistake from my side). Any clue what's happening?

**Comment by vince62s** [comment]
You need to use -gpu 0 for translationg on gpu otherwise it may be slow on cpu
Results depend on lots of things, you may have too little data and trained not enough steps.

**Comment by fuzihaofzh** [comment]
I also encountered this problem. Just leave some hint for those who need it. 
After some debugging. I found that this problem is caused by that the lengths for src in rnn_encoder.py is conflict with the exact length for each sentence in emb. This is caused by some of my own operation. So, please check that the lengths is correct.
