### ISSUE TITLE
result = unpickler.load() No module named 'onmt.inputters'

### ISSUE THREAD

**Issue by ZhengDeQuan** [OpenNMT/OpenNMT-py#1011]
python3.6 
torch0.4.1
torchtext0.3.1
when I run the train.py with the following command
python seq2seq/train.py -data data/seq2seq-h2 -save_model seq2seq_models/seq2seq -word_vec_size 300 -pre_word_vecs_enc data/seq2seq-h2.embed.enc.pt -pre_word_vecs_dec data/seq2seq-h2.embed.dec.pt -epochs 50 -gpuid 0 -seed 123

error occurs:
Traceback (most recent call last):
  File "seq2seq/train.py", line 514, in <module>
    main()
  File "seq2seq/train.py", line 488, in main
    first_dataset = next(lazily_load_dataset("train"))
  File "seq2seq/train.py", line 337, in lazily_load_dataset
    yield lazy_dataset_loader(pt, corpus_type)
  File "seq2seq/train.py", line 328, in lazy_dataset_loader
    dataset = torch.load(pt_file)
  File "/home/zhengquan/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/zhengquan/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'onmt.inputters'

**Comment by MiladAlshomary** [comment]
Have you solved this issue? I am facing the same error

**Comment by sajastu** [comment]
Any solution? I'm having this problem when trying to evaluate the Bottom-Up  summarization model: https://github.com/sebastianGehrmann/OpenNMT-py/tree/copy_constraint

**Comment by vince62s** [comment]
update torchtext as in the requirements

**Comment by juxinchenggithub** [comment]
I have the same problem ,how can  I solve the problem
