### ISSUE TITLE
Self attention is not working with GPU

### ISSUE THREAD

**Issue by himanshudce** [OpenNMT/OpenNMT-py#1042]
I tried training the the transformer model on GPU but it starts training on CPU please resolve the problem
I used this to train
CUDA_VISIBLE_DEVICES=0 python train.py -data finaldata/BPE/enta -save_model finaldata/new -gpuid 0                                        \
    -encoder_type transformer -decoder_type transformer                                                \
    -layers 4 -rnn_size 1024  -word_vec_size 1024                                                      \
    -max_grad_norm 0 -optim adam -position_encoding -dropout 0.2 -param_init 0                         \
    -batch_size 32 -report_every 100 -warmup_steps 4000 -learning_rate 1 -decay_method noam \

**Comment by Sumith1896** [comment]
Could you use `-world_size 1 -gpu_ranks 0` instead of `-gpuid 0` and check if it works? 

List of all options here: http://opennmt.net/OpenNMT-py/options/train.html

**Comment by himanshudce** [comment]
Hi, thank you for reply.
But when i am using ( -world_size 1 -gpu_ranks 0 ) this instead of gupid 0 i got cuda error
RuntimeError: CUDA error: out of memory
what should i do ?

**Comment by Sumith1896** [comment]
Can you post the commands and the log?

**Comment by himanshudce** [comment]
(myenv) aditya@falcon:~/selfattn/OpenNMT-py$ CUDA_VISIBLE_DEVICES=0 python train.py -data finaldata/BPE/enta -save_model finaldata/new -gpu_ranks 0 -world_size 1 -encoder_type transformer -decoder_type transformer -layers 2 -rnn_size 512 -word_vec_size 512 -max_grad_norm 0 -optim adam -position_encoding -dropout 0.2 -param_init 0 -batch_size 32 -report_every 100 -learning_rate 1 -decay_method noam
[2018-11-07 10:41:54,185 INFO] Loading train dataset from finaldata/BPE/enta.train.0.pt, number of examples: 176693
[2018-11-07 10:41:54,258 INFO]  * vocabulary size. source = 23954; target = 25108
[2018-11-07 10:41:54,258 INFO] Building model...
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    main(opt)
  File "train.py", line 51, in main
    single_main(opt, 0)
  File "/home/aditya/selfattn/OpenNMT-py/onmt/train_single.py", line 117, in main
    model = build_model(model_opt, opt, fields, checkpoint)
  File "/home/aditya/selfattn/OpenNMT-py/onmt/model_builder.py", line 273, in build_model
    use_gpu(opt), checkpoint)
  File "/home/aditya/selfattn/OpenNMT-py/onmt/model_builder.py", line 264, in build_base_model
    model.to(device)
  File "/home/aditya/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 379, in to
    return self._apply(convert)
  File "/home/aditya/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/aditya/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/aditya/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/aditya/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home/aditya/anaconda3/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 377, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: out of memory

this is what i got

**Comment by vince62s** [comment]
There could be many reason for this, depending on the RAM of your GPU.
you need to control your sequence length when using sentence batch, or switch to token batch and then you'll control the memory better.

**Comment by himanshudce** [comment]
Hi,
      I have enough Memory and RAM to train any model, is there any other reason that can be possible, I have also tried on different Systems, It is training on CPU without error but always giving an error on GPU. 
Is there any other method/change in code to use transformer model with GPU that someone tried.
please suggest.

Also what is this error 
https://github.com/OpenNMT/OpenNMT-py/issues/237   

thankyou

**Comment by vince62s** [comment]
Just use this command line here and post the log
https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md

**Comment by himanshudce** [comment]
Hi vince,
      Simply using gpu_ranks 0 worked for me, as given in this https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md , Thank you for all your help.
