### ISSUE TITLE
[Help  Wanted] python3 -m unittest discover failing with pytorch 1.0

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT-py#1055]
If someone has time to dig, when using Pytorch 1.0 nightly, the unittest discover fails with this error.
Thanks.
NB: All other adhoc tests are fine (which is disturbing ....)

======================================================================
ERROR: test_nmtmodel_forward_[('layers',_10)] (onmt.tests.test_models.TestModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/tests/test_models.py", line 242, in test_method
    getattr(self, methodname)(opt)
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/tests/test_models.py", line 144, in nmtmodel_forward
    outputs, attn = model(test_src, test_tgt, test_length)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/models/model.py", line 43, in forward
    enc_state, memory_bank, lengths = self.encoder(src, lengths)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/encoders/rnn_encoder.py", line 66, in forward
    memory_bank, encoder_final = self.rnn(packed_emb)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/rnn.py", line 182, in forward
    self.num_layers, self.dropout, self.training, self.bidirectional)
TypeError: lstm() received an invalid combination of arguments - got (Tensor, Tensor, tuple, list, bool, int, float, bool, NoneType), but expected one of:
 * (Tensor data, Tensor batch_sizes, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, tuple, list, bool, int, float, bool, NoneType)
 * (Tensor input, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, tuple, list, bool, int, float, bool, NoneType)

**Comment by vince62s** [comment]
#1105
