### ISSUE TITLE
TRuntimeError: invalid argument 1: tensor must have one dimension at /opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/TH/generic/THTensorMath.c:733

### ISSUE THREAD

**Issue by Ticman** [OpenNMT/OpenNMT-py#1074]
Hi ! I've got this error while translating. Can somebody help me to fix it ?

**Comment by vince62s** [comment]
you need to post more info.
pytorch version, python version, onmt-py master ?
command lien and if opssible a bit more context on your preprocess and training.
full trace also.

**Comment by Ticman** [comment]
Ok, Here the full trace :

Traceback (most recent call last):
  File "translate.py", line 36, in <module>
    main(opt)
  File "translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/home/jopo/OpenNMT-py/onmt/translate/translator.py", line 221, in translate
    for batch in data_iter:
  File "/home/jopo/anaconda3/lib/python3.6/site-packages/torchtext/data/iterator.py", line 156, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "/home/jopo/anaconda3/lib/python3.6/site-packages/torchtext/data/batch.py", line 34, in __init__
    setattr(self, name, field.process(batch, device=device))
  File "/home/jopo/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py", line 201, in process
    tensor = self.numericalize(padded, device=device)
  File "/home/jopo/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py", line 321, in numericalize
    arr = self.postprocessing(arr, None)
  File "/home/jopo/OpenNMT-py/onmt/inputters/text_dataset.py", line 235, in make_src
    src_vocab_size = max([t.max() for t in data]) + 1
  File "/home/jopo/OpenNMT-py/onmt/inputters/text_dataset.py", line 235, in <listcomp>
    src_vocab_size = max([t.max() for t in data]) + 1
RuntimeError: invalid argument 1: tensor must have one dimension at /opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/TH/generic/THTensorMath.c:733

**Comment by vince62s** [comment]
you don't give version of pytorch torchtext and so on

**Comment by Ticman** [comment]
pytorch 0.4.0
torchtext ?? How do see the version

**Comment by vince62s** [comment]
read the home
https://github.com/OpenNMT/OpenNMT-py

**Comment by shahbazsyed** [comment]
@Ticman Also, check for empty lines in your files.

**Comment by vince62s** [comment]
reopen if needed.
