### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'model'

### ISSUE THREAD

**Issue by shirishr** [OpenNMT/OpenNMT-py#1087]
When I run python translate.py for image translation as

`python translate.py -data_type img -model py-model.pt -src_dir data/im2text/images  -src data/im2text/src-test.txt -output pred.txt -max_length 150 -beam_size 5 -gpu 0 -verbose`

I get this error:

Traceback (most recent call last):
  File "translate.py", line 33, in <module>
    main(opt)
  File "translate.py", line 20, in main
    translator = make_translator(opt, report_score=True)
  File "/home/sam/Documents/NLP/OpenNMT-py/onmt/translate/Translator.py", line 28, in make_translator
    onmt.ModelConstructor.load_test_model(opt, dummy_opt.__dict__)
  File "/home/sam/Documents/NLP/OpenNMT-py/onmt/ModelConstructor.py", line 118, in load_test_model
    checkpoint = torch.load(opt.model,
AttributeError: 'Namespace' object has no attribute 'model'

**Comment by shirishr** [comment]
@vince62s 
Thank you sir. I was sure I had done a git pull. But maybe not.

**Comment by eduamf** [comment]
I'm using the version 0.6 (the last one compatible with pytorch 0.4.1) and received the same error.
