### ISSUE TITLE
Conv2conv out of memory at validation time

### ISSUE THREAD

**Issue by ZeweiChu** [OpenNMT/OpenNMT-py#1089]
Here is the script I used. 

For preprocessing: 
```python ../OpenNMT-py/preprocess.py -train_src "$INPUT_FILENAME".train.src.txt -train_tgt "$INPUT_FILENAME".train.tgt.txt -valid_src "$INPUT_FILENAME".valid.src.txt -valid_tgt "$INPUT_FILENAME".valid.tgt.txt -save_data data.share -share_vocab -src_seq_length_trunc 500 -src_seq_length 50000 -tgt_seq_length 50000```

For training:
```python ../OpenNMT-py/train.py -data data.share -save_model $MODEL_NAME/model -world_size 1 -gpu_ranks 0 -global_attention general -batch_size 8 -encoder_type cnn -decoder_type cnn -enc_layers 7 -dec_layers 3 -cnn_kernel_width 5 -optim adam -learning_rate 0.001 -start_decay_steps 10000 -decay_steps 5000 -share_embeddings -save_checkpoint_steps 10000```

At 10000 steps:

> [2018-12-03 09:28:41,180 INFO] Loading valid dataset from data.share.valid.0.pt, number of examples: 5200
> Traceback (most recent call last):
>   File "../OpenNMT-py/train.py", line 120, in <module>
>     main(opt)
>   File "../OpenNMT-py/train.py", line 51, in main
>     single_main(opt, 0)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/train_single.py", line 154, in main
>     opt.valid_steps)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/trainer.py", line 190, in train
>     valid_stats = self.validate(valid_iter)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/trainer.py", line 236, in validate
>     outputs, attns = self.model(src, tgt, src_lengths)
>   File "/home/yijingxiao/dev/anaconda3/envs/py37-torch-0.4.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/models/model.py", line 43, in forward
>     enc_state, memory_bank, lengths = self.encoder(src, lengths)
>   File "/home/yijingxiao/dev/anaconda3/envs/py37-torch-0.4.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/encoders/cnn_encoder.py", line 40, in forward
>     out = self.cnn(emb_remap)
>   File "/home/yijingxiao/dev/anaconda3/envs/py37-torch-0.4.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/utils/cnn_factory.py", line 52, in forward
>     x = x + conv(x)
>   File "/home/yijingxiao/dev/anaconda3/envs/py37-torch-0.4.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/utils/cnn_factory.py", line 31, in forward
>     x_var = self.conv(x_var)
>   File "/home/yijingxiao/dev/anaconda3/envs/py37-torch-0.4.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/modules/weight_norm.py", line 168, in forward
>     self.padding, self.dilation, self.groups)
> RuntimeError: CUDA error: out of memory

If I change batch size to 32, I get out of memory immediately:

> [2018-12-03 09:06:10,089 INFO] Loading train dataset from data.share.train.0.pt, number of examples: 220615
> [2018-12-03 09:06:10,149 INFO]  * vocabulary size. source = 50004; target = 50004
> [2018-12-03 09:06:10,149 INFO] Building model...
> [2018-12-03 09:06:12,557 INFO] NMTModel(
>   (encoder): CNNEncoder(
>     (embeddings): Embeddings(
>       (make_embedding): Sequential(
>         (emb_luts): Elementwise(
>           (0): Embedding(50004, 500, padding_idx=1)
>         )
>       )
>     )
>     (linear): Linear(in_features=500, out_features=500, bias=True)
>     (cnn): StackedCNN(
>       (layers): ModuleList(
>         (0): GatedConv(
>           (conv): WeightNormConv2d(500, 1000, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0))
>           (dropout): Dropout(p=0.3)
>         )
>         (1): GatedConv(
>           (conv): WeightNormConv2d(500, 1000, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0))
>           (dropout): Dropout(p=0.3)
>         )
>         (2): GatedConv(
>           (conv): WeightNormConv2d(500, 1000, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0))
>           (dropout): Dropout(p=0.3)
>         )
>         (3): GatedConv(
>           (conv): WeightNormConv2d(500, 1000, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0))
>           (dropout): Dropout(p=0.3)
>         )
>         (4): GatedConv(
>           (conv): WeightNormConv2d(500, 1000, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0))
>           (dropout): Dropout(p=0.3)
>         )
>         (5): GatedConv(
>           (conv): WeightNormConv2d(500, 1000, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0))
>           (dropout): Dropout(p=0.3)
>         )
>         (6): GatedConv(
>           (conv): WeightNormConv2d(500, 1000, kernel_size=(5, 1), stride=(1, 1), padding=(2, 0))
>           (dropout): Dropout(p=0.3)
>         )
>       )
>     )
>   )
>   (decoder): CNNDecoder(
>     (embeddings): Embeddings(
>       (make_embedding): Sequential(
>         (emb_luts): Elementwise(
>           (0): Embedding(50004, 500, padding_idx=1)
>         )
>       )
>     )
>     (linear): Linear(in_features=500, out_features=500, bias=True)
>     (conv_layers): ModuleList(
>       (0): GatedConv(
>         (conv): WeightNormConv2d(500, 1000, kernel_size=(5, 1), stride=(1, 1))
>         (dropout): Dropout(p=0.3)
>       )
>       (1): GatedConv(
>         (conv): WeightNormConv2d(500, 1000, kernel_size=(5, 1), stride=(1, 1))
>         (dropout): Dropout(p=0.3)
>       )
>       (2): GatedConv(
>         (conv): WeightNormConv2d(500, 1000, kernel_size=(5, 1), stride=(1, 1))
>         (dropout): Dropout(p=0.3)
>       )
>     )
>     (attn_layers): ModuleList(
>       (0): ConvMultiStepAttention(
>         (linear_in): Linear(in_features=500, out_features=500, bias=True)
>       )
>       (1): ConvMultiStepAttention(
>         (linear_in): Linear(in_features=500, out_features=500, bias=True)
>       )
>       (2): ConvMultiStepAttention(
>         (linear_in): Linear(in_features=500, out_features=500, bias=True)
>       )
>     )
>   )
>   (generator): Sequential(
>     (0): Linear(in_features=500, out_features=50004, bias=True)
>     (1): LogSoftmax()
>   )
> )
> [2018-12-03 09:06:12,557 INFO] encoder: 42766500
> [2018-12-03 09:06:12,557 INFO] decoder: 33560004
> [2018-12-03 09:06:12,557 INFO] * number of parameters: 76326504
> [2018-12-03 09:06:12,558 INFO] Starting training on GPU: [0]
> [2018-12-03 09:06:12,558 INFO] Start training...
> [2018-12-03 09:06:15,761 INFO] Loading train dataset from data.share.train.0.pt, number of examples: 220615
> Traceback (most recent call last):
>   File "../OpenNMT-py/train.py", line 120, in <module>
>     main(opt)
>   File "../OpenNMT-py/train.py", line 51, in main
>     single_main(opt, 0)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/train_single.py", line 154, in main
>     opt.valid_steps)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/trainer.py", line 175, in train
>     report_stats)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/trainer.py", line 283, in _gradient_accumulation
>     self.model(src, tgt, src_lengths)
>   File "/home/yijingxiao/dev/anaconda3/envs/py37-torch-0.4.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/models/model.py", line 43, in forward
>     enc_state, memory_bank, lengths = self.encoder(src, lengths)
>   File "/home/yijingxiao/dev/anaconda3/envs/py37-torch-0.4.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/encoders/cnn_encoder.py", line 40, in forward
>     out = self.cnn(emb_remap)
>   File "/home/yijingxiao/dev/anaconda3/envs/py37-torch-0.4.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/utils/cnn_factory.py", line 52, in forward
>     x = x + conv(x)
>   File "/home/yijingxiao/dev/anaconda3/envs/py37-torch-0.4.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/utils/cnn_factory.py", line 31, in forward
>     x_var = self.conv(x_var)
>   File "/home/yijingxiao/dev/anaconda3/envs/py37-torch-0.4.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/yijingxiao/research/post-modifier/OpenNMT-py/onmt/modules/weight_norm.py", line 168, in forward
>     self.padding, self.dilation, self.groups)
> RuntimeError: CUDA error: out of memory

**Comment by ZeweiChu** [comment]
Just in case someone is curious, I changed the valid_batch_size.
