### ISSUE TITLE
Bug when checkpoint model has no opt.attention_type

### ISSUE THREAD

**Issue by bpopeters** [OpenNMT/OpenNMT-py#111]
I'm attempting to translate with a model I made a few days ago. Unfortunately, I'm getting this error:

```
Traceback (most recent call last): has no attribute 'attention_type'
  File "translate.py", line 176, in <module>
    main()
  File "translate.py", line 77, in main
    translator = onmt.Translator(opt)
  File "/home/bpop/thesis/mg2p/OpenNMT-py/onmt/Translator.py", line 36, in __init__
    decoder = onmt.Models.Decoder(model_opt, self.tgt_dict)
  File "/home/bpop/thesis/mg2p/OpenNMT-py/onmt/Models.py", line 218, in __init__
    attn_type=opt.attention_type)
AttributeError: 'Namespace' object has no attribute 'attention_type'
```

I set model_opt.attention_type = 'dotprod' as a quick fix in Translator.py, but this causes another error:

```
Traceback (most recent call last):
  File "translate.py", line 177, in <module>
    main()
  File "translate.py", line 78, in main
    translator = onmt.Translator(opt)
  File "/home/bpop/thesis/mg2p/OpenNMT-py/onmt/Translator.py", line 48, in __init__
    model.load_state_dict(checkpoint['model'])
  File "/home/bpop/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 331, in load_state_dict
    .format(name))
KeyError: 'unexpected key "encoder.word_lut.weight" in state_dict'
```

**Comment by sebastianGehrmann** [comment]
Hey, we are aware of this issue and currently working on a fix for that in #104. 

For now, you can use a version before we merged #66 into the master? (i.e. 94ecb04)
