### ISSUE TITLE
crashes when n_beam set to 10 

### ISSUE THREAD

**Issue by Sumith1896** [OpenNMT/OpenNMT-py#1112]
translate command
```
python ../../translate.py -model model.pt -src test-src.txt -output pred-dump.txt -max_length 1000 -replace_unk -verbose -gpu 1 -n_best 10 -dump_beam beam-dump.txt
```
error log
```
Traceback (most recent call last):
  File "../../translate.py", line 36, in <module>
    main(opt)
  File "../../translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 222, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 326, in translate_batch
    return self._translate_batch(batch, data)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 654, in _translate_batch
    ret = self._from_beam(beam)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/translator.py", line 668, in _from_beam
    scores, ks = b.sort_finished(minimum=n_best)
  File "/home/users/sumith/OpenNMT-py/onmt/translate/beam.py", line 161, in sort_finished
    s = global_scores[i]
IndexError: index 5 is out of bounds for dimension 0 with size 5
```

**Comment by da03** [comment]
I think n beam needs to be smaller than beam size? So setting beam size to 10 should work in your case.

**Comment by Sumith1896** [comment]
Whoops! Thanks a lot @da03
