### ISSUE TITLE
RuntimeError when translating image to text

### ISSUE THREAD

**Issue by steveatgit** [OpenNMT/OpenNMT-py#1121]
I also meet this issue similar to #683 when I translate image to text, my command is：
`python translate.py -data_type img -model models_image/demo-model_step_25000.pt -src_dir data/im2text/images -src data/im2text/src-test.txt -output testout/image/pred.txt -max_length 150 -beam_size 5 -gpu 0 -verbose`

**the error log is:**
Traceback (most recent call last):
  File "translate.py", line 37, in <module>
    main(opt)
  File "translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/data1/minisearch/upload/quwei3/OpenNMT-py/onmt/translate/translator.py", line 191, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/data1/minisearch/upload/quwei3/OpenNMT-py/onmt/translate/translator.py", line 295, in translate_batch
    return self._translate_batch(batch, data)
  File "/data1/minisearch/upload/quwei3/OpenNMT-py/onmt/translate/translator.py", line 595, in _translate_batch
    batch, data_type)
  File "/data1/minisearch/upload/quwei3/OpenNMT-py/onmt/translate/translator.py", line 305, in _run_encoder
    src, src_lengths)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/minisearch/upload/quwei3/OpenNMT-py/onmt/encoders/image_encoder.py", line 60, in forward
    src = F.relu(self.layer1(src[:, :, :, :] - 0.5), True)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 1, 3, 3], expected input[30, 3, 160, 600] to have 1 channels, but got 3 channels instead

_Originally posted by @steveatgit in https://github.com/OpenNMT/OpenNMT-py/issue_comments#issuecomment-448442640_

**Comment by vince62s** [comment]
you may have a mismatch with image_channel_size (3 versus 1, ie color vs gray scale) or something like that. not an expert of img2text though.

**Comment by steveatgit** [comment]
I followed the steps in our Example: Image to Text, http://zh.opennmt.net/OpenNMT-py/im2text.html.
Everything is the same with example.
My env:
Centos 7.5
python 2.7.5
torch 0.4.1
cuda v10.0

**Comment by vince62s** [comment]
you need to add -image_channel_size 1 at the end of your translate.py command line.

**Comment by steveatgit** [comment]
Thanks very much. It worked.
Please close it.

**Comment by fjssharpsword** [comment]
Thanks very much. It worked.
