### ISSUE TITLE
[Help Wanted]  weight of size error using ResNet

### ISSUE THREAD

**Issue by SoonmoKwon** [OpenNMT/OpenNMT-py#1159]
I used OpenNMT for seq2seq model on image to text.
In the model, I tried to use pre-trained ResNet for image process.

However, there is an weight of size error like this.

```
Traceback (most recent call last):
  File "/home3/smkwon/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home3/smkwon/anaconda3/envs/openNMT_py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home3/smkwon/anaconda3/envs/openNMT_py36/lib/python3.6/site-packages/pretrainedmodels/models/torchvision_models.py", line 340, in forward
    x = self.features(input)
  File "/home3/smkwon/anaconda3/envs/openNMT_py36/lib/python3.6/site-packages/pretrainedmodels/models/torchvision_models.py", line 322, in features
    x = self.conv1(input)
  File "/home3/smkwon/anaconda3/envs/openNMT_py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home3/smkwon/anaconda3/envs/openNMT_py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 1, 40, 160] to have 3 channels, but got 1 channels instead
```

My image size is [1,100,500]

Thanks,

**Comment by SoonmoKwon** [comment]
I solved problem
