### ISSUE TITLE
[Help wanted] during training, the code is failed to load data.

### ISSUE THREAD

**Issue by SoonmoKwon** [OpenNMT/OpenNMT-py#1160]
I build img2text model using transformer.
When I implement train.py, an error occurs.

```
Traceback (most recent call last):
  File "/home3/smkwon/MyCode/train.py", line 64, in run
    single_main(opt, device_id)
  File "/home3/smkwon/MyCode/onmt/train_single.py", line 154, in main
    trainer.train(train_iter, valid_iter, opt.train_steps, opt.valid_steps)
  File "/home3/smkwon/MyCode/onmt/trainer.py", line 146, in train
    for i, batch in enumerate(train_iter):
  File "/home3/smkwon/MyCode/onmt/inputters/inputter.py", line 476, in __iter__
    for batch in cur_iter:
  File "/home3/smkwon/anaconda3/envs/openNMT_py36/lib/python3.6/site-packages/torchtext/data/iterator.py", line 156, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "/home3/smkwon/anaconda3/envs/openNMT_py36/lib/python3.6/site-packages/torchtext/data/batch.py", line 34, in __init__
    setattr(self, name, field.process(batch, device=device))
  File "/home3/smkwon/anaconda3/envs/openNMT_py36/lib/python3.6/site-packages/torchtext/data/field.py", line 237, in process
    tensor = self.numericalize(padded, device=device)
  File "/home3/smkwon/anaconda3/envs/openNMT_py36/lib/python3.6/site-packages/torchtext/data/field.py", line 357, in numericalize
    arr = self.postprocessing(arr, None)
  File "/home3/smkwon/MyCode/onmt/inputters/inputter.py", line 56, in make_img
    c = data[0].size(0)
IndexError: list index out of range
```

The error is occurred during load the data from preprocess (*.pt) file.
After 10~20 data are loaded, the error is occurred.

**Comment by bpopeters** [comment]
This might be related to recent changes to preprocessing. What exact commands did you run with preprocess.py and train.py?

**Comment by SoonmoKwon** [comment]
@bpopeters 
The code is following:
```
python preprocess.py -data_type img \
                     -src_dir ../Data/COCO \
                     -train_src ../Data/COCO/txtfile_new/coco_train_src_1.txt \
                     -train_tgt ../Data/COCO/txtfile_new/coco_train_tgt_1.txt \
                     -valid_src ../Data/COCO/txtfile_new/coco_val_src_1.txt \
                     -valid_tgt ../Data/COCO/txtfile_new/coco_val_tgt_1.txt \
                     -save_data ../Data/COCO/preprocessmodel/shard5000_legnth50 \
                     -tgt_seq_length 50 \
                     -tgt_words_min_frequency 2 \
                     -shard_size 5000 \
                     -image_channel_size 3
```

```
python train.py -model_type img \
                -data ../Data/COCO/preprocessmodel/shard5000_legnth50 \
                -save_model ../training/shard5000_length50_training \
                -image_model resnet152 \
                -decoder_type transformer \
                -position_encoding \
                -word_vec_size 512 \
                -rnn_size 512 \
                -transformer_ff 2048 \
                -heads 8 \
                -max_generator_batches 10 \
                -layers 6 \
                -visible_gpu 0,2 \
                -world_size 2 \
                -gpu_ranks 0 1 \
                -batch_size 5 \
                -valid_batch_size 3 \
                -batch_type tokens \
                -normalization tokens \
                -accum_count 1 \
                -max_grad_norm 5 \
                -optim adam \
                -adam_beta2 0.998 \
                -decay_method noam \
                -valid_steps 50000 \
                -train_steps 1000000 \
                -warmup_steps 8000 \
                -learning_rate 2 \
                -param_init 0 \
                -param_init_glorot \
                -dropout 0.1 \
                -image_channel_size 3 \
                -label_smoothing 0.1 \
                -tensorboard \
                -tensorboard_log_dir runs
```

'image_model' and 'visible_gpu' are added by myself.

Thanks.

**Comment by SoonmoKwon** [comment]
When I use previous version, the command works.
I think there is a problem a current update implementing torch v. 1.0.

**Comment by SoonmoKwon** [comment]
@vince62s I use pre-trained image encoder, and make feature map. It served as key and value in transformer decoder.

**Comment by SoonmoKwon** [comment]
I found an empty array append when build p_batch.

If I solve the problem, I will let you know how to solve it.

**Comment by SoonmoKwon** [comment]
In onmt.inputters.inputters.OreredIterator.create_batches, an empty array is including in p_batch.
When  we use image-caption dataset, torchtext.data.batch yield empty array firstly.
I fix the function not to yield empty array.
