### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by joseph840617** [OpenNMT/OpenNMT-py#1163]
python train.py -data data/demo -save_model demo-model -gpu_ranks 0

[2019-01-09 18:15:45,703 INFO]  * vocabulary size. source = 24997; target = 35820
[2019-01-09 18:15:45,704 INFO] Building model...
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    main(opt)
  File "train.py", line 51, in main
    single_main(opt, 0)
  File "C:\Users\TensorWindows\Desktop\OpenNMT-py-master\onmt\train_single.py", line 131, in main
    model = build_model(model_opt, opt, fields, checkpoint)
  File "C:\Users\TensorWindows\Desktop\OpenNMT-py-master\onmt\model_builder.py", line 301, in build_model
    model = build_base_model(model_opt, fields, use_gpu(opt), checkpoint)
  File "C:\Users\TensorWindows\Desktop\OpenNMT-py-master\onmt\model_builder.py", line 294, in build_base_model
    model.to(device)
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 381, in to
    return self._apply(convert)
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "E:\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

It work to python train.py -data data/demo -save_model demo-model
(i use rtx 2080 )

**Comment by vince62s** [comment]
I have never tried on Windows.
Please make sure you are on master and let us know your pytorch, python versions as well as cuda (10  I guess since you have a rtx2080)

**Comment by joseph840617** [comment]
@vince62s  
python 3.5.5
pytorch 1.0.0
cuda 9

I try torch.cuda.is_available() 
return true, so I think it not cuda version error

**Comment by joseph840617** [comment]
@vince62s 
I change cuda 10, it can work now.
thanks !

**Comment by vtrokhymenko** [comment]
hi @vince62s 

I have CUDA Version: 10.0
And get error like 'RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED' after 'python train.py -data data/demo -save_model demo-model -world_size 1 -gpu_ranks 0'.
Of course, before I run 'CUDA_VISIBLE_DEVICES=0 '
But when run 'torch.cuda.is_available()' he say 'True'

How I can fix this error?

**Comment by vince62s** [comment]
do you have pytorch 1.0.1post2 ?

**Comment by vtrokhymenko** [comment]
I have version '1.0.0'
u want to say, that your code doesn't work with my version?

Maybe u can say what the version master I can take to work with torch.__verison__ = '1.0.0'

**Comment by vince62s** [comment]
your error looks like a mismatch between you pytorch installation and your cuda installation.

just make sure you install pytorch with the right wheel.
pick the right selection here: https://pytorch.org/get-started/locally/

**Comment by vtrokhymenko** [comment]
after updates to `1.0.1.post2` the work
but I wanted to run with my torch version

thx

**Comment by vtrokhymenko** [comment]
in requirements.txt u wrote `torch>=1.0` but your code doesn't work with all version like `1.0.0`

maybe u will write the version where your code will work?

**Comment by vince62s** [comment]
it does work with 1.0 too but what I am telling you is that your installation of 1.0 is not correct / not in line with your cuda installation.
I can't help you more, find an admin locally, thanks.
btw, there is no point of using 1.0 when 1.0.1 is out and with less bugs.

**Comment by vtrokhymenko** [comment]
yes, I agree with u

plus, I run with my old version this code and the work
today I decided to run a new model, but after that I clone repo I get error

**Comment by playma** [comment]
Go to pytorch website, and choose the version which satisfies your cuda version
https://pytorch.org/

`cu100 = cuda 10`
pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
