### ISSUE TITLE
How to due with this when preprocess the data?

### ISSUE THREAD

**Issue by karlgeorge** [OpenNMT/OpenNMT-py#1167]
when doing
python preprocess.py -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo
[2019-01-10 17:07:12,320 INFO] Building & saving training data...
[2019-01-10 17:07:12,320 INFO] Reading source and target files: data/src-train.txt data/tgt-train.txt.
[2019-01-10 17:07:12,484 INFO] Building shard 0.
[2019-01-10 17:07:12,686 INFO]  * saving 0th train data shard to data/demo.train.0.pt.
Traceback (most recent call last):
  File "preprocess.py", line 177, in <module>
    main()
  File "preprocess.py", line 167, in main
    train_dataset_files = build_save_dataset('train', fields, opt)
  File "preprocess.py", line 100, in build_save_dataset
    dataset.save(data_path)
  File "/home/zhangliang/test/OpenNMT-py/onmt/inputters/dataset_base.py", line 96, in save
    torch.save(self, path)
  File "/home/zhangliang/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 218, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/zhangliang/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 143, in _with_file_like
    return body(f)
  File "/home/zhangliang/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 218, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/zhangliang/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 291, in _save
    pickler.dump(obj)
  File "/home/zhangliang/test/OpenNMT-py/onmt/inputters/dataset_base.py", line 61, in __reduce_ex__
    return super(DatasetBase, self).__reduce_ex__()
TypeError: __reduce_ex__() takes exactly one argument (0 given)

**Comment by karlgeorge** [comment]
> it's a known issue with Python 3.7
> #991 seems to fix it but it breaks Python 2.7
> If you're willing to look into it, a PR is welcome.

Actually, there is no problem on my PC(python version 3.5). The problem occurred on a lab server(python version 3.7). So what I should do is to change the python version of the server? I'm a beginner and what does PR mean? Thanks a lot!

**Comment by vince62s** [comment]
ask someone if you can switch to Python 3.6 or 3.5 on that server.
Cheers.
