### ISSUE TITLE
Error with dynamic_dict and copy_attn when using train_from

### ISSUE THREAD

**Issue by conorg000** [OpenNMT/OpenNMT-py#1168]
Hi there, it seems I can no longer successfully load a model checkpoint (train_from) and continue training. I get the error "AssertionError: using -copy_attn you need to pass in -dynamic_dict during preprocess stage."
My dataset has already been preprocessed with dynamic_dict. Even when I run preprocess.py again with dynamic_dict, the error persists (I'm on master). I tried training from scratch (rather than using train_from) and it worked, which tells me that it has to do with model checkpoints and train_from.
As recently as yesterday, I could use train_from with a checkpoint and have it successfully train on a dataset.
Does anyone have an idea of what I should do differently? I'd like to avoid retraining all of my models from scratch 😝 Thanks for your help
Using Python 3.6 and Torch 0.4.1

**Comment by vince62s** [comment]
can you please copy paste the exact error with back trace ? thanks.

**Comment by conorg000** [comment]
Hi @vince62s , thanks for the quick reply, here it is:

[2019-01-10 15:40:43,559 INFO] Loading checkpoint from /models/copy512_step_195000.pt
[2019-01-10 15:40:50,089 INFO] Loading vocab from checkpoint at /models/copy512_step_195000.pt.
[2019-01-10 15:41:40,899 INFO]  * src vocab size = 50004
[2019-01-10 15:41:40,899 INFO]  * tgt vocab size = 50004
[2019-01-10 15:41:40,899 INFO] Building model...
-----
[2019-01-10 15:41:45,217 INFO] encoder: 27179008
[2019-01-10 15:41:45,217 INFO] decoder: 30902613
[2019-01-10 15:41:45,217 INFO] * number of parameters: 58081621
[2019-01-10 15:41:45,232 INFO] Starting training on GPU: [0]
[2019-01-10 15:41:45,233 INFO] Start training...
[2019-01-10 15:42:34,364 INFO] Loading dataset from /data/baseline.train.0.pt, number of examples: 300000
Traceback (most recent call last):
  File "OpenNMT-py/train.py", line 120, in <module>
    main(opt)
  File "OpenNMT-py/train.py", line 51, in main
    single_main(opt, 0)
  File "/content/OpenNMT-py/onmt/train_single.py", line 164, in main
    trainer.train(train_iter, valid_iter, opt.train_steps, opt.valid_steps)
  File "/content/OpenNMT-py/onmt/trainer.py", line 175, in train
    report_stats)
  File "/content/OpenNMT-py/onmt/trainer.py", line 287, in _gradient_accumulation
    trunc_size, self.shard_size, normalization)
  File "/content/OpenNMT-py/onmt/utils/loss.py", line 168, in sharded_compute_loss
    shard_state = self._make_shard_state(batch, output, range_, attns)
  File "/content/OpenNMT-py/onmt/modules/copy_generator.py", line 155, in _make_shard_state
    raise AssertionError("using -copy_attn you need to pass in "
AssertionError: using -copy_attn you need to pass in -dynamic_dict during preprocess stage.

**Comment by vince62s** [comment]
@bpopeters I let you inquire? , related to the last PR.

**Comment by bpopeters** [comment]
I don't think this is the cause of the issue, but it couldn't hurt to update to torch 1.0 -- I cannot guarantee that 0.4.1 will not cause problems in the future.

You are correct in that the issue has to do with training from a checkpoint. When training from scratch, the model knows how to work with the old preprocessed data, but I must something related to it when loading from a checkpoint. Unfortunately I won't be able to have a closer look until probably Monday, so between now and then the best bet would be to continue to training without the commits from #1132.

**Comment by conorg000** [comment]
Thanks @bpopeters and @vince62s for your input! I've been away for a few days, so I will have a go with latest pytorch release today or tomorrow and get back to you - cheers!

**Comment by bpopeters** [comment]
I would not expect the latest pytorch and torchtext to solve this problem, however. I know what's causing it, I just need to deep a little deeper to find out how to solve it.

**Comment by vince62s** [comment]
git pull and confirm it's working thanks.
