### ISSUE TITLE
'Batch' object has no attribute 'src_map'

### ISSUE THREAD

**Issue by vtrokhymenko** [OpenNMT/OpenNMT-py#1170]
Hi

I download English Summarization (from 2018/03/20 1.1g) from http://opennmt.net/Models-py/ and after that, I run `python translate.py ...` and 2018/03/20 received next error:

```
Traceback (most recent call last):                                                                                                                                         │
  File "translate.py", line 35, in <module>                                                                                                                                │
    main(opt)                                                                                                                                                              │
  File "translate.py", line 20, in main                                                                                                                                    │
    attn_debug=opt.attn_debug                                                                                                                                              │
  File "/home/vtrokhymenko/jupyter/pre-trained/openNMT/onmt/translate/translator.py", line 206, in translate                                                               │
    batch, data, attn_debug, fast=self.fast                                                                                                                                │
  File "/home/vtrokhymenko/jupyter/pre-trained/openNMT/onmt/translate/translator.py", line 453, in translate_batch                                                         │
    return self._translate_batch(batch, data)                                                                                                                              │
  File "/home/vtrokhymenko/jupyter/pre-trained/openNMT/onmt/translate/translator.py", line 784, in _translate_batch                                                        │
    if data.data_type == 'text' and self.copy_attn else None)                                                                                                              │
AttributeError: 'Batch' object has no attribute 'src_map'                              
```

Doing prediction on test dataset from cnndm 

How I can fix this error?

**Comment by vtrokhymenko** [comment]
also this trouble in the pre-trained model on 900MB

**Comment by vtrokhymenko** [comment]
@ratishsp maybe u can help me with above problem?

**Comment by vince62s** [comment]
try the last release: https://github.com/OpenNMT/OpenNMT-py/releases/tag/0.7.0

**Comment by vtrokhymenko** [comment]
thx, at now I will check your release and write they fix my problem or no

**Comment by vtrokhymenko** [comment]
they work, thx

**Comment by vince62s** [comment]
@bpopeters

**Comment by bpopeters** [comment]
I'm confused, why did this get closed and then opened and then closed again? This still needs to be fixed, doesn't it?

**Comment by vince62s** [comment]
sorry my fault. I thought torchtext 0.4 would fix it, but I mixed up with another issue. unsure though.

**Comment by vince62s** [comment]
git pull and confirm it's working, thanks.
