### ISSUE TITLE
Vocab is not saving when running in colab with my own data.

### ISSUE THREAD

**Issue by udaysaal** [OpenNMT/OpenNMT-py#1179]
Preprocess failed while saving the vocab file.

Traceback (most recent call last):
  File "/content/gdrive/My Drive/machinetranslation/OpenNMT/OpenNMT/preprocess.py", line 178, in <module>
    main()
  File "/content/gdrive/My Drive/machinetranslation/OpenNMT/OpenNMT/preprocess.py", line 174, in main
    build_save_vocab(train_dataset_files, fields, opt)
  File "/content/gdrive/My Drive/machinetranslation/OpenNMT/OpenNMT/preprocess.py", line 119, in build_save_vocab
    torch.save(fields, vocab_path)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 218, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 143, in _with_file_like
    return body(f)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 218, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 291, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <function Field.<lambda> at 0x7f3b42e51400>: attribute lookup Field.<lambda> on torchtext.data.field failed

**Comment by vince62s** [comment]
make sure pytorch == 1.0 and torchtext >=0.4

**Comment by udaysaal** [comment]
@vince62s  There is no version of torchtext >=0.4

**Comment by udaysaal** [comment]
@vince62s Thank you, running now.

**Comment by gongzhitaao** [comment]
@vince62s torchtext has latest version 0.3.1?

**Comment by vince62s** [comment]
yes but if you follow the intruction on the homepage, requirements will install git+https://github.com/pytorch/text
