### ISSUE TITLE
Rest server error: dict object has no attribute seed 

### ISSUE THREAD

**Issue by TinDang97** [OpenNMT/OpenNMT-py#1186]
Hi,

My problem is:
> Pre-loading model 0
Traceback (most recent call last):
  File "server.py", line 119, in <module>
    debug=args.debug)
  File "server.py", line 24, in start
    translation_server.start(config_file)
  File "/home/dinht/OpenNMT-py/onmt/translate/translation_server.py", line 96, in start
    self.preload_model(opt, model_id=model_id, **kwargs)
  File "/home/dinht/OpenNMT-py/onmt/translate/translation_server.py", line 132, in preload_model
    model = ServerModel(opt, model_id, **model_kwargs)
  File "/home/dinht/OpenNMT-py/onmt/translate/translation_server.py", line 211, in __init__
    set_random_seed(opt.seed, opt.cuda)
AttributeError: 'dict' object has no attribute 'seed'

This is my conf.json
`{
	"models_root": "./available_models/",
	"models": [
		{
			"id": 0,
			"model": "demo-model_step_10000.pt",
			"timeout": 600,
			"on_timeout": "to_cpu",
			"load": true,
			"opt": {
					"beam_size": 5000
				}
		}
	]
}`

And i use python 2.7.

I hope you help me to fix it.

**Comment by TinDang97** [comment]
> try to change this line:
> https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translation_server.py#L211
> to opt.seed => self.opt.seed
> if it works, send a PR

Hi vince62s,

I have been changed it like:
`opt.seed => self.opt.seed`
and:
`opt.cuda => self.opt.cuda`

My server was started. 
Thank you very much for your support.

**Comment by vince62s** [comment]
@daphnei in case you have time to fix this with a PR. Thanks.

**Comment by daphnei** [comment]
Sorry for introducing the bug, thanks for fixing!
