### ISSUE TITLE
Need CUDA check for "attention is all you need "  model 

### ISSUE THREAD

**Issue by everwind** [OpenNMT/OpenNMT-py#121]
command:
python train.py -data data/demo.train.pt -save_model demo-model -encoder_layer transformer -decoder_layer transformer -rnn_size 512 -word_vec_size 512
I meet the following errors:
Traceback (most recent call last):
  File "train.py", line 440, in <module>
    main()
  File "train.py", line 436, in main
    trainModel(model, trainData, validData, dataset, optim)
  File "train.py", line 274, in trainModel
    train_stats = trainEpoch(epoch)
  File "train.py", line 246, in trainEpoch
    dec_state)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/plat/peakzeng/workspace/OpenNMT-py-master/onmt/Models.py", line 381, in forward
    else dec_state)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/plat/peakzeng/workspace/OpenNMT-py-master/onmt/Models.py", line 276, in forward
    input.transpose(0, 1))
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/plat/peakzeng/workspace/OpenNMT-py-master/onmt/modules/Transformer.py", line 103, in forward
    .expand_as(attn_mask), 0)
  File "/usr/lib64/python2.7/site-packages/torch/tensor.py", line 267, in __add__
    return self.add(other)
TypeError: add received an invalid combination of arguments - got (torch.cuda.ByteTensor), but expected one of:
 * (int value)
      didn't match because some of the arguments have invalid types: (torch.cuda.ByteTensor)
 * (torch.ByteTensor other)
      didn't match because some of the arguments have invalid types: (torch.cuda.ByteTensor)
 * (torch.SparseByteTensor other)
      didn't match because some of the arguments have invalid types: (torch.cuda.ByteTensor)
 * (int value, torch.ByteTensor other)
 * (int value, torch.SparseByteTensor other)

**Comment by srush** [comment]
This looks like a CUDA/non-cuda issue. Are you translating on GPU or CPU?

**Comment by srush** [comment]
The issue is this line, you can just delete .cuda()

https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/Transformer.py#L87

If you want to submit a PR with a GPU check we would be grateful.

**Comment by sebastianGehrmann** [comment]
#127 should have fixed it.
