### ISSUE TITLE
Translation with target word features fails

### ISSUE THREAD

**Issue by flauted** [OpenNMT/OpenNMT-py#1218]
I'm seeing that preprocessing and training with (source and) target word features is fine, but the translation doesn't work. Am I missing something? Is this behavior expected?

I'm on commit 5d6f23b2711198f5a78f07822cbdf1f2bd75a385, tag 0.7.1

Here's all the steps to reproduce from the demo data.

----
Put this in a script and run from the data folder. Requires spacy and English/German language models (``conda install spacy -c conda-forge`` or however you prefer, ``python -m spacy download en``, ``python -m spacy download de``) 
```
# meant to be run from the data folder
import spacy
for side, lang in [("src", "en"), ("tgt", "de")]:
    nlp = spacy.load(lang)
    for split in ["train", "val", "test"]:
        if side == "tgt" and split == "test":
            continue  # no test tgt data given
        print(side, lang, split)
        o = open("{:s}-{:s}-feats.txt".format(side, split), "w")
        with open("{:s}-{:s}.txt".format(side, split)) as f:
            for line in f:
                doc = nlp(line.strip("\n"))
                line = []
                for token in doc:
                    if side == "src":
                        line.append(u'￨'.join(
                            [token.text, token.pos_, token.tag_, token.ent_type_]))
                    else:
                        line.append(u'￨'.join(
                            [token.text, token.pos_, token.tag_]))
                line = " ".join(line)
                o.write(line + "\n")
        o.close()
```
Verify that the train source data has three features (looks like two at first glance but the ``ent_type_`` is usually ``""``)
```
head -n 2 data/src-train-feats.txt
```
```
It￨PRON￨PRP￨ is￨VERB￨VBZ￨ not￨ADV￨RB￨ acceptable￨ADJ￨JJ￨ that￨ADP￨IN￨ ,￨PUNCT￨,￨ with￨ADP￨IN￨ the￨DET￨DT￨ help￨NOUN￨NN￨ of￨ADP￨IN￨ the￨DET￨DT￨ national￨ADJ￨JJ￨ bureaucracies￨NOUN￨NNS￨ ,￨PUNCT￨,￨ Parliament￨PROPN￨NNP￨ORG &￨CCONJ￨CC￨ORG apos;s￨VERB￨VBZ￨ORG legislative￨ADJ￨JJ￨ prerogative￨NOUN￨NN￨ should￨VERB￨MD￨ be￨VERB￨VB￨ made￨VERB￨VBN￨ null￨ADJ￨JJ￨ and￨CCONJ￨CC￨ void￨ADJ￨JJ￨ by￨ADP￨IN￨ means￨NOUN￨NNS￨ of￨ADP￨IN￨ implementing￨VERB￨VBG￨ provisions￨NOUN￨NNS￨ whose￨ADJ￨WP$￨ content￨NOUN￨NN￨ ,￨PUNCT￨,￨ purpose￨NOUN￨NN￨ and￨CCONJ￨CC￨ extent￨NOUN￨NN￨ are￨VERB￨VBP￨ not￨ADV￨RB￨ laid￨VERB￨VBN￨ down￨PART￨RP￨ in￨ADP￨IN￨ advance￨NOUN￨NN￨ .￨PUNCT￨.￨
Federal￨PROPN￨NNP￨ Master￨PROPN￨NNP￨ Trainer￨PROPN￨NNP￨PERSON and￨CCONJ￨CC￨ Senior￨PROPN￨NNP￨ Instructor￨PROPN￨NNP￨ of￨ADP￨IN￨ the￨DET￨DT￨ORG Italian￨PROPN￨NNP￨ORG Federation￨PROPN￨NNP￨ORG of￨ADP￨IN￨ORG Aerobic￨PROPN￨NNP￨ORG Fitness￨PROPN￨NNP￨ORG ,￨PUNCT￨,￨ORG Group￨PROPN￨NNP￨ORG Fitness￨PROPN￨NNP￨ORG ,￨PUNCT￨,￨ORG Postural￨PROPN￨NNP￨ORG Gym￨PROPN￨NNP￨ORG ,￨PUNCT￨,￨ Stretching￨PROPN￨NNP￨ORG and￨CCONJ￨CC￨ORG Pilates￨PROPN￨NNPS￨ORG ;￨PUNCT￨:￨ from￨ADP￨IN￨ 2004￨NUM￨CD￨DATE ,￨PUNCT￨,￨ he￨PRON￨PRP￨ has￨VERB￨VBZ￨ been￨VERB￨VBN￨ collaborating￨VERB￨VBG￨ with￨ADP￨IN￨ Antiche￨PROPN￨NNP￨ORG Terme￨PROPN￨NNP￨ORG as￨ADP￨IN￨ personal￨ADJ￨JJ￨ Trainer￨PROPN￨NNP￨PERSON and￨CCONJ￨CC￨ Instructor￨PROPN￨NNP￨PERSON of￨ADP￨IN￨ Stretching￨PROPN￨NNP￨ ,￨PUNCT￨,￨ Pilates￨PROPN￨NNP￨NORP and￨CCONJ￨CC￨ Postural￨PROPN￨NNP￨ORG Gym￨PROPN￨NNP￨ORG .￨PUNCT￨.￨
```
Verify that the train target data has two features
```
 head -n 2 data/tgt-train-feats.txt 
```
```
Es￨PRON￨PPER geht￨VERB￨VVFIN nicht￨PART￨PTKNEG an￨PART￨PTKVZ ,￨PUNCT￨$, dass￨SCONJ￨KOUS über￨ADP￨APPR Ausführungsbestimmungen￨NOUN￨NN ,￨PUNCT￨$, deren￨DET￨PRELAT Inhalt￨NOUN￨NN ,￨PUNCT￨$, Zweck￨NOUN￨NN und￨CONJ￨KON Ausmaß￨NOUN￨NN vorher￨ADV￨ADV nicht￨PART￨PTKNEG bestimmt￨VERB￨VVPP ist￨AUX￨VAFIN ,￨PUNCT￨$, zusammen￨ADV￨ADV mit￨ADP￨APPR den￨DET￨ART nationalen￨ADJ￨ADJA Bürokratien￨NOUN￨NN das￨DET￨ART Gesetzgebungsrecht￨NOUN￨NN des￨DET￨ART Europäischen￨ADJ￨ADJA Parlaments￨NOUN￨NN ausgehebelt￨VERB￨VVPP wird￨AUX￨VAFIN .￨PUNCT￨$.
Meistertrainer￨NOUN￨NN und￨CONJ￨KON leitender￨ADJ￨ADJA Dozent￨NOUN￨NN des￨DET￨ART italienischen￨ADJ￨ADJA Fitnessverbands￨NOUN￨NN für￨ADP￨APPR Aerobic￨NOUN￨NN ,￨PUNCT￨$, Gruppenfitness￨PROPN￨NE ,￨PUNCT￨$, Haltungsgymnastik￨NOUN￨NN ,￨PUNCT￨$, Stretching￨NOUN￨NN und￨CONJ￨KON Pilates￨NOUN￨NN ;￨PUNCT￨$. arbeitet￨VERB￨VVFIN seit￨ADP￨APPR 2004￨NUM￨CARD bei￨ADP￨APPR Antiche￨ADJ￨ADJA Terme￨NOUN￨NN als￨ADP￨APPR Personal￨NOUN￨NN Trainer￨NOUN￨NN und￨CONJ￨KON Lehrer￨NOUN￨NN für￨ADP￨APPR Stretching￨PROPN￨NE ,￨PUNCT￨$, Pilates￨NOUN￨NN und￨CONJ￨KON Rückengymnastik￨NOUN￨NN .￨PUNCT￨$.
```
Preprocess
```
python preprocess.py -train_src data/src-train-feats.txt -train_tgt data/tgt-train-feats.txt -valid_src data/src-val-feats.txt -valid_tgt data/tgt-val-feats.txt -save_data data/demo-feats
```
```
[2019-01-24 22:47:00,052 INFO] Extracting features...
[2019-01-24 22:47:00,052 INFO]  * number of source features: 3.
[2019-01-24 22:47:00,052 INFO]  * number of target features: 2.
[2019-01-24 22:47:00,052 INFO] Building `Fields` object...
[2019-01-24 22:47:00,053 INFO] Building & saving training data...
[2019-01-24 22:47:00,053 INFO] Reading source and target files: data/src-train-feats.txt data/tgt-train-feats.txt.
[2019-01-24 22:47:00,235 INFO] Building shard 0.
[2019-01-24 22:47:01,020 INFO]  * saving 0th train data shard to data/demo-feats.train.0.pt.
[2019-01-24 22:47:02,866 INFO] Building & saving validation data...
[2019-01-24 22:47:02,866 INFO] Reading source and target files: data/src-val-feats.txt data/tgt-val-feats.txt.
[2019-01-24 22:47:02,920 INFO] Building shard 0.
[2019-01-24 22:47:03,155 INFO]  * saving 0th valid data shard to data/demo-feats.valid.0.pt.
[2019-01-24 22:47:03,765 INFO] Building & saving vocabulary...
[2019-01-24 22:47:04,395 INFO]  * reloading data/demo-feats.train.0.pt.
[2019-01-24 22:47:04,976 INFO]  * tgt vocab size: 34388.
[2019-01-24 22:47:04,976 INFO]  * tgt_feat_0 vocab size: 21.
[2019-01-24 22:47:04,976 INFO]  * tgt_feat_1 vocab size: 57.
[2019-01-24 22:47:05,025 INFO]  * src vocab size: 22910.
[2019-01-24 22:47:05,025 INFO]  * src_feat_0 vocab size: 18.
[2019-01-24 22:47:05,025 INFO]  * src_feat_1 vocab size: 52.
[2019-01-24 22:47:05,025 INFO]  * src_feat_2 vocab size: 21.
```
Train for 500 steps and save
```
python train.py -data data/demo-feats -save_model demo-model -world_size 1 -gpu_ranks 0 -train_steps 500 -save_checkpoint_steps 500
```
```
[2019-01-24 22:48:01,608 INFO]  * src vocab size = 22910
[2019-01-24 22:48:01,608 INFO]  * src_feat_0 vocab size = 18
[2019-01-24 22:48:01,608 INFO]  * src_feat_1 vocab size = 52
[2019-01-24 22:48:01,608 INFO]  * src_feat_2 vocab size = 21
[2019-01-24 22:48:01,608 INFO]  * tgt vocab size = 34388
[2019-01-24 22:48:01,608 INFO]  * tgt_feat_0 vocab size = 21
[2019-01-24 22:48:01,608 INFO]  * tgt_feat_1 vocab size = 57
[2019-01-24 22:48:01,608 INFO] Building model...
[2019-01-24 22:48:04,867 INFO] NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(22910, 500, padding_idx=1)
          (1): Embedding(18, 7, padding_idx=1)
          (2): Embedding(52, 15, padding_idx=1)
          (3): Embedding(21, 8, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(530, 500, num_layers=2, dropout=0.3)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(34388, 500, padding_idx=1)
          (1): Embedding(21, 8, padding_idx=1)
          (2): Embedding(57, 16, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(1024, 500)
        (1): LSTMCell(500, 500)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=500, out_features=500, bias=False)
      (linear_out): Linear(in_features=1000, out_features=500, bias=False)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=500, out_features=34388, bias=True)
    (1): LogSoftmax()
  )
)
[2019-01-24 22:48:04,867 INFO] encoder: 15524074
[2019-01-24 22:48:04,867 INFO] decoder: 40229468
[2019-01-24 22:48:04,867 INFO] * number of parameters: 55753542
[2019-01-24 22:48:04,868 INFO] Starting training on GPU: [0]
[2019-01-24 22:48:04,868 INFO] Start training...
[2019-01-24 22:48:05,498 INFO] Loading dataset from data/demo-feats.train.0.pt, number of examples: 9918
[2019-01-24 22:48:10,264 INFO] Step 50/  500; acc:   3.91; ppl: 77395.17; xent: 11.26; lr: 1.00000; 14233/13928 tok/s;      5 sec
[2019-01-24 22:48:14,362 INFO] Step 100/  500; acc:   4.25; ppl: 12170.59; xent: 9.41; lr: 1.00000; 17286/17127 tok/s;      9 sec
[2019-01-24 22:48:18,713 INFO] Step 150/  500; acc:   7.20; ppl: 4613.63; xent: 8.44; lr: 1.00000; 16796/16467 tok/s;     14 sec
[2019-01-24 22:48:19,958 INFO] Loading dataset from data/demo-feats.train.0.pt, number of examples: 9918
[2019-01-24 22:48:23,710 INFO] Step 200/  500; acc:   8.16; ppl: 2758.43; xent: 7.92; lr: 1.00000; 15223/14917 tok/s;     19 sec
[2019-01-24 22:48:27,757 INFO] Step 250/  500; acc:   8.64; ppl: 1847.83; xent: 7.52; lr: 1.00000; 18583/18271 tok/s;     23 sec
[2019-01-24 22:48:32,070 INFO] Step 300/  500; acc:  10.32; ppl: 1404.58; xent: 7.25; lr: 1.00000; 15848/15609 tok/s;     27 sec
[2019-01-24 22:48:33,841 INFO] Loading dataset from data/demo-feats.train.0.pt, number of examples: 9918
[2019-01-24 22:48:37,118 INFO] Step 350/  500; acc:  10.99; ppl: 1123.27; xent: 7.02; lr: 1.00000; 15600/15156 tok/s;     32 sec
[2019-01-24 22:48:41,162 INFO] Step 400/  500; acc:  11.82; ppl: 913.98; xent: 6.82; lr: 1.00000; 18792/18433 tok/s;     36 sec
[2019-01-24 22:48:45,121 INFO] Step 450/  500; acc:  13.37; ppl: 757.51; xent: 6.63; lr: 1.00000; 16709/16766 tok/s;     40 sec
[2019-01-24 22:48:47,505 INFO] Loading dataset from data/demo-feats.train.0.pt, number of examples: 9918
[2019-01-24 22:48:50,372 INFO] Step 500/  500; acc:  12.66; ppl: 742.07; xent: 6.61; lr: 1.00000; 15759/15146 tok/s;     46 sec
[2019-01-24 22:48:50,372 INFO] Saving checkpoint demo-model_step_500.pt
```
Try to run translation but fail.
```
python translate.py -model demo-model_step_500.pt -src data/src-test-feats.txt -verbose
```
```
[2019-01-24 22:49:15,038 INFO] Translating shard 0.
Traceback (most recent call last):
  File "/home/dylan/code/OpenNMT-py/./translate.py", line 42, in <module>
    main(opt)
  File "/home/dylan/code/OpenNMT-py/./translate.py", line 27, in main
    attn_debug=opt.attn_debug
  File "/home/dylan/code/OpenNMT-py/onmt/translate/translator.py", line 210, in translate
    batch, data, attn_debug, fast=self.fast
  File "/home/dylan/code/OpenNMT-py/onmt/translate/translator.py", line 458, in translate_batch
    return self._translate_batch(batch, data)
  File "/home/dylan/code/OpenNMT-py/onmt/translate/translator.py", line 806, in _translate_batch
    src_map=src_map, step=i
  File "/home/dylan/code/OpenNMT-py/onmt/translate/translator.py", line 499, in _decode_and_generate
    decoder_in, memory_bank, memory_lengths=memory_lengths, step=step
  File "/home/dylan/miniconda3/envs/opennmt2712/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dylan/code/OpenNMT-py/onmt/decoders/decoder.py", line 161, in forward
    tgt, memory_bank, memory_lengths=memory_lengths)
  File "/home/dylan/code/OpenNMT-py/onmt/decoders/decoder.py", line 323, in _run_forward_pass
    emb = self.embeddings(tgt)
  File "/home/dylan/miniconda3/envs/opennmt2712/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dylan/code/OpenNMT-py/onmt/modules/embeddings.py", line 207, in forward
    source = self.make_embedding(source)
  File "/home/dylan/miniconda3/envs/opennmt2712/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dylan/miniconda3/envs/opennmt2712/lib/python2.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/dylan/miniconda3/envs/opennmt2712/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dylan/code/OpenNMT-py/onmt/modules/util_class.py", line 25, in forward
    assert len(self) == len(inputs_)
AssertionError
```

**Comment by vince62s** [comment]
I don't think it ever worked with target features. Even surprised it trained.
@Henry-E did you work on this?

@flauted What about source features only, does it train and translate ok ?

**Comment by Henry-E** [comment]
No I never got around to it sorry. There's someone I know who might have it implemented but their code may not be public.

**Comment by flauted** [comment]
Yes it works fine if you use ``-train_tgt data/tgt-train.txt`` and ``-valid_tgt data/tgt-val.txt``. So as far as I'm concerned this issue can be closed.
