### ISSUE TITLE
error of using random sampling when decode

### ISSUE THREAD

**Issue by njuzrs** [OpenNMT/OpenNMT-py#1225]
To improve the diversity of decoder, I have try the parameter of "random_sampling_topk", but it come up with the error:
[2019-01-28 03:14:45,565 ERROR] model opt: {'models': ['./available_models/buydata_v2.pt'], 'avg_raw_probs': False, 'data_type': 'text', 'src': 'dummy_src', 'src_dir': '', 'tgt': None, 'shard_size': 10000, 'output': 'pred.txt', 'report_bleu': False, 'report_rouge': False, 'report_time': False, 'dynamic_dict': False, 'share_vocab': False, 'random_sampling_topk': 2, 'random_sampling_temp': 0.8, 'seed': 829, 'fast': False, 'beam_size': 1, 'min_length': 0, 'max_length': 40, 'max_sent_length': None, 'stepwise_penalty': True, 'length_penalty': 'wu', 'coverage_penalty': 'summary', 'alpha': 0.9, 'beta': 5.0, 'block_ngram_repeat': 0, 'ignore_when_blocking': ["['.', '</t>', '<t>']"], 'replace_unk': False, 'verbose': True, 'log_file': '', 'log_file_level': '0', 'attn_debug': False, 'dump_beam': '', 'n_best': 1, 'batch_size': 30, 'gpu': 0, 'sample_rate': 16000, 'window_size': 0.02, 'window_stride': 0.01, 'window': 'hamming', 'image_channel_size': 3, 'cuda': True}
[2019-01-28 03:14:45,571 ERROR] Traceback (most recent call last):
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translation_server.py", line 379, in run
    batch_size=self.opt.batch_size)
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translator.py", line 220, in translate
    batch, data, attn_debug, fast=self.fast
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translator.py", line 468, in translate_batch
    return_attention=attn_debug or self.replace_unk)
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translator.py", line 406, in _translate_random_sampling
    batch_offset=torch.arange(batch_size, dtype=torch.long)
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translator.py", line 520, in _decode_and_generate
    decoder_in, memory_bank, memory_lengths=memory_lengths, step=step
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangrongsheng/OpenNMT-py/onmt/decoders/transformer.py", line 232, in forward
    step=step)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangrongsheng/OpenNMT-py/onmt/decoders/transformer.py", line 80, in forward
    type="self")
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangrongsheng/OpenNMT-py/onmt/modules/multi_headed_attn.py", line 126, in forward
    query, key, value = self.linear_query(query),\
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1354, in linear
    output = input.matmul(weight.t())
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:258
Could you tell me how it happen?

**Comment by vince62s** [comment]
What if you try to do it in command line directly without the translation_server ?

**Comment by njuzrs** [comment]
@vince62s It also come op with the problem:
Traceback (most recent call last):
  File "translate.py", line 42, in <module>
    main(opt)
  File "translate.py", line 27, in main
    attn_debug=opt.attn_debug
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translator.py", line 220, in translate
    batch, data, attn_debug, fast=self.fast
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translator.py", line 468, in translate_batch
    return_attention=attn_debug or self.replace_unk)
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translator.py", line 406, in _translate_random_sampling
    batch_offset=torch.arange(batch_size, dtype=torch.long)
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translator.py", line 545, in _decode_and_generate
    batch_offset=batch_offset
  File "/home/zhangrongsheng/OpenNMT-py/onmt/modules/copy_generator.py", line 21, in collapse_copy_scores
    src_vocab = src_vocabs[index]
RuntimeError: CUDA error: device-side assert triggered

**Comment by njuzrs** [comment]
@vince62s the command line is:
python -u translate.py 
-gpu 1 
-batch_size 50 
-beam_size 1 
-random_sampling_topk 2 
-random_sampling_temp 0.8
 -model models/buydata-v2/v2_step_22000.pt 
-src data/buydata/v2/test.txt.src 
-output data/buydata/v2/test.txt.out 
-max_length 40 
-verbose 
-stepwise_penalty 
-coverage_penalty summary 
-beta 5 
-length_penalty wu 
-alpha 0.9 
-block_ngram_repeat 0 
-ignore_when_blocking "." "</t>" "<t>"

**Comment by njuzrs** [comment]
It works well by the operation, it seems the problem of the function "_translate_random_sampling". The code in translator.py is:
        with torch.no_grad():
            if self.beam_size == 1:
                return self._translate_random_sampling(
                    batch,
                    data,
                    self.max_length,
                    min_length=self.min_length,
                    sampling_temp=self.random_sampling_temp,
                    keep_topk=self.sample_from_topk,
                    return_attention=attn_debug or self.replace_unk)
            if fast:
                return self._fast_translate_batch(
                    batch,
                    data,
                    self.max_length,
                    min_length=self.min_length,
                    n_best=self.n_best,
                    return_attention=attn_debug or self.replace_unk)
            else:
                return self._translate_batch(batch, data)

**Comment by vince62s** [comment]
@daphnei can you have a look please ?

**Comment by daphnei** [comment]
If you run on cpu, (remove `-gpu 1`) does it work?

I obviously don't have access to your checkpoint/input file, but I can't seem to reproduce your error within my own setup.

**Comment by njuzrs** [comment]
@daphnei After I remove "-gpu 1", I meet the error:
Traceback (most recent call last):
  File "translate.py", line 42, in <module>
    main(opt)
  File "translate.py", line 27, in main
    attn_debug=opt.attn_debug
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translator.py", line 220, in translate
    batch, data, attn_debug, fast=self.fast
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translator.py", line 468, in translate_batch
    return_attention=attn_debug or self.replace_unk)
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translator.py", line 414, in _translate_random_sampling
    log_probs, sampling_temp, keep_topk)
  File "/home/zhangrongsheng/OpenNMT-py/onmt/translate/translator.py", line 330, in sample_with_temperature
    topk_ids = torch.argmax(dist.sample(), dim=1, keepdim=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributions/multinomial.py", line 91, in sample
    samples = self._categorical.sample(torch.Size((self.total_count,)) + sample_shape)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributions/categorical.py", line 110, in sample
    sample_2d = torch.multinomial(probs_2d, 1, True)
RuntimeError: invalid argument 2: invalid multinomial distribution (encountering probability entry < 0) at /pytorch/aten/src/TH/generic/THTensorRandom.cpp:298

the command line I run:
https://github.com/OpenNMT/OpenNMT-py/issues/1225#issuecomment-458038977
the model file and test file are in the command '-model' and '-src'.
and I run the code in copy mechanism.

**Comment by daphnei** [comment]
If you replace likes 328 and 329 with 
```
dist = torch.distributions.Multinomial(
    probs=F.softmax(logits, dim=-1), total_count=1)
```
does it still fail?

**Comment by njuzrs** [comment]
I try it and it still fail with the same error as https://github.com/OpenNMT/OpenNMT-py/issues/1225#issuecomment-458381253

**Comment by daphnei** [comment]
I cannot reproduce this. Perhaps if you post your exact files that cause the bug `models/buydata-v2/v2_step_22000.pt` and 
`data/buydata/v2/test.txt.src` I can try again.
