### ISSUE TITLE
bug when add tgt file during translatation.

### ISSUE THREAD

**Issue by wuhaixutab** [OpenNMT/OpenNMT-py#129]
haixu@my-machine:~/Desktop/OpenNMT-cls2mdn$ python3 translate.py -model cls2mdn_model/_acc_29.00_ppl_259.68_e10.pt -src data/cls_test.txt -output pred.txt -replace_unk -verbose -gpu 0 -batch_size 1 -beam_size 4 -tgt data/mdn_test.txt 
Traceback (most recent call last):
  File "translate.py", line 176, in <module>
    main()
  File "translate.py", line 110, in main
    = translator.translate(srcBatch, tgtBatch)
  File "/home/haixu/Desktop/OpenNMT-cls2mdn/onmt/Translator.py", line 250, in translate
    pred, predScore, attn, goldScore = self.translateBatch(batch)
  File "/home/haixu/Desktop/OpenNMT-cls2mdn/onmt/Translator.py", line 133, in translateBatch
    context, decStates)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'state'

**Comment by sebastianGehrmann** [comment]
Hey, I suspect that this is related to #111 - when did you train the model?
