### ISSUE TITLE
training with -share_decoder_embeddings is broken

### ISSUE THREAD

**Issue by bpopeters** [OpenNMT/OpenNMT-py#131]
When you enable -share_decoder_embeddings, you get this error:

```
Traceback (most recent call last):
  File "train.py", line 440, in <module>
    main()
  File "train.py", line 372, in main
    generator[0].weight = decoder.word_lut.weight
  File "/home/bpop/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 238, in __getattr__
    type(self).__name__, name))
AttributeError: 'Decoder' object has no attribute 'word_lut'
```

I think probably what was intended here was to use decoder.embeddings.word_lut.weight, but I'm not totally sure on that point as I haven't delved sufficiently into the depths of Models.py.

**Comment by srush** [comment]
Yes, this is a bug. Will fix soon.
