### ISSUE TITLE
Pickle error while running the preprocessing

### ISSUE THREAD

**Issue by andreaferretti** [OpenNMT/OpenNMT-py#1313]
I am trying to run the preprocessing as explained in the quickstart

```sh
python -m preprocess \
  -train_src "$DATA_DIR/$LANG1.train" \
  -train_tgt "$DATA_DIR/$LANG2.train" \
  -valid_src "$DATA_DIR/$LANG1.validation" \
  -valid_tgt "$DATA_DIR/$LANG2.validation" \
  -save_data "$DATA_DIR/data"
```

Preprocessing of train files seems to be ok, but it finally fails when saving the vocabulary (or so I understand):

```
[2019-02-18 11:15:38,508 INFO]  * reloading data/translate/en-it/data.train.33.pt.
[2019-02-18 11:16:05,591 INFO]  * reloading data/translate/en-it/data.train.34.pt.
[2019-02-18 11:16:28,518 INFO]  * tgt vocab size: 50004.
[2019-02-18 11:16:36,087 INFO]  * src vocab size: 50002.
Traceback (most recent call last):
  File "/Users/andrea/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/andrea/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/andrea/.local/share/virtualenvs/charade-MvDoWtjx/src/opennmt/preprocess.py", line 176, in <module>
    main()
  File "/Users/andrea/.local/share/virtualenvs/charade-MvDoWtjx/src/opennmt/preprocess.py", line 172, in main
    build_save_vocab(train_dataset_files, fields, opt)
  File "/Users/andrea/.local/share/virtualenvs/charade-MvDoWtjx/src/opennmt/preprocess.py", line 110, in build_save_vocab
    torch.save(fields, vocab_path)
  File "/Users/andrea/.local/share/virtualenvs/charade-MvDoWtjx/lib/python3.6/site-packages/torch/serialization.py", line 219, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/Users/andrea/.local/share/virtualenvs/charade-MvDoWtjx/lib/python3.6/site-packages/torch/serialization.py", line 144, in _with_file_like
    return body(f)
  File "/Users/andrea/.local/share/virtualenvs/charade-MvDoWtjx/lib/python3.6/site-packages/torch/serialization.py", line 219, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/Users/andrea/.local/share/virtualenvs/charade-MvDoWtjx/lib/python3.6/site-packages/torch/serialization.py", line 292, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <function Field.<lambda> at 0x114f7abf8>: attribute lookup Field.<lambda> on torchtext.data.field failed
```

**Comment by vince62s** [comment]
Please make sure you have pytorch >=1.0 AND torchtext 0.40 from the github master repo.

**Comment by andreaferretti** [comment]
I confirm this was an issue due to using torchtext 0.3.2 (which is the latest version published on Pip). With torchtext 0.4.0 this works fine

**Comment by splurgein** [comment]
I get a similar error 
pytorch =1.0.0a0+db5d313 AND torchtext 0.40

Traceback (most recent call last):
  File "preprocess.py", line 156, in <module>
    main(opt)
  File "preprocess.py", line 141, in main
    build_save_vocab(train_dataset_files, fields, opt)
  File "preprocess.py", line 92, in build_save_vocab
    torch.save(fields, vocab_path)
  File "/hpc_modules/at10.0-based/deeplearning/pytorch-1.0.0/lib64/python3.5/site-packages/torch/serialization.py", line 218, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/hpc_modules/at10.0-based/deeplearning/pytorch-1.0.0/lib64/python3.5/site-packages/torch/serialization.py", line 143, in _with_file_like
    return body(f)
  File "/hpc_modules/at10.0-based/deeplearning/pytorch-1.0.0/lib64/python3.5/site-packages/torch/serialization.py", line 218, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/hpc_modules/at10.0-based/deeplearning/pytorch-1.0.0/lib64/python3.5/site-packages/torch/serialization.py", line 291, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <class 'module'>: attribute lookup module on builtins failed
