### ISSUE TITLE
Error with embeddings_to_torch.py

### ISSUE THREAD

**Issue by feralvam** [OpenNMT/OpenNMT-py#1331]
Hello,
I am trying to use `embeddings_to_torch.py` with my own data but I get an error:

```
Traceback (most recent call last):
  File "/tools/OpenNMT-py/tools/embeddings_to_torch.py", line 22, in get_vocabs
    vocab = fields[side].base_field.vocab
AttributeError: 'list' object has no attribute 'base_field'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/falva/anaconda3/envs/py3env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/falva/anaconda3/envs/py3env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tools/OpenNMT-py/tools/embeddings_to_torch.py", line 130, in <module>
    main()
  File "/tools/OpenNMT-py/tools/embeddings_to_torch.py", line 88, in main
    enc_vocab, dec_vocab = get_vocabs(opt.dict_file)
  File "/tools/OpenNMT-py/tools/embeddings_to_torch.py", line 24, in get_vocabs
    vocab = fields[side].vocab
AttributeError: 'list' object has no attribute 'vocab'
```

Any idea what the problem is? Thank you.

**Comment by flauted** [comment]
Can you try preprocessing your data again?

**Comment by feralvam** [comment]
That worked. I forgot I had pre-processed those files a while back, and perhaps something has changed in a more current version. Thanks!
