### ISSUE TITLE
install requirements.txt

### ISSUE THREAD

**Issue by sevilaybayatli** [OpenNMT/OpenNMT-py#1351]
when I was trying to install requirements.txt after clone OpenNMT-py,I got the error below

 install pip install -r requirements.txt
Collecting git+https://github.com/pytorch/text.git@master#wheel=torchtext (from -r requirements.txt (line 4))
  Cloning https://github.com/pytorch/text.git (to master) to /tmp/pip-UQvLyZ-build
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Collecting tqdm==4.30.* (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/76/4c/103a4d3415dafc1ddfe6a6624333971756e2d3dd8c6dc0f520152855f040/tqdm-4.30.0-py2.py3-none-any.whl
Collecting torch>=1.0 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/93/b3/672813e65ac7605bac14a2a8e40e1a18e03bf0ac588c6a799508ee66c289/torch-1.0.1.post2-cp27-cp27mu-manylinux1_x86_64.whl (582.5MB)
    99% |████████████████████████████████| 582.5MB 916kB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/_vendor/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/_vendor/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 55, in dumps
    "body": _b64_encode_bytes(body),
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/serialize.py", line 12, in _b64_encode_bytes
    return base64.b64encode(b).decode("ascii")
MemoryError

**Comment by pltrdy** [comment]
This may help: https://stackoverflow.com/a/31526029/5903959

**Comment by sevilaybayatli** [comment]
now got this error

OpenNMT-py$ pip --no-cache-dir install -r requirements.txt
Collecting git+https://github.com/pytorch/text.git@master#wheel=torchtext
(from -r requirements.txt (line 4))
  Cloning https://github.com/pytorch/text.git (to master) to
/tmp/pip-b4BtYw-build
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages
(from -r requirements.txt (line 1))
Collecting tqdm==4.30.* (from -r requirements.txt (line 2))
  Downloading
https://files.pythonhosted.org/packages/76/4c/103a4d3415dafc1ddfe6a6624333971756e2d3dd8c6dc0f520152855f040/tqdm-4.30.0-py2.py3-none-any.whl
(47kB)
    100% |████████████████████████████████| 51kB 511kB/s
Collecting torch>=1.0 (from -r requirements.txt (line 3))
  Downloading
https://files.pythonhosted.org/packages/93/b3/672813e65ac7605bac14a2a8e40e1a18e03bf0ac588c6a799508ee66c289/torch-1.0.1.post2-cp27-cp27mu-manylinux1_x86_64.whl
(582.5MB)
    100% |████████████████████████████████| 582.6MB 822kB/s
Collecting future (from -r requirements.txt (line 5))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None,
status=None)) after connection broken by 'ProtocolError('Connection
aborted.', error(104, 'Connection reset by peer'))': /simple/future/
  Downloading
https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
(829kB)
    100% |████████████████████████████████| 829kB 958kB/s
Collecting configargparse (from -r requirements.txt (line 6))
  Downloading
https://files.pythonhosted.org/packages/55/ea/f0ade52790bcd687127a302b26c1663bf2e0f23210d5281dbfcd1dfcda28/ConfigArgParse-0.14.0.tar.gz
Collecting requests (from torchtext==0.4.0->-r requirements.txt (line 4))
  Downloading
https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
(57kB)
    100% |████████████████████████████████| 61kB 1.2MB/s
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages
(from torchtext==0.4.0->-r requirements.txt (line 4))
Collecting certifi>=2017.4.17 (from requests->torchtext==0.4.0->-r
requirements.txt (line 4))
  Downloading
https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
(158kB)
    100% |████████████████████████████████| 163kB 756kB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests->torchtext==0.4.0->-r
requirements.txt (line 4))
  Downloading
https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
(133kB)
    100% |████████████████████████████████| 143kB 1.0MB/s
Collecting idna<2.9,>=2.5 (from requests->torchtext==0.4.0->-r
requirements.txt (line 4))
  Downloading
https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
(58kB)
    100% |████████████████████████████████| 61kB 894kB/s
Collecting urllib3<1.25,>=1.21.1 (from requests->torchtext==0.4.0->-r
requirements.txt (line 4))
  Downloading
https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
(118kB)
    100% |████████████████████████████████| 122kB 1.0MB/s
Installing collected packages: tqdm, torch, future, configargparse,
certifi, chardet, idna, urllib3, requests, torchtext
Exception:
Traceback (most recent call last):
  File
"/home/sevilay/.local/lib/python2.7/site-packages/pip/basecommand.py", line
215, in main
    status = self.run(options, args)
  File
"/home/sevilay/.local/lib/python2.7/site-packages/pip/commands/install.py",
line 342, in run
    prefix=options.prefix_path,
  File
"/home/sevilay/.local/lib/python2.7/site-packages/pip/req/req_set.py", line
784, in install
    **kwargs
  File
"/home/sevilay/.local/lib/python2.7/site-packages/pip/req/req_install.py",
line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File
"/home/sevilay/.local/lib/python2.7/site-packages/pip/req/req_install.py",
line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/wheel.py",
line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/sevilay/.local/lib/python2.7/site-packages/pip/wheel.py",
line 316, in clobber
    ensure_dir(destdir)
  File
"/home/sevilay/.local/lib/python2.7/site-packages/pip/utils/__init__.py",
line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied:
'/usr/local/lib/python2.7/dist-packages/tqdm-4.30.0.dist-info'

**Comment by pltrdy** [comment]
https://www.google.com/search?q=pip%20install%20OSError%3A%20[Errno%2013]%20Permission%20denied%3A

**Comment by sevilaybayatli** [comment]
thank you for your help my problem solved :)

**Comment by Warkanlock** [comment]
I'm added into the README.md for future users 

https://github.com/OpenNMT/OpenNMT-py/pull/1437
