### ISSUE TITLE
some question(images)

### ISSUE THREAD

**Issue by softwaregitgub** [OpenNMT/OpenNMT-py#1357]
![1552569794](https://user-images.githubusercontent.com/40431492/54360264-78169100-469f-11e9-8c8c-377692c42b94.jpg)
![1552569923(1)](https://user-images.githubusercontent.com/40431492/54360400-c035b380-469f-11e9-83c2-12d2b2e8b43f.jpg)

Is this problem caused by -src_vocab? I  I am not very clear about this, is this vocab.pt to be created by myself? Or is it generated in the preprocessing stage? What is his format? How do I specifically use it? I am very confused about this. Thank you teacher for your answer?

**Comment by pltrdy** [comment]
Provide the full error trace (we don't even see the exception on your screenshot...).

The vocab file is created during pre-processing. You just need to set the `-data` flag with the same value as `-save_data` in preprocess.

**Comment by softwaregitgub** [comment]
[2019-03-15 12:35:34,324 INFO]  * reloading /py/OpenNMT/data/im2text/a/demo.train.25477.pt.
[2019-03-15 12:35:34,377 INFO]  * reloading /py/OpenNMT/data/im2text/a/demo.train.25478.pt.
[2019-03-15 12:35:34,430 INFO]  * reloading /py/OpenNMT/data/im2text/a/demo.train.25479.pt.
[2019-03-15 12:35:34,485 INFO]  * reloading /py/OpenNMT/data/im2text/a/demo.train.25480.pt.
[2019-03-15 12:35:34,486 INFO]  * tgt vocab size: 503.
Traceback (most recent call last):
  File "E:/py/OpenNMT/preprocess.py", line 155, in <module>
    main(opt)
  File "E:/py/OpenNMT/preprocess.py", line 140, in main
    build_save_vocab(train_dataset_files, fields, opt)
  File "E:/py/OpenNMT/preprocess.py", line 91, in build_save_vocab
    torch.save(fields, vocab_path)
  File "D:\Anaconda3\lib\site-packages\torch\serialization.py", line 218, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "D:\Anaconda3\lib\site-packages\torch\serialization.py", line 143, in _with_file_like
    return body(f)
  File "D:\Anaconda3\lib\site-packages\torch\serialization.py", line 218, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "D:\Anaconda3\lib\site-packages\torch\serialization.py", line 291, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <function Field.<lambda> at 0x0000017358624268>: attribute lookup Field.<lambda> on torchtext.data.field failed

Thank you for your answer! New question, how can this be solved? Thank you teacher for your answer.

**Comment by vince62s** [comment]
wrong version of torchtext, please meet the requirements.

**Comment by softwaregitgub** [comment]
> wrong version of torchtext, please meet the requirements.

Thank you teacher for your answer! I replaced the appropriate version.
