### ISSUE TITLE
AttributeError: Can't get attribute 'TextDataset' on <module 'onmt.inputters.text_dataset' from '/home/zhangliang/OpenNMT-py/onmt/inputters/text_dataset.py'>

### ISSUE THREAD

**Issue by karlgeorge** [OpenNMT/OpenNMT-py#1380]
this happened after updating to 0.8.2:
Traceback (most recent call last):
  File "train.py", line 109, in <module>
    main(opt)
  File "train.py", line 39, in main
    single_main(opt, 0)
  File "/home/zhangliang/OpenNMT-py/onmt/train_single.py", line 118, in main
    valid_steps=opt.valid_steps)
  File "/home/zhangliang/OpenNMT-py/onmt/trainer.py", line 208, in train
    self._accum_batches(train_iter)):
  File "/home/zhangliang/OpenNMT-py/onmt/trainer.py", line 142, in _accum_batches
    for batch in iterator:
  File "/home/zhangliang/OpenNMT-py/onmt/inputters/inputter.py", line 588, in __iter__
    for batch in self._iter_dataset(path):
  File "/home/zhangliang/OpenNMT-py/onmt/inputters/inputter.py", line 558, in _iter_dataset
    cur_dataset = torch.load(path)
  File "/home/zhangliang/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/zhangliang/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'TextDataset' on <module 'onmt.inputters.text_dataset' from '/home/zhangliang/OpenNMT-py/onmt/inputters/text_dataset.py'>

**Comment by karlgeorge** [comment]
There is no problem after re-preprocess my datasets. Before that what i use was the data preprocessed by the pre-version.
