### ISSUE TITLE
n_best error in translate.py: IndexError: list index out of range

### ISSUE THREAD

**Issue by alphadl** [OpenNMT/OpenNMT-py#1388]
When I translate a file with 3000 lines text by using default n_best, all work well~
However, when I set the n_best to 10, it reports this error when translation finished 2000 lines

```
Traceback (most recent call last):
  File "***/translate.py", line 48, in <module>
    main(opt)
  File "***/translate.py", line 32, in main
    attn_debug=opt.attn_debug
  File "***/onmt/translate/translator.py", line 327, in translate
    translations = xlation_builder.from_batch(batch_data)
  File "***/onmt/translate/translation.py", line 89, in from_batch
    for n in range(self.n_best)]
  File "***/onmt/translate/translation.py", line 89, in <listcomp>
    for n in range(self.n_best)]
IndexError: list index out of range
```

**Comment by vince62s** [comment]
You need a beam >=10

**Comment by chrisrytting** [comment]
Why do you need a beam >= 10 @vince62s ?

**Comment by vince62s** [comment]
When you want n_best = 10 hypotheses you need a beam > 10 to create that many choices.
