### ISSUE TITLE
Running on GPU IDs 4,5,6,7 on the same node

### ISSUE THREAD

**Issue by pbamotra** [OpenNMT/OpenNMT-py#1456]
```
/workspace/OpenNMT-py# CUDA_VISIBLE_DEVICES="4,5,6,7" python train.py -data data/cate2/processed -save_model cate_model_reverse --encoder_type transformer --decoder_type transformer --layers 4 -world_size 8 -gpu_ranks 4 5 6 7 --tensorboard    
                                                                                                                                   
[2019-06-04 08:41:35,843 INFO] Loading dataset from data/cate2/processed.train.0.pt
THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=33 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    main(opt)
  File "train.py", line 78, in main
    p.join()
  File "/opt/conda/envs/learn-dev/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/opt/conda/envs/learn-dev/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/opt/conda/envs/learn-dev/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "train.py", line 180, in signal_handler
    raise Exception(msg)
Exception: 

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/workspace/OpenNMT-py/train.py", line 138, in run
    single_main(opt, device_id, batch_queue, semaphore)
  File "/workspace/OpenNMT-py/onmt/train_single.py", line 45, in main
    configure_process(opt, device_id)
  File "/workspace/OpenNMT-py/onmt/train_single.py", line 38, in configure_process
    torch.cuda.set_device(device_id)
  File "/opt/conda/envs/learn-dev/lib/python3.7/site-packages/torch/cuda/__init__.py", line 265, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:33

```

What am I doing wrong here?

With world size 4, I get

```
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    main(opt)
  File "train.py", line 21, in main
    ArgumentParser.validate_train_opts(opt)
  File "/workspace/OpenNMT-py/onmt/utils/parse.py", line 101, in validate_train_opts
    "-gpu_ranks should have master(=0) rank "
AssertionError: -gpu_ranks should have master(=0) rank unless -world_size is greater than len(gpu_ranks).
```

**Comment by pltrdy** [comment]
Because if you set `CUDA_VISIBLE_DEVICES="4,5,6,7"` then CUDA really sees 4 GPUs. Which means that device ids in pytorch goes from 0 to 4 so you should set `-gpu_ranks 0 1 2 3`.

In other words, you would use `-gpu_ranks 4 5 6 7` only if you have >=8 GPUs visible, i.e. you set `CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"`
