### ISSUE TITLE
A Similar Error with #1454

### ISSUE THREAD

**Issue by ColainCYY** [OpenNMT/OpenNMT-py#1500]
Hi, my error is samiliar with [#1454](https://github.com/OpenNMT/OpenNMT-py/issues/1454)，but no error-information about queues.

I confirmed that my code is the latest. The OPENNMT has run for 3000 steps before the error. Thanks!
```
Traceback (most recent call last):
  File "train.py", line 200, in <module>
    main(opt)
  File "train.py", line 82, in main
    p.join()
  File "/srv/data0/hzcuiyuanyuan/anaconda2/envs/py36/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/srv/data0/hzcuiyuanyuan/anaconda2/envs/py36/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/srv/data0/hzcuiyuanyuan/anaconda2/envs/py36/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "train.py", line 184, in signal_handler
    raise Exception(msg)
Exception:

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/srv/data0/hzcuiyuanyuan/py36/OpenNMT-py/train.py", line 142, in run
    single_main(opt, device_id, batch_queue, semaphore)
  File "/srv/data0/hzcuiyuanyuan/py36/OpenNMT-py/onmt/train_single.py", line 139, in main
    valid_steps=opt.valid_steps)
  File "/srv/data0/hzcuiyuanyuan/py36/OpenNMT-py/onmt/trainer.py", line 224, in train
    self._accum_batches(train_iter)):
  File "/srv/data0/hzcuiyuanyuan/py36/OpenNMT-py/onmt/trainer.py", line 162, in _accum_batches
    for batch in iterator:
  File "/srv/data0/hzcuiyuanyuan/py36/OpenNMT-py/onmt/train_single.py", line 116, in _train_iter
    batch = batch_queue.get()
  File "/srv/data0/hzcuiyuanyuan/anaconda2/envs/py36/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/srv/data0/hzcuiyuanyuan/anaconda2/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 109, in rebuild_cuda_tensor
    event_sync_required)
RuntimeError: CUDA error: unknown error
```

**Comment by vince62s** [comment]
Please post your command line and pytorch version
