### ISSUE TITLE
list index out of range while translating file

### ISSUE THREAD

**Issue by stushar22** [OpenNMT/OpenNMT-py#1508]
Traceback (most recent call last):
  File "translate.py", line 48, in <module>
    main(opt)
  File "translate.py", line 32, in main
    attn_debug=opt.attn_debug
  File "/home/aai/OpenNMT-py/onmt/translate/translator.py", line 300, in translate
    filter_pred=self._filter_pred
  File "/home/aai/OpenNMT-py/onmt/inputters/dataset_base.py", line 130, in __init__
    ex = Example.fromdict(ex_dict, ex_fields)
  File "/home/aai/miniconda3/envs/tts/lib/python3.7/site-packages/torchtext/data/example.py", line 28, in fromdict
    setattr(ex, name, field.preprocess(data[key]))
  File "/home/aai/OpenNMT-py/onmt/inputters/text_dataset.py", line 148, in preprocess
    return [f.preprocess(x) for _, f in self.fields]
  File "/home/aai/OpenNMT-py/onmt/inputters/text_dataset.py", line 148, in <listcomp>
    return [f.preprocess(x) for _, f in self.fields]
  File "/home/aai/miniconda3/envs/tts/lib/python3.7/site-packages/torchtext/data/field.py", line 215, in preprocess
    x = self.tokenize(x.rstrip('\n'))
  File "/home/aai/OpenNMT-py/onmt/inputters/text_dataset.py", line 68, in _feature_tokenize
    tokens = [t.split(feat_delim)[layer] for t in tokens]
  File "/home/aai/OpenNMT-py/onmt/inputters/text_dataset.py", line 68, in <listcomp>
    tokens = [t.split(feat_delim)[layer] for t in tokens]
IndexError: list index out of range

**Comment by vince62s** [comment]
post your command line.

**Comment by stushar22** [comment]
> post your command line.

Copy pasted it above please refer it

**Comment by vince62s** [comment]
this is a trace back not a command line.

**Comment by stushar22** [comment]
> this is a trace back not a command line.

![ListIndexOutofBound](https://user-images.githubusercontent.com/41885910/61620818-3cb05280-ac8f-11e9-8506-a4358d2af0c4.png)
Please see this .
I have trained model for English to Hindi language. My src train data was POS tagged.

**Comment by vince62s** [comment]
something must be wrong with your phrasetable.

**Comment by stushar22** [comment]
> something must be wrong with your phrasetable.

Thanks for your help :-)
I figured out it was not phrasetable but it was test file. I had not POS tagged test file content. It worked well after POS tagging.
