### ISSUE TITLE
BLEU score perl script fails on Windows with tokens like <sta>

### ISSUE THREAD

**Issue by catskillsresearch** [OpenNMT/OpenNMT-py#1518]
My output tokens for a machine translation task include items like <sta>, <laugh> and so on.  When I include the --report_bleu option on evaluation, I get the complaint 
from Perl on Windows "< was unexpected at this time".  Is there a way to preprocess the Perl input to escape the '<' characters?  The full dump looks like this (the character set is Arabic):

```
CMD perl C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg/tools/multi-bleu.perl [b'\xd9\x85 \xd9\x87\r\n', b'\xda\xa9 \xd8\xa7 \xd8\xb1\r\n', b'\xda\x86 \xdb\x90\r\n', b'\xd9\xbe \xd9\x87 <space> \xd8\xae \xdb\x8c \xd8\xb1 <space> \xdb\x8c \xdb\x90\r\n', b'\xd8\xaf \xd8\xba \xd9\x87 <space> \xd9\x87 \xd9\x85\r\n', b'\xda\xa9 \xda\x9a \xdb\x90 \xd9\x86 \xd9\x87\r\n', b'\xda\xa9 \xda\x93 \xd9\x84\r\n', b'\xda\xa9 \xd9\x88 \xd9\x87\r\n', b'\xda\x85 \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd8\xb3 \xdb\x90\r\n', b'\xd8\xaf \xdb\x90 <space> \xd9\x88 \xd8\xac \xd9\x87\r\n', b'\xd8\xaa \xd9\x87 <space> \xd8\xa8 \xd9\x87 <space> \xd8\xaf \xd8\xa7\r\n', b'<no-speech> <space> \xda\x85 \xd9\x86 \xda\xab \xd9\x87\r\n', b'\xda\xa9 \xd9\x88 \xdb\x90\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xd8\xa7 \xd9\x88 \xd8\xb3 -\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xd9\x87 \xd9\x84 \xd9\x88\r\n', b'\xdb\x8c \xd8\xae -\r\n', b'\xd9\x86 \xd9\x87\r\n', b'\xd9\x88 \xd9\x84 \xdb\x90\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd8\xae \xd9\x88 <space> \xda\x86 \xdb\x90\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x84 \xd9\x88\r\n', b'\xd9\xbe \xdb\x8c \xd8\xba \xd8\xa7 \xd9\x85\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\xbe \xda\x9a \xd8\xaa \xd9\x88\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xd8\xb4 \xd9\x8a\r\n', b'\xda\x86 \xdb\x90\r\n', b'\xd9\xbe \xd9\x88 \xd9\x87 <space> \xd9\x86 \xd9\x87 <space> \xd8\xb4 \xd9\x88 \xd9\x85\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x84 \xd9\x88 <space> <sta>\r\n', b'\xd9\x86 \xd9\x87\r\n', b'\xda\x85 \xd9\x87\r\n', b'\xd9\x88 \xd9\x87\r\n', b'\xda\x85 \xd9\x88 \xda\xa9\r\n', b'\xd9\x86 \xd9\x87\r\n', b'\xd9\x87 \xd9\x84 \xd9\x88\r\n', b'\xd9\x84 \xd9\x85 \xd9\x88 \xd9\x86 \xda\x81 <space> \xd8\xaf \xdb\x90 <space> \xda\xa9 \xda\x93 \xd8\xa6\r\n', b'\xd8\xa8 \xd9\x84\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x85 \xd9\x87 <space> \xd8\xa8 \xd9\x87 <space> \xd9\x88 \xda\xa9 \xda\x93 \xd9\x88\r\n', b'\xd8\xa7 \xd9\x88\r\n', b'\xda\xa9 \xd8\xa8 \xd8\xa7 \xda\x93 \xdb\x90\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xda\x85 \xd9\x88 \xda\xa9\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\xbe \xd9\x87\r\n', b'\xda\x9a \xd9\x87 <space> \xd8\xaa \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'<no-speech> <space> \xda\xa9 \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xd8\xa8 \xd9\x84 \xda\xa9 \xd9\x84\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87 <space> \xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x87\r\n', b'\xd9\x88 \xd8\xb9 \xd9\x84 \xdb\x8c \xda\xa9 \xd9\x85\r\n', b'\xda\x85 \xd9\x86 \xda\xab \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd8\xa7 \xd9\x88 \xd8\xa7 \xd8\xb2\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x88 \xd8\xb9 \xd9\x84 \xdb\x8c \xda\xa9 \xd9\x85\r\n', b'\xda\x9a \xd9\x87 <space> <hes>\r\n', b'\xd8\xba \xd9\x86 \xda\x86 \xdb\x90\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x85 \xd9\x87 <space> \xd8\xae \xd8\xa8 -\r\n', b'\xd9\x87 \xd9\x84 \xd9\x88\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x88 <space> \xda\xa9 \xd9\x87 <space> \xd9\x86 \xd9\x87\r\n', b'<dtmf>\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x85 \xd8\xaf \xd8\xa7 \xd8\xb3 \xdb\x90\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n']
< was unexpected at this time.

Traceback (most recent call last):
  File "translate.py", line 51, in <module>
    main(opt)
  File "translate.py", line 35, in main
    attn_debug=opt.attn_debug
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg\onmt\translate\translator.py", line 392, in translate
    msg = self._report_bleu(tgt)
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg\onmt\translate\translator.py", line 836, in _report_bleu
    stdin=self.out_file, shell=True
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'perl C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg/tools/multi-bleu.perl [b'\xd9\x85 \xd9\x87\r\n', b'\xda\xa9 \xd8\xa7 \xd8\xb1\r\n', b'\xda\x86 \xdb\x90\r\n', b'\xd9\xbe \xd9\x87 <space> \xd8\xae \xdb\x8c \xd8\xb1 <space> \xdb\x8c \xdb\x90\r\n', b'\xd8\xaf \xd8\xba \xd9\x87 <space> \xd9\x87 \xd9\x85\r\n', b'\xda\xa9 \xda\x9a \xdb\x90 \xd9\x86 \xd9\x87\r\n', b'\xda\xa9 \xda\x93 \xd9\x84\r\n', b'\xda\xa9 \xd9\x88 \xd9\x87\r\n', b'\xda\x85 \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd8\xb3 \xdb\x90\r\n', b'\xd8\xaf \xdb\x90 <space> \xd9\x88 \xd8\xac \xd9\x87\r\n', b'\xd8\xaa \xd9\x87 <space> \xd8\xa8 \xd9\x87 <space> \xd8\xaf \xd8\xa7\r\n', b'<no-speech> <space> \xda\x85 \xd9\x86 \xda\xab \xd9\x87\r\n', b'\xda\xa9 \xd9\x88 \xdb\x90\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xd8\xa7 \xd9\x88 \xd8\xb3 -\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xd9\x87 \xd9\x84 \xd9\x88\r\n', b'\xdb\x8c \xd8\xae -\r\n', b'\xd9\x86 \xd9\x87\r\n', b'\xd9\x88 \xd9\x84 \xdb\x90\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd8\xae \xd9\x88 <space> \xda\x86 \xdb\x90\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x84 \xd9\x88\r\n', b'\xd9\xbe \xdb\x8c \xd8\xba \xd8\xa7 \xd9\x85\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\xbe \xda\x9a \xd8\xaa \xd9\x88\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xd8\xb4 \xd9\x8a\r\n', b'\xda\x86 \xdb\x90\r\n', b'\xd9\xbe \xd9\x88 \xd9\x87 <space> \xd9\x86 \xd9\x87 <space> \xd8\xb4 \xd9\x88 \xd9\x85\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x84 \xd9\x88 <space> <sta>\r\n', b'\xd9\x86 \xd9\x87\r\n', b'\xda\x85 \xd9\x87\r\n', b'\xd9\x88 \xd9\x87\r\n', b'\xda\x85 \xd9\x88 \xda\xa9\r\n', b'\xd9\x86 \xd9\x87\r\n', b'\xd9\x87 \xd9\x84 \xd9\x88\r\n', b'\xd9\x84 \xd9\x85 \xd9\x88 \xd9\x86 \xda\x81 <space> \xd8\xaf \xdb\x90 <space> \xda\xa9 \xda\x93 \xd8\xa6\r\n', b'\xd8\xa8 \xd9\x84\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x85 \xd9\x87 <space> \xd8\xa8 \xd9\x87 <space> \xd9\x88 \xda\xa9 \xda\x93 \xd9\x88\r\n', b'\xd8\xa7 \xd9\x88\r\n', b'\xda\xa9 \xd8\xa8 \xd8\xa7 \xda\x93 \xdb\x90\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xda\x85 \xd9\x88 \xda\xa9\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\xbe \xd9\x87\r\n', b'\xda\x9a \xd9\x87 <space> \xd8\xaa \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'<no-speech> <space> \xda\xa9 \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xd8\xa8 \xd9\x84 \xda\xa9 \xd9\x84\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87 <space> \xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x87\r\n', b'\xd9\x88 \xd8\xb9 \xd9\x84 \xdb\x8c \xda\xa9 \xd9\x85\r\n', b'\xda\x85 \xd9\x86 \xda\xab \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd8\xa7 \xd9\x88 \xd8\xa7 \xd8\xb2\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x88\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x88 \xd8\xb9 \xd9\x84 \xdb\x8c \xda\xa9 \xd9\x85\r\n', b'\xda\x9a \xd9\x87 <space> <hes>\r\n', b'\xd8\xba \xd9\x86 \xda\x86 \xdb\x90\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x85 \xd9\x87 <space> \xd8\xae \xd8\xa8 -\r\n', b'\xd9\x87 \xd9\x84 \xd9\x88\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x88 <space> \xda\xa9 \xd9\x87 <space> \xd9\x86 \xd9\x87\r\n', b'<dtmf>\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xd9\x87 \xd9\x85 \xd8\xaf \xd8\xa7 \xd8\xb3 \xdb\x90\r\n', b'\xda\x9a \xd9\x87\r\n', b'\xda\x9a \xd9\x87\r\n']' returned non-zero exit status 1.
```

**Comment by vince62s** [comment]
unfortunately you will have to get some help in the "Perl on Windows" world....
