### ISSUE TITLE
Error in preprocess.py

### ISSUE THREAD

**Issue by ayushidalmia** [OpenNMT/OpenNMT-py#152]
I get the following error on preprocessing

```
Building source vocabulary...
Traceback (most recent call last):
  File "preprocess.py", line 293, in <module>
    main()
  File "preprocess.py", line 249, in main
    opt.src_vocab_size)
  File "preprocess.py", line 117, in initVocabulary
    genWordVocab, genFeaturesVocabs = makeVocabulary(dataFile, vocabSize)
  File "preprocess.py", line 96, in makeVocabulary
    vocab = vocab.prune(size)
  File "/home/ayushidalmia/OpenNMT-py/onmt/Dict.py", line 111, in prune
    for i in idx[:size]:
ValueError: result of slicing is an empty tensor
```

I digged deeper and found that I am using src_vocab_size=0 as I did not want to prune any vocabulary. This was the notion for the lua code. In order to not prune, here I should use a value greater than my vocab or not give any value at all?

**Comment by ayushidalmia** [comment]
Created a  PR for it here:

https://github.com/OpenNMT/OpenNMT-py/pull/153

**Comment by srush** [comment]
Oh I see, this agrees with lua. Will accept PR.
