### ISSUE TITLE
Coverage loss option failing

### ISSUE THREAD

**Issue by catskillsresearch** [OpenNMT/OpenNMT-py#1528]
When I add coverage loss options to my training batch, it fails.  If I remove the options the training proceeds normally. In particular these two options:

`-coverage_attn -lambda_coverage 0.5`

and I get this result:

`python train.py -gpu_ranks 0 -tensorboard -report_every 1 -train_steps 3000000 -warmup_steps 1 -save_checkpoint_steps 1000 -batch_size 200  -model_type audio -sample_rate 8000 -enc_rnn_size 1024 -dec_rnn_size 1024  -enc_layers 6 -dec_layers 2 -audio_enc_pooling 1,1,1,2,2,2 -rnn_type LSTM -global_attention general -max_grad_norm 100 -bridge -image_channel_size 1 -dropout 0.1 -coverage_attn -lambda_coverage 0.5 -data g:\OS_PRE_STAGE\conversational\training\audio_to_letters_shards\pashto -save_model g:\OS_PRE_STAGE\conversational\training\audio_to_letters_model\model2_1024_1024_6_2_LSTM_adam_200_1000 -optim adam -learning_rate 0.0003 -learning_rate_decay 0.8 -normalization sents -train_from g:\OS_PRE_STAGE\conversational\training\audio_to_letters_model\model2_1024_1024_6_2_LSTM_adam_2_1000_step_599000.pt 
[2019-08-12 23:09:31,557 INFO] Loading checkpoint from g:\OS_PRE_STAGE\conversational\training\audio_to_letters_model\model2_1024_1024_6_2_LSTM_adam_2_1000_step_599000.pt
[2019-08-12 23:09:31,791 INFO] Loading vocab from checkpoint at g:\OS_PRE_STAGE\conversational\training\audio_to_letters_model\model2_1024_1024_6_2_LSTM_adam_2_1000_step_599000.pt.
[2019-08-12 23:09:31,791 INFO]  * tgt vocab size = 75
[2019-08-12 23:09:31,791 INFO] Building model...
C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\torch\nn\modules\rnn.py:54: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
[2019-08-12 23:09:35,228 INFO] NMTModel(
  (encoder): AudioEncoder(
    (dropout): Dropout(p=0.1)
    (W): Linear(in_features=1024, out_features=1024, bias=False)
    (batchnorm_0): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn_0): LSTM(81, 1024, dropout=0.1)
    (pool_0): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (rnn_1): LSTM(1024, 1024, dropout=0.1)
    (pool_1): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (batchnorm_1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn_2): LSTM(1024, 1024, dropout=0.1)
    (pool_2): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (batchnorm_2): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn_3): LSTM(1024, 1024, dropout=0.1)
    (pool_3): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (batchnorm_3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn_4): LSTM(1024, 1024, dropout=0.1)
    (pool_4): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (batchnorm_4): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn_5): LSTM(1024, 1024, dropout=0.1)
    (pool_5): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (batchnorm_5): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(75, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.1)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.1)
      (layers): ModuleList(
        (0): LSTMCell(1524, 1024)
        (1): LSTMCell(1024, 1024)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=1024, out_features=1024, bias=False)
      (linear_out): Linear(in_features=2048, out_features=1024, bias=False)
      (linear_cover): Linear(in_features=1, out_features=1024, bias=False)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=1024, out_features=75, bias=True)
    (1): Cast()
    (2): LogSoftmax()
  )
)
[2019-08-12 23:09:35,228 INFO] encoder: 47579136
[2019-08-12 23:09:35,228 INFO] decoder: 22102727
[2019-08-12 23:09:35,228 INFO] * number of parameters: 69681863
[2019-08-12 23:09:35,697 INFO] Starting training on GPU: [0]
[2019-08-12 23:09:35,697 INFO] Start training loop without validation...
[2019-08-12 23:09:35,697 INFO] Loading dataset from g:\OS_PRE_STAGE\conversational\training\audio_to_letters_shards\pashto.train.00.pt
[2019-08-12 23:09:35,712 INFO] number of examples: 1000
Traceback (most recent call last):
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg\onmt\trainer.py", line 369, in _gradient_accumulation
    trunc_size=trunc_size)
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg\onmt\utils\loss.py", line 165, in __call__
    loss, stats = self._compute_loss(batch, **shard)
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg\onmt\utils\loss.py", line 265, in _compute_loss
    loss += coverage_loss
RuntimeError: output with shape [] doesn't match the broadcast shape [2200]
[2019-08-12 23:09:36,134 INFO] At step 599001, we removed a batch - accum 0
Traceback (most recent call last):
  File "train.py", line 109, in <module>
    main(opt)
  File "train.py", line 39, in main
    single_main(opt, 0)
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg\onmt\train_single.py", line 143, in main
    valid_steps=opt.valid_steps)
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg\onmt\trainer.py", line 251, in train
    report_stats)
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg\onmt\trainer.py", line 445, in _maybe_report_training
    multigpu=self.n_gpu > 1)
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg\onmt\utils\report_manager.py", line 77, in report_training
    step, num_steps, learning_rate, report_stats)
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg\onmt\utils\report_manager.py", line 128, in _report_training
    learning_rate, self.start_time)
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg\onmt\utils\statistics.py", line 120, in output
    self.accuracy(),
  File "C:\Users\erxnm\Anaconda3\envs\cuda_torch\lib\site-packages\opennmt_py-0.9.1-py3.7.egg\onmt\utils\statistics.py", line 90, in accuracy
    return 100 * (self.n_correct / self.n_words)
ZeroDivisionError: division by zero
`
Can someone please suggest a fix?

NOTE: When I debug into this, the loss is a single number (tensor shape 1), but the coverage loss is a size 2800 vector.  So it's trying to add apples and oranges here:

`        loss = self.criterion(scores, gtruth)
        if self.lambda_coverage != 0.0:
            coverage_loss = self._compute_coverage_loss(
                std_attn=std_attn, coverage_attn=coverage_attn)
            loss += coverage_loss`

I would expect self.criterion and self._compute_coverage_loss to return the same tensor shape by construction.

![coverage_loss_bug](https://user-images.githubusercontent.com/38082822/62940210-13bc4280-bda1-11e9-9938-27d2aae49ee8.JPG)

NOTE: The Loss function is NLLLoss.  It returns a single number.    Then _compute_coverage_loss is

`    def _compute_coverage_loss(self, std_attn, coverage_attn):
        covloss = torch.min(std_attn, coverage_attn).sum(2).view(-1)
        covloss *= self.lambda_coverage
        return covloss
`
The line 

`    covloss = torch.min(std_attn, coverage_attn).sum(2).view(-1)
`
returns a long vector.  If I add a sum(0) at the end I'm OK but that's just a guess:

`torch.min(std_attn, coverage_attn).sum(2).view(-1).sum(0)`

**Comment by XinnuoXu** [comment]
Yeah, I also met this problem...

**Comment by pltrdy** [comment]
Thanks for reporting it. Strange that I had no issue with this, however I opened a PR doing ~ what you suggested (using just 1 sum along all dimensions).

You can try I'll be testing it as well.

**Comment by catskillsresearch** [comment]
Hi Paul, can you give me some tips on how to implement Word Error Rate as a loss function?  This is WER=(nInserts+nDeletes+nReplaces)/Length(target).  The insertions, deletions and replacements can be computed with Levenshtein.editops (https://pypi.org/project/python-Levenshtein/).

I'm asking because I tried doing a Pashto audio to Pashto graphemes translator with OpenNMT-py.  I found that with batch sizes of even 2, accuracy showed 99% after 21 hours of training, but then if you go to batch size 1, you see 100% followed by 2 or 3 50% matches frequently.  I.e. the loss function doesn't batch well and results are very spotty.  I gave a talk on this at NIST a few days ago and I was laughed out of the room by people doing successful translators using Kaldi + Rover pre-trained with 50 other languages for all but the top layer.  My slides are attached.  Also the NIST specification is attached.  Look at page 17 for WER.  Look at pages 34 and 35 of my slides for the huge dropoff in accuracy going from batch > 1 to batch 1.  I am hoping that implementing WER as a loss function would fix this.  I also added use of coverage loss in my model, because of a problem that without it, really long predictions can be generated versus the target phrase.  Other people have noted this problem here.
[opensat19_crc_slides_20aug2019_version_20190820.pdf](https://github.com/OpenNMT/OpenNMT-py/files/3530639/opensat19_crc_slides_20aug2019_version_20190820.pdf)

[opensat19_evaluation_plan_v4_3-28-19_1.pdf](https://github.com/OpenNMT/OpenNMT-py/files/3530634/opensat19_evaluation_plan_v4_3-28-19_1.pdf)
