### ISSUE TITLE
Error in running the speech to text toy example

### ISSUE THREAD

**Issue by kushagra1729** [OpenNMT/OpenNMT-py#1540]
Hey! Thanks for writing this package. I am using python version 3.5 and Pytorch version 1.2.0 and I am on master branch updated with the repository.
I followed the exact steps mentioned in http://opennmt.net/OpenNMT-py/speech2text.html. I am able to download the data and pre-process but while training, I am getting this error :
[2019-08-22 23:11:52,556 INFO] encoder: 7952384
[2019-08-22 23:11:52,556 INFO] decoder: 4206763
[2019-08-22 23:11:52,556 INFO] * number of parameters: 12159147
[2019-08-22 23:11:52,557 INFO] Starting training on GPU: [0]
[2019-08-22 23:11:52,557 INFO] Start training loop and validate every 10000 steps...
[2019-08-22 23:11:52,558 INFO] Loading dataset from data/speech/demo.train.0.pt
[2019-08-22 23:11:52,612 INFO] number of examples: 300
Traceback (most recent call last):
  File "train.py", line 200, in <module>
    main(opt)
  File "train.py", line 86, in main
    single_main(opt, 0)
  File "/exp/juneja/OpenNMT-py/onmt/train_single.py", line 143, in main
    valid_steps=opt.valid_steps)
  File "/exp/juneja/OpenNMT-py/onmt/trainer.py", line 243, in train
    report_stats)
  File "/exp/juneja/OpenNMT-py/onmt/trainer.py", line 357, in _gradient_accumulation
    outputs, attns = self.model(src, tgt, src_lengths, bptt=bptt)
  File "/home/juneja/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/exp/juneja/OpenNMT-py/onmt/models/model.py", line 42, in forward
    enc_state, memory_bank, lengths = self.encoder(src, lengths)
  File "/home/juneja/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/exp/juneja/OpenNMT-py/onmt/encoders/audio_encoder.py", line 119, in forward
    memory_bank = pool(memory_bank)
  File "/home/juneja/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/juneja/.local/lib/python3.5/site-packages/torch/nn/modules/pooling.py", line 76, in forward
    self.return_indices)
  File "/home/juneja/.local/lib/python3.5/site-packages/torch/_jit_internal.py", line 134, in fn
    return if_false(*args, **kwargs)
  File "/home/juneja/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 456, in _max_pool1d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: Given input size: (8x1x1). Calculated output size: (8x1x0). Output size is too small

**Comment by vince62s** [comment]
Do you mind trying with pytorch 1.1 ?

**Comment by francoishernandez** [comment]
Just tried again with pytorch 1.2.0 and it's working fine here. (Ubuntu 18.04.3 // python 3.6.8)
@kushagra1729 do you have the proper requirements installed (e.g. torch audio links to a specific commit in requirements.opt.txt)?
Also, did preprocessing run properly?

**Comment by malahmadi1** [comment]
I've got the same issue, I followed exactly the instructions to run the speech recognizer. I've pytorch 1.2 and Python 3.6.8). and yes @francoishernandez, the preprocessing went through without any issue. 

python3 train.py -model_type audio -enc_rnn_size 512 -dec_rnn_size 512 -audio_enc_pooling 1,1,2,2 -dropout 0 -enc_layers 4 -dec_layers 1 -rnn_type LSTM -data data/speech/demo -save_model demo-model -global_attention mlp -gpu_ranks 0 -batch_size 8 -optim adam -max_grad_norm 100 -learning_rate 0.0003 -learning_rate_decay 0.8 -train_steps 1000
[2019-08-26 04:00:16,267 INFO]  * tgt vocab size = 31
[2019-08-26 04:00:16,267 INFO] Building model...
[2019-08-26 04:00:19,272 INFO] NMTModel(
  (encoder): AudioEncoder(
    (W): Linear(in_features=512, out_features=512, bias=False)
    (batchnorm_0): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn_0): LSTM(161, 512)
    (pool_0): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (rnn_1): LSTM(512, 512)
    (pool_1): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (batchnorm_1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn_2): LSTM(512, 512)
    (pool_2): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (batchnorm_2): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn_3): LSTM(512, 512)
    (pool_3): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (batchnorm_3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(31, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.0, inplace=False)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.0, inplace=False)
      (layers): ModuleList(
        (0): LSTMCell(1012, 512)
      )
    )
    (attn): GlobalAttention(
      (linear_context): Linear(in_features=512, out_features=512, bias=False)
      (linear_query): Linear(in_features=512, out_features=512, bias=True)
      (v): Linear(in_features=512, out_features=1, bias=False)
      (linear_out): Linear(in_features=1024, out_features=512, bias=True)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=512, out_features=31, bias=True)
    (1): Cast()
    (2): LogSoftmax()
  )
)
[2019-08-26 04:00:19,272 INFO] encoder: 7952384
[2019-08-26 04:00:19,272 INFO] decoder: 4206763
[2019-08-26 04:00:19,272 INFO] * number of parameters: 12159147
[2019-08-26 04:00:19,273 INFO] Starting training on GPU: [0]
[2019-08-26 04:00:19,273 INFO] Start training loop and validate every 10000 steps...
[2019-08-26 04:00:19,274 INFO] Loading dataset from data/speech/demo.train.0.pt
[2019-08-26 04:00:19,278 INFO] number of examples: 300
Traceback (most recent call last):
  File "train.py", line 200, in <module>
    main(opt)
  File "train.py", line 86, in main
    single_main(opt, 0)
  File "/home/mohammad/Dropbox/PycharmProjects/OpenNMT-py/onmt/train_single.py", line 143, in main
    valid_steps=opt.valid_steps)
  File "/home/mohammad/Dropbox/PycharmProjects/OpenNMT-py/onmt/trainer.py", line 243, in train
    report_stats)
  File "/home/mohammad/Dropbox/PycharmProjects/OpenNMT-py/onmt/trainer.py", line 357, in _gradient_accumulation
    outputs, attns = self.model(src, tgt, src_lengths, bptt=bptt)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mohammad/Dropbox/PycharmProjects/OpenNMT-py/onmt/models/model.py", line 42, in forward
    enc_state, memory_bank, lengths = self.encoder(src, lengths)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mohammad/Dropbox/PycharmProjects/OpenNMT-py/onmt/encoders/audio_encoder.py", line 119, in forward
    memory_bank = pool(memory_bank)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 76, in forward
    self.return_indices)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/_jit_internal.py", line 134, in fn
    return if_false(*args, **kwargs)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 456, in _max_pool1d
    input, kernel_size, stride, padding, dilation, ceil_mode)
**RuntimeError: Given input size: (8x1x1). Calculated output size: (8x1x0). Output size is too small**

**Comment by francoishernandez** [comment]
@malahmadi1 for next time please do not re-open an issue for the same topic (#1544).
I ran the whole thing from scratch:
```
wget -O data/speech.tgz http://lstm.seas.harvard.edu/latex/speech.tgz
tar zxf data/speech.tgz -C data/

python3 preprocess.py \
	-data_type audio \
	-src_dir data/speech/an4_dataset \
	-train_src data/speech/src-train.txt \
	-train_tgt data/speech/tgt-train.txt \
	-valid_src data/speech/src-val.txt \
	-valid_tgt data/speech/tgt-val.txt \
	-shard_size 300 -save_data data/speech/demo

python3 train.py \
	-model_type audio \
	-enc_rnn_size 512 -dec_rnn_size 512 \
	-audio_enc_pooling 1,1,2,2 \
	-dropout 0 -enc_layers 4 -dec_layers 1 \
	-rnn_type LSTM \
	-data data/speech/demo \
	-save_model demo-model \
	-global_attention mlp \
	-batch_size 8 \
	-optim adam -max_grad_norm 100 \
	-learning_rate 0.0003 \
	-learning_rate_decay 0.8 -train_steps 100000 \
	-gpu_ranks 0 -world_size 1
```
and it's running fine. Not sure what could happen here.

Do you have the version of torchaudio specified in [`requirements.opt.txt`](https://github.com/OpenNMT/OpenNMT-py/blob/master/requirements.opt.txt)?

**Comment by francoishernandez** [comment]
Could you send one of your preprocessed shards so that we have a look?

**Comment by francoishernandez** [comment]
Yes please send demo.train.0.pt, demo.valid.0.pt and demo.vocab.pt. I just want to make sure those are correct.

**Comment by francoishernandez** [comment]
Not sure why but your preprocessed data is not correct.
The audio `src` is supposed to have two dimensions (features x windows). In your case you always have 1 as second dimension, which is why the pooling fails.

```
In [10]: data.examples[0].src.size()
Out[10]: torch.Size([161, 1])
```
where you should have for instance
```
In [10]: data.examples[0].src.size()
Out[10]: torch.Size([161, 71])
```
