### ISSUE TITLE
speech to text

### ISSUE THREAD

**Issue by malahmadi1** [OpenNMT/OpenNMT-py#1544]
I'm trying to run the example: http://opennmt.net/OpenNMT-py/speech2text.html
to train a speech to text.
I tried it on different python versions (python3.6, python3.7) with pytorch 1.2 

the preprocessing step went through and worked. However when I start training the model using the following command: 
python train.py -model_type audio -enc_rnn_size 512 -dec_rnn_size 512 -audio_enc_pooling 1,1,2,2 -dropout 0 -enc_layers 4 -dec_layers 1 -rnn_type LSTM -data data/speech/demo -save_model demo-model -global_attention mlp -gpu_ranks 0 -batch_size 8 -optim adam -max_grad_norm 100 -learning_rate 0.0003 -learning_rate_decay 0.8 -train_steps 100000

I got this error: **RuntimeError: Given input size: (8x1x1). Calculated output size: (8x1x0). Output size is too small** 

Here is the full details of the error: 

[2019-08-27 11:56:34,496 INFO]  * tgt vocab size = 31
[2019-08-27 11:56:34,496 INFO] Building model...
[2019-08-27 11:56:37,214 INFO] NMTModel(
  (encoder): AudioEncoder(
    (W): Linear(in_features=512, out_features=512, bias=False)
    (batchnorm_0): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn_0): LSTM(161, 512)
    (pool_0): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (rnn_1): LSTM(512, 512)
    (pool_1): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (batchnorm_1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn_2): LSTM(512, 512)
    (pool_2): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (batchnorm_2): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn_3): LSTM(512, 512)
    (pool_3): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (batchnorm_3): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(31, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.0, inplace=False)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.0, inplace=False)
      (layers): ModuleList(
        (0): LSTMCell(1012, 512)
      )
    )
    (attn): GlobalAttention(
      (linear_context): Linear(in_features=512, out_features=512, bias=False)
      (linear_query): Linear(in_features=512, out_features=512, bias=True)
      (v): Linear(in_features=512, out_features=1, bias=False)
      (linear_out): Linear(in_features=1024, out_features=512, bias=True)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=512, out_features=31, bias=True)
    (1): Cast()
    (2): LogSoftmax()
  )
)
[2019-08-27 11:56:37,214 INFO] encoder: 7952384
[2019-08-27 11:56:37,214 INFO] decoder: 4206763
[2019-08-27 11:56:37,214 INFO] * number of parameters: 12159147
[2019-08-27 11:56:37,215 INFO] Starting training on GPU: [0]
[2019-08-27 11:56:37,215 INFO] Start training loop and validate every 10000 steps...
[2019-08-27 11:56:37,216 INFO] Loading dataset from data/speech/demo.train.0.pt
[2019-08-27 11:56:37,220 INFO] number of examples: 300
Traceback (most recent call last):
  File "train.py", line 200, in <module>
    main(opt)
  File "train.py", line 86, in main
    single_main(opt, 0)
  File "/home/mohammad/Dropbox/PycharmProjects/OpenNMT-py/onmt/train_single.py", line 143, in main
    valid_steps=opt.valid_steps)
  File "/home/mohammad/Dropbox/PycharmProjects/OpenNMT-py/onmt/trainer.py", line 243, in train
    report_stats)
  File "/home/mohammad/Dropbox/PycharmProjects/OpenNMT-py/onmt/trainer.py", line 357, in _gradient_accumulation
    outputs, attns = self.model(src, tgt, src_lengths, bptt=bptt)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mohammad/Dropbox/PycharmProjects/OpenNMT-py/onmt/models/model.py", line 42, in forward
    enc_state, memory_bank, lengths = self.encoder(src, lengths)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mohammad/Dropbox/PycharmProjects/OpenNMT-py/onmt/encoders/audio_encoder.py", line 120, in forward
    memory_bank = pool(memory_bank)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 76, in forward
    self.return_indices)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/_jit_internal.py", line 134, in fn
    return if_false(*args, **kwargs)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 456, in _max_pool1d
    input, kernel_size, stride, padding, dilation, ceil_mode)
**RuntimeError: Given input size: (8x1x1). Calculated output size: (8x1x0). Output size is too small**

**Comment by vince62s** [comment]
duplicate
