### ISSUE TITLE
Train.py with Transformer on multiple GPUs

### ISSUE THREAD

**Issue by yiulau** [OpenNMT/OpenNMT-py#1546]
When I tried to train a MT transformer model on multiple gpu's I got an error. There is no problem when training on 1 gpu only. There is also no problem when training an RNN on multiple GPU's.

```
export CUDA_VISIBLE_DEVICES=0,1

python  ~/OpenNMT-py-master/train.py -data ./tmp/processed_data_wmt -save_model wmt_transformer \
        -layers 6 -rnn_size 512 -word_vec_size 512 -transformer_ff 2048 -heads 8  \
        -encoder_type transformer -decoder_type transformer -position_encoding \
        -train_steps 200000  -max_generator_batches 2 -dropout 0.1 \
        -batch_size 4096 -batch_type tokens -normalization tokens  -accum_count 2 \
        -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 2 \
        -max_grad_norm 0 -param_init 0  -param_init_glorot \
        -label_smoothing 0.1 -valid_steps 10000 -save_checkpoint_steps 10000 \
        -world_size 2 -gpu_ranks 0 1



```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
Traceback (most recent call last):
  File "/home/yiu/OpenNMT-py-master/train.py", line 200, in <module>
    prepare(preparation_data)
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yiu/OpenNMT-py-master/train.py", line 7, in <module>
    main(opt)
    import onmt.opts as opts
  File "/home/yiu/OpenNMT-py-master/train.py", line 78, in main
  File "/home/yiu/OpenNMT-py-master/onmt/__init__.py", line 4, in <module>
    import onmt.inputters
  File "/home/yiu/OpenNMT-py-master/onmt/inputters/__init__.py", line 6, in <module>
    from onmt.inputters.inputter import \
  File "/home/yiu/OpenNMT-py-master/onmt/inputters/inputter.py", line 11, in <module>
    producer.start()
    import torchtext.data
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/site-packages/torchtext/__init__.py", line 1, in <module>
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/multiprocessing/process.py", line 112, in start
    from . import data
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/site-packages/torchtext/data/__init__.py", line 2, in <module>
    from .dataset import Dataset, TabularDataset
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/site-packages/torchtext/data/dataset.py", line 13, in <module>
    from ..utils import download_from_url, unicode_csv_reader
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/site-packages/torchtext/utils.py", line 2, in <module>
    self._popen = self._Popen(self)
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    import requests
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import (
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/site-packages/urllib3/connectionpool.py", line 45, in <module>
    from .util.queue import LifoQueue
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    return Popen(process_obj)
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
    super().__init__(process_obj)
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1371, in find_spec
KeyboardInterrupt
    self._launch(process_obj)
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 62, in _launch
    f.write(fp.getbuffer())
  File "/home/yiu/OpenNMT-py-master/train.py", line 184, in signal_handler
    raise Exception(msg)
Exception:

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/home/yiu/OpenNMT-py-master/train.py", line 138, in run
    gpu_rank = onmt.utils.distributed.multi_init(opt, device_id)
  File "/home/yiu/OpenNMT-py-master/onmt/utils/distributed.py", line 27, in multi_init
    world_size=dist_world_size, rank=opt.gpu_ranks[device_id])
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 406, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 95, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon)
RuntimeError: Address already in use

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/yiu/.conda/envs/ttext/lib/python3.7/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated

```

**Comment by francoishernandez** [comment]
You must have another process already running with the same port. (This is linked with torch.distributed stuff.)
Please see #1298.

**Comment by francoishernandez** [comment]
Add the `-master_port XXXX` argument with `XXXX` being a free port on your machine.
The default one for OpenNMT-py is 5000. You may try 5001 for instance.
