### ISSUE TITLE
Please throw FileNotFoundError in preprocess.py before run preprocess, not after 1 shard is created

### ISSUE THREAD

**Issue by ttpro1995** [OpenNMT/OpenNMT-py#1575]
When I run preprocess and forgot to create directory, it show error. However, I would prefer FileNotFoundError be throw before 1 shard is run. Because sometime I forgot to create a directory, and waste time for 1 shard (or all, if I does not choice to make shard) before the FileNotFoundError show up.  

```
2019-09-19 18:24:58,824 INFO] Extracting features...
[2019-09-19 18:24:58,833 INFO]  * number of source features: 0.
[2019-09-19 18:24:58,833 INFO]  * number of target features: 0.
[2019-09-19 18:24:58,834 INFO] Building `Fields` object...
[2019-09-19 18:24:58,834 INFO] Building & saving training data...
[2019-09-19 18:24:58,834 INFO] Reading source and target files: /data/Pusheen/vlsp_2019/data/src_train.txt /data/Pusheen/vlsp_2019/data/tgt_train.txt.
[2019-09-19 18:24:58,875 INFO] Building shard 0.
100%|██████████| 10000/10000 [08:48<00:00, 18.90it/s]
[2019-09-19 18:33:54,844 INFO]  * saving 0th train data shard to /data/zmining/vlsp_2019/preprocessfull2/demo.train.0.pt.
Traceback (most recent call last):
  File "preprocess.py", line 220, in <module>
    main(opt)
  File "preprocess.py", line 201, in main
    'train', fields, src_reader, tgt_reader, opt)
  File "preprocess.py", line 127, in build_save_dataset
    dataset.save(data_path)
  File "/home/Pusheen/app/OpenNMT-py/onmt/inputters/dataset_base.py", line 154, in save
    torch.save(self, path)
  File "/home/Pusheen/anaconda3/envs/opennmt_speech2text/lib/python3.7/site-packages/torch/serialization.py", line 224, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/Pusheen/anaconda3/envs/opennmt_speech2text/lib/python3.7/site-packages/torch/serialization.py", line 147, in _with_file_like
    f = open(f, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/data/Pusheen/vlsp_2019/preprocessfull2/demo.train.0.pt'
```

**Comment by vince62s** [comment]
Yo don't seem to be on master and usignyour own code, are you ?
