### ISSUE TITLE
multi-GPU issue: CUDA error: all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by expectation-maximization** [OpenNMT/OpenNMT-py#1605]
Traceback (most recent call last):                                                                                                                                                     [0/1981]
  File "/home/xu.likui/anaconda2/bin/onmt_train", line 11, in <module>
    load_entry_point('OpenNMT-py==1.0.0rc1', 'console_scripts', 'onmt_train')()
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/OpenNMT_py-1.0.0rc1-py3.6.egg/onmt/bin/train.py", line 200, in main
    train(opt)
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/OpenNMT_py-1.0.0rc1-py3.6.egg/onmt/bin/train.py", line 82, in train
    p.join()
  File "/home/xu.likui/anaconda2/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/home/xu.likui/anaconda2/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/xu.likui/anaconda2/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/OpenNMT_py-1.0.0rc1-py3.6.egg/onmt/bin/train.py", line 184, in signal_handler
    raise Exception(msg)
Exception:

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/OpenNMT_py-1.0.0rc1-py3.6.egg/onmt/bin/train.py", line 142, in run
    single_main(opt, device_id, batch_queue, semaphore)
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/OpenNMT_py-1.0.0rc1-py3.6.egg/onmt/train_single.py", line 84, in main
    model = build_model(model_opt, opt, fields, checkpoint)
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/OpenNMT_py-1.0.0rc1-py3.6.egg/onmt/model_builder.py", line 240, in build_model
    model = build_base_model(model_opt, fields, use_gpu(opt), checkpoint)
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/OpenNMT_py-1.0.0rc1-py3.6.egg/onmt/model_builder.py", line 232, in build_base_model
    model.to(device)
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 432, in to
    return self._apply(convert)
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  [Previous line repeated 1 more times]
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/home/xu.likui/anaconda2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 430, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable

my command line is : onmt_train -data data/demo -save_model demo-model -world_size 2 -gpu_ranks 0 1 -train_steps 1000

follow command can work: onmt_train -data data/demo -save_model demo-model -world_size 1 -gpu_ranks 0 -train_steps 1000

i try git pull , don't work.

**Comment by francoishernandez** [comment]
Is your GPU in exclusive mode?

**Comment by expectation-maximization** [comment]
yes, exclusive mode
nvidia-smi  --query | grep 'Compute Mode'
    Compute Mode                    : Exclusive_Process
    Compute Mode                    : Exclusive_Process
    Compute Mode                    : Exclusive_Process
    Compute Mode                    : Exclusive_Process

**Comment by francoishernandez** [comment]
You need to switch back to default mode.
In the multi-gpu scenario, there are two processes spawned for each GPU (basically one for training and one to receive data from what we call the 'batch producer'). This is for speed and memory optimization (#1450).

**Comment by vince62s** [comment]
@francoishernandez let's add this in the README for clarification (or FAQ)

**Comment by expectation-maximization** [comment]
switch back to default mode, it works.  thanks.
