### ISSUE TITLE
AttributeError: 'Batch' object has no attribute 'src_ex_vocab'

### ISSUE THREAD

**Issue by DhanshreeA** [OpenNMT/OpenNMT-py#1611]
I tried to fine tune a model trained on the CNN/DM data with some of my data, and I got this error:
```
/home/ubuntu/dhanshree/OpenNMT-py/.venv/local/lib/python3.5/site-packages/torchtext-0.4.0-py3.5.egg/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).

  var = torch.tensor(arr, dtype=self.dtype, device=device)

Traceback (most recent call last):
  File "/home/ubuntu/dhanshree/OpenNMT-py/onmt/trainer.py", line 370, in _gradient_accumulation
    trunc_size=trunc_size)

  File "/home/ubuntu/dhanshree/OpenNMT-py/onmt/utils/loss.py", line 165, in __call__
    loss, stats = self._compute_loss(batch, **shard)

  File "/home/ubuntu/dhanshree/OpenNMT-py/onmt/modules/copy_generator.py", line 233, in _compute_loss
    batch, self.tgt_vocab, None)

  File "/home/ubuntu/dhanshree/OpenNMT-py/onmt/modules/copy_generator.py", line 21, in collapse_copy_scores
    src_vocab = batch.src_ex_vocab[b]
AttributeError: 'Batch' object has no attribute 'src_ex_vocab'
```

**Comment by vince62s** [comment]
What version did you use to train your first model. Are you currently on master ?

**Comment by francoishernandez** [comment]
@DhanshreeA reopen if needed.

**Comment by FazeleTavakoli** [comment]
this issue is still persisting
