### ISSUE TITLE
Report_bleu  and report_rouge error

### ISSUE THREAD

**Issue by Simons2017** [OpenNMT/OpenNMT-py#1618]
My command is:
`onmt_translate -gpu 0                -batch_size 20                -beam_size 5                -model models/cnndm_step_20000.pt                -src data/cnndm/test.txt.src.txt                -output testout/cnndm.out                -min_length 35                -verbose                -stepwise_penalty                -coverage_penalty summary                -beta 5                -length_penalty wu                -alpha 0.9                -verbose                -block_ngram_repeat 3        -report_bleu       -report_rouge               -log_file log       -tgt data/cnndm/test.txt.tgt.txt
`
I got this:
ERROR: could not find reference file [b....\n, at /home/OpenNMT-py-master/tools/multi-bleu.perl line 32.
Traceback (most recent call last):
  File "/home/anaconda3/bin/onmt_translate", line 10, in <module>
    sys.exit(main())
  File "/home/OpenNMT-py-master/onmt/bin/translate.py", line 49, in main
    translate(opt)
  File "/home/OpenNMT-py-master/onmt/bin/translate.py", line 33, in translate
    attn_debug=opt.attn_debug
  File "/home/OpenNMT-py-master/onmt/translate/translator.py", line 415, in translate
    msg = self._report_bleu(tgt)
  File "/home/OpenNMT-py-master/onmt/translate/translator.py", line 860, in _report_bleu
    stdin=self.out_file, shell=True
  File "/home/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/cai/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'perl /home/OpenNMT-py-master/tools/multi-bleu.perl [b"...", b"...\n"]' returned non-zero exit status 2.

usage: test_rouge.py [-h] [-c C] [-r R]
test_rouge.py: error: unrecognized arguments: b... .\n]
Traceback (most recent call last):
  File "/home/anaconda3/bin/onmt_translate", line 10, in <module>
    sys.exit(main())
  File "/home/OpenNMT-py-master/onmt/bin/translate.py", line 49, in main
    translate(opt)
  File "/home/OpenNMT-py-master/onmt/bin/translate.py", line 33, in translate
    attn_debug=opt.attn_debug
  File "/home/OpenNMT-py-master/onmt/translate/translator.py", line 418, in translate
    msg = self._report_rouge(tgt)
  File "/home/OpenNMT-py-master/onmt/translate/translator.py", line 871, in _report_rouge
    shell=True, stdin=self.out_file
  File "/home/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python /home/OpenNMT-py-master/onmt/translate/tools/test_rouge.py -r [b"...\n", b"....\n"] -c STDIN' returned non-zero exit status 2.

("..." are my data)

**Comment by francoishernandez** [comment]
Yes these options are not working currently, we need to fix it. #1429 #1530
