### ISSUE TITLE
OverflowError: math range error

### ISSUE THREAD

**Issue by Simons2017** [OpenNMT/OpenNMT-py#1619]
indeed using a beam size of 15 did not trigger the error.
closing for now.

_Originally posted by @vince62s in https://github.com/OpenNMT/OpenNMT-py/issues/749#issuecomment-427932303_
 
I have tried the above method, but still got:
Traceback (most recent call last):
File "translate.py", line 29, in 
main(opt)
File "translate.py", line 18, in main
opt.batch_size, opt.attn_debug)
File "/home/OpenNMT-py/onmt/translate/Translator.py", line 200, in translate
self._report_score('PRED', pred_score_total, pred_words_total)
File "/home/OpenNMT-py/onmt/translate/Translator.py", line 394, in _report_score
name, math.exp(-score_total / words_total)))
OverflowError: math range error

**Comment by francoishernandez** [comment]
It seems you are on very old version of the code. Could you try with master/latest release?

**Comment by vince62s** [comment]
reopen if needed
