### ISSUE TITLE
IndexError when set enc_layers and dec_layers

### ISSUE THREAD

**Issue by chifish** [OpenNMT/OpenNMT-py#1620]
[2019-10-30 21:20:04,848 INFO] number of examples: 126007
Traceback (most recent call last):
  File "OpenNMT-py/train.py", line 200, in <module>
    main(opt)
  File "OpenNMT-py/train.py", line 86, in main
    single_main(opt, 0)
  File "/home/cxq/OpenNMT-py/onmt/train_single.py", line 143, in main
    valid_steps=opt.valid_steps)
  File "/home/cxq/OpenNMT-py/onmt/trainer.py", line 243, in train
    report_stats)
  File "/home/cxq/OpenNMT-py/onmt/trainer.py", line 357, in _gradient_accumulation
    outputs, attns = self.model(src, tgt, src_lengths, bptt=bptt)
  File "/home/cxq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cxq/OpenNMT-py/onmt/models/model.py", line 47, in forward
    memory_lengths=lengths)
  File "/home/cxq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cxq/OpenNMT-py/onmt/decoders/decoder.py", line 213, in forward
    tgt, memory_bank, memory_lengths=memory_lengths)
  File "/home/cxq/OpenNMT-py/onmt/decoders/decoder.py", line 390, in _run_forward_pass
    rnn_output, dec_state = self.rnn(decoder_input, dec_state)
  File "/home/cxq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cxq/OpenNMT-py/onmt/models/stacked_rnn.py", line 26, in forward
    h_1_i, c_1_i = layer(input_feed, (h_0[i], c_0[i]))
IndexError: index 4 is out of bounds for dimension 0 with size 4

========my command to train=====================
CUDA_VISIBLE_DEVICES=1 python3 OpenNMT-py/train.py -data my_data/uni -save_model lstm_uni \
        -enc_layers 4 -dec_layers 8 -rnn_size 512 -word_vec_size 512 \
        -encoder_type brnn -decoder_type rnn \
        -train_steps 100000  -max_generator_batches 2 -dropout 0.2 \
        -batch_size 2048 -batch_type tokens -normalization tokens  -accum_count 2 \
        -learning_rate 1.0 -start_decay_steps 20000 -decay_steps 1000 \
        -label_smoothing 0.1 -valid_steps 2000 \
        -save_checkpoint_steps 2000 -keep_checkpoint 9 \
        -world_size 1 -gpu_ranks 0 -log_file lstm_uni.log

BTW
it is ok to set -layers parameter

**Comment by francoishernandez** [comment]
See #917 and #389 .
