### ISSUE TITLE
train.py execution  error

### ISSUE THREAD

**Issue by sdlmw** [OpenNMT/OpenNMT-py#1624]
Hi guys，

```
export CUDA_VISIBLE_DEVICES=0,1

onmt_train -data /MT-work/Jonckers_en-zh -save_model /MT-work/Jonckers_en-zh_model -world_size 2 -gpu_ranks 0 1
```
Errors in carrying out training steps：
`Traceback (most recent call last):
  File "/home/mtuser/miniconda3/bin/onmt_train", line 11, in <module>
    load_entry_point('OpenNMT-py==1.0.0rc2', 'console_scripts', 'onmt_train')()
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/OpenNMT_py-1.0.0rc2-py3.7.egg/onmt/__init__.py", line 4, in <module>
    import onmt.inputters
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/OpenNMT_py-1.0.0rc2-py3.7.egg/onmt/inputters/__init__.py", line 6, in <module>
    from onmt.inputters.inputter import \
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/OpenNMT_py-1.0.0rc2-py3.7.egg/onmt/inputters/inputter.py", line 10, in <module>
    import torch
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/torch/__init__.py", line 280, in <module>
    from .functional import *
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/torch/functional.py", line 2, in <module>
    import torch.nn.functional as F
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F401
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 5, in <module>
    from .. import functional as F
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 14, in <module>
    from .._jit_internal import boolean_dispatch, List
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/torch/_jit_internal.py", line 489, in <module>
    import typing
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/typing.py", line 1357, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/home/mtuser/miniconda3/lib/python3.7/site-packages/typing.py", line 1005, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
`

The current machine environment is a Conda container，python 3.7 and typing version:  3.7.4.1,
I tried the environment reloading, still the same error. Is it not the same version of the tool I use?

**Comment by sdlmw** [comment]
Solved, I had uninsatll Typing
