### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by welleozean** [OpenNMT/OpenNMT-py#1627]
I am starting experimenting with OpenNMT on Windows 10 and Anaconda Python. I am experiencing the following error with the Quickstart example:

```

(base) C:\Users\XX\Desktop>onmt_preprocess -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo
[2019-11-04 18:50:11,907 INFO] Extracting features...
Traceback (most recent call last):
  File "c:\users\xx\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xx\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\XX\Anaconda3\Scripts\onmt_preprocess.exe\__main__.py", line 7, in <module>
  File "c:\users\xx\anaconda3\lib\site-packages\onmt\bin\preprocess.py", line 283, in main
    preprocess(opt)
  File "c:\users\xx\anaconda3\lib\site-packages\onmt\bin\preprocess.py", line 244, in preprocess
    src_nfeats += count_features(src) if opt.data_type == 'text' \
  File "c:\users\xx\anaconda3\lib\site-packages\onmt\bin\preprocess.py", line 229, in count_features
    first_tok = f.readline().split(None, 1)[0]
IndexError: list index out of range

```

Not quite sure where the problem lies. Should the environment be initialized some way?

**Comment by vince62s** [comment]
what pytorch version did you install ?

**Comment by welleozean** [comment]
My installed version is 1.2.0

**Comment by francoishernandez** [comment]
Are you using the data files from the repo?
I just tested a clean install on Windows 10 - pytorch 1.2.0 - `pip install OpenNMT-py` and the command ran fine.

**Comment by welleozean** [comment]
Just did a clean install of everything...and now all works perfectly. Probably I must have messed up somthing in my first attemp. Thank you.
