### ISSUE TITLE
Multi GPU Fails with `RuntimeError: The size of tensor a (0) must match the size of tensor b (5) at non-singleton dimension 3`

### ISSUE THREAD

**Issue by rawkintrevo** [OpenNMT/OpenNMT-py#1634]
Using the following training line: 

```bash
CUDA_VISABLE_DEVICES=0,1 onmt_train \
           -data data/data \
           -save_model newdawn \
           -pre_word_vecs_enc "data/embeddings.enc.pt" \
           -pre_word_vecs_dec "data/embeddings.dec.pt" \
           -layers 4 \
           -rnn_size 512 \
           -word_vec_size 512 \
           -max_grad_norm 0 \
           -optim adam \
           -encoder_type transformer \
           -decoder_type transformer \
           -position_encoding \
           -dropout 0\.2 \
           -param_init 0 \
           -warmup_steps 8000 \
           -learning_rate 2 \
           -decay_method noam \
           -label_smoothing 0.1 \
           -adam_beta2 0.998 \
           -batch_size 4096 \
           -valid_batch_size 16 \
           -batch_type tokens \
           -normalization tokens \
           -max_generator_batches 2 \
           -train_steps 200000 \
           -accum_count 5 \
           -share_embeddings \
           -copy_attn \
           -param_init_glorot \
           -world_size 2 \
           -gpu_ranks 0 1 \
           -save_checkpoint_steps 1000 \
           -keep_checkpoint 3 \
```

I get the output:

```
<snip>
       )
        (layer_norm_1): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
        (layer_norm_2): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
        (drop): Dropout(p=0.2, inplace=False)
      )
    )
    (layer_norm): LayerNorm((512,), eps=1e-06, elementwise_affine=True)
  )
  (generator): CopyGenerator(
    (linear): Linear(in_features=512, out_features=31367, bias=True)
    (linear_copy): Linear(in_features=512, out_features=1, bias=True)
  )
)
[2019-11-08 17:57:50,940 INFO] encoder: 28670464
[2019-11-08 17:57:50,940 INFO] decoder: 32908936
[2019-11-08 17:57:50,940 INFO] * number of parameters: 61579400
[2019-11-08 17:57:50,940 INFO] encoder: 28670464
[2019-11-08 17:57:50,940 INFO] decoder: 32908936
[2019-11-08 17:57:50,940 INFO] * number of parameters: 61579400
[2019-11-08 17:57:50,944 INFO] Starting training on GPU: [0, 1]
[2019-11-08 17:57:50,944 INFO] Starting training on GPU: [0, 1]
[2019-11-08 17:57:50,944 INFO] Start training loop and validate every 10000 steps...
[2019-11-08 17:57:50,944 INFO] Start training loop and validate every 10000 steps...
[2019-11-08 17:57:59,895 INFO] number of examples: 100000
/home/rawkintrevo/.local/lib/python3.6/site-packages/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/home/rawkintrevo/.local/lib/python3.6/site-packages/onmt/bin/train.py", line 142, in run
    single_main(opt, device_id, batch_queue, semaphore)
  File "/home/rawkintrevo/.local/lib/python3.6/site-packages/onmt/train_single.py", line 143, in main
    valid_steps=opt.valid_steps)
  File "/home/rawkintrevo/.local/lib/python3.6/site-packages/onmt/trainer.py", line 243, in train
    report_stats)
  File "/home/rawkintrevo/.local/lib/python3.6/site-packages/onmt/trainer.py", line 358, in _gradient_accumulation
    outputs, attns = self.model(src, tgt, src_lengths, bptt=bptt)
  File "/home/rawkintrevo/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rawkintrevo/.local/lib/python3.6/site-packages/onmt/models/model.py", line 42, in forward
    enc_state, memory_bank, lengths = self.encoder(src, lengths)
  File "/home/rawkintrevo/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rawkintrevo/.local/lib/python3.6/site-packages/onmt/encoders/transformer.py", line 127, in forward
    out = layer(out, mask)
  File "/home/rawkintrevo/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rawkintrevo/.local/lib/python3.6/site-packages/onmt/encoders/transformer.py", line 50, in forward
    mask=mask, attn_type="self")
  File "/home/rawkintrevo/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rawkintrevo/.local/lib/python3.6/site-packages/onmt/modules/multi_headed_attn.py", line 199, in forward
    scores = scores.masked_fill(mask, -1e18)
RuntimeError: The size of tensor a (0) must match the size of tensor b (5) at non-singleton dimension 3
```
If I reduce to one GPU, everything works swimmingly. I'm on OpenNMT-py v1.0.0.rc1
Ideas for work around / bug fix?

**Comment by vince62s** [comment]
what is you pytorch version?

**Comment by rawkintrevo** [comment]
1.3.0

**Comment by vince62s** [comment]
might not be the reason but fall back to 1.2, there are bugs in 1.3.0

**Comment by rawkintrevo** [comment]
no joy. rolled back 1.2.0, same error. 

fairseq works with multigpu, so I'm fairly confident this is an opennmt-py problem.

**Comment by vince62s** [comment]
we also train everyday on multi-gpu :)
other ideas:
check your torchtext version
try without pre_word_vecs_
try without copy_attn

**Comment by rawkintrevo** [comment]
torchtext is 0.4.0
error persists without copy attn / pre_word_vecs
:/

**Comment by vince62s** [comment]
it's weird because this message:
UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)

stems from older version of pytorch/torchtext
did you preprocess with an older version ?

Did you install OpenNMT-py with pip ? git clone?

**Comment by rawkintrevo** [comment]
I might have preprocessed on another machine. However, that UserWarning happens in single GPU as well.  I installed on all machines with pip, directly from the repo with something like:

```
pip install git+https://github.com/OpenNMT/OpenNMT-py@OpenNMT-py v1.0.0.rc1
```

**Comment by rawkintrevo** [comment]
Should I try to re-preprocess it on the machine where its running?

**Comment by francoishernandez** [comment]
Another strange thing is that your multi-gpu log seems to log for every gpu process. This is not supposed to happen, as logging is restricted to the first gpu process.
A simple test you could try is run the [quickstart commands](http://opennmt.net/OpenNMT-py/quickstart.html) with [the toy data](https://github.com/OpenNMT/OpenNMT-py/tree/master/data), to see if it runs properly when adding the multi gpu opts.

**Comment by rawkintrevo** [comment]
^^ I was having another issue and manually turned that on. (multi gpu logging).

**Comment by vince62s** [comment]
reopen if needed
