### ISSUE TITLE
RuntimeError: Length of all samples has to be greater than 0

### ISSUE THREAD

**Issue by AjayViknesh** [OpenNMT/OpenNMT-py#1642]
`Traceback (most recent call last):
  File "translate.py", line 6, in <module>
    main()
  File "/home/ewall-lap/Desktop/NLP DMS/addons/OpenNMT-py/onmt/bin/translate.py", line 51, in main
    translate(opt)
  File "/home/ewall-lap/Desktop/NLP DMS/addons/OpenNMT-py/onmt/bin/translate.py", line 35, in translate
    attn_debug=opt.attn_debug
  File "/home/ewall-lap/Desktop/NLP DMS/addons/OpenNMT-py/onmt/translate/translator.py", line 351, in translate
    batch, data.src_vocabs, attn_debug
  File "/home/ewall-lap/Desktop/NLP DMS/addons/OpenNMT-py/onmt/translate/translator.py", line 544, in translate_batch
    return_attention=attn_debug or self.replace_unk)
  File "/home/ewall-lap/Desktop/NLP DMS/addons/OpenNMT-py/onmt/translate/translator.py", line 636, in _translate_batch
    src, enc_states, memory_bank, src_lengths = self._run_encoder(batch)
  File "/home/ewall-lap/Desktop/NLP DMS/addons/OpenNMT-py/onmt/translate/translator.py", line 551, in _run_encoder
    src, src_lengths)
  File "/home/ewall-lap/Desktop/Internal/translate/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ewall-lap/Desktop/NLP DMS/addons/OpenNMT-py/onmt/encoders/rnn_encoder.py", line 74, in forward
    packed_emb = pack(emb, lengths_list)
  File "/home/ewall-lap/Desktop/Internal/translate/lib/python3.5/site-packages/torch/nn/utils/rnn.py", line 282, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0`

Hi! I am getting the above issue if I am having any empty lines in the data.

Is there any option where I can omit those empty lines.

Please let me know if any.

**Comment by francoishernandez** [comment]
Easiest is to clean your data before hand, with some command line tools like `sed` for instance.
