### ISSUE TITLE
onmt_translate w/ LSTM seq2seq fails but succeeds w/Transformer

### ISSUE THREAD

**Issue by jkamalu** [OpenNMT/OpenNMT-py#1648]
Salut/Hello! I am training a en-fr translation model with OpenNMT-py and am running into trouble with the onmt_translate script. I am able to preprocess and train an LSTM seq2seq model as well as a Transformer model. Subsequently, I am able to use the transformer model to translate, but the LSTM model fails with the error output at the bottom of the issue. Please, if you have any idea what is causing this error, I would really appreciate your help (I think it may be a bug given the transformer is able to be used for inference on the same data). cc: @rdiehlmartinez

Data is preprocessed with the following options. Embeddings are processed separately. Note that without filter_valid, training fails.
```
train_src: data/europarl-v7/europarl-v7.fr-en.en.train
train_tgt: data/europarl-v7/europarl-v7.fr-en.fr.train
valid_src: data/europarl-v7/europarl-v7.fr-en.en.val
valid_tgt: data/europarl-v7/europarl-v7.fr-en.fr.val
save_data: data/data

src_vocab_size: 30000
tgt_vocab_size: 30000
filter_valid: True
lower: True
```

The model is trained 10000 steps with validation metrics with this config and training runs smoothly, yielding good ppl and cce scores.

```
world_size: 1
gpu_ranks: 0
data: data/data
save_model: runs/second/model
keep_checkpoint: 10
pre_word_vecs_enc: data/embeddings.enc.pt
pre_word_vecs_dec: data/embeddings.dec.pt
word_vec_size: 200
layers: 3
bridge: True
optim: adam
learning_rate: 0.001
train_steps: 100000
valid_steps: 10000
report_every: 1000
log_file: runs/second/log.txt
tensorboard: True
tensorboard_log_dir: runs/second
```

The model is made to translate with the following options and fails with the error log below.

```
src: data/europarl-v7/europarl-v7.fr-en.en.val
tgt: data/europarl-v7/europarl-v7.fr-en.fr.val
model: runs/second/model_step_90000.pt
report_bleu: True
report_rouge: True
```

(nmt) john_kamalu@myvm:~/unidirectional-NMT$ onmt_translate --config config/config-translate.yml
[2019-11-19 05:01:05,033 INFO] Translating shard 0.
Traceback (most recent call last):
  File "/home/john_kamalu/miniconda3/envs/nmt/bin/onmt_translate", line 8, in <module>
    sys.exit(main())
  File "/home/john_kamalu/miniconda3/envs/nmt/lib/python3.7/site-packages/onmt/bin/translate.py", line 49, in main
    translate(opt)
  File "/home/john_kamalu/miniconda3/envs/nmt/lib/python3.7/site-packages/onmt/bin/translate.py", line 33, in translate
    attn_debug=opt.attn_debug
  File "/home/john_kamalu/miniconda3/envs/nmt/lib/python3.7/site-packages/onmt/translate/translator.py", line 351, in translate
    batch, data.src_vocabs, attn_debug
  File "/home/john_kamalu/miniconda3/envs/nmt/lib/python3.7/site-packages/onmt/translate/translator.py", line 544, in translate_batch
                    ratio=self.ratio,
    return_attention=attn_debug or self.replace_unk)
  File "/home/john_kamalu/miniconda3/envs/nmt/lib/python3.7/site-packages/onmt/translate/translator.py", line 636, in _translate_batch
    src, enc_states, memory_bank, src_lengths = self._run_encoder(batch)
  File "/home/john_kamalu/miniconda3/envs/nmt/lib/python3.7/site-packages/onmt/translate/translator.py", line 551, in _run_encoder
    src, src_lengths)
  File "/home/john_kamalu/miniconda3/envs/nmt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/john_kamalu/miniconda3/envs/nmt/lib/python3.7/site-packages/onmt/encoders/rnn_encoder.py", line 74, in forward
    packed_emb = pack(emb, lengths_list)
  File "/home/john_kamalu/miniconda3/envs/nmt/lib/python3.7/site-packages/torch/nn/utils/rnn.py", line 282, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0

**Comment by francoishernandez** [comment]
It looks like Transformer allows empty examples in a batch, but LSTM do not.
Did you try removing the empty lines from your validation set?

**Comment by jkamalu** [comment]
I did manually look for empty lines but found no lines to have 0 length. This is curiously not a problem during training with the --filter_valid flag set. Why is it not possible for the the onmt_translate script to take a .pt file as input?

**Comment by francoishernandez** [comment]
> Why is it not possible for the the onmt_translate script to take a .pt file as input?

Your `.pt` file would come from original bitexts so I'm not sure to understand the need here.
