### ISSUE TITLE
OverflowError when running summarization

### ISSUE THREAD

**Issue by Khev** [OpenNMT/OpenNMT-py#1655]
Hi there,

Task: summarization

Problem: when testing the model (running the ``` translate.py ``` script), I keep getting a ``` OverflowError ``` on the 10000-th test datum.

Has anyone else had this issue?

``` Traceback (most recent call last):
  File "translate.py", line 6, in <module>
    main()
  File "/home/khev/research/OpenNMT-py/onmt/bin/translate.py", line 49, in main
    translate(opt)
  File "/home/khev/research/OpenNMT-py/onmt/bin/translate.py", line 33, in translate
    attn_debug=opt.attn_debug
  File "/home/khev/research/OpenNMT-py/onmt/translate/translator.py", line 405, in translate
    pred_words_total)
  File "/home/khev/research/OpenNMT-py/onmt/translate/translator.py", line 843, in _report_score
    name, math.exp(-score_total / words_total)))
OverflowError: math range error

```

**Comment by vince62s** [comment]
can you try #1639 ?

**Comment by francoishernandez** [comment]
@pltrdy didn't you have the same issue?

**Comment by pltrdy** [comment]
Yes it's an issue. I have not been using sharding a lot, therefore it causes no trouble (the issue is raised after everything is done in my case) but yeah, it need to be fixed.

This said, it happens in pretty much everycase, so I'm not sure what to do (other than just ignoring the exception)
