### ISSUE TITLE
translate.py says UnicodeEncodeError

### ISSUE THREAD

**Issue by tanmayb123** [OpenNMT/OpenNMT-py#169]
I'm training a model to run an English -> French NMT task, and when I try and run `translate.py` with `python translate.py -model french_model_acc_56.86_ppl_8.75_e2.pt -src test.txt -replace_unk -verbose`, I get the following error:
```
/home/tanmay/OpenNMT-py/onmt/modules/GlobalAttention.py:133: UserWarning: mask is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  a_t.data.masked_fill_(self.mask, -float('inf'))
Traceback (most recent call last):
  File "translate.py", line 176, in <module>
    main()
  File "translate.py", line 122, in main
    for i in predBatch[b][0]]) + '\n')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
```
This is the content of `test.txt`:
```
We will discuss the details later .
```

**Comment by tanmayb123** [comment]
Update: When I use `python3` instead of `python`, it works! Is there a way this can work with python2?

**Comment by srush** [comment]
Hmm, I thought this was fixed. Are you using the latest code?

**Comment by srush** [comment]
Okay, I think this should be fixed now.
