### ISSUE TITLE
Transformer model not compatible with audio type

### ISSUE THREAD

**Issue by archomt** [OpenNMT/OpenNMT-py#1696]
I am receiving the error "RuntimeError: The size of tensor a (2) must match the size of tensor b (1411) at non-singleton dimension 3" when I train a speech translation model with transformer, the script I used is :

**python  train.py  -model_type audio -data data/speech/en2fr -save_model /home/work_nfs3/cgmi/workspace/speechMT/s2t/OpenNMT-py-master/models/st_en2fr/basic_large/en2fr-model-transformer \
        -layers 6 -rnn_size 512 -word_vec_size 512 -transformer_ff 2048 -heads 8  \
        -encoder_type transformer -decoder_type transformer -position_encoding \
        -train_steps 200000  -max_generator_batches 2 -dropout 0.1 \
        -batch_size 4096 -batch_type tokens -normalization tokens  -accum_count 2 \
        -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 2 \
        -max_grad_norm 0 -param_init 0  -param_init_glorot \
        -label_smoothing 0.1 -valid_steps 10000 -save_checkpoint_steps 10000 \
	-gpu_ranks 0** 

The output are as follows:
[2020-01-06 17:33:04,052 INFO] encoder: 12156928
[2020-01-06 17:33:04,052 INFO] decoder: 76479316
[2020-01-06 17:33:04,052 INFO] * number of parameters: 88636244
[2020-01-06 17:33:04,060 INFO] Starting training on GPU: [0]
[2020-01-06 17:33:04,060 INFO] Start training loop and validate every 10000 steps...
[2020-01-06 17:33:04,061 INFO] Loading dataset from data/speech/en2fr.train.0.pt
[2020-01-06 17:33:04,114 INFO] number of examples: 294
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    main()
  File "/home/work_nfs3/cgmi/workspace/speechMT/s2t/OpenNMT-py-master/onmt/bin/train.py", line 204, in main
    train(opt)
  File "/home/work_nfs3/cgmi/workspace/speechMT/s2t/OpenNMT-py-master/onmt/bin/train.py", line 88, in train
    single_main(opt, 0)
  File "/home/work_nfs3/cgmi/workspace/speechMT/s2t/OpenNMT-py-master/onmt/train_single.py", line 143, in main
    valid_steps=opt.valid_steps)
  File "/home/work_nfs3/cgmi/workspace/speechMT/s2t/OpenNMT-py-master/onmt/trainer.py", line 244, in train
    report_stats)
  File "/home/work_nfs3/cgmi/workspace/speechMT/s2t/OpenNMT-py-master/onmt/trainer.py", line 365, in _gradient_accumulation
    with_align=self.with_align)
  File "/home/work_nfs/cgmi/tools/anaconda3/envs/conda4st/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/work_nfs3/cgmi/workspace/speechMT/s2t/OpenNMT-py-master/onmt/models/model.py", line 51, in forward
    with_align=with_align)
  File "/home/work_nfs/cgmi/tools/anaconda3/envs/conda4st/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/work_nfs3/cgmi/workspace/speechMT/s2t/OpenNMT-py-master/onmt/decoders/transformer.py", line 282, in forward
    with_align=with_align)
  File "/home/work_nfs/cgmi/tools/anaconda3/envs/conda4st/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/work_nfs3/cgmi/workspace/speechMT/s2t/OpenNMT-py-master/onmt/decoders/transformer.py", line 68, in forward
    output, attns = self._forward(*args, **kwargs)
  File "/home/work_nfs3/cgmi/workspace/speechMT/s2t/OpenNMT-py-master/onmt/decoders/transformer.py", line 138, in _forward
    attn_type="context")
  File "/home/work_nfs/cgmi/tools/anaconda3/envs/conda4st/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/work_nfs3/cgmi/workspace/speechMT/s2t/OpenNMT-py-master/onmt/modules/multi_headed_attn.py", line 199, in forward
    scores = scores.masked_fill(mask, -1e18)
RuntimeError: The size of tensor a (2) must match the size of tensor b (1411) at non-singleton dimension 3
Accounting: time=81 threads=1
Finished at 2020年 01月 06日 星期一 17:33:07 CST with status 1

What can I do to avoid this error? Thank you.

**Comment by francoishernandez** [comment]
Hi @archomt 
The speech codepath was never really made compatible with Transformer.
If you feel like diving into it, a PR would be very welcome.
