### ISSUE TITLE
RuntimeError: CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by longsamaa** [OpenNMT/OpenNMT-py#1764]
Hi,
I am trying to follow this tutorial:
https://opennmt.net/OpenNMT-py/quickstart.html
and when training I use the command:
onmt_train -data data / demo -save_model demo-model -gpu_ranks 0
An error occurred during training:
```
[2020-03-28 20:04:59,038 INFO] Loading dataset from data\demo.train.0.pt
[2020-03-28 20:04:59,148 INFO] number of examples: 10000
[2020-03-28 20:04:59,490 INFO] Step 2200/100000; acc:  23.23; ppl: 120.08; xent: 4.79; lr: 1.00000; 7596/7785 tok/s;    407 sec
Traceback (most recent call last):
  File "c:\users\alienware\anaconda3\lib\site-packages\opennmt_py-1.1.1-py3.7.egg\onmt\trainer.py", line 400, in _gradient_accumulation
    trunc_size=trunc_size)
  File "c:\users\alienware\anaconda3\lib\site-packages\opennmt_py-1.1.1-py3.7.egg\onmt\utils\loss.py", line 165, in __call__
    for shard in shards(shard_state, shard_size):
  File "c:\users\alienware\anaconda3\lib\site-packages\opennmt_py-1.1.1-py3.7.egg\onmt\utils\loss.py", line 381, in shards
    torch.autograd.backward(inputs, grads)
  File "c:\users\alienware\anaconda3\lib\site-packages\torch\autograd\__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure
[2020-03-28 20:05:08,838 INFO] At step 2249, we removed a batch - accum 0
Traceback (most recent call last):
  File "C:\Users\Alienware\anaconda3\Scripts\onmt_train-script.py", line 11, in <module>
    load_entry_point('OpenNMT-py==1.1.1', 'console_scripts', 'onmt_train')()
  File "c:\users\alienware\anaconda3\lib\site-packages\opennmt_py-1.1.1-py3.7.egg\onmt\bin\train.py", line 206, in main
    train(opt)
  File "c:\users\alienware\anaconda3\lib\site-packages\opennmt_py-1.1.1-py3.7.egg\onmt\bin\train.py", line 88, in train
    single_main(opt, 0)
  File "c:\users\alienware\anaconda3\lib\site-packages\opennmt_py-1.1.1-py3.7.egg\onmt\train_single.py", line 143, in main
    valid_steps=opt.valid_steps)
  File "c:\users\alienware\anaconda3\lib\site-packages\opennmt_py-1.1.1-py3.7.egg\onmt\trainer.py", line 265, in train
    report_stats)
  File "c:\users\alienware\anaconda3\lib\site-packages\opennmt_py-1.1.1-py3.7.egg\onmt\trainer.py", line 422, in _gradient_accumulation
    self.optim.step()
  File "c:\users\alienware\anaconda3\lib\site-packages\opennmt_py-1.1.1-py3.7.egg\onmt\utils\optimizers.py", line 359, in step
    clip_grad_norm_(group['params'], self._max_grad_norm)
  File "c:\users\alienware\anaconda3\lib\site-packages\torch\nn\utils\clip_grad.py", line 32, in clip_grad_norm_
    param_norm = p.grad.data.norm(norm_type)
  File "c:\users\alienware\anaconda3\lib\site-packages\torch\tensor.py", line 339, in norm
    return torch.norm(self, p, dim, keepdim, dtype=dtype)
  File "c:\users\alienware\anaconda3\lib\site-packages\torch\functional.py", line 747, in norm
    return torch._C._VariableFunctions.norm(input, p)
RuntimeError: CUDA error: unspecified launch failure
```

I use python 3.7.4 and gpu is rtx 2060.
Thank you!

**Comment by francoishernandez** [comment]
That's strange. Just ran it again it seems to go fine.
Is this repeatable?

**Comment by longsamaa** [comment]
> That's strange. Just ran it again it seems to go fine.
> Is this repeatable?


I tried again, but the problem was this

**Comment by longsamaa** [comment]
I have tried training many times but still have this problem

**Comment by kadir-gunel** [comment]
@longsamaa did you manage to solve the issue ?
