### ISSUE TITLE
error when use transformor as encoder

### ISSUE THREAD

**Issue by wuhaixutab** [OpenNMT/OpenNMT-py#177]
Traceback (most recent call last):
  File "train.py", line 316, in <module>
    main()
  File "train.py", line 312, in main
    trainModel(model, train, valid, fields, optim)
  File "train.py", line 178, in trainModel
    train_stats = trainEpoch(epoch)
  File "train.py", line 142, in trainEpoch
    model(src, tgt, src_lengths, dec_state)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/haixu/Desktop/OpenNMT8.21/onmt/Models.py", line 467, in forward
    enc_hidden, context = self.encoder(src, lengths)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/haixu/Desktop/OpenNMT8.21/onmt/Models.py", line 198, in forward
    out = self.transformer[i](out, input[:, :, 0].transpose(0, 1))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/haixu/Desktop/OpenNMT8.21/onmt/modules/Transformer.py", line 69, in forward
    mid, _ = self.self_attn(input, input, input, mask=mask)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/haixu/Desktop/OpenNMT8.21/onmt/modules/MultiHeadedAttn.py", line 39, in forward
    aeq(self.d_model % 8, 0)
  File "/home/haixu/Desktop/OpenNMT8.21/onmt/modules/Util.py", line 9, in aeq
    assert a == base, str(args)
AssertionError: (4, 0)

**Comment by sebastianGehrmann** [comment]
Hi, the transformer model is not yet documented. See #123

**Comment by srush** [comment]
You need to have all the parameters be size 512 or 256 for transformer to work.

**Comment by wuhaixutab** [comment]
what do you mean by "all the parameters"? including what?

**Comment by sebastianGehrmann** [comment]
`word_vec_size`, `feature_vec_size` (if you use this) and `rnn_size`.

**Comment by VincentCCL** [comment]
If I try with this command
`python train.py -data /home/jerom/INT/Resources/Bijbel/preprocess_data -save_model rembrandt -encoder_type transformer -word_vec_size 256 -gpuid 0 -rnn_size 256`
I get:
```
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    main(opt)
  File "train.py", line 53, in main
    single_main(opt, -1)
  File "/home/local/opennmt/OpenNMT-py/onmt/train_single.py", line 141, in main
    opt.valid_steps)
  File "/home/local/opennmt/OpenNMT-py/onmt/trainer.py", line 177, in train
    report_stats)
  File "/home/local/opennmt/OpenNMT-py/onmt/trainer.py", line 285, in _gradient_accumulation
    self.model(src, tgt, src_lengths)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/local/opennmt/OpenNMT-py/onmt/models/model.py", line 46, in forward
    memory_lengths=lengths)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/local/opennmt/OpenNMT-py/onmt/decoders/decoder.py", line 171, in forward
    tgt, memory_bank, memory_lengths=memory_lengths)
  File "/home/local/opennmt/OpenNMT-py/onmt/decoders/decoder.py", line 343, in _run_forward_pass
    rnn_output, dec_state = self.rnn(decoder_input, dec_state)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/local/opennmt/OpenNMT-py/onmt/models/stacked_rnn.py", line 23, in forward
    h_0, c_0 = hidden
ValueError: need more than 1 value to unpack

```

Any solution for this?

**Comment by vince62s** [comment]
Please read the doc and examples.

**Comment by VincentCCL** [comment]
can you point to a specific url?

**Comment by vince62s** [comment]
http://opennmt.net/OpenNMT-py/FAQ.html
