### ISSUE TITLE
training errors with '-train_from'

### ISSUE THREAD

**Issue by lihongzheng-nlp** [OpenNMT/OpenNMT-py#1774]
I  trained with pretrained embeddings, but it stopped after some epoches, and I continued the training from where it corrupted with the command:`CUDA_VISIBLE_DEVICES=0 python ~/opennmt/train.py -data ../bpe/data -save_model vi2zh-10-model -word_vec_size 300 -pre_word_vecs_enc embeddings.enc.pt -pre_word_vecs_dec embeddings.dec.pt -world_size 1 -gpu_ranks 0 -log_file training-new.log -train_from vi2zh-10-model_step_30000.pt`

But it gave some errors:
Traceback (most recent call last):
  File "/home2/sj/anaconda3/lib/python3.6/tarfile.py", line 2294, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/home2/sj/anaconda3/lib/python3.6/tarfile.py", line 1090, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/home2/sj/anaconda3/lib/python3.6/tarfile.py", line 1026, in frombuf
    raise EmptyHeaderError("empty header")
tarfile.EmptyHeaderError: empty header

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home2/sj/.local/lib/python3.6/site-packages/torch/serialization.py", line 595, in _load
    return legacy_load(f)
  File "/home2/sj/.local/lib/python3.6/site-packages/torch/serialization.py", line 506, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/home2/sj/anaconda3/lib/python3.6/tarfile.py", line 1586, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/home2/sj/anaconda3/lib/python3.6/tarfile.py", line 1616, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/home2/sj/anaconda3/lib/python3.6/tarfile.py", line 1479, in __init__
    self.firstmember = self.next()
  File "/home2/sj/anaconda3/lib/python3.6/tarfile.py", line 2309, in next
    raise ReadError("empty file")
tarfile.ReadError: empty file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home2/sj/opennmt/train.py", line 6, in <module>
    main()
  File "/home2/sj/translation/OpenNMT-py-master-GPU-v3/onmt/bin/train.py", line 200, in main
    train(opt)
  File "/home2/sj/translation/OpenNMT-py-master-GPU-v3/onmt/bin/train.py", line 29, in train
    map_location=lambda storage, loc: storage)
  File "/home2/sj/.local/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home2/sj/.local/lib/python3.6/site-packages/torch/serialization.py", line 597, in _load
    if _is_zipfile(f):
  File "/home2/sj/.local/lib/python3.6/site-packages/torch/serialization.py", line 75, in _is_zipfile
    if ord(magic_byte) != ord(read_byte):
TypeError: ord() expected a character, but string of length 0 found

So what's the problem? I can train the models successfully before without the `-train_from`. I'm totally confused. Thank you very much!

**Comment by francoishernandez** [comment]
It looks like your checkpoint is empty or corrupted. Maybe it was not saved properly. Did you try with another one?
