### ISSUE TITLE
IndexError while evaluating with a model trained with guided alignment. 

### ISSUE THREAD

**Issue by ArbinTimilsina** [OpenNMT/OpenNMT-py#1787]
I came across the following error while running evaluation. I am running OpenNMT-py 1.1.1 and using the transformer model trained with guided alignment. For translation, I have `replace_unk` and `report_align` set to True.
```
File ".../onmt/translate/translation.py", line 51, in _build_target_tokens
    _, max_index = attn[i][:len(src_raw)].max(0)
IndexError: index 12 is out of bounds for dimension 0 with size 7
```
This error happens only during evaluation when I pass the `-tgt` file to the `translator.translate()`. If I don’t pass the -tgt file, I don’t come across this error.

Also, in my case, the following source-target combination would create this error:
```
Source: ▁sub ▁v f ▁: ▁né mon e , ▁dr oo , ▁ve en , ▁ ¤ aka ¤ 
Target: ▁vo ▁by ▁: ▁ ¤ aka ¤
```

**Comment by francoishernandez** [comment]
That's strange, I'm not sure to get why the `-tgt` arg is of importance here.
@Zenglinxiao any idea?
@ArbinTimilsina could you please post the full trace?

**Comment by ArbinTimilsina** [comment]
@francoishernandez, below is the full trace:
```
  File ".../onmt/translate/translator.py", line 357, in translate
    translations = xlation_builder.from_batch(batch_data)
  File ".../onmt/translate/translation.py", line 101, in from_batch
    for n in range(self.n_best)]
  File ".../onmt/translate/translation.py", line 101, in <listcomp>
    for n in range(self.n_best)]
  File ".../onmt/translate/translation.py", line 51, in _build_target_tokens
    _, max_index = attn[i][:len(src_raw)].max(0)
IndexError: index 12 is out of bounds for dimension 0 with size 7
```

**Comment by Zenglinxiao** [comment]
Oh. Thanks for this report. I just checked the code, so the problem came from the #L477 in translator.py that was used for debugging purpose. When you set -tgt, we do the align forward using the tgt rather than prediction, so latter when build prediction sentence, this cause a mismatch by using the output prediction and alignment between src and tgt.

**Comment by fkurushin** [comment]
@Zenglinxiao I have the similar error but not in the `translation.py` can you put some light on my problem too?

```bash
(.venv) fkurushin@search-seara-nlp-gpu-05:~/Chinese-Russian-translator$ onmt_translate     --model=/data/translator/models_step_100000.pt     --src=/data/translator/parallel/zh_test_ecom_bpe.txt     --output=/data/translator/parallel/ru_test_ecom_bpe.txt     --batch_size=5000     --beam_size=5     --verbose --replace_unk --batch_type=tokens
[2024-04-18 20:57:12,354 INFO] Loading checkpoint from /data/translator/models_step_100000.pt
[2024-04-18 20:57:12,870 INFO] Loading data into the model
Traceback (most recent call last):
  File "/home/fkurushin/Chinese-Russian-translator/.venv/bin/onmt_translate", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py', 'console_scripts', 'onmt_translate')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fkurushin/Chinese-Russian-translator/OpenNMT-py/onmt/bin/translate.py", line 45, in main
    translate(opt)
  File "/home/fkurushin/Chinese-Russian-translator/OpenNMT-py/onmt/bin/translate.py", line 20, in translate
    _, _ = engine.infer_file()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/fkurushin/Chinese-Russian-translator/OpenNMT-py/onmt/inference_engine.py", line 35, in infer_file
    scores, preds = self._translate(infer_iter)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fkurushin/Chinese-Russian-translator/OpenNMT-py/onmt/inference_engine.py", line 159, in _translate
    scores, preds = self.translator._translate(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fkurushin/Chinese-Russian-translator/OpenNMT-py/onmt/translate/translator.py", line 496, in _translate
    batch_data = self.translate_batch(batch, attn_debug)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fkurushin/Chinese-Russian-translator/OpenNMT-py/onmt/translate/translator.py", line 878, in translate_batch
    return self._translate_batch_with_strategy(batch, decode_strategy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fkurushin/Chinese-Russian-translator/OpenNMT-py/onmt/translate/translator.py", line 953, in _translate_batch_with_strategy
    decode_strategy.advance(log_probs, attn)
  File "/home/fkurushin/Chinese-Russian-translator/OpenNMT-py/onmt/translate/beam_search.py", line 354, in advance
    current_attn = attn[self.select_indices]
                   ~~~~^^^^^^^^^^^^^^^^^^^^^
IndexError: index 1040 is out of bounds for dimension 0 with size 1
```

appreciate !

**Comment by hegdekasha** [comment]
I am getting exactly the above error... Please Help me!!!!!!!!

[2024-06-04 12:00:35,278 INFO] Loading checkpoint from /home/mu/Downloads/OpenNMT-py/kan-hin/run/model_step_100000.pt
[2024-06-04 12:00:35,630 INFO] Loading data into the model
Traceback (most recent call last):
  File "/usr/local/bin/onmt_translate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/onmt/bin/translate.py", line 45, in main
    translate(opt)
  File "/usr/local/lib/python3.10/dist-packages/onmt/bin/translate.py", line 20, in translate
    _, _ = engine.infer_file()
  File "/usr/local/lib/python3.10/dist-packages/onmt/inference_engine.py", line 35, in infer_file
    scores, preds = self._translate(infer_iter)
  File "/usr/local/lib/python3.10/dist-packages/onmt/inference_engine.py", line 159, in _translate
    scores, preds = self.translator._translate(
  File "/usr/local/lib/python3.10/dist-packages/onmt/translate/translator.py", line 496, in _translate
    batch_data = self.translate_batch(batch, attn_debug)
  File "/usr/local/lib/python3.10/dist-packages/onmt/translate/translator.py", line 878, in translate_batch
    return self._translate_batch_with_strategy(batch, decode_strategy)
  File "/usr/local/lib/python3.10/dist-packages/onmt/translate/translator.py", line 953, in _translate_batch_with_strategy
    decode_strategy.advance(log_probs, attn)
  File "/usr/local/lib/python3.10/dist-packages/onmt/translate/beam_search.py", line 354, in advance
    current_attn = attn[self.select_indices]
IndexError: index 35 is out of bounds for dimension 0 with size 1
