### ISSUE TITLE
TypeError when run demo of QuickStart

### ISSUE THREAD

**Issue by SeekaMoon** [OpenNMT/OpenNMT-py#1799]
Hello, when I try to run the demo of QuickStart, it raises a TypeError.

`onmt_preprocess -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo`

`Traceback (most recent call last):`
`  File "/usr/local/bin/onmt_preprocess", line 5, in <module>`
`    from onmt.bin.preprocess import main`
`  File "/usr/local/lib/python3.5/dist-packages/onmt/__init__.py", line 4, in <module>`
`    import onmt.inputters`
`  File "/usr/local/lib/python3.5/dist-packages/onmt/inputters/__init__.py", line 6, in <module>`
`    from onmt.inputters.inputter import \`
`  File "/usr/local/lib/python3.5/dist-packages/onmt/inputters/inputter.py", line 17, in <module>`
`    from onmt.inputters.image_dataset import image_fields`
`  File "/usr/local/lib/python3.5/dist-packages/onmt/inputters/image_dataset.py", line 13, in <module>`
`    from torchvision import transforms`
`  File "/usr/local/lib/python3.5/dist-packages/torchvision/__init__.py", line 3, in <module>`
`    from torchvision import models`
`  File "/usr/local/lib/python3.5/dist-packages/torchvision/models/__init__.py", line 12, in <module>`
`    from . import detection`
`  File "/usr/local/lib/python3.5/dist-packages/torchvision/models/detection/__init__.py", line 1, in <module>`
`    from .faster_rcnn import *`
`  File "/usr/local/lib/python3.5/dist-packages/torchvision/models/detection/faster_rcnn.py", line 14, in <module>`
`    from .roi_heads import RoIHeads`
`  File "/usr/local/lib/python3.5/dist-packages/torchvision/models/detection/roi_heads.py", line 210, in <module>`
`    @torch.jit.script`
`  File "/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py", line 1290, in script`
`    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))`
`  File "/usr/local/lib/python3.5/dist-packages/torch/jit/_recursive.py", line 568, in try_compile_fn`
`    return torch.jit.script(fn, _rcb=rcb)`
`  File "/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py", line 1290, in script`
`    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))`
`  File "/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py", line 2030, in _get_overloads`
`    compiled_fns.append(_compile_function_with_overload(overload_fn, qual_name, obj))`
`  File "/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py", line 2010, in _compile_function_with_overload`
`    overload_signature = torch.jit.annotations.get_signature(overload_fn, None, None, inspect.ismethod(overload_fn))`
`  File "/usr/local/lib/python3.5/dist-packages/torch/jit/annotations.py", line 79, in get_signature`
`    signature = parse_type_line(type_line, rcb, loc)`
`  File "/usr/local/lib/python3.5/dist-packages/torch/jit/annotations.py", line 165, in parse_type_line`
`    arg_types = [ann_to_type(ann, loc) for ann in arg_ann]`
`  File "/usr/local/lib/python3.5/dist-packages/torch/jit/annotations.py", line 165, in <listcomp>`
`    arg_types = [ann_to_type(ann, loc) for ann in arg_ann]`
`  File "/usr/local/lib/python3.5/dist-packages/torch/jit/annotations.py", line 303, in ann_to_type`
`    the_type = try_ann_to_type(ann, loc)`
`  File "/usr/local/lib/python3.5/dist-packages/torch/jit/annotations.py", line 296, in try_ann_to_type`
`    the_type = torch._C._resolve_type_from_object(ann, loc, fake_rcb)`
`TypeError: _resolve_type_from_object(): incompatible function arguments. The following argument types are supported:`
`    1. (arg0: object, arg1: torch._C._jit_tree_views.SourceRange, arg2: Callable[[str], function]) -> torch._C.Type`
``
`Invoked with: typing.Union[int, NoneType], None, <function try_ann_to_type.<locals>.fake_rcb at 0x7f58003392f0>`

It seems like a problem of torchvision.

The vision of torch is `1.5.0+cu101`, the vision of torchvision is `0.6.0+cu101` and the vision of torchtext is `0.4.0`.

Thank you.

**Comment by SeekaMoon** [comment]
OK, I have solve this problem. It looks like opennmt is not compatible with the latest torch (1.5.0) and torchvision (0.6.0). When I use `torch==1.4.0` and `torchvision==0.5.0`, this problem doesn' t exist anymore.
