### ISSUE TITLE
CUDA: Out of memory 

### ISSUE THREAD

**Issue by banhtrangtrungcut** [OpenNMT/OpenNMT-py#1825]
My commands: 
`python train.py -valid_batch_size 16 -data data/demo -save_model data-demo -gpu_ranks 0`

My issue: 
```
[2020-07-08 13:02:52,367 INFO] encoder: 28047000
[2020-07-08 13:02:52,371 INFO] decoder: 28529749
[2020-07-08 13:02:52,372 INFO] * number of parameters: 56576749
[2020-07-08 13:02:52,374 INFO] Starting training on GPU: [0]
[2020-07-08 13:02:52,374 INFO] Start training loop and validate every 10000 steps...
[2020-07-08 13:02:52,374 INFO] Loading dataset from data\demo.train.0.pt
[2020-07-08 13:02:54,248 INFO] number of examples: 122206
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    main()
  File "D:\OpenNMT-py\onmt\bin\train.py", line 209, in main
    train(opt)
  File "D:\OpenNMT-py\onmt\bin\train.py", line 91, in train
    single_main(opt, 0)
  File "D:\OpenNMT-py\onmt\train_single.py", line 146, in main
    valid_steps=opt.valid_steps)
  File "D:\OpenNMT-py\onmt\trainer.py", line 265, in train
    report_stats)
  File "D:\OpenNMT-py\onmt\trainer.py", line 388, in _gradient_accumulation
    with_align=self.with_align)
  File "C:\Users\84946\.conda\envs\tf-gpu\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\OpenNMT-py\onmt\models\model.py", line 51, in forward
    with_align=with_align)
  File "C:\Users\84946\.conda\envs\tf-gpu\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\OpenNMT-py\onmt\decoders\decoder.py", line 214, in forward
    tgt, memory_bank, memory_lengths=memory_lengths)
  File "D:\OpenNMT-py\onmt\decoders\decoder.py", line 391, in _run_forward_pass
    rnn_output, dec_state = self.rnn(decoder_input, dec_state)
  File "C:\Users\84946\.conda\envs\tf-gpu\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\OpenNMT-py\onmt\models\stacked_rnn.py", line 26, in forward
    h_1_i, c_1_i = layer(input_feed, (h_0[i], c_0[i]))
  File "C:\Users\84946\.conda\envs\tf-gpu\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\84946\.conda\envs\tf-gpu\lib\site-packages\torch\nn\modules\rnn.py", line 955, in forward
    self.bias_ih, self.bias_hh,
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 1.20 GiB already allocated; 19.35 MiB free; 1.21 GiB reserved in total by PyTorch)
```

I've read all of `CUDA: out of memory` that I found on github and google but my problem is not solved yet. 
Can anyone help?

**Comment by banhtrangtrungcut** [comment]
I reduced the `-batch_size` to `32` and it worked.
