### ISSUE TITLE
Translate function gives AttributeError: 'tuple' object has no attribute 'size'

### ISSUE THREAD

**Issue by arushi-08** [OpenNMT/OpenNMT-py#1827]
Hello, I have encountered the following error, when I run the translate function after training model and preprocessing data: 
```
Traceback (most recent call last):
  File "/usr/local/bin/onmt_translate", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py==1.1.1', 'console_scripts', 'onmt_translate')())
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-1.1.1-py3.6.egg/onmt/bin/translate.py", line 48, in main
    translate(opt)
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-1.1.1-py3.6.egg/onmt/bin/translate.py", line 32, in translate
    align_debug=opt.align_debug
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-1.1.1-py3.6.egg/onmt/translate/translator.py", line 362, in translate
    batch, data.src_vocabs, attn_debug
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-1.1.1-py3.6.egg/onmt/translate/translator.py", line 551, in translate_batch
    decode_strategy)
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-1.1.1-py3.6.egg/onmt/translate/translator.py", line 714, in _translate_batch_with_strategy
    batch, decode_strategy.predictions)
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-1.1.1-py3.6.egg/onmt/translate/translator.py", line 494, in _align_forward
    enc_states = tile(enc_states, n_best, dim=1)
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-1.1.1-py3.6.egg/onmt/utils/misc.py", line 60, in tile
    perm = list(range(len(x.size())))
AttributeError: 'tuple' object has no attribute 'size'
```
The code I want to run is:
```
!onmt_translate \
 -model demomodelchecking_step_200.pt \
 -src /content/drive/My\ Drive/nmt_data.en \
 -beam_size 5 \
 -n_best 5 \
 -output data/pred.txt \
 -replace_unk -verbose \
 -report_align
```
So I tried printing this `x` in `perm = list(range(len(x.size())))` and it is:
```
(tensor([[[-0.2097,  0.0797, -0.0469,  ...,  0.1075,  0.0763, -0.1312],
         [-0.2097,  0.0798, -0.0471,  ...,  0.1078,  0.0763, -0.1311],
         [-0.2097,  0.0798, -0.0473,  ...,  0.1084,  0.0764, -0.1309],
         ...,
         [-0.0861, -0.0564,  0.0218,  ...,  0.0022,  0.0675,  0.0410],
         [-0.0861, -0.0564,  0.0218,  ...,  0.0022,  0.0675,  0.0410],
         [-0.0861, -0.0564,  0.0218,  ...,  0.0022,  0.0675,  0.0410]],

        [[ 0.2831,  0.0557, -0.1619,  ...,  0.4825,  0.7572, -0.0737],
         [ 0.2828,  0.0558, -0.1619,  ...,  0.4819,  0.7566, -0.0737],
         [ 0.2823,  0.0559, -0.1618,  ...,  0.4808,  0.7555, -0.0735],
         ...,
         [ 0.0806,  0.0329,  0.0115,  ..., -0.0021,  0.0750,  0.0136],
         [ 0.0806,  0.0329,  0.0115,  ..., -0.0021,  0.0750,  0.0136],
         [ 0.0806,  0.0329,  0.0115,  ..., -0.0021,  0.0750,  0.0136]]]), tensor([[[-0.4934,  0.2120, -0.1298,  ...,  0.2400,  0.2317, -0.2579],
         [-0.4932,  0.2120, -0.1301,  ...,  0.2406,  0.2318, -0.2579],
         [-0.4930,  0.2120, -0.1307,  ...,  0.2419,  0.2320, -0.2578],
         ...,
         [-0.2006, -0.1166,  0.0466,  ...,  0.0044,  0.1708,  0.0903],
         [-0.2006, -0.1166,  0.0466,  ...,  0.0044,  0.1708,  0.0903],
         [-0.2006, -0.1166,  0.0466,  ...,  0.0044,  0.1708,  0.0903]],

        [[ 0.7324,  0.2454, -0.5503,  ...,  1.1976,  1.9693, -0.3309],
         [ 0.7315,  0.2457, -0.5498,  ...,  1.1963,  1.9621, -0.3307],
         [ 0.7299,  0.2461, -0.5491,  ...,  1.1934,  1.9490, -0.3300],
         ...,
         [ 0.2026,  0.0862,  0.0325,  ..., -0.0059,  0.1600,  0.0447],
         [ 0.2026,  0.0862,  0.0325,  ..., -0.0059,  0.1600,  0.0447],
         [ 0.2026,  0.0862,  0.0325,  ..., -0.0059,  0.1600,  0.0447]]]))
```
I have tried to run the demo scripts too, and I am arriving at the same error.
Should I remove `.size()` to get the length of the tuple? Or am I not supposed to get `x` as a tuple in the first place?
Thank you.

**Comment by puneethsaladi** [comment]
From the stack trace, I see that the error occurs when tile() is called on enc_states returned by the encoder. It should not be a tuple.

**Comment by francoishernandez** [comment]
Hey @arushi-08 
What kind of model is this? Can you share the command line you used to train it?

**Comment by arushi-08** [comment]
Hi @francoishernandez! I am running the default model, which is 2-layer LSTM with 500 hidden units on both the encoder/decoder. 
```
!onmt_train -data data/demo -save_model demomodelchecking -train_steps 200 -gpu_ranks 0
```
I am running this on colab.

**Comment by francoishernandez** [comment]
That's probably the issue. The `-report_align` flag is intended to be used with Transformer models trained with alignments (#1615), not RNN (for which you can get alignments through the attention matrix `-attn_debug`).

Could probably be a good idea to add an assert to make this explicit.

**Comment by arushi-08** [comment]
Yes! That was it. Thank you for your time!
