### ISSUE TITLE
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

### ISSUE THREAD

**Issue by LinuxBeginner** [OpenNMT/OpenNMT-py#1838]
There was no issue at the time of pre-processing and training. Following issue came up when I tried to translate :

`!python translate.py -model models/tr-6.pt -src dataset/test.en -output dataset/pred1.tr -replace_unk -verbose`
 OR
`!onmt_translate -model models/tr-6.pt -src dataset/test.en -output dataset/pred1.tr -replace_unk -verbose`

ERROR:

[2020-08-01 10:16:31,220 INFO] Translating shard 0.
Traceback (most recent call last):
  File "translate.py", line 6, in <module>
    main()
  File "/content/drive/My Drive/NMT/OpenNMT-py/onmt/bin/translate.py", line 48, in main
    translate(opt)
  File "/content/drive/My Drive/NMT/OpenNMT-py/onmt/bin/translate.py", line 32, in translate
    align_debug=opt.align_debug
  File "/content/drive/My Drive/NMT/OpenNMT-py/onmt/translate/translator.py", line 362, in translate
    batch, data.src_vocabs, attn_debug
  File "/content/drive/My Drive/NMT/OpenNMT-py/onmt/translate/translator.py", line 551, in translate_batch
    decode_strategy)
  File "/content/drive/My Drive/NMT/OpenNMT-py/onmt/translate/translator.py", line 683, in _translate_batch_with_strategy
    decode_strategy.advance(log_probs, attn)
  File "/content/drive/My Drive/NMT/OpenNMT-py/onmt/translate/beam_search.py", line 212, in advance
    torch.div(self.topk_ids, vocab_size, out=self._batch_index)
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

[ Note: There was no issue while translating also. The issue came up since yesterday. NO modification in the code was done. ]
[ NOTE: Running the whole code in Google Colab, so for each new Colab notebook session, I have to 

`pip install OpenNMT-py` ]

**Comment by thilakshiK** [comment]
Even I’m facing this issue in Google Colab.

**Comment by LinuxBeginner** [comment]
`pip install OpenNMT-py` unless someone change the OpenNMT-py/onmt/translate/beam_search.py  in the master code.

So, 

```
git clone https://github.com/OpenNMT/OpenNMT-py.git
cd OpenNMT-py
python setup.py install
```

And change the line 212 in  OpenNMT-py/onmt/translate/beam_search.py from
 `torch.div(self.topk_ids, vocab_size, out=self._batch_index)`
to
`torch.floor_divide(self.topk_ids, vocab_size, out=self._batch_index)`


We might also get the following error too in Google collab:

```
Traceback (most recent call last):
  File "translate.py", line 6, in <module>
    main()
  File "/content/drive/My Drive/NMT/OpenNMT-py/onmt/bin/translate.py", line 48, in main
    translate(opt)
  File "/content/drive/My Drive/NMT/OpenNMT-py/onmt/bin/translate.py", line 18, in translate
    translator = build_translator(opt, logger=logger, report_score=True)
  File "/content/drive/My Drive/NMT/OpenNMT-py/onmt/translate/translator.py", line 28, in build_translator
    fields, model, model_opt = load_test_model(opt)
  File "/content/drive/My Drive/NMT/OpenNMT-py/onmt/model_builder.py", line 95, in load_test_model
    map_location=lambda storage, loc: storage)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 765, in _legacy_load
    result = unpickler.load()
AttributeError: Can't get attribute '_split_tokenizer' on <module 'torchtext.data.utils' from '/usr/local/lib/python3.6/dist-packages/torchtext/data/utils.py'>

```
This is caused by torchtext version **below** 0.4.0

`pip install torchtext==0.4.0`

 resolve the second issue.

After all this I still get the following warning:
```
/content/drive/My Drive/NMT/OpenNMT-py/onmt/translate/beam_search.py:272: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  finished_hyp = self.is_finished[i].nonzero().view(-1)
```

**Comment by thilakshiK** [comment]
@LinuxBeginner Thanks a lot. Your solution worked for me 😀. However, I didn't get any warnings or errors.

**Comment by MalouNetlight** [comment]
Hint: This is caused by a change in pytorch 1.6.0. : https://github.com/pytorch/pytorch/releases
In their new release, they changed the warning to an error, which is why @LinuxBeginner you got the error message in the first place:
> Throw a RuntimeError for deprecated torch.div and torch.addcdiv integer floor division behavior
> In 1.5.1 and older PyTorch releases torch.div , torch.addcdiv, and the / operator perform integer floor division. In 1.6 attempting to perform integer division throw a RuntimeError, and in 1.7 the behavior will change so that these operations always perform true division (consistent with Python and NumPy division).

What I did is just to pin the version to pytorch==1.5.1. That also solved the issue

**Comment by vince62s** [comment]
yes we've not looked into the changes for pytorch 1.6
We'll try to do this over the summer.
Best is to use pytorch 1.4 but obviously 1.5 seems to work fine too.
