### ISSUE TITLE
CUDA outof memory on validation loop.

### ISSUE THREAD

**Issue by BrightXiaoHan** [OpenNMT/OpenNMT-py#1852]
I train my own model with "python onmt/bin/train.py -data examples/enzh/en-zh.atok.low -save_model enzh_model --encoder_type transformer --decoder_type transformer --enc_layers 6 --dec_layers 6 --rnn_size 512 -src_word_vec_size 512 -tgt_word_vec_size 512  --optim adam -learning_rate 0.001 -world_size 4 -gpu_ranks 0 1 2 3"，when validate model every 10000 loops, raise error like this
```
Traceback (most recent call last):
  File "onmt/bin/train.py", line 201, in <module>
Process SpawnProcess-5:
    main()
  File "onmt/bin/train.py", line 197, in main
    train(opt)
  File "onmt/bin/train.py", line 91, in train
    p.join()
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/multiprocessing/process.py", line 149, in join
Traceback (most recent call last):
    res = self._popen.wait(timeout)
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/bin/train.py", line 129, in batch_producer
    b = next_batch(device_id)
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/bin/train.py", line 119, in next_batch
    semaphore.acquire()
KeyboardInterrupt
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "onmt/bin/train.py", line 181, in signal_handler
    raise Exception(msg)
Exception: 

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/bin/train.py", line 139, in run
    single_main(opt, device_id, batch_queue, semaphore)
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/train_single.py", line 145, in main
    trainer.train(
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/trainer.py", line 279, in train
    valid_stats = self.validate(
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/trainer.py", line 339, in validate
    outputs, attns = valid_model(src, tgt, src_lengths,
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/models/model.py", line 49, in forward
    dec_out, attns = self.decoder(dec_in, memory_bank,
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/decoders/transformer.py", line 314, in forward
    output, attn, attn_align = layer(
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/decoders/transformer.py", line 93, in forward
    output, attns = self._forward(*args, **kwargs)
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/decoders/transformer.py", line 154, in _forward
    query, _ = self.self_attn(input_norm, input_norm, input_norm,
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/modules/multi_headed_attn.py", line 202, in forward
    attn = self.softmax(scores).to(query.dtype)
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1140, in forward
    return F.softmax(input, self.dim, _stacklevel=5)
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/site-packages/torch/nn/functional.py", line 1498, in softmax
    ret = input.softmax(dim)
RuntimeError: CUDA out of memory. Tried to allocate 2.18 GiB (GPU 0; 10.92 GiB total capacity; 6.64 GiB already allocated; 2.16 GiB free; 8.16 GiB reserved in total by PyTorch)
```
so, I reduce my batch size from 64 to 32 and valid_batch size from 32 to 16.  But the "CUDA out of memory" was still there.  Why I training with batch size 64 is ok, but training with batch size 32 and validating with 16 is error?

**Comment by BrightXiaoHan** [comment]
I solve this by set --valid_steps 999999. haha. But when I execute the translate script with 
```
python onmt/bin/translate.py -gpu 0 -model enzh*.pt -src examples/enzh/en.test -tgt examples/enzh/zh.test  -replace_unk -verbose -output en-zh.test.pred.atok --batch_size 4  --beam_size 1
```
This is a really low batch_size, The error was still there.
```
[2020-08-24 09:52:37,414 INFO] Translating shard 0.
/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/site-packages/torchtext/data/example.py:52: UserWarning: Example class will be retired in the 0.8.0 release and moved to torchtext.legacy. Please see 0.7.0 release notes for further information.
  warnings.warn('Example class will be retired in the 0.8.0 release and moved to torchtext.legacy. Please see 0.7.0 release notes for further information.', UserWarning)
/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/site-packages/torchtext/data/iterator.py:48: UserWarning: OrderedIterator class will be retired in the 0.8.0 release and moved to torchtext.legacy. Please see 0.7.0 release notes for further information.
  warnings.warn('{} class will be retired in the 0.8.0 release and moved to torchtext.legacy. Please see 0.7.0 release notes for further information.'.format(self.__class__.__name__), UserWarning)
/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/site-packages/torchtext/data/batch.py:23: UserWarning: Batch class will be retired in the 0.8.0 release and moved to torchtext.legacy. Please see 0.7.0 release notes for further information.
  warnings.warn('{} class will be retired in the 0.8.0 release and moved to torchtext.legacy. Please see 0.7.0 release notes for further information.'.format(self.__class__.__name__), UserWarning)
[2020-08-24 09:52:43,980 INFO] 
SENT 1: ['These', 'expenditure', 'items', 'include', 'commitments', 'approved', 'by', 'the', 'Controller', 'for', 'future', 'financial', 'periods', 'in', 'accordance', 'with', 'financial', 'rule', '1￭', '0￭', '6', '￭.￭', '7', '￭.']
PRED 1: 这些 项目 包括 主计长 根据 财务 细则 1￭ 0￭ 6 ￭.￭ 7 核准 的 未来 财政 期间 支出 项目 。
PRED SCORE: -0.0000
GOLD 1: 这些 支出 项目 包括 主计长 根据 财务 细则 1￭ 0￭ 6 ￭.￭ 7 核准 的 未来 财政 期间 的 承 付款 。
GOLD SCORE: -14.9426

[2020-08-24 09:52:43,980 INFO] 
SENT 2: ['Contrary', 'to', 'what', 'the', 'Japanese', 'representative', 'said', 'yesterday', '￭,', 'our', 'nuclear', 'deterrent', 'is', 'a', 'reliable', 'guarantee', 'of', 'peace', 'and', 'stability', 'on', 'the', 'Korean', 'peninsula', 'and', 'beyond', '￭.']
PRED 2: 与 昨天 的 日本 代表 所说 的 那样 ， 我们 的 核威慑 是 对 朝鲜半岛 和平 与 稳定 的 可靠 和 可靠 的 威慑 。
PRED SCORE: -0.0000
GOLD 2: 与 日本 代表 昨天 的 发言 相反 ， 我们 的 核威慑 力量 是 对 朝鲜半岛 和 周边地区 和平 与 稳定 的 可靠 保障 。
GOLD SCORE: -36.4085

[2020-08-24 09:52:43,980 INFO] 
SENT 3: ['2', '￭.', 'The', 'secretariat', 'has', 'the', 'honour', 'to', 'present', 'to', 'the', 'Working', 'Group', '￭,', 'in', 'the', 'annex', 'to', 'the', 'present', 'note', '￭,', 'document', 'UNEP', '￭/￭', 'FAO', '￭/￭', 'RC', '￭/￭', 'COP', '￭.￭', '1', '￭/￭', '2￭', '0', '￭.']
PRED 3: 2 . 工作组 谨 随函 附上 UNEP / FAO / RC / COP ￭.￭ 1 / 2￭ 0 号 文件 附件 所载 的 秘书处 的 说明 。
PRED SCORE: -0.0000
GOLD 3: 2 . 秘书处 谨此 在 本 说明 的 附件 中向 工作组 转发 文件 UNEP / FAO / RC / COP ￭.￭ 1 / 2￭ 0 。
GOLD SCORE: -33.2022

[2020-08-24 09:52:43,980 INFO] 
SENT 4: ['Summary', 'record', 'of', 'the', '9￭', 'th', 'meeting']
PRED 4: 第 9 次 会议 简要 记录
PRED SCORE: -0.0181
GOLD 4: 第 9 次 会议
GOLD SCORE: -11.3116

[2020-08-24 09:52:52,234 INFO] 
SENT 5: ['Between', '1￭', '9￭', '9￭', '0', 'and', '1￭', '9￭', '9￭', '5', '￭,', 'the', 'trade', 'balance', 'of', 'Togo', 'was', 'in', 'deficit', '￭,', 'rising', 'to', '8￭', '8', 'million', 'CFA', 'francs', 'in', '1￭', '9￭', '9￭', '5', '￭.']
PRED 5: 1￭ 9￭ 9￭ 5 年 至 1￭ 9￭ 9￭ 8 年 期间 ， 多哥 的 贸易赤字 增加 了 8￭ 0 万 非洲法郎 ， 1￭ 9￭ 9￭ 5 年 的 贸易赤字 增加 到 5￭ 0￭ 0 万 非洲法郎 。
PRED SCORE: -0.0000
GOLD 5: 1￭ 9￭ 9￭ 0 - 1￭ 9￭ 9￭ 5 年 期间 ， 多哥 的 贸易 平衡 为 赤字 ， 1￭ 9￭ 9￭ 5 年 赤字 数额 升至 8￭ 8￭ 0￭ 0 万 非洲法郎 。
GOLD SCORE: -67.2072

[2020-08-24 09:52:52,235 INFO] 
SENT 6: ['8￭', '3', '￭.', 'Ms', '￭.', 'Muth￭', 'uk￭', 'um￭', 'aran￭', 'a', '(￭', 'Sri', 'Lanka', '￭)', 'said', 'that', '￭,', 'despite', 'all', 'the', 'efforts', 'of', 'the', 'international', 'community', '￭,', 'terrorism', 'continued', 'to', 'devast￭', 'ate', 'communities', 'around', 'the', 'world', '￭.']
PRED 6: 8￭ 3 . Mu￭ uk￭ an￭ uk￭ um￭ uk￭ um￭ ar￭ um￭ uk￭ um￭ ana 女士 （ 斯里兰卡 ） 说 ， 尽管 国际 社会 继续 努力 ， 但 世界各地 的 恐怖主义 继续 破坏 国际 社会 。
PRED SCORE: -0.0000
GOLD 6: 8￭ 3 . Muth￭ uk￭ um￭ ar￭ ana 女士 ( 斯里兰卡 ) 说 ， 尽管 国际 社会 做出 所有 努力 ， 但 恐怖主义 仍然 继续 摧毁 全世界 的 社区 。
GOLD SCORE: -46.0005

[2020-08-24 09:52:52,235 INFO] 
SENT 7: ['2', '￭.', 'The', 'research', 'and', 'field', 'programmes', 'in', 'which', 'the', 'non', '￭—￭', 'governmental', 'organizations', 'are', 'involved', 'inform', 'our', 'responses', 'to', 'the', 'report', 'of', 'the', 'working', 'group', 'on', 'the', 'draft', 'optional', 'protocol', '￭.']
PRED 7: 2 . 工作组 报告 草稿 介绍 了 非政府 组织 参与 的 研究 和 对 任择 议定书 的 答复 ， 并 向 其 通报 了 该 领域 的 研究 方案 。
PRED SCORE: -0.0000
GOLD 7: 2 . 非政府 组织 参与 的 研究 和 实地 方案 是 我们 对 任择 议定书 起草 工作组 报告 的 答复 的 基础 。
GOLD SCORE: -51.1303

[2020-08-24 09:52:52,235 INFO] 
SENT 8: ['The', 'first', 'such', 'trial', 'was', 'initiated', 'on', '2￭', '7', 'February', 'and', 'completed', 'on', '5', 'June', '1￭', '9￭', '9￭', '8', '￭.']
PRED 8: 第一个 审判 于 1￭ 9￭ 9￭ 7 年 2 月 2￭ 5 日 完成 ， 并于 6 月 8 日 开始 。
PRED SCORE: -0.0000
GOLD 8: 第一￭ 例 这样 的 审判 于 1￭ 9￭ 9￭ 8 年 2 月 2￭ 7 日 开始 ， 1￭ 9￭ 9￭ 8 年 6 月 5 日 完成 。
GOLD SCORE: -24.4396

Traceback (most recent call last):
  File "onmt/bin/translate.py", line 52, in <module>
    main()
  File "onmt/bin/translate.py", line 48, in main
    translate(opt)
  File "onmt/bin/translate.py", line 25, in translate
    translator.translate(
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/translate/translator.py", line 361, in translate
    batch_data = self.translate_batch(
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/translate/translator.py", line 550, in translate_batch
    return self._translate_batch_with_strategy(batch, src_vocabs,
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/translate/translator.py", line 656, in _translate_batch_with_strategy
    "gold_score": self._gold_score(
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/translate/translator.py", line 277, in _gold_score
    gs = self._score_target(
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/translate/translator.py", line 724, in _score_target
    log_probs, attn = self._decode_and_generate(
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/translate/translator.py", line 598, in _decode_and_generate
    log_probs = self.model.generator(dec_out.squeeze(0))
  File "/home/yyq/miniconda3/envs/opennmt-py/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yyq/MachineTranslation/OpenNMT-py/onmt/decoders/ensemble.py", line 102, in forward
    distributions = torch.stack(
RuntimeError: CUDA out of memory. Tried to allocate 926.00 MiB (GPU 0; 10.92 GiB total capacity; 9.57 GiB already allocated; 591.38 MiB free; 9.76 GiB reserved in total by PyTorch)
```

**Comment by francoishernandez** [comment]
Maybe there is a very long line in the next 4 lines of your test set? Also, what is your vocab size(s)?

**Comment by BrightXiaoHan** [comment]
I solve this. I use "-model enzh*.pt", so the program ensemble all the checkpoint at inference time. I should specify one checkpoint. I'm so stupid.
