### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

### ISSUE THREAD

**Issue by JustCunn** [OpenNMT/OpenNMT-py#1873]
I am trying to use 2 GPUs on the same node to train a GGNN/rnn. Here's my training script:
```
onmt_train -data $data_path/final -encoder_type ggnn -layers 2 -decoder_type rnn -rnn_size 256 \
-learning_rate 0.1 -start_decay_steps 15000 \
-learning_rate_decay 0.8 -global_attention general -batch_size 32 -word_vec_size 256 \
-bridge -train_steps 300000 -world_size 2 -gpu_ranks 0 1 -accum_count 2 -save_checkpoint_steps 50000 \
-save_model $data_path/final-model -src_vocab $data_path/srcvocab.txt -n_edge_types 7 -state_dim 256 -n_steps 10 -n_node 220 > $data_path/train.final.out
echo "train.sh complete" >> $data_path/train.out
```

When I start training, I get this error:
```
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/onmt/bin/train.py", line 145, in run
    error_queue.put((opt.gpu_ranks[device_id], traceback.format_exc()))
KeyboardInterrupt
Traceback (most recent call last):
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/bin/onmt_train", line 8, in <module>
    sys.exit(main())
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/onmt/bin/train.py", line 197, in main
    train(opt)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/onmt/bin/train.py", line 91, in train
    p.join()
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/onmt/bin/train.py", line 181, in signal_handler
    raise Exception(msg)
Exception: 

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/onmt/bin/train.py", line 139, in run
    single_main(opt, device_id, batch_queue, semaphore)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/onmt/train_single.py", line 150, in main
    valid_steps=opt.valid_steps)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/onmt/trainer.py", line 265, in train
    report_stats)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/onmt/trainer.py", line 391, in _gradient_accumulation
    with_align=self.with_align)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/onmt/models/model.py", line 45, in forward
    enc_state, memory_bank, lengths = self.encoder(src, lengths)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/onmt/encoders/ggnn_encoder.py", line 222, in forward
    in_states.append(self.in_fcs[i](prop_state))
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/functional.py", line 1678, in linear
    output += bias
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

```

Any idea what's the reason I can't use both GPUs on my node?

**Comment by Zenglinxiao** [comment]
Hello @JustCunn,
In the initial ggnn implementation, the author set the device manually in the [ggnn_encoder.py](https://github.com/OpenNMT/OpenNMT-py/blob/585499a4509b1c2dac7683b7588f3f544f89119e/onmt/encoders/ggnn_encoder.py#L211-L216) in the encoder, make it impossible to train through multi gpu. I found & fixed this error when testing for v2. You can apply [my change](https://github.com/OpenNMT/OpenNMT-py/blob/2c63a535c8c85ba77eeac2e179cfa0e70d0a90fe/onmt/encoders/ggnn_encoder.py#L213-L214) to your code to see if this works for your setting.
PS: tested with the sample files (data/ggnn*) provided by the author, will raise AssertionError using your options, but runable by only change  `n_edge_types` to 9, not sure why though.
Any idea @SteveKommrusch ?

**Comment by SteveKommrusch** [comment]
I think your change to remove the hardcoded cuda:0 and allow multi gpu
makes sense. Thanks; I didn't have a multigpu to test on. Can you
checkin or do a pull request for your change? As for the edge type issue; I
think I need to review it - it may be an issue with srcvocab parsing and
not really an edge format issue (if the COMMA delimiter is misinterpreted
you can get that assertion).

Regards,
Steve

**Comment by JustCunn** [comment]
I didn't see this email, apologies for splitting the conversation in two places. Yes, I can check-in/pull request for the issue.I'll check the comma misinterpretation just to rule it out, or not. Simple enough, just removing the ( , , ) token and start preprocessing again.Thanks,Justin
