### ISSUE TITLE
translate.py does not work with --tgt

### ISSUE THREAD

**Issue by marcotcr** [OpenNMT/OpenNMT-py#188]
Used the quickstart data.
Traceback:
```Traceback (most recent call last):
  File "translate.py", line 165, in <module>
    main()
  File "translate.py", line 86, in main
    data = onmt.IO.ONMTDataset(opt.src, opt.tgt, translator.fields, None)
  File "/home/marcotcr/OpenNMT-py/onmt/IO.py", line 149, in __init__
    if opt.dynamic_dict:
AttributeError: 'NoneType' object has no attribute 'dynamic_dict'
```
Even if the offending if is commented out, translator.translate does not work with tgt:
```
Traceback (most recent call last):
  File "translate.py", line 165, in <module>
    main()
  File "translate.py", line 96, in main
    = translator.translate(batch, data)
  File "/home/marcotcr/OpenNMT-py/onmt/Translator.py", line 216, in translate
    pred, predScore, attn, goldScore = self.translateBatch(batch, data)
  File "/home/marcotcr/OpenNMT-py/onmt/Translator.py", line 103, in translateBatch
    decStates)
  File "/home/marcotcr/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/marcotcr/OpenNMT-py/onmt/Models.py", line 296, in forward
    s_len, n_batch_, _ = src.size()
AttributeError: 'tuple' object has no attribute 'size'
```

**Comment by srush** [comment]
We're working on improving this option. You should be able to run without it for now.

**Comment by marcotcr** [comment]
Is there another way to score different translations?

A separate question: is there a way to get the top-k translations for an input sentence?

Thanks,

**Comment by Henderake** [comment]
There's a [-n_best](https://github.com/OpenNMT/OpenNMT-py/blob/master/translate.py#L48-L50) option in translate.py to output the top-k translations.

**Comment by srush** [comment]
Should be fixed. Let me know if you have other issues.

**Comment by eeric** [comment]
make OpenNMT project audio list and sentences text list, as following:
https://github.com/eeric/OpenNMT-py-make-tgt-train.txt/blob/master/openNMT_make_label.py
