### ISSUE TITLE
Make`-report_align` compatibility more explicit (transformer only)

### ISSUE THREAD

**Issue by texttheater** [OpenNMT/OpenNMT-py#1893]
I followed [the quickstart](https://opennmt.net/OpenNMT-py/quickstart.html) and all steps worked. Now in step 3, when I add the `-report_align` option as described [in the FAQ](https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md), I get an exception:

```
 ✘  ke@thot  python-3.8.5  ~/git/trnslt  onmt_translate -model toy-ende/run/model_step_1000.pt -src toy-ende/src-test.txt -output toy-ende/pred_1000.txt -verbose -report_align
[2020-10-19 11:17:24,248 INFO] Translating shard 0.
Traceback (most recent call last):
  File "/home/ke/git/trnslt/.direnv/python-3.8.5/bin/onmt_translate", line 8, in <module>
    sys.exit(main())
  File "/home/ke/git/trnslt/.direnv/python-3.8.5/lib/python3.8/site-packages/onmt/bin/translate.py", line 47, in main
    translate(opt)
  File "/home/ke/git/trnslt/.direnv/python-3.8.5/lib/python3.8/site-packages/onmt/bin/translate.py", line 25, in translate
    translator.translate(
  File "/home/ke/git/trnslt/.direnv/python-3.8.5/lib/python3.8/site-packages/onmt/translate/translator.py", line 356, in translate
    batch_data = self.translate_batch(
  File "/home/ke/git/trnslt/.direnv/python-3.8.5/lib/python3.8/site-packages/onmt/translate/translator.py", line 546, in translate_batch
    return self._translate_batch_with_strategy(batch, src_vocabs,
  File "/home/ke/git/trnslt/.direnv/python-3.8.5/lib/python3.8/site-packages/onmt/translate/translator.py", line 709, in _translate_batch_with_strategy
    results["alignment"] = self._align_forward(
  File "/home/ke/git/trnslt/.direnv/python-3.8.5/lib/python3.8/site-packages/onmt/translate/translator.py", line 490, in _align_forward
    enc_states = tile(enc_states, n_best, dim=1)
  File "/home/ke/git/trnslt/.direnv/python-3.8.5/lib/python3.8/site-packages/onmt/utils/misc.py", line 69, in tile
    perm = list(range(len(x.size())))
AttributeError: 'tuple' object has no attribute 'size'
```

**Comment by francoishernandez** [comment]
@Zenglinxiao can you have a look?

**Comment by Zenglinxiao** [comment]
Hello @texttheater,
Your provided tutorial link is not correct, but I assume you refer to the [quickstart](https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/quickstart.md) as you mentioned "step".
In the quickstart, you train a LSTM model by default if you not change the configuration file. Our `-report_align` feature should only be used with transformer.

**Comment by texttheater** [comment]
Thanks, I fixed the link. Yes, your explanation makes sense. I'd suggest putting a more informative error message into the code. Thanks a lot!
