### ISSUE TITLE
Function whole_word_mask with a bug in bart.py ??

### ISSUE THREAD

**Issue by lianrzh** [OpenNMT/OpenNMT-py#1901]
the function change the tokens list with some tensor type,  and the problem would happen.
the configure of bart is:
`# BART
insert_ratio: 0.1 
random_ratio: 1.0 
mask_ratio: 0.15
rotate_ratio: 0.0 
mask_length: 'span-poisson'
poisson_lambda: 1
eeplace_length: 1 `
`TypeError: sequence item 2: expected str instance, Tensor found`
Traceback (most recent call last):
  File "/data/app/anaconda3/envs/pytorch-1.2/bin/onmt_train", line 11, in <module>
    load_entry_point('OpenNMT-py==2.0.0rc1', 'console_scripts', 'onmt_train')()
  File "/data/app/anaconda3/envs/pytorch-1.2/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/bin/train.py", line 169, in main
    train(opt)
  File "/data/app/anaconda3/envs/pytorch-1.2/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/bin/train.py", line 154, in train
    train_process(opt, device_id=0)
  File "/data/app/anaconda3/envs/pytorch-1.2/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/train_single.py", line 107, in main
    valid_steps=opt.valid_steps)
  File "/data/app/anaconda3/envs/pytorch-1.2/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/trainer.py", line 225, in train
    self._accum_batches(train_iter)):
  File "/data/app/anaconda3/envs/pytorch-1.2/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/trainer.py", line 163, in _accum_batches
    for batch in iterator:
  File "/data/app/anaconda3/envs/pytorch-1.2/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/inputters/inputter.py", line 206, in __iter__
    for batch in self.iterable:
  File "/data/app/anaconda3/envs/pytorch-1.2/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/inputters/dynamic_iterator.py", line 238, in __iter__
    dataset = self.dataset_adapter(bucket)
  File "/data/app/anaconda3/envs/pytorch-1.2/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/inputters/dynamic_iterator.py", line 70, in __call__
    examples = self._to_examples(bucket, is_train=self.is_train)
  File "/data/app/anaconda3/envs/pytorch-1.2/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/inputters/dynamic_iterator.py", line 59, in _to_examples
    maybe_example = self._process(item, is_train=is_train)
  File "/data/app/anaconda3/envs/pytorch-1.2/lib/python3.7/site-packages/OpenNMT_py-2.0.0rc1-py3.7.egg/onmt/inputters/dynamic_iterator.py", line 41, in _process
    maybe_example['src'] = ' '.join(maybe_example['src'])

**Comment by Zenglinxiao** [comment]
Thanks for reporting, this is indeed a bug. I've created a PR to fix the mentioned issue. Please let me know if there is any other problems.

**Comment by lianrzh** [comment]
@Zenglinxiao 
1. the variable `vocab` used in class BARTNoising should be `self.vocab = vocab['src']` ?

**Comment by Zenglinxiao** [comment]
> @Zenglinxiao `tokens = self.insertion_noise(tokens, n_insert / len(tokens))` : the variable `len(tokens)` maybe equal to 0 sometimes ?

Hello, I check the path again. I supose you meant the [line](https://github.com/OpenNMT/OpenNMT-py/blob/1b1e6c1ce5b29d09e87881797dce786148f51090/onmt/transforms/bart.py#L238).

That's indeed a triky edge case. So far, I think the only case may triger this potentiel `ZeroDivisionError` comes when:
- `-mask_ratio` set to 1.0;
- `-replace_length` to be 0;
- `-mask_length` to be `span-poisson`;
- and all token in the line are regcognized as word_start.

Tell me if you think there exists another scenario that cause this problem.
Maybe someone will config their setting this way, who knows, but yes, I think we can fix this later.
(PS: If you like, feel free to open a PR to fix it.)

**Comment by lianrzh** [comment]
I meet the `ZeroDivisionError` when:

-  `-mask_ratio` set to 0.15;
- `-replace_length` set to 0;
- `-mask_length` to be `span-poisson`;
- `-poisson_lambda` to be 1;
- and all token in the line are recognized as word_start.

I want to random delete some words in the source field.

**Comment by Zenglinxiao** [comment]
> I meet the `ZeroDivisionError` when:
> 
>     * `-mask_ratio` set to 0.15;
> 
>     * `-replace_length` set to 0;
> 
>     * `-mask_length` to be `span-poisson`;
> 
>     * `-poisson_lambda` to be 1;
> 
>     * and all token in the line are recognized as word_start.
> 
> 
> I want to random delete some words in the source field.

Hello @lianrzh,
I don't think your mentioned settings will cause the `ZeroDivisionError` after reviewing the bart code. And I also tried with a large corpus, no exception encoutered during transformed sample saving stage.
Could you please print the example which causes this `ZeroDivisionError` in your case?
