### ISSUE TITLE
rnn_type: "SRU" does not work

### ISSUE THREAD

**Issue by jhandsel** [OpenNMT/OpenNMT-py#1935]
I am unable to get the Simple Recurrent Unit to work with the toy example.

My operating system is Ubuntu and I am using:
- OpenNMT-py installed from the latest sources
- nvidia-cuda-toolkit version 10.1.243-3
- pynvrtc-8.0
- cupy 8.1.0

Training fails with a runtime error:
```
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
```

The full output:
```
(opennmt) jennifer@xxxx:~/toy-ende$ onmt_train -config toy_en_de.yaml 
[2020-11-14 21:36:56,139 INFO] Missing transforms field for corpus_1 data, set to default: [].
[2020-11-14 21:36:56,139 WARNING] Corpus corpus_1's weight should be given. We default it to 1 for you.
[2020-11-14 21:36:56,139 INFO] Missing transforms field for valid data, set to default: [].
[2020-11-14 21:36:56,139 INFO] Parsed 2 corpora from -data.
[2020-11-14 21:36:56,139 INFO] Get special vocabs from Transforms: {'src': set(), 'tgt': set()}.
[2020-11-14 21:36:56,140 INFO] Loading vocab from text file...
[2020-11-14 21:36:56,140 INFO] Loading src vocabulary from run/example.vocab.src
[2020-11-14 21:36:56,199 INFO] Loaded src vocab has 24995 tokens.
[2020-11-14 21:36:56,210 INFO] Loading tgt vocabulary from run/example.vocab.tgt
[2020-11-14 21:36:56,307 INFO] Loaded tgt vocab has 35816 tokens.
[2020-11-14 21:36:56,321 INFO] Building fields with vocab in counters...
[2020-11-14 21:36:56,397 INFO]  * tgt vocab size: 35820.
[2020-11-14 21:36:56,431 INFO]  * src vocab size: 24997.
[2020-11-14 21:36:56,433 INFO]  * src vocab size = 24997
[2020-11-14 21:36:56,433 INFO]  * tgt vocab size = 35820
[2020-11-14 21:36:56,434 INFO] Building model...
[2020-11-14 21:37:02,330 INFO] NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(24997, 500, padding_idx=1)
        )
      )
    )
    (rnn): SRU(
      (rnn_lst): ModuleList(
        (0): SRUCell()
        (1): SRUCell()
      )
    )
  )
  (decoder): StdRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(35820, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3, inplace=False)
    (rnn): SRU(
      (rnn_lst): ModuleList(
        (0): SRUCell()
        (1): SRUCell()
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=500, out_features=500, bias=False)
      (linear_out): Linear(in_features=1000, out_features=500, bias=False)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=500, out_features=35820, bias=False)
    (1): Cast()
    (2): LogSoftmax(dim=-1)
  )
)
[2020-11-14 21:37:02,331 INFO] encoder: 14000500
[2020-11-14 21:37:02,331 INFO] decoder: 38072000
[2020-11-14 21:37:02,331 INFO] * number of parameters: 52072500
[2020-11-14 21:37:02,333 INFO] Starting training on GPU: [0]
[2020-11-14 21:37:02,333 INFO] Start training loop and validate every 500 steps...
[2020-11-14 21:37:02,334 INFO] corpus_1's transforms: TransformPipe()
[2020-11-14 21:37:02,335 INFO] Loading ParallelCorpus(src-train.txt, tgt-train.txt, align=None)...
Traceback (most recent call last):
  File "/home/jennifer/miniconda3/envs/opennmt/bin/onmt_train", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py==2.0.0rc2', 'console_scripts', 'onmt_train')())
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/OpenNMT_py-2.0.0rc2-py3.8.egg/onmt/bin/train.py", line 169, in main
    train(opt)
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/OpenNMT_py-2.0.0rc2-py3.8.egg/onmt/bin/train.py", line 154, in train
    train_process(opt, device_id=0)
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/OpenNMT_py-2.0.0rc2-py3.8.egg/onmt/train_single.py", line 102, in main
    trainer.train(
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/OpenNMT_py-2.0.0rc2-py3.8.egg/onmt/trainer.py", line 242, in train
    self._gradient_accumulation(
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/OpenNMT_py-2.0.0rc2-py3.8.egg/onmt/trainer.py", line 366, in _gradient_accumulation
    outputs, attns = self.model(
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/OpenNMT_py-2.0.0rc2-py3.8.egg/onmt/models/model.py", line 45, in forward
    enc_state, memory_bank, lengths = self.encoder(src, lengths)
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/OpenNMT_py-2.0.0rc2-py3.8.egg/onmt/encoders/rnn_encoder.py", line 76, in forward
    memory_bank, encoder_final = self.rnn(packed_emb)
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/OpenNMT_py-2.0.0rc2-py3.8.egg/onmt/models/sru.py", line 641, in forward
    h, c = rnn(prevx, c0[i])
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/OpenNMT_py-2.0.0rc2-py3.8.egg/onmt/models/sru.py", line 553, in forward
    h, c = SRU_Compute(self.activation_type, n_out,
  File "/home/jennifer/miniconda3/envs/opennmt/lib/python3.8/site-packages/torch/autograd/function.py", line 159, in __call__
    raise RuntimeError(
RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
```

To replicate: follow the example in [Quickstart](https://opennmt.net/OpenNMT-py/quickstart.html) but with the following config

```# toy_en_de.yaml

## Where the samples will be written
save_data: toy-ende/run/example
## Where the vocab(s) will be written
src_vocab: toy-ende/run/example.vocab.src
tgt_vocab: toy-ende/run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: toy-ende/src-train.txt
        path_tgt: toy-ende/tgt-train.txt
    valid:
        path_src: toy-ende/src-val.txt
        path_tgt: toy-ende/tgt-val.txt

# SRU
rnn_type: "SRU"
input_feed: 0

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: toy-ende/run/model
save_checkpoint_steps: 500
train_steps: 1000
valid_steps: 500```

**Comment by francoishernandez** [comment]
Hey there,
Yes, SRU seems to be broken since pytorch 1.6.
If you'd like to investigate and come up with a fix we'd likely accept a PR.

**Comment by jhandsel** [comment]
Awesome, I'll look into it and see if I can come up with a fix.
