### ISSUE TITLE
RuntimeError: expected scalar type Long but found Float

### ISSUE THREAD

**Issue by thainq0797** [OpenNMT/OpenNMT-py#1937]
I hope someone will help me.
After I successfully run the file run_train_newser.sh (Model Hi_MAP). When I run file run_inference_newser.sh, the problem is as follows:
/usr/local/lib/python3.6/dist-packages/torchtext/data/field.py:323: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)
Traceback (most recent call last):
  File "/content/drive/My Drive/MultiNews/code/Hi_MAP/translate.py", line 37, in <module>
    main(opt)
  File "/content/drive/My Drive/MultiNews/code/Hi_MAP/translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/content/drive/My Drive/MultiNews/code/Hi_MAP/onmt/translate/translator.py", line 233, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/content/drive/My Drive/MultiNews/code/Hi_MAP/onmt/translate/translator.py", line 342, in translate_batch
    return self._translate_batch(batch, data)
  File "/content/drive/My Drive/MultiNews/code/Hi_MAP/onmt/translate/translator.py", line 651, in _translate_batch
    beam_attn.data[:, j, :memory_lengths[j]])
  File "/content/drive/My Drive/MultiNews/code/Hi_MAP/onmt/translate/beam.py", line 140, in advance
    self.attn.append(attn_out.index_select(0, prev_k))
RuntimeError: expected scalar type Long but found Float

**Comment by francoishernandez** [comment]
I think this issue belongs to the Multi-News repo, which is based on an older version of OpenNMT-py: https://github.com/Alex-Fabbri/Multi-News
