### ISSUE TITLE
Can't load pretrained model in translation task

### ISSUE THREAD

**Issue by KYRIEZX** [OpenNMT/OpenNMT-py#1941]
I download the WMT19 models by using translate script like this:
`onmt_translate --model wmt19.de-en.joined-dict.ensemble/model1.pt --src ../en-de.txt --random_sampling_topk 10 --random_sampling_temp 0.5 --beam_size 1 --gpu 6
`
but eventually the error reported:
```
Traceback (most recent call last):
  File "/usr/local/bin/onmt_translate", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py==2.0.0rc2', 'console_scripts', 'onmt_translate')())
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-2.0.0rc2-py3.6.egg/onmt/bin/translate.py", line 47, in main
    translate(opt)
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-2.0.0rc2-py3.6.egg/onmt/bin/translate.py", line 18, in translate
    translator = build_translator(opt, logger=logger, report_score=True)
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-2.0.0rc2-py3.6.egg/onmt/translate/translator.py", line 29, in build_translator
    fields, model, model_opt = load_test_model(opt)
  File "/usr/local/lib/python3.6/dist-packages/OpenNMT_py-2.0.0rc2-py3.6.egg/onmt/model_builder.py", line 86, in load_test_model
    model_opt = ArgumentParser.ckpt_model_opts(checkpoint['opt'])
KeyError: 'opt'
```

**Comment by francoishernandez** [comment]
[This looks like a fairseq model.](https://www.google.com/search?client=safari&sxsrf=ALeKk00Lw8kbMez9hXNSgd_a9-c8EELr-A%3A1605613136976&source=hp&ei=ULazX_DTOM-Ua4X9j7AG&q=wmt19.de-en.joined-dict.ensemble&oq=wmt19.de-en.joined-dict.ensemble&gs_lcp=CgZwc3ktYWIQA1DTAVjTAWDBBGgAcAB4AIABiQGIAYkBkgEDMC4xmAEAoAECoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwjwu7GFv4ntAhVPyhoKHYX-A2YQ4dUDCAo&uact=5)
