### ISSUE TITLE
Getting error at PREPROCESSING step..

### ISSUE THREAD

**Issue by debartha-saha** [OpenNMT/OpenNMT-py#1966]
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/content/OpenNMT-py/onmt/bin/preprocess.py", line 54, in process_one_shard
    assert len(src_shard) == len(tgt_shard)
AssertionError

.............................
I am getting the above error while running preprocess.py on my dataset.
please, help me to solve the problem.

**Comment by francoishernandez** [comment]
This means your source and target data don't have the same number of lines.
