### ISSUE TITLE
How to ensemble models with different source vocabulary

### ISSUE THREAD

**Issue by len2618187** [OpenNMT/OpenNMT-py#1970]
When inferencing, I have several models with different source vocabulary and same target vocabulary and same data.
Then get :

**Comment by len2618187** [comment]
Traceback (most recent call last):
  File "/apdcephfs/share_47076/cardli/wmt/ja2en/OpenNMT-py-1.1.1/translate.py", line 6, in <module>
    main()
  File "/apdcephfs/share_47076/cardli/wmt/ja2en/OpenNMT-py-1.1.1/onmt/bin/translate.py", line 48, in main
    translate(opt)
  File "/apdcephfs/share_47076/cardli/wmt/ja2en/OpenNMT-py-1.1.1/onmt/bin/translate.py", line 18, in translate
    translator = build_translator(opt, report_score=True)
  File "/apdcephfs/share_47076/cardli/wmt/ja2en/OpenNMT-py-1.1.1/onmt/translate/translator.py", line 28, in build_translator
    fields, model, model_opt = load_test_model(opt)
  File "/apdcephfs/share_47076/cardli/wmt/ja2en/OpenNMT-py-1.1.1/onmt/decoders/ensemble.py", line 152, in load_test_model
    "Ensemble models must use the same " \
AssertionError: Ensemble models must use the same preprocessed data

**Comment by francoishernandez** [comment]
You can't. As hinted in the the error, models must have the same vocab. You might be able to build some custom code to match the intersection of the vocabs though, but it wouldn't be straightforward.
