### ISSUE TITLE
Model not training. inputter.py", line 309, in _load_vocab   for token, count in vocab: ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by seamusl** [OpenNMT/OpenNMT-py#1979]
With ONMT 2.0, python 3.6 and sentencepiece running on Colab, the model does not train. I get the following error in inputter.py

  File "/content/OpenNMT-py/onmt/inputters/inputter.py", line 309, in _load_vocab
    for token, count in vocab:
ValueError: not enough values to unpack (expected 2, got 1)

My notebook creates the vocab files which I have inspected. Each has 2 columns. Therfore, I don't see why it is failing with:
"ValueError: not enough values to unpack (expected 2, got 1)"

Any ideas would be much appreciated. Thanks.
 
The full instructions and colab output are as follows: 

!spm_train --input=data/train.txt --model_prefix=myspm --vocab_size=30000 –character_coverage=1
!onmt_build_vocab -config config.yaml -n_sample -1

[2021-01-03 15:18:21,816 INFO] Counter vocab from -1 samples.
[2021-01-03 15:18:21,817 INFO] n_sample=-1: Build vocab on full datasets.
[2021-01-03 15:18:21,935 INFO] corpus_1's transforms: TransformPipe(SentencePieceTransform(share_vocab=False, src_subword_model=myspm.model, tgt_subword_model=myspm.model, src_subword_alpha=0.0, tgt_subword_alpha=0.0, src_subword_vocab=, tgt_subword_vocab=, src_vocab_threshold=0, tgt_vocab_threshold=0, src_subword_nbest=1, tgt_subword_nbest=1))
[2021-01-03 15:18:21,937 INFO] Loading ParallelCorpus(data/src-train.txt, data/tgt-train.txt, align=None)...
[2021-01-03 15:18:25,747 INFO] Transform statistics for corpus_1:
Subword(SP/Tokenizer): 1562506 -> 2125268 tok

[2021-01-03 15:18:25,834 INFO] Counters src:14894
[2021-01-03 15:18:25,835 INFO] Counters tgt:20889

!onmt_train -config config.yaml

[2021-01-03 15:18:36,063 INFO] Parsed 2 corpora from -data.
[2021-01-03 15:18:36,064 INFO] Get special vocabs from Transforms: {'src': set(), 'tgt': set()}.
[2021-01-03 15:18:36,064 INFO] Loading vocab from text file...
[2021-01-03 15:18:36,064 INFO] Loading src vocabulary from /content/gdrive/MyDrive/datasets/gaen/data/run/vocab.src
[2021-01-03 15:18:36,096 INFO] Loaded src vocab has 14894 tokens.
Traceback (most recent call last):
  File "/usr/local/bin/onmt_train", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py', 'console_scripts', 'onmt_train')())
  File "/content/OpenNMT-py/onmt/bin/train.py", line 169, in main
    train(opt)
  File "/content/OpenNMT-py/onmt/bin/train.py", line 103, in train
    checkpoint, fields, transforms_cls = _init_train(opt)
  File "/content/OpenNMT-py/onmt/bin/train.py", line 80, in _init_train
    fields, transforms_cls = prepare_fields_transforms(opt)
  File "/content/OpenNMT-py/onmt/bin/train.py", line 34, in prepare_fields_transforms
    opt, src_specials=specials['src'], tgt_specials=specials['tgt'])
  File "/content/OpenNMT-py/onmt/inputters/fields.py", line 34, in build_dynamic_fields
    min_freq=opts.src_words_min_frequency)
  File "/content/OpenNMT-py/onmt/inputters/inputter.py", line 309, in _load_vocab
    for token, count in vocab:
ValueError: not enough values to unpack (expected 2, got 1)

** The following is my config.yaml file **

## Where the vocab(s) will be written
src_vocab: /content/gdrive/MyDrive/datasets/gaen/data/run/vocab.src
tgt_vocab: /content/gdrive/MyDrive/datasets/gaen/data/run/vocab.tgt

# Corpus opts:
data:
    corpus_1:
        path_src: data/src-train.txt
        path_tgt: data/tgt-train.txt
        transforms: [sentencepiece]
        weight: 1
    valid:
        path_src: data/src-val.txt
        path_tgt: data/tgt-val.txt
        transforms: [sentencepiece]

# Tokenization options
#### Subword
src_subword_model: myspm.model
tgt_subword_model: myspm.model
src_subword_nbest: 1
src_subword_alpha: 0.0
tgt_subword_nbest: 1
tgt_subword_alpha: 0.0

#### Filter
src_seq_length: 150
tgt_seq_length: 150

# silently ignore empty lines in the data
skip_empty_level: silent

# General opts
## Where the samples will be written
save_data: data/run/
keep_checkpoint: 50
save_checkpoint_steps: 5000
average_decay: 0.0005
seed: 1234
report_every: 100
train_steps: 100000
valid_steps: 5000

# Batching
queue_size: 10000
bucket_size: 32768
world_size: 2
gpu_ranks: [0, 1]
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 16
batch_size_multiple: 1
max_generator_batches: 0
accum_count: [3]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
share_decoder_embeddings: true
share_embeddings: true

**Comment by francoishernandez** [comment]
There probably is an issue with your vocab files. How were these generated? Can you post an extract of it?

**Comment by seamusl** [comment]
I have it working now. 

I have a new config.yaml (outlined below). The main difference is that I am now using
        transforms: [onmt_tokenize]
whereas before I was using 
        transforms: [sentencepiece]

I'm not sure why it is working now since I am still using spm_train to train the sentencepiece model before training.

NEW CONFIG.YAML

## Where the vocab(s) will be written
# src_vocab: /data/run/vocab.src
# tgt_vocab: data/run/vocab.tgt

### Transform related opts:

# Tokenization options
src_subword_type: sentencepiece
src_subword_model: myspm.model
tgt_subword_type: sentencepiece
tgt_subword_model: myspm.model
# Number of candidates for SentencePiece sampling
subword_nbest: 20
# Smoothing parameter for SentencePiece sampling
subword_alpha: 0.1
# Specific arguments for pyonmttok
src_onmttok_kwargs: "{'mode': 'none', 'spacer_annotate': True}"
tgt_onmttok_kwargs: "{'mode': 'none', 'spacer_annotate': True}"

#### Filter
src_seq_length: 150
tgt_seq_length: 150

# Corpus opts:
data:
    corpus_1:
        path_src: data/src-train.txt
        path_tgt: data/tgt-train.txt
        transforms: [onmt_tokenize, filtertoolong]
        weight: 1
    valid:
        path_src: data/src-val.txt
        path_tgt: data/tgt-val.txt
        transforms: [onmt_tokenize]

# silently ignore empty lines in the data
skip_empty_level: silent

# Transformer Model Hyperparameters
save_data: data/run/
save_checkpoint_steps: 10000
valid_steps: 10000
train_steps: 30000
seed: 2093
report_every: 100
keep_checkpoint: 3

# To resume training from previous checkpoint, specify name e.g. model_step_10000.pt
# train_from: model_step_10000.pt

# Batching
queue_size: 10000
bucket_size: 32768
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 8
max_generator_batches: 2
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]

# Train on a single GPU
world_size: 1
gpu_ranks: [0]
