### ISSUE TITLE
Error loading pretrained word embeddings 

### ISSUE THREAD

**Issue by ylhsieh** [OpenNMT/OpenNMT-py#20]
When calling `train.py` with `-pre_word_vecs_enc pretrained.embeddings.pt` it displays an error
```
Traceback (most recent call last):
  File "train.py", line 352, in <module>
    main()
  File "train.py", line 289, in main
    encoder = onmt.Models.Encoder(opt, dicts['src'])
  File "/home/xxxx/RNN/onmt/Models.py", line 28, in __init__
    self.word_lut.weight.copy_(pretrained)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 63, in __getattr__
    raise AttributeError(name)
AttributeError: copy_
```
It seems like there is nothing called `copy_` in `/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py`
I saved a `torch.Tensor` in the file `pretrained.embeddings.pt` and gave this file to the training script. Is there a bug?

**Comment by ylhsieh** [comment]
A related issue: I found that `Decoder` in https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L88 is referencing `opt.pre_word_vecs_enc`, which I believe should be `opt.pre_word_vecs_dec`?
