### ISSUE TITLE
Model not training. inputter.py", line 309, in _load_vocab for token, count in vocab: ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by TomasZhang19** [OpenNMT/OpenNMT-py#2000]
With ONMT 2.0, python 3.6 and sentencepiece running on Colab, the model does not train. I get the following error in inputter.py.
[2021-01-27 07:01:51,886 WARNING] Corpus corpus_1's weight should be given. We default it to 1 for you.
[2021-01-27 07:01:51,887 INFO] Parsed 2 corpora from -data.
[2021-01-27 07:01:51,887 INFO] Get special vocabs from Transforms: {'src': set(), 'tgt': set()}.
[2021-01-27 07:01:51,888 INFO] Loading vocab from text file...
[2021-01-27 07:01:51,888 INFO] Loading src vocabulary from zh-en/run/zh-en.vocab.zh
[2021-01-27 07:01:52,038 INFO] Loaded src vocab has 39730 tokens.
Traceback (most recent call last):
  File "/home/y192235032/.conda/envs/pytorch171/bin/onmt_train", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py', 'console_scripts', 'onmt_train')())
  File "/home/y192235032/OpenNMT/OpenNMT-py/onmt/bin/train.py", line 169, in main
    train(opt)
  File "/home/y192235032/OpenNMT/OpenNMT-py/onmt/bin/train.py", line 103, in train
    checkpoint, fields, transforms_cls = _init_train(opt)
  File "/home/y192235032/OpenNMT/OpenNMT-py/onmt/bin/train.py", line 80, in _init_train
    fields, transforms_cls = prepare_fields_transforms(opt)
  File "/home/y192235032/OpenNMT/OpenNMT-py/onmt/bin/train.py", line 34, in prepare_fields_transforms
    opt, src_specials=specials['src'], tgt_specials=specials['tgt'])
  File "/home/y192235032/OpenNMT/OpenNMT-py/onmt/inputters/fields.py", line 34, in build_dynamic_fields
    min_freq=opts.src_words_min_frequency)
  File "/home/y192235032/OpenNMT/OpenNMT-py/onmt/inputters/inputter.py", line 309, in _load_vocab
    for token, count in vocab:
ValueError: not enough values to unpack (expected 2, got 1)

I am doing a ZH to EN translation task. The ZH vocab file is as follows:
。 29014
， 28025
的@@ 26194
，@@ 18697
和@@ 16171
在@@ 15328
是@@ 10888
我们@@ 9606
我@@ 9482
的 9464
他们@@ 7120
“@@ 7119
这些@@ 7076
这个@@ 6965
一个@@ 6710
有@@ 6513
而@@ 6092
了@@ 5857
、@@ 5847
你@@ 5825
他@@ 5795
来@@ 5554
这@@ 5465
。@@ 5324
从@@ 5263
的。 5252
......

And the EN vocab file is as follow:
the 184745
to 116358
of 107516
and 102271
a 98885
that 70767
in 68094
I 60392
is 55325
you 46708
we 42565
And 39169
this 33595
it 32740
was 27302
for 26425
are 24855
have 24606
-- 23458
on 22853
with 22410
they 19616
can 18944
about 18892
what 18139
be 18015
as 17515
at 17318
So 16734
not 16038
all 15270
my 14649
from 14192
do 13890
an 13707
but 13199
so 13151
like 12970

Could you please tell me how to solve the problem?

**Comment by TomasZhang19** [comment]
I use the following commands to generate vocab files:
subword-nmt learn-joint-bpe-and-vocab -i ./zh-en/train.tags.zh-en.en -s 32000 -o ./zh-en/run/bpe32k.en --write-vocabulary ./zh-en/run/zh-en.vocab.en
subword-nmt learn-joint-bpe-and-vocab -i ./zh-en/train.tags.zh-en.zh -s 32000 -o ./zh-en/run/bpe32k.zh --write-vocabulary ./zh-en/run/zh-en.vocab.zh

**Comment by francoishernandez** [comment]
@Zenglinxiao any idea what might be the issue here?

**Comment by Zenglinxiao** [comment]
As the error suggests, it seems there are some lines not in the form of `<vocab> <freq>` in the middle of your vocabulary file, so when iterating, il failed to unpack the tuple we want. You may need to check the ZH vocabulary file first. Maybe a `try...except` to replace line 309-310 of inputter.py to catch where the error line comes from.

**Comment by TomasZhang19** [comment]
> As the error suggests, it seems there are some lines not in the form of `<vocab> <freq>` in the middle of your vocabulary file, so when iterating, il failed to unpack the tuple we want. You may need to check the ZH vocabulary file first. Maybe a `try...except` to replace line 309-310 of inputter.py to catch where the error line comes from.

Thank you very much. I find two wrong lines in ZH vocab file.
