### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by RakhimBek** [OpenNMT/OpenNMT-py#2014]
Hello! 
While running `onmt_train -config toy_en_de.yaml` I get this:

Traceback (most recent call last):
  File "/usr/local/bin/onmt_train", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/3.7/site-packages/onmt/bin/train.py", line 169, in main
    train(opt)
  File "/Library/Python/3.7/site-packages/onmt/bin/train.py", line 154, in train
    train_process(opt, device_id=0)
  File "/Library/Python/3.7/site-packages/onmt/train_single.py", line 59, in main
    configure_process(opt, device_id)
  File "/Library/Python/3.7/site-packages/onmt/train_single.py", line 19, in configure_process
    torch.cuda.set_device(device_id)
  File "/Library/Python/3.7/site-packages/torch/cuda/__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

freeze:
torch==1.6.0
OpenNMT-py==2.0.1

Is there any solution for this?

**Comment by RakhimBek** [comment]
Seems like I have no compatible GPU (AMD Radeon Pro 5500M, Intel UHD Graphics) for PyTorch. (

**Comment by francoishernandez** [comment]
If you feel like it you could try building pytorch for ROCm (the AMD equivalent of CUDA) and let us know how it goes...
