### ISSUE TITLE
How to configure SRU parameters in Version 1.0.0

### ISSUE THREAD

**Issue by LittleRooki** [OpenNMT/OpenNMT-py#2066]
Hi！I tried to apply sru to the decoder when the encoder is transformer in OpenNMT verion 1.0.0, but there are some problems when I trained, as follows：

Traceback (most recent call last):
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/OpenNMT_py-1.0.0-py3.7.egg/onmt/trainer.py", line 377, in _gradient_accumulation
    trunc_size=trunc_size)
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/OpenNMT_py-1.0.0-py3.7.egg/onmt/utils/loss.py", line 165, in __call__
    for shard in shards(shard_state, shard_size):
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/OpenNMT_py-1.0.0-py3.7.egg/onmt/utils/loss.py", line 381, in shards
    torch.autograd.backward(inputs, grads)
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/torch-1.2.0-py3.7-linux-x86_64.egg/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function SRU_ComputeLegacyBackward returned an invalid gradient at index 3 - got [78, 512] but expected shape compatible with [25, 78, 512]
[2021-05-24 09:46:07,328 INFO] At step 100, we removed a batch - accum 7
Traceback (most recent call last):
  File "/home/caohang/anaconda3/envs/onmt1.0/bin/onmt_train", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py==1.0.0', 'console_scripts', 'onmt_train')())
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/OpenNMT_py-1.0.0-py3.7.egg/onmt/bin/train.py", line 204, in main
    train(opt)
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/OpenNMT_py-1.0.0-py3.7.egg/onmt/bin/train.py", line 88, in train
    single_main(opt, 0)
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/OpenNMT_py-1.0.0-py3.7.egg/onmt/train_single.py", line 143, in main
    valid_steps=opt.valid_steps)
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/OpenNMT_py-1.0.0-py3.7.egg/onmt/trainer.py", line 252, in train
    report_stats)
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/OpenNMT_py-1.0.0-py3.7.egg/onmt/trainer.py", line 453, in _maybe_report_training
    multigpu=self.n_gpu > 1)
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/OpenNMT_py-1.0.0-py3.7.egg/onmt/utils/report_manager.py", line 75, in report_training
    step, num_steps, learning_rate, report_stats)
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/OpenNMT_py-1.0.0-py3.7.egg/onmt/utils/report_manager.py", line 125, in _report_training
    learning_rate, self.start_time)
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/OpenNMT_py-1.0.0-py3.7.egg/onmt/utils/statistics.py", line 120, in output
    self.accuracy(),
  File "/home/caohang/anaconda3/envs/onmt1.0/lib/python3.7/site-packages/OpenNMT_py-1.0.0-py3.7.egg/onmt/utils/statistics.py", line 90, in accuracy
    return 100 * (self.n_correct / self.n_words)
ZeroDivisionError: division by zero

My configuration is：

data: toy-ende/demo 
save_model: demo-model 
save_checkpoint_steps: 1000
keep_checkpoint: 10
seed: 3435
train_steps: 5000
valid_steps: 1000
warmup_steps: 800
report_every: 100
world_size: 1
gpu_ranks: [0]
decoder_type: rnn
encoder_type: transformer
word_vec_size: 512
rnn_type: SRU
input_feed: 0
rnn_size: 512
enc_layers: 6
dec_layers: 2
transformer_ff: 2048
heads: 8
accum_count: 8
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0
batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1
max_generator_batches: 2
param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

How should I set it correctly？Can you give me the correct configuration file？

**Comment by francoishernandez** [comment]
#1935
