### ISSUE TITLE
There seems to be a bug in translation with a model trained with word features and "copy_attn" enabled

### ISSUE THREAD

**Issue by MoonFighter** [OpenNMT/OpenNMT-py#2098]
I trained a model with word features, and also with "copy_attn" enabled, since I need the model to learn to copy OOV from source sentence, and there is no problem in training.
However, when I use it to translate, there is "IndexError: list index out of range".

Here is how I called: 
      python translate.py -config my_config_file
here is what is in my_config_file:

gpu: 0
batch_size: 10
beam_size: 50
model: my_model/model_transformer_step_7000.pt
src: my_data/test.tokens.src
src_feats:
       feat0: my_data/test.tags.src
min_length: 35
verbose: True
stepwise_penalty: True
coverage_penalty: summary
beta: 5
length_penalty: wu
alpha: 0.9
block_ngram_repeat: 3

Here is the error message:
Traceback (most recent call last):
  File "translate.py", line 6, in <module>
    main()
  File "/mnt/OpenNMT-py/onmt/bin/translate.py", line 54, in main
    translate(opt)
  File "/mnt/OpenNMT-py/onmt/bin/translate.py", line 38, in translate
    align_debug=opt.align_debug
  File "/mnt/OpenNMT-py/onmt/translate/translator.py", line 416, in translate
    translations = xlation_builder.from_batch(batch_data)
  File "/mnt/OpenNMT-py/onmt/translate/translation.py", line 113, in from_batch
    for n in range(self.n_best)]
  File "/mnt/OpenNMT-py/onmt/translate/translation.py", line 113, in <listcomp>
    for n in range(self.n_best)]
  File "/mnt/OpenNMT-py/onmt/translate/translation.py", line 57, in _build_target_tokens
    tokens.append(src_vocab.itos[tok - len(vocab)])
IndexError: list index out of range

during debuging, I found that a pred tok_id is: 50067. Since the total size of vocab  is: 50004, and total size of src_vocab (dynamic vocab from source sentence) is 39, the maximum tok_id should be 50004 + 39 -1 = 50042 < 50067. Obviously, there is a bug here.

**Comment by MoonFighter** [comment]
After debug, I found the bug, and created PR #2100 .
