### ISSUE TITLE
AttributeError: 'Batch' object has no attribute 'alignment' in Loss.py

### ISSUE THREAD

**Issue by pj-parag** [OpenNMT/OpenNMT-py#211]
In the following line, I am getting this error:
Traceback (most recent call last):
  File "train.py", line 309, in <module>
    main()
  File "train.py", line 305, in main
    trainModel(model, train, valid, fields, optim)
  File "train.py", line 166, in trainModel
    train_stats = trainEpoch(epoch)
  File "train.py", line 136, in trainEpoch
    tgt_r)
  File "OpenNMT-py/onmt/Loss.py", line 148, in makeLossBatch
    else batch.alignment[range_[0] + 1: range_[1]],
AttributeError: 'Batch' object has no attribute 'alignment'

https://github.com/OpenNMT/OpenNMT-py/blame/master/onmt/Loss.py#L148

I am trying training including copy using -copy_attn flag. This error was not coming earlier, however, with the latest commit this is happening.

Thanks

**Comment by sebastianGehrmann** [comment]
Did you preprocess with the `dynamic_dict` option? This is required for `copy_attn`.

**Comment by srush** [comment]
@sebastian Can we make this fail earlier and with a nicer error to tell people what to do?

**Comment by sebastianGehrmann** [comment]
@srush good idea. Will do.

**Comment by pj-parag** [comment]
@sebastianGehrmann @srush Thank you for the quick reply. I did not use that option. However, it fails in preprocess which I tried that. Following is how I ran,
**************************************
python preprocess.py -train_src ../processed/train.input -train_tgt ../processed/train.output -valid_src ../processed/dev.input -valid_tgt ../processed/dev.output -save_data data/gph -dynamic_dict
NVIDIA: no NVIDIA devices found
Preparing training ...
Building Training...
Building Vocab...
Building Valid...
Saving train/valid/fields
Traceback (most recent call last):
  File "preprocess.py", line 77, in <module>
    main()
  File "preprocess.py", line 72, in main
    torch.save(train, open(opt.save_data + '.train.pt', 'wb'))
  File "/home/p/virtual-envs/pytorch/local/lib/python2.7/site-packages/torch/serialization.py", line 120, in save
    return _save(obj, f, pickle_module, pickle_protocol)
  File "/home/p/virtual-envs/pytorch/local/lib/python2.7/site-packages/torch/serialization.py", line 186, in _save
    pickler.dump(obj)
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
******************************************
Might be some silly thing again.

Thanks,
Parag

**Comment by srush** [comment]
just merged https://github.com/OpenNMT/OpenNMT-py/pull/213 which fixes this.

**Comment by pj-parag** [comment]
@srush Thanks for this fixes. But training still does not work.

Traceback (most recent call last):
  File "train.py", line 307, in <module>
    main()
  File "train.py", line 303, in main
    trainModel(model, train, valid, fields, optim)
  File "train.py", line 171, in trainModel
    valid_stats = eval(model, criterion, validData, fields)
  File "train.py", line 74, in eval
    _, batch_stats = loss.computeLoss(batch=batch, **gen_state)
  File "/home/p/g2t/graph_to_text/OpenNMT-py/onmt/Loss.py", line 180, in computeLoss
    if target[i] == 0 and align.data[i] != 0:
IndexError: index 449 is out of range for dimension 0 (of size 49)

*************************************************************
Is this related?

Thanks a lot,
Parag

**Comment by srush** [comment]
Okay, looking into it. Is this just on the test data. Can you send me what you ran?

**Comment by pj-parag** [comment]
I tried it again on demo data, the error is at the same place but a different message. Also, I am running the experiments on GPUS. Following are the commands and error log:

python preprocess.py -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo -dynamic_dict 

python train.py -data data/demo -copy_attn -save_model demo-model

Traceback (most recent call last):
  File "train.py", line 307, in <module>
    main()
  File "train.py", line 303, in main
    trainModel(model, train, valid, fields, optim)
  File "train.py", line 171, in trainModel
    valid_stats = eval(model, criterion, validData, fields)
  File "train.py", line 74, in eval
    _, batch_stats = loss.computeLoss(batch=batch, **gen_state)
  File "/home/p/OpenNMT-py/onmt/Loss.py", line 180, in computeLoss
    if target[i] == 0 and align.data[i] != 0:
  File "/home/p/virtual-envs/pytorch/local/lib/python2.7/site-packages/torch/tensor.py", line 152, in __bool__
    " objects is ambiguous")
RuntimeError: bool value of non-empty torch.ByteTensor objects is ambiguous

Thanks

**Comment by srush** [comment]
I was able to replicated. Fix is being pushed.

**Comment by wuhaixutab** [comment]
I have the same error during training:

Traceback (most recent call last):
  File "train.py", line 307, in <module>
    main()
  File "train.py", line 303, in main
    trainModel(model, train, valid, fields, optim)
  File "train.py", line 166, in trainModel
    train_stats = trainEpoch(epoch)
  File "train.py", line 141, in trainEpoch
    **shard)
  File "/home/haixu/Desktop/OpenNMT9.4/onmt/Loss.py", line 175, in computeLoss
    unbottle(scores_data), batch, self.tgt_vocab)
  File "/home/haixu/Desktop/OpenNMT9.4/onmt/IO.py", line 226, in collapse_copy_scores
    scores[:, b, ti] += scores[:, b, offset + i]
IndexError: index 3460 is out of range for dimension 1 (of size 3460)

**Comment by vince62s** [comment]
you need to be on master + pytorch 1.0 + torchtext >= 0.4

**Comment by 520jefferson** [comment]
@vince62s 
i use the master branch pytorch 1.0  + torchtext = 0.3.1

when i try to install torchtext==0.4.0 , i got this as follows:
Could not find a version that satisfies the requirement torchtext==0.4.0 (from versions: 0.1.1, 0.2.0, 0.2.1, 0.2.3, 0.3.1)

**Comment by vince62s** [comment]
you need to install as in the requirements.txt

**Comment by 520jefferson** [comment]
@vince62s 
it's the version of torchtext, after i download the torchtext and upgrate to 0.4.0, the error is gone. thx
