### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by caiyingchun** [OpenNMT/OpenNMT-py#2115]
I got this error when I run ```python translate.py --model ./checkpoints/ChEMBL/ChEMBL_model_average.pt --src ./data/ChEMBL/src-test.txt```. 
My pytorch version is 1.7.0. How to correct it. Thanks a lot. 

```/data/deep3d/SyntaLinker/onmt/translate/beam_search.py:164: UserWarning: An output with one or more elements was resized since it had shape [150], which does not match the required output shape [30, 5].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729047590/work/aten/src/ATen/native/Resize.cpp:19.)
  torch.mul(self.topk_scores, length_penalty, out=self.topk_log_probs)
Traceback (most recent call last):
  File "translate.py", line 5, in <module>
    main()
  File "/data/deep3d/SyntaLinker/onmt/bin/translate.py", line 49, in main
    translate(opt)
  File "/data/deep3d/SyntaLinker/onmt/bin/translate.py", line 33, in translate
    attn_debug=opt.attn_debug
  File "/data/deep3d/SyntaLinker/onmt/translate/translator.py", line 350, in translate
    batch, data.src_vocabs, attn_debug
  File "/data/deep3d/SyntaLinker/onmt/translate/translator.py", line 446, in translate_batch
    return_attention=attn_debug or self.replace_unk)
  File "/data/deep3d/SyntaLinker/onmt/translate/translator.py", line 607, in _translate_batch
    strategy.advance(log_probs, attn)
  File "/data/deep3d/SyntaLinker/onmt/translate/beam_search.py", line 167, in advance
    torch.div(self.topk_ids,vocab_size, out=self._batch_index)
RuntimeError: result type Float can't be cast to the desired output type Long
```

**Comment by wyupupup** [comment]
Pls how this problem is fixed, I'm suffering from the same error in other codes.
