### ISSUE TITLE
SentencePiece transformer: TypeError: not a string

### ISSUE THREAD

**Issue by RealHinome** [OpenNMT/OpenNMT-py#2141]
Hey.

I try to use the `transforms` of the corpus by using `transforms: [sentencepiece]`.

Version:
- sentencepiece: 0.1.96
- OpenNMT-py: 2.2.0
- MacOS (M1): 12.1

In my yaml config file I've (`fr.yaml`):
```yaml
save_data: data/run/fr
## Where the vocab(s) will be written
src_vocab: data/run/fr.vocab.src
tgt_vocab: data/run/fr.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: data/corpus_1/src-train.txt
        path_tgt: data/corpus_1/tgt-train.txt
        weight: 1
        transforms: [sentencepiece]
    valid:
        path_src: data/src-val.txt
        path_tgt: data/tgt-val.txt
        transforms: [sentencepiece]

#Where to save the checkpoints
save_model: data/run/model

save_checkpoint_steps: 20000
keep_checkpoint: 20000
seed: 3435
train_steps: 600000
valid_steps: 200000
report_every: 50

encoder_type: brnn
word_vec_size: 128
rnn_size: 512
layers: 1

optim: adam
learning_rate: 0.001
adagrad_accumulator_init: 0.1
max_grad_norm: 2

batch_size: 16
dropout: 0.0
```

Error:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/onmt_build_vocab", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/onmt/bin/build_vocab.py", line 63, in main
    build_vocab_main(opts)
  File "/opt/homebrew/lib/python3.9/site-packages/onmt/bin/build_vocab.py", line 32, in build_vocab_main
    transforms = make_transforms(opts, transforms_cls, fields)
  File "/opt/homebrew/lib/python3.9/site-packages/onmt/transforms/transform.py", line 176, in make_transforms
    transform_obj.warm_up(vocabs)
  File "/opt/homebrew/lib/python3.9/site-packages/onmt/transforms/tokenize.py", line 110, in warm_up
    load_src_model.Load(self.src_subword_model)
  File "/opt/homebrew/lib/python3.9/site-packages/sentencepiece/__init__.py", line 367, in Load
    return self.LoadFromFile(model_file)
  File "/opt/homebrew/lib/python3.9/site-packages/sentencepiece/__init__.py", line 171, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string
```

I installed SentencePiece via Homebrew (`brew install sentencepiece`) and after just ran `pip install sentencepiece`.

Thanks for your future help! 👋🏻

**Comment by Zenglinxiao** [comment]
As the error suggests, `src_subword_model` is missing for SentencePiece model loading. You need to provide a SentencePiece model file path in your config. Check options at [OpenNMT-py doc](https://opennmt.net/OpenNMT-py/options/build_vocab.html#Transform/Subword/Common)

**Comment by RealHinome** [comment]
Hey!

Thanks this helps me.

Have a nice day!
