### ISSUE TITLE
Extra custom loss

### ISSUE THREAD

**Issue by anderleich** [OpenNMT/OpenNMT-py#2153]
Hi,

I need to add a custom extra loss to perfrom joint learning. This loss comes from a classification head I placed after the encoder in the Transformer architecture. I've managed to find where the actual NMT loss is computed so I decided to add this extra loss there:

https://github.com/OpenNMT/OpenNMT-py/blob/fc3409ce08785915728dac9e9c9fb49f73027917/onmt/utils/loss.py#L196

However, loss computation is done in shards so in the tests I've done `backward()` is called twice. In addition there is another `backward()` call here after shards loop has been finished:

https://github.com/OpenNMT/OpenNMT-py/blob/fc3409ce08785915728dac9e9c9fb49f73027917/onmt/utils/loss.py#L457

Which is the purpos of this backward call?

So inside the method __call__() of the LossComputeBase class I've added the following code:
```
batch_stats = onmt.utils.Statistics()
class_loss, class_stats = self._compute_class_loss(stargets_logits, stargets_refs)
class_loss.backward()
batch_stats.update(class_stats)
```
This code computes my custom loss as usual. However adding this code chunk results in an error:

```
Traceback (most recent call last):
  File "venv/bin/onmt_train", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py', 'console_scripts', 'onmt_train')())
  File "OpenNMT-py/onmt/bin/train.py", line 173, in main
    train(opt)
  File "OpenNMT-py/onmt/bin/train.py", line 158, in train
    train_process(opt, device_id=0)
  File "OpenNMT-py/onmt/train_single.py", line 114, in main
    valid_steps=opt.valid_steps)
  File "OpenNMT-py/onmt/trainer.py", line 246, in train
    report_stats)
  File "OpenNMT-py/onmt/trainer.py", line 380, in _gradient_accumulation
    loss, batch_stats = self.train_loss(
  File "OpenNMT-py/onmt/utils/loss.py", line 202, in __call__
    for shard in shards(shard_state, shard_size):
  File "OpenNMT-py/onmt/utils/loss.py", line 485, in shards
    torch.autograd.backward(inputs, grads)
  File "venv/lib/python3.6/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
Exception ignored in: <generator object ParallelCorpus.load at 0x7f7e80060eb8>
Traceback (most recent call last):
  File "OpenNMT-py/onmt/inputters/corpus.py", line 171, in load
  File "/usr/lib/python3.6/contextlib.py", line 123, in __exit__
AttributeError: 'NoneType' object has no attribute 'exc_info'
```

Any clues? It is something realted to the way bakcward() calls are managed by I can't get the logic behind it

**Comment by anderleich** [comment]
Yes, indeed!

I had to use the `retain_graph` option as the `backward()` call for each shard seems to remove it from history

Thanks!
