### ISSUE TITLE
torch.div() (1.6.0) does not have 'rounding_mode' parameter

### ISSUE THREAD

**Issue by hosseinfani** [OpenNMT/OpenNMT-py#2203]
According to the torch 1.6.0 here: https://pytorch.org/docs/1.6.0/generated/torch.div.html?highlight=torch%20div#torch.div
there is no 'rounding_mode' parameter. 

But in translator:
https://github.com/OpenNMT/OpenNMT-py/blob/0f411ce11a83b18c0223ac94ccc11a35403763df/onmt/translate/beam_search.py#L282

That's why I receive this error:
```
onmt_translate -model ./../output/test/nmt/f0/run/model_step_100.pt -src ./../output/test/nmt/f0/src-test.txt -output ./../output/test/nmt/f0/test.epoch100.pred.csv -gpu 0 --min_length 2 -verbose 
[2022-09-15 20:32:19,980 INFO] Translating shard 0.
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\nuecg\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\nuecg\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\nuecg\Scripts\onmt_translate.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\envs\nuecg\lib\site-packages\onmt\bin\translate.py", line 54, in main
    translate(opt)
  File "c:\programdata\anaconda3\envs\nuecg\lib\site-packages\onmt\bin\translate.py", line 38, in translate
    align_debug=opt.align_debug
  File "c:\programdata\anaconda3\envs\nuecg\lib\site-packages\onmt\translate\translator.py", line 440, in translate
    phrase_table=phrase_table)
  File "c:\programdata\anaconda3\envs\nuecg\lib\site-packages\onmt\translate\translator.py", line 487, in _translate
    batch, data.src_vocabs, attn_debug
  File "c:\programdata\anaconda3\envs\nuecg\lib\site-packages\onmt\translate\translator.py", line 861, in translate_batch
    batch, src_vocabs, decode_strategy
  File "c:\programdata\anaconda3\envs\nuecg\lib\site-packages\onmt\translate\translator.py", line 947, in _translate_batch_with_strategy
    decode_strategy.advance(log_probs, attn)
  File "c:\programdata\anaconda3\envs\nuecg\lib\site-packages\onmt\translate\beam_search.py", line 283, in advance
    rounding_mode='trunc')
TypeError: div() got an unexpected keyword argument 'rounding_mode'
```

**Comment by hosseinfani** [comment]
`self._batch_index = torch.floor_divide(self.topk_ids, vocab_size)`

**Comment by vince62s** [comment]
Yes the behavior changed in pytorch 1.9, we'll update the requirements to make sure people install a more recent version of Torch (1.6.0 is quite old)
