### ISSUE TITLE
RuntimeError: inconsistent tensor size

### ISSUE THREAD

**Issue by renzhe0009** [OpenNMT/OpenNMT-py#224]
Hi,
I run
 `python3 translate.py -model data-radicalstoke/radicalstoke-model_e18.pt -src data-radicalstoke/devtest_data_in.txt -output data-radicalstoke/devtest_result_3.07.txt -gpu 0
`
and got a error:
```
Loading model
Traceback (most recent call last):
  File "translate.py", line 151, in <module>
    main()
  File "translate.py", line 77, in main
    translator = onmt.Translator(opt, dummy_opt.__dict__)
  File "/home/zhang/Downloads/OpenNMT-py-master/onmt/Translator.py", line 26, in __init__
    opt.cuda, checkpoint)
  File "/home/zhang/Downloads/OpenNMT-py-master/onmt/Models.py", line 576, in make_base_model
    model.load_state_dict(checkpoint['model'])
  File "/home/zhang/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 335, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: inconsistent tensor size at /b/wheel/pytorch-src/torch/lib/TH/generic/THTensorCopy.c:51
```

I trained model by **3** word features.

 ```
* vocabulary size. source = 4245; target = 6090
 * src feature 0 size = 214
 * src feature 1 size = 32
 * src feature 2 size = 25
 * number of training sentences. 672292
 * maximum batch size. 10
Building model...
NMTModel (
  (encoder): Encoder (
    (embeddings): Embeddings (
      (emb_luts): ModuleList (
        (0): Embedding(4245, 100, padding_idx=1)
        (1): Embedding(214, 73, padding_idx=1)
        (2): Embedding(32, 16, padding_idx=1)
        (3): Embedding(25, 13, padding_idx=1)
      )
    )
    (rnn): LSTM(202, 512, dropout=0.2)
  )
  (decoder): Decoder (
    (embeddings): Embeddings (
      (emb_luts): ModuleList (
        (0): Embedding(6090, 100, padding_idx=1)
      )
    )
    (rnn): StackedLSTM (
      (dropout): Dropout (p = 0.2)
      (layers): ModuleList (
        (0): LSTMCell(612, 512)
      )
    )
    (dropout): Dropout (p = 0.2)
    (attn): GlobalAttention (
      (linear_in): Linear (512 -> 512)
      (linear_out): Linear (1024 -> 512)
      (sm): Softmax ()
      (tanh): Tanh ()
    )
  )
  (generator): Sequential (
    (0): Linear (512 -> 6090)
    (1): LogSoftmax ()
  )
)
Intializing params
* number of parameters: 8732977
generator.0.weight 3118080
generator.0.bias 6090
encoder:  1907327
decoder:  3701480
```

Any help? Thanks in advance.

**Comment by sukhad-app** [comment]
Did you solve the issue ?
