### ISSUE TITLE
onmt_train crashes in inputter.py

### ISSUE THREAD

**Issue by PJ-Finlay** [OpenNMT/OpenNMT-py#2242]
```
File "/home/argosopentech/OpenNMT-py/onmt/inputters/inputter.py", line 133, in _read_vocab_file
    if int(line.split(None, 1)[1]) >= min_count:                                                         
IndexError: list index out of range 
```

I've started getting this error when trying to run onmt_train. It looks like a possible bug in inputter.py.

```
Traceback (most recent call last):                                                                       
  File "/home/argosopentech/env/bin/onmt_train", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py', 'console_scripts', 'onmt_train')())
  File "/home/argosopentech/OpenNMT-py/onmt/bin/train.py", line 65, in main
    train(opt)                                                                                           
  File "/home/argosopentech/OpenNMT-py/onmt/bin/train.py", line 50, in train
    train_process(opt, device_id=0)                                                                      
  File "/home/argosopentech/OpenNMT-py/onmt/train_single.py", line 131, in main                                                                                                                                    
    checkpoint, vocabs, transforms_cls = _init_train(opt)                     
  File "/home/argosopentech/OpenNMT-py/onmt/train_single.py", line 75, in _init_train
    vocabs, transforms_cls = prepare_transforms_vocabs(opt)          
  File "/home/argosopentech/OpenNMT-py/onmt/train_single.py", line 28, in prepare_transforms_vocabs
    vocabs = build_vocab(opt, specials)                                                                  
  File "/home/argosopentech/OpenNMT-py/onmt/inputters/inputter.py", line 55, in build_vocab                                                                                                                        
    src_vocab = _read_vocab_file(opt.src_vocab, opt.src_words_min_frequency)    
  File "/home/argosopentech/OpenNMT-py/onmt/inputters/inputter.py", line 133, in _read_vocab_file
    if int(line.split(None, 1)[1]) >= min_count:                                                         
IndexError: list index out of range 
```

**Comment by PJ-Finlay** [comment]
These are the values I see `line` at inputter.py:133 

```
В        118
ισχύουν  118
ΓΙΚΑ     118
ÁČ       117
✓        117
117
```

It looks like the last line is causing the issue.

**Comment by PJ-Finlay** [comment]
I think this might have been introduced in [1c8c5aff9d8fb7d7190eb3a2c0f7a72562db79fc](https://github.com/OpenNMT/OpenNMT-py/commit/1c8c5aff9d8fb7d7190eb3a2c0f7a72562db79fc) because that's when I started getting this issue.

**Comment by vince62s** [comment]
see my comment here https://github.com/OpenNMT/OpenNMT-py/pull/2243

closing since it requires more info on the build_vocab processing to better understand what is the source issue.

**Comment by PJ-Finlay** [comment]
I think it's the same problem as [this issue](https://forum.opennmt.net/t/opennmt-py-error-when-training-with-large-amount-of-data/4310/6) where the `[’\r’, 7975] = carriage return.` character can be used as a token by SentencePiece. When we split with `str.split` splits on any white-space which includes carriage return characters.

I only get this issue intermittently, I think when there are enough carriage return characters in the dataset.

This is a script for finding bad lines:
```
import pathlib

vocab_file = pathlib.Path("sentencepiece.vocab")

with open(vocab_file, "r") as f:
    vocab = f.read().splitlines() 
    for line in vocab:
        split_line = line.split(None, 1)
        if len(split_line) != 2:
            print(f"Bad line: \"{line}\"")
```
