### ISSUE TITLE
MultiHeadedAttention model_dim % head_count != 0

### ISSUE THREAD

**Issue by PJ-Finlay** [OpenNMT/OpenNMT-py#2244]
After upgrading to OpenNMT-py v3.0 I've started getting this error when trying to train a model. It looks like the head_count and model_dim params of MultiHeadedAttention are being set incorrectly.

```
[2022-11-06 04:17:26,283 INFO] Building model...                                
Traceback (most recent call last):                                              
  File "/home/argosopentech/env/bin/onmt_train", line 33, in <module>                                                                                                                                      
    sys.exit(load_entry_point('OpenNMT-py', 'console_scripts', 'onmt_train')()) 
  File "/home/argosopentech/OpenNMT-py/onmt/bin/train.py", line 65, in main     
    train(opt)                                                                  
  File "/home/argosopentech/OpenNMT-py/onmt/bin/train.py", line 50, in train                            
    train_process(opt, device_id=0)
  File "/home/argosopentech/OpenNMT-py/onmt/train_single.py", line 136, in main                         
    model = build_model(model_opt, opt, vocabs, checkpoint)                                                                                                                                                  File "/home/argosopentech/OpenNMT-py/onmt/model_builder.py", line 327, in build_model
    model = build_base_model(model_opt, vocabs, use_gpu(opt), checkpoint)                                                                                                                                    File "/home/argosopentech/OpenNMT-py/onmt/model_builder.py", line 242, in build_base_model
    model = build_task_specific_model(model_opt, vocabs)                                                                                                                                                     File "/home/argosopentech/OpenNMT-py/onmt/model_builder.py", line 158, in build_task_specific_model
    encoder, src_emb = build_encoder_with_embeddings(model_opt, vocabs)                                                                                                                                    
  File "/home/argosopentech/OpenNMT-py/onmt/model_builder.py", line 131, in build_encoder_with_embeddings
    encoder = build_encoder(model_opt, src_emb)
  File "/home/argosopentech/OpenNMT-py/onmt/model_builder.py", line 73, in build_encoder
    return str2enc[enc_type].from_opt(opt, embeddings)                                                                                                                                                     
  File "/home/argosopentech/OpenNMT-py/onmt/encoders/transformer.py", line 109, in from_opt
    return cls(
  File "/home/argosopentech/OpenNMT-py/onmt/encoders/transformer.py", line 98, in __init__
    [TransformerEncoderLayer(
  File "/home/argosopentech/OpenNMT-py/onmt/encoders/transformer.py", line 98, in <listcomp>
    [TransformerEncoderLayer(
  File "/home/argosopentech/OpenNMT-py/onmt/encoders/transformer.py", line 35, in __init__
    self.self_attn = MultiHeadedAttention(
  File "/home/argosopentech/OpenNMT-py/onmt/modules/multi_headed_attn.py", line 118, in __init__
    assert model_dim % head_count == 0
AssertionError
```

**Comment by PJ-Finlay** [comment]
I fixed this issue with:
```
# config.yml
heads: 8
hidden_size: 512
```

I had previously been using `rnn_size: 512` which no longer works.
