### ISSUE TITLE
Error with translate.py

### ISSUE THREAD

**Issue by HermitCrab404** [OpenNMT/OpenNMT-py#2276]
I saw another person with this issue and they said they just updated OpenNMT and it worked, however I updated it and am continuing to have this error. The input I used: `python translate.py -model model_step_3600.pt -src data/aslg.test.en  -output pred.txt -gpu 0 -replace_unk -beam_size 4`

This error is obviously with beam_search, but I didn't want to change anything incase I broke it.

This is the error I got:
`[2022-12-16 19:15:11,964 INFO] Translating shard 0.
/content/transformer-slt/onmt/translate/beam_search.py:187: UserWarning: An output with one or more elements was resized since it had shape [120], which does not match the required output shape [30, 4]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:17.)
  torch.mul(self.topk_scores, length_penalty, out=self.topk_log_probs)
Traceback (most recent call last):
  File "translate.py", line 6, in <module>
    main()
  File "/content/transformer-slt/onmt/bin/translate.py", line 48, in main
    translate(opt)
  File "/content/transformer-slt/onmt/bin/translate.py", line 25, in translate
    translator.translate(
  File "/content/transformer-slt/onmt/translate/translator.py", line 351, in translate
    batch_data = self.translate_batch(
  File "/content/transformer-slt/onmt/translate/translator.py", line 546, in translate_batch
    return self._translate_batch_with_strategy(batch, src_vocabs,
  File "/content/transformer-slt/onmt/translate/translator.py", line 677, in _translate_batch_with_strategy
    decode_strategy.advance(log_probs, attn)
  File "/content/transformer-slt/onmt/translate/beam_search.py", line 190, in advance
    torch.div(self.topk_ids, vocab_size, out=self._batch_index)
RuntimeError: result type Float can't be cast to the desired output type Long`

**Comment by HermitCrab404** [comment]
I have figured out the solution on line 190 of beam_search torch.div to torch.floor_divide, worked for me
