### ISSUE TITLE
Server doesn't work on GPU v3.0.4 (and likely master branch with GPU index 0)

### ISSUE THREAD

**Issue by robertBrnnn** [OpenNMT/OpenNMT-py#2325]
Hi,

The translation server in v3.0.4 doesn't work when configured for GPU. 

I had to change https://github.com/OpenNMT/OpenNMT-py/blob/v3.0.4/onmt/translate/translation_server.py#L551 to `scores, predictions = self.translator._translate(
                        IterOnDevice(infer_iter, self.translator._dev.index if self.translator._use_cuda else -1))` to be able to translate on either CPU or GPU. 

Without this change, the following error occurs when using GPU: 
```
ERROR:onmt:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translation_server.py", line 554, in run
    scores, predictions = self.translator._translate(
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 349, in _translate
    batch_data = self.translate_batch(
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 730, in translate_batch
    return self._translate_batch_with_strategy(
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 775, in _translate_batch_with_strategy
    src, enc_final_hs, enc_out, src_len = self._run_encoder(batch)
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 739, in _run_encoder
    enc_out, enc_final_hs, src_len = self.model.encoder(
  File "/usr/local/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/onmt/encoders/transformer.py", line 125, in forward
    enc_out = self.embeddings(src)
  File "/usr/local/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/onmt/modules/embeddings.py", line 267, in forward
    source = module(source)
  File "/usr/local/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/onmt/modules/util_class.py", line 26, in forward
    emb_out = [f(x) for f, x in zip(self, emb_)]
  File "/usr/local/lib/python3.8/site-packages/onmt/modules/util_class.py", line 26, in <listcomp>
    emb_out = [f(x) for f, x in zip(self, emb_)]
  File "/usr/local/lib64/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/torch/nn/modules/sparse.py", line 160, in forward
    return F.embedding(
  File "/usr/local/lib64/python3.8/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)
```

I see this has been addressed in the master branch, however the logic in master branch https://github.com/OpenNMT/OpenNMT-py/blob/fcc205ba43489315df265fedb39e91f08ed1f414/onmt/translate/translation_server.py#L566 will only work if the GPU you're using isn't index 0 i.e. `( 0 or -1)    -->   -1`.  

We've been in the process of migrating to v3 in order to test whether bug https://github.com/OpenNMT/OpenNMT-py/issues/2269 is also fixed. I see in master branch Translators now support source features, which is functionality we need to be able to migrate to v3.

Do you have an idea when the master branch will be released?

**Comment by vince62s** [comment]
@anderleich is looking into it.
I'll release 3.0.5 shortly when this is fixed + pending transforms PR.
