### ISSUE TITLE
Translation server error with 'wu' coverage penalty and replace unk options

### ISSUE THREAD

**Issue by robertBrnnn** [OpenNMT/OpenNMT-py#2365]
Hi,

Using latest version of OpenNMT-py 3.1.1, the following two options result in different errors:

1. Using a coverage penalty, specifically "wu"
2. Setting replace_unk to True

This is a working config with above mentioned options disabled:
```
{
"models_root": "...",
"models": [
  {"id": 1, "model": "model.pt", "load": true, "opt": {"gpu": 0, "beam_size": 5, "length_penalty": "wu", "coverage_penalty": "none", "alpha": 0.2, "beta": 0.2}, "tokenizer": {"type": "sentencepiece", "model": "spm.model"}}
]
}
```

Failing config 1 (coverage_penalty = wu):
```
{
"models_root": "...",
"models": [
  {"id": 1, "model": "model.pt", "load": true, "opt": {"gpu": 0, "beam_size": 5, "length_penalty": "wu", "coverage_penalty": "wu", "alpha": 0.2, "beta": 0.2}, "tokenizer": {"type": "sentencepiece", "model": "spm.model"}}
]
}
```

Error output:
```
[2023-05-08 14:10:17,051 ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translation_server.py", line 587, in run
    self.translator._translate(infer_iter)
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 353, in _translate
    batch_data = self.translate_batch(
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 801, in translate_batch
    return self._translate_batch_with_strategy(
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 891, in _translate_batch_with_strategy
    decode_strategy.advance(log_probs, attn)
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/beam_search.py", line 321, in advance
    self.topk_scores -= cov_penalty.view(_B, self.beam_size).float()
RuntimeError: shape '[1, 5]' is invalid for input of size 25
```

Failing config 2 (replace_unk = true):
```
{
"models_root": "...",
"models": [
  {"id": 1, "model": "model.pt", "load": true, "opt": {"gpu": 0, "beam_size": 5, "length_penalty": "wu", "coverage_penalty": "none", "replace_unk": true, "alpha": 0.2, "beta": 0.2}, "tokenizer": {"type": "sentencepiece", "model": "spm.model"}}
]
}
```

Error output:
```
[2023-05-08 14:13:13,926 ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translation_server.py", line 587, in run
    self.translator._translate(infer_iter)
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 353, in _translate
    batch_data = self.translate_batch(
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 801, in translate_batch
    return self._translate_batch_with_strategy(
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 894, in _translate_batch_with_strategy
    decode_strategy.update_finished()
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/beam_search.py", line 166, in update_finished
    self.alive_attn.view(
RuntimeError: shape '[3, 1, 5, 6]' is invalid for input of size 450
```

Thanks.

**Comment by vince62s** [comment]
do you have a model config to share so that I can try ?

**Comment by vince62s** [comment]
I did not ask you your data but the model config, don't think it would be an issue. Otherwise can't help you further.

**Comment by robertBrnnn** [comment]
OK, just to clarify then, are you asking for the config used to train the model or the actual model? I can provide the config used to train the model, but I cannot provide the actual model itself.

**Comment by vince62s** [comment]
so it's a regular vanilla transformer.
replace_unk won't work, searach previous issues / forum for explanation

for the coverage_penalty: what batch_size are you using when you got the error ?

**Comment by robertBrnnn** [comment]
The configs I posted in the description were using the default batch size and batch type i.e. I didn't specify a batch_size or batch_type. 

Below are outputs with different batch_type and batch_size, the error in all cases is the same. 

Command used to start the server: 
`python3 -m onmt.bin.server --port 8080 --ip 0.0.0.0 --config models.conf `

Curl command: 
`curl <host>:<port>/translator/translate -X POST -d '[{"id": 1, "src": "Where are my cats today"}]' -H 'content-type: application/json'`

Model config 1:
```
{
"models_root": "/data/training/",
"models": [
  {"id": 1, "model": "model_v3.pt", "load": true, "opt": {"gpu": 0, "beam_size": 5, "length_penalty": "wu", "coverage_penalty": "wu", "alpha": 0.2, "beta": 0.2, "batch_size": 32, "batch_type": "tokens"}, "tokenizer": {"type": "sentencepiece", "model": "spm.model"}}
]
}
```

Output with model conf 1:
```
[2023-05-19 10:39:24,741 ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translation_server.py", line 587, in run
    self.translator._translate(infer_iter)
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 353, in _translate
    batch_data = self.translate_batch(
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 801, in translate_batch
    return self._translate_batch_with_strategy(
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 891, in _translate_batch_with_strategy
    decode_strategy.advance(log_probs, attn)
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/beam_search.py", line 321, in advance
    self.topk_scores -= cov_penalty.view(_B, self.beam_size).float()
RuntimeError: shape '[1, 5]' is invalid for input of size 25
```

Model conf 2 (without wu coverage penalty, same batch size and batch type):
```
{
"models_root": "/data/training/",
"models": [
  {"id": 1, "model": "model_v3.pt", "load": true, "opt": {"gpu": 0, "beam_size": 5, "length_penalty": "wu", "coverage_penalty": "none", "alpha": 0.2, "beta": 0.2, "batch_size": 32, "batch_type": "tokens"}, "tokenizer": {"type": "sentencepiece", "model": "spm.model"}}
]
}
```

Output with model conf 2:
```
[[{"n_best":1,"pred_score":-2.1375200748443604,"src":"Where are my cats today","tgt":"Wo sind meine Katzen heute"}]]
```

Model config 3, using `sents` batch type, and `batch_size` 1 and `wu` coverage penalty:
```
{
"models_root": "/data/training/length_ratio",
"models": [
  {"id": 1, "model": "model_v3.pt", "load": true, "opt": {"gpu": 0, "beam_size": 5, "length_penalty": "wu", "coverage_penalty": "wu", "alpha": 0.2, "beta": 0.2, "batch_size": 1, "batch_type": "sents"}, "tokenizer": {"type": "sentencepiece", "model": "spm.model"}}
]
}
```

Output model config3:
```
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translation_server.py", line 587, in run
    self.translator._translate(infer_iter)
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 353, in _translate
    batch_data = self.translate_batch(
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 801, in translate_batch
    return self._translate_batch_with_strategy(
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/translator.py", line 891, in _translate_batch_with_strategy
    decode_strategy.advance(log_probs, attn)
  File "/usr/local/lib/python3.8/site-packages/onmt/translate/beam_search.py", line 321, in advance
    self.topk_scores -= cov_penalty.view(_B, self.beam_size).float()
RuntimeError: shape '[1, 5]' is invalid for input of size 25
```

**Comment by robertBrnnn** [comment]
The issue occurs with a `beam_size > 1`, just tried the below config and it worked. 

Model config: 
```
{
"models_root": "/data/training/length_ratio",
"models": [
  {"id": 1, "model": "model_v3.pt", "load": true, "opt": {"gpu": 0, "beam_size": 1, "length_penalty": "wu", "coverage_penalty": "wu", "alpha": 0.2, "beta": 0.2, "batch_size": 32, "batch_type": "tokens"}, "tokenizer": {"type": "sentencepiece", "model": "spm.model"}}
]
}
```

Output:
```
[[{"n_best":1,"pred_score":-2.816187858581543,"src":"Where are my cats today","tgt":"Wo sind meine Katzen heute"}]]
```

Also, the issue affects coverage penalty in general when `beam_size > 1`; I tried with coverage penalty of `summary` and `beam_size=5` and got the same error.

**Comment by robertBrnnn** [comment]
Thanks @vince62s for the fix, and your patience :)

Would you happen to have a rough idea when the next release including this fix will be?
