### ISSUE TITLE
"attention is all you need " model

### ISSUE THREAD

**Issue by beichao1314** [OpenNMT/OpenNMT-py#237]
I'm testing transformer model, and command: 
```
python train.py -data my_data/enzh.pt -encoder_type transformer -decoder_type transformer -optim adam -learning_rate 0.001 -rnn_size 512 -word_vec_size 512 -gpuid 0
```
I have tested it on CPU, it works well. But I tested it on GPU
and get the error similar to #121 
```
Traceback (most recent call last):
  File "train.py", line 310, in <module>
    main()
  File "train.py", line 306, in main
    train_model(model, train, valid, fields, optim)
  File "train.py", line 169, in train_model
    train_stats = train_epoch(epoch)
  File "train.py", line 133, in train_epoch
    model(src, tgt, src_lengths, dec_state)
  File "/home/zyyt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zyyt/train/iwslt/OpenNMT-py/onmt/Models.py", line 739, in forward
    else dec_state)
  File "/home/zyyt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zyyt/train/iwslt/OpenNMT-py/onmt/Models.py", line 663, in forward
    src_pad_mask, tgt_pad_mask)
  File "/home/zyyt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zyyt/train/iwslt/OpenNMT-py/onmt/modules/Transformer.py", line 111, in forward
    .expand_as(tgt_pad_mask), 0)
  File "/home/zyyt/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 293, in __add__
    return self.add(other)
TypeError: add received an invalid combination of arguments - got (torch.ByteTensor), but expected one of:
 * (int value)
      didn't match because some of the arguments have invalid types: (torch.ByteTensor)
 * (torch.cuda.ByteTensor other)
      didn't match because some of the arguments have invalid types: (torch.ByteTensor)
 * (torch.cuda.sparse.ByteTensor other)
      didn't match because some of the arguments have invalid types: (torch.ByteTensor)
 * (int value, torch.cuda.ByteTensor other)
 * (int value, torch.cuda.sparse.ByteTensor other)
```
And I just add ``` .cuda()``` at this line https://github.com/OpenNMT/OpenNMT-py/blob/f30bad29d06fdef317f1bff9a88870372fa1fecd/onmt/modules/Transformer.py#L91
It works well.
This just is a simple test.

**Comment by JianyuZhan** [comment]
It is weird the `register_buffer('mask', self.mask)`  doesn't make `TransformerDecoder` get the `cuda`  behavior.

The cuda propagation hierarchy is like

```
    NMTModel   <-  cuda()
          |
    NMTModel.decoder = TransformerDecoder()
          |                
    decoder.transformer = ModuleList([onmt.modules.TransformerDecoder])
         |
    transformer[i].mask    <- register_buffer()
```

When calling `cuda()` on the top-est `NMTModel`, it recursively descends along the hierarchy into the leaf module, calling `cuda()` along the way on `_parameters` and `_buffers` of each module.

**Comment by srush** [comment]
@beichao1314 is this with the latest version of the code. 

Also you will want to run with a larger set of options:

```
python train.py -data demo/data -save_model demo/model -gpuid 0                                        \
    -encoder_type transformer -decoder_type transformer                                                \
    -layers 4 -rnn_size 1024  -word_vec_size 1024                                                      \
    -max_grad_norm 0 -optim adam -position_encoding -dropout 0.2 -param_init 0                         \
    -batch_size 32 -epochs 30 -report_every 100 -warmup_steps 4000 -learning_rate 1 -decay_method noam \
    -start_checkpoint_at 20 
```

**Comment by srush** [comment]
Fixed in https://github.com/OpenNMT/OpenNMT-py/pull/240

**Comment by beichao1314** [comment]
I'm sorry to late reply.
Thanks for all your work!
