### ISSUE TITLE
No module named utils.rnn

### ISSUE THREAD

**Issue by xjtu-zeng** [OpenNMT/OpenNMT-py#24]
$ python preprocess.py -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo
Traceback (most recent call last):
  File "preprocess.py", line 1, in <module>
    import onmt
  File "/home/zeng/opensource/OpenNMT-py/onmt/__init__.py", line 2, in <module>
    import onmt.Models
  File "/home/zeng/opensource/OpenNMT-py/onmt/Models.py", line 5, in <module>
    from torch.nn.utils.rnn import pad_packed_sequence as unpack
ImportError: No module named utils.rnn

**Comment by bmccann** [comment]
https://discuss.pytorch.org/t/sovled-pytorch-example-openmt-importerror-no-module-named-utils-rnn/1498

**Comment by loretoparisi** [comment]
@bmccann I have tried the two commands and

```
Step 3/9 : RUN pip uninstall http://download.pytorch.org/whl/cu80/torch-0.1.9.post2-cp27-none-linux_x86_64.whl &&     pip install http://download.pytorch.org/whl/cu80/torch-0.1.10.post2-cp27-none-linux_x86_64.whl
 ---> Running in 5764c984384e
Uninstalling torch-0.1:
  /usr/local/lib/python2.7/dist-packages/tools
  /usr/local/lib/python2.7/dist-packages/torch
  /usr/local/lib/python2.7/dist-packages/torch-0.1-py2.7.egg-info
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 346, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 103, in remove
    response = ask('Proceed (y/n)? ', ('y', 'n'))
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 158, in ask
    response = input(message)
EOFError: EOF when reading a line
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

**Comment by bmccann** [comment]
This might help:

https://discuss.pytorch.org/t/cannot-install-pytorch-on-ubuntu14-04-via-pip/1189/4

Let me know

**Comment by xjtu-zeng** [comment]
maybe what you need to uninstall is not the link(whl) you typed here, whether it's different with the one you installed before?
