### ISSUE TITLE
[bug] RuntimeError occurs when I use Adam optimizer and noam decay method together.

### ISSUE THREAD

**Issue by stellarway** [OpenNMT/OpenNMT-py#2432]
An error occurs when using Adam Optimizer and Noam Decay methods at the same time. (noamwd method as well)
In case of using more than one gpu, it automatically interrupted due to the failure of multiprocessing, and In case of using only one gpu, it occurs following runtime error.

```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Fatal Python error: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x55b376cad020)

Thread 0x00007f3e2f7b5700 (most recent call first):
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/socket.py", line 292 in accept
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/connection.py", line 609 in accept
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/connection.py", line 463 in accept
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/resource_sharer.py", line 142 in _serve
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/threading.py", line 870 in run
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f3e2efb4700 (most recent call first):
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/traceback.py", line 105 in print_exception
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/traceback.py", line 163 in print_exc
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/queues.py", line 276 in _on_queue_feeder_error
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/multiprocessing/queues.py", line 267 in _feed
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/threading.py", line 870 in run
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f3f134a12c0 (most recent call first):
<no Python frame>
Traceback (most recent call last):
  File "OpenNMT-py/train.py", line 6, in <module>
    main()
  File "/home/user/workspace/230703_onmt_wh/OpenNMT-py/onmt/bin/train.py", line 67, in main
    train(opt)
  File "/home/user/workspace/230703_onmt_wh/OpenNMT-py/onmt/bin/train.py", line 52, in train
    train_process(opt, device_id=0)
  File "/userhome/user/workspace/230703_onmt_wh/OpenNMT-py/onmt/train_single.py", line 232, in main
    trainer.train(
  File "/home/user/workspace/230703_onmt_wh/OpenNMT-py/onmt/trainer.py", line 307, in train
    self._gradient_accumulation(
  File "/home/user/workspace/230703_onmt_wh/OpenNMT-py/onmt/trainer.py", line 538, in _gradient_accumulation
    self.optim.step()
  File "/home/user/workspace/230703_onmt_wh/OpenNMT-py/onmt/utils/optimizers.py", line 428, in step
    self._scaler.step(self._optimizer)
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 341, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 288, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/site-packages/torch/optim/adam.py", line 234, in step
    adam(params_with_grad,
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/site-packages/torch/optim/adam.py", line 300, in adam
    func(params,
  File "/home/user/anaconda3/envs/onmt_env/lib/python3.8/site-packages/torch/optim/adam.py", line 412, in _single_tensor_adam
    param.addcdiv_(exp_avg, denom, value=-step_size)
RuntimeError: value cannot be converted to type float without overflow
```

Please check out and clear this issue. If it is possible, It would be helpful that you let me the cause.

**Comment by vince62s** [comment]
post your config file, I never had any issue making this work.

**Comment by stellarway** [comment]
> post your config file, I never had any issue making this work.

here is my config file

```
### Meta:
tensorboard: true
tensorboard_log_dir: /home/tf-dev-02/workspace/230703_onmt_wh/logs/

### vocab:
src_vocab: longleg_koja_data/vocab/spm_ko.vocab
tgt_vocab: longleg_koja_data/vocab/spm_ja.vocab
src_vocab_size: 60000
tgt_vocab_size: 90000
vocab_size_multiple: 8
src_words_min_frequency: 2
tgt_words_min_frequency: 2
share_vocab: False

### Transform related opts:
#### Sampling
switchout_temperature: 1.0
tokendrop_temperature: 1.0
tokenmask_temperature: 1.0
#### Filter
src_seq_length: 300
tgt_seq_length: 300
#### BART
permute_sent_ratio: 0.0
rotate_ratio: 0.0
insert_ratio: 0.0
random_ratio: 0.0
mask_ratio: 0.0
mask_length: subword
poisson_lambda: 3.0
replace_length: 1

# Corpus opts:
data:
    corpus_1:
        path_src: longleg_koja_data/pretrain.last3.ko.train.newtok
        path_tgt: longleg_koja_data/pretrain.last3.ja.train.newtok
        transforms: [tokenmask, tokendrop, filtertoolong]
    valid:
        path_src: longleg_koja_data/pretrain.last3.ko.test.newtok
        path_tgt: longleg_koja_data/pretrain.last3.ja.test.newtok
        transforms: [filtertoolong]

# Model configuration
save_model: models/test_ckpt_/
keep_checkpoint: 50
save_checkpoint_steps: 500
average_decay: 0.0001
seed: 2345
report_every: 100
train_steps: 100000
valid_steps: 100

queue_size: 10000
bucket_size: 32768
world_size: 1
gpu_ranks: 0
batch_type: "tokens"
batch_size: 2048
valid_batch_size: 2048
batch_size_multiple: 1
max_generator_batches: 0
accum_count: [3]
accum_steps: [0]

model_dtype: "fp16"
optim: "adam" #fusedadam
learning_rate: 1e-10
warmup_steps: 6000
decay_method: "noamwd"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

encoder_type: transformer
decoder_type: transformer
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
enc_hid_size: 512
dec_hid_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
share_decoder_embeddings: true
share_embeddings: false
position_encoding: true
```

**Comment by stellarway** [comment]
> I guess your learning rate is way too low

I think that cannot be cause... Initially I tried at (learning_rate == 0.8) but error occurred in the same way...
I gradually reduced learning rate, but all trials was failed.

**Comment by vince62s** [comment]
what version are you using? I am seeing rnn_size which is deprecated.

**Comment by stellarway** [comment]
> what version are you using? I am seeing rnn_size which is deprecated.

config file same as v.2.X, but script is v3.X

**Comment by vince62s** [comment]
can't help you, you need to be very specific. please git pull master or at least last pip version et start again.
