### ISSUE TITLE
ValueError on calling onmt_translate

### ISSUE THREAD

**Issue by Lguyogiro** [OpenNMT/OpenNMT-py#2455]
I have a successfully trained model which I was able to use for translation on a different machine at an earlier date.

Now, when I call `onmt_translate`, I get the following error:
```
Traceback (most recent call last):
  File "/envs/dev_onmt/bin/onmt_translate", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-py', 'console_scripts', 'onmt_translate')())
  File "../OpenNMT-py/onmt/bin/translate.py", line 54, in main
    translate(opt)
  File "../OpenNMT-py/onmt/bin/translate.py", line 16, in translate
    translator = build_translator(opt, logger=logger, report_score=True)
  File "../OpenNMT-py/onmt/translate/translator.py", line 33, in build_translator
    fields, model, model_opt = load_test_model(opt)
  File "../OpenNMT-py/onmt/model_builder.py", line 96, in load_test_model
    model = build_base_model(model_opt, fields, use_gpu(opt), checkpoint,
  File "../OpenNMT-py/onmt/model_builder.py", line 239, in build_base_model
    model = build_task_specific_model(model_opt, fields)
  File "../OpenNMT-py/onmt/model_builder.py", line 151, in build_task_specific_model
    encoder, src_emb = build_encoder_with_embeddings(model_opt, fields)
  File "../OpenNMT-py/onmt/model_builder.py", line 122, in build_encoder_with_embeddings
    src_emb = build_src_emb(model_opt, fields)
  File "../OpenNMT-py/onmt/model_builder.py", line 114, in build_src_emb
    src_emb = build_embeddings(model_opt, src_field)
  File "../OpenNMT-py/onmt/model_builder.py", line 32, in build_embeddings
    pad_indices = [f.vocab.stoi[f.pad_token] for _, f in text_field]
  File "../OpenNMT-py/onmt/model_builder.py", line 32, in <listcomp>
    pad_indices = [f.vocab.stoi[f.pad_token] for _, f in text_field]
ValueError: too many values to unpack (expected 2)
``` 

I installed from source using `pip install -e .`.

**Comment by Lguyogiro** [comment]
On second look, I think this is related to version mismatch...I will try updating my local version and see if this solves the issue

**Comment by Lguyogiro** [comment]
Yes this was the issue.. I had an old version of the code.
