### ISSUE TITLE
Bug in Encoder-Decoder Translation models

### ISSUE THREAD

**Issue by henyee** [OpenNMT/OpenNMT-py#2468]
There seems to be a bug with the models trained with the default configuration in the documents with v3.4.0. An earlier 3.x version didn't have this bug. I suspect it was introduced due to the various decoder (LLM) support that was recently added.
```
#test.yaml
# Data
data:
    corpus:
        path_src: /datatok.zh
        path_tgt: /data.tok.en
        transforms: [filtertoolong]
        weight: 1        
    valid:
        path_src: /data_val.tok.zh
        path_tgt: /data_val.tok.en
        transforms: [filtertoolong]        

# General opts
save_model: model
save_checkpoint_steps: 1
valid_steps: 1
train_steps: 1

# Vocabulary files that were just created
src_vocab: /sp_zh_en_opennmt.vocab
tgt_vocab: /sp_zh_en_opennmt.vocab
src_vocab_size: 100000
tgt_vocab_size: 100000
share_vocab: True

# Batching
bucket_size: 262144
world_size: 2
gpu_ranks: [0, 1]
num_workers: 2
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 2048
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp16"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
hidden_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
```
with the command `onmt_train --config  /test.yaml ` and training for just 1 step to save the model.
Training and validation isn't a problem (for even more steps):
```
[2023-09-12 03:33:25,749 INFO] Train perplexity: 99214.7
[2023-09-12 03:33:25,749 INFO] Train accuracy: 0
[2023-09-12 03:33:25,749 INFO] Sentences processed: 256
[2023-09-12 03:33:25,749 INFO] Average bsz: 1500/1952/64
[2023-09-12 03:33:25,749 INFO] Validation perplexity: 99144.2
[2023-09-12 03:33:25,749 INFO] Validation accuracy: 0
[2023-09-12 03:33:28,742 INFO] Saving checkpoint model_step_1.pt
```
However, when loading the checkpoint for continued training or translation, we get this error.
```
#onmt_translate --model model_step_1.pt --src /media/nvme4/training_data/test.zh --output  /media/nvme4/training_d
ata/output.txt --gpu 0   
[2023-09-12 03:34:29,449 INFO] Loading checkpoint from model_step_1.pt
[2023-09-12 03:34:30,669 INFO] Loading data into the model
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/bin/onmt_translate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/onmt/bin/translate.py", line 56, in main
    translate(opt)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/onmt/bin/translate.py", line 23, in translate
    translator = build_translator(opt, logger=logger, report_score=True)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/onmt/translate/translator.py", line 34, in build_translator
    vocabs, model, model_opt = load_test_model(opt, device_id)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/onmt/model_builder.py", line 137, in load_test_model
    model.load_state_dict(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/onmt/models/model.py", line 132, in load_state_dict
    raise ValueError(
ValueError: Missing key in checkpoint: encoder.embeddings.make_embedding.emb_luts.0.weight
```
```
# For continued training
[2023-09-12 03:40:05,105 INFO]  Starting process pid: 505689  
[2023-09-12 03:40:05,106 INFO]  Starting process pid: 505690  
[2023-09-12 03:40:06,300 INFO] Parsed 2 corpora from -data.
[2023-09-12 03:40:06,300 INFO] Loading checkpoint from model_step_1.pt
[2023-09-12 03:40:06,916 INFO] Building model...
[2023-09-12 03:40:07,554 INFO] Switching model to float32 for amp/apex_amp
[2023-09-12 03:40:07,554 INFO] Non quantized layer compute is fp16
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/bin/onmt_train", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/onmt/bin/train.py", line 67, in main
    train(opt)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/onmt/bin/train.py", line 49, in train
    p.join()
  File "/root/miniconda3/envs/py3.10/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/onmt/utils/distributed.py", line 166, in signal_handler
    raise Exception(msg)
Exception: 

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/onmt/utils/distributed.py", line 178, in spawned_train
    process_fn(opt, device_id=device_id)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/onmt/train_single.py", line 165, in main
    model = build_model(model_opt, opt, vocabs, checkpoint, device_id)
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/onmt/model_builder.py", line 412, in build_model
    model.load_state_dict(
  File "/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/onmt/models/model.py", line 132, in load_state_dict
    raise ValueError(
ValueError: Missing key in checkpoint: encoder.embeddings.make_embedding.emb_luts.0.weight

Process SpawnProcess-1:
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/py3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/miniconda3/envs/py3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
```
If `strict=False` is set in this [function](https://github.com/OpenNMT/OpenNMT-py/blob/eb24258a00f7fdb65ef95fd1879e0f8c795e1d65/onmt/models/model.py#L48C9-L48C24), the error won't appear, but the continued training or translation seem to give worse acc/ppl or gives gibberish (same gibberish for two different test sentences. It also doesn't match the ppl one would expect from training about 25000 steps which is some semblance of understanding the translation task)

**Comment by vince62s** [comment]
thanks for reporting. Obviously there is a bug in multigpu "data_parallel" mode. Please confirm it works in single GPU I will look into the issue.

**Comment by vince62s** [comment]
I pushed a fix, let me know if it works as expected now, thanks.
