### ISSUE TITLE
all_reduce_and_rescale_tensors gives IndexError: list index out of range

### ISSUE THREAD

**Issue by Garfounkel** [OpenNMT/OpenNMT-py#2594]
Got the following error during training:

```
Traceback (most recent call last):
  File "/workspace/src/onmt/onmt_training.py", line 70, in <module>
    main()
  File "/workspace/src/onmt/onmt_training.py", line 67, in main
    train(opt)
  File "/workspace/src/onmt/onmt_training.py", line 52, in train
    p.join()
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/opt/conda/lib/python3.10/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/opt/conda/lib/python3.10/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/opt/conda/lib/python3.10/site-packages/onmt/utils/distributed.py", line 165, in signal_handler
    raise Exception(msg)
Exception: 
-- Tracebacks above this line can probably
                 be ignored --
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/onmt/utils/distributed.py", line 177, in spawned_train
    process_fn(opt, device_id=device_id)
  File "/opt/conda/lib/python3.10/site-packages/onmt/train_single.py", line 237, in main
    trainer.train(
  File "/opt/conda/lib/python3.10/site-packages/onmt/trainer.py", line 319, in train
    self._gradient_accumulation(
  File "/opt/conda/lib/python3.10/site-packages/onmt/trainer.py", line 546, in _gradient_accumulation
    onmt.utils.distributed.all_reduce_and_rescale_tensors(
  File "/opt/conda/lib/python3.10/site-packages/onmt/utils/distributed.py", line 51, in all_reduce_and_rescale_tensors
    tensors[0].new(math.ceil(buffer_size / tensors[0].element_size())).zero_()
IndexError: list index out of range
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
[E ProcessGroupNCCL.cpp:475] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=44065, OpType=ALLREDUCE, NumelIn=25991168, NumelOut=25991168, Timeout(ms)=10800000) ran for 10800745 milliseconds before timing out.
```

- I don't think it's OOM because I would see a log like `Step 1, cuda OOM - batch removed` (I tried with double the batch_size to confirm it gives OOM).
- The error consistently happen at the same batch after 8000 steps with this seed.
- I tried to increase the limit of the shm volume to 10g. Doesn't solve the issue.

Here's the calling code (within `onmt.trainer.py`):
```python
if self.n_gpu > 1 and self.parallel_mode == "data_parallel":
    grads = [
        p.grad.data
        for p in self.model.parameters()
        if p.requires_grad and p.grad is not None
    ]
    onmt.utils.distributed.all_reduce_and_rescale_tensors(
        grads, float(self.n_gpu)
    )
```

The function `all_reduce_and_rescale_tensors` can't handle empty tensors. Now the problem is I have no idea why at this specific batch the gradients would be empty. Any ideas?

Full logs and config:
[log_all_reduce_and_rescale_tensors.txt](https://github.com/user-attachments/files/16015592/log_all_reduce_and_rescale_tensors.txt)
[train_config.yaml](https://github.com/user-attachments/files/16015606/train_config.txt)

**Comment by vince62s** [comment]
Please read the README of the project, we are no longer supporting OpenNMT-py and switching to https://github.com/eole-nlp/eole
I suggest you to switch to eole if you intend to get support in the future.
