### ISSUE TITLE
No such file or directory: 'multi30k_model_e13_*.pt'

### ISSUE THREAD

**Issue by loretoparisi** [OpenNMT/OpenNMT-py#26]
I did the training successfully 

```
...
Epoch 13,   450/  454; acc:  75.87; ppl:   2.87; 2975 src tok/s; 3085 tgt tok/s;   1714 s elapsed
Train perplexity: 2.91169
Train accuracy: 75.7449
Validation perplexity: 5.64726
Validation accuracy: 70.0177
Decaying learning rate to 0.015625
```

and then from the same folder

```
root@27277298c897:/# python translate.py -gpu 0 -model multi30k_model_e13_*.pt -src data/multi30k/test.en.atok -tgt data/multi30k/test.de.atok -replace_unk -verbose -output multi30k.test.pred.atok
Traceback (most recent call last):
  File "translate.py", line 135, in <module>
    main()
  File "translate.py", line 62, in main
    translator = onmt.Translator(opt)
  File "/musixmatch/onmt/Translator.py", line 12, in __init__
    checkpoint = torch.load(opt.model)
  File "/usr/local/lib/python2.7/dist-packages/torch/serialization.py", line 220, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'multi30k_model_e13_*.pt'
```

The root folder content is

```
-rw-r--r-- 1 root root      1137 Apr  3 15:07 LICENSE.md
-rw-r--r-- 1 root root      3606 Apr  3 15:07 README.md
drwxr-xr-x 5 root root      4096 Apr  3 15:53 data
-rw-r--r-- 1 root root      4826 Apr  3 15:53 multi-bleu.perl
-rw-r--r-- 1 root root 131591914 Apr  3 15:56 multi30k_model_acc_28.59_ppl_86.75_e1.pt
-rw-r--r-- 1 root root 131591914 Apr  3 15:58 multi30k_model_acc_37.08_ppl_38.35_e2.pt
-rw-r--r-- 1 root root 131591914 Apr  3 16:00 multi30k_model_acc_52.30_ppl_15.70_e3.pt
-rw-r--r-- 1 root root 131591914 Apr  3 16:02 multi30k_model_acc_58.82_ppl_10.89_e4.pt
-rw-r--r-- 1 root root 131591914 Apr  3 16:04 multi30k_model_acc_62.22_ppl_8.55_e5.pt
-rw-r--r-- 1 root root 131591914 Apr  3 16:09 multi30k_model_acc_64.36_ppl_7.17_e7.pt
-rw-r--r-- 1 root root 131591914 Apr  3 16:07 multi30k_model_acc_64.60_ppl_7.32_e6.pt
-rw-r--r-- 1 root root 131591914 Apr  3 16:11 multi30k_model_acc_66.44_ppl_6.52_e8.pt
-rw-r--r-- 1 root root 131591914 Apr  3 16:13 multi30k_model_acc_68.62_ppl_5.88_e9.pt
-rw-r--r-- 1 root root 131591914 Apr  3 16:15 multi30k_model_acc_69.69_ppl_5.68_e10.pt
-rw-r--r-- 1 root root 131591914 Apr  3 16:18 multi30k_model_acc_69.71_ppl_5.67_e11.pt
-rw-r--r-- 1 root root 131591914 Apr  3 16:22 multi30k_model_acc_70.02_ppl_5.65_e13.pt
-rw-r--r-- 1 root root 131591914 Apr  3 16:20 multi30k_model_acc_70.04_ppl_5.64_e12.pt
-rw-r--r-- 1 root root    196775 Apr  3 15:53 nonbreaking_prefix.de
-rw-r--r-- 1 root root    159010 Apr  3 15:53 nonbreaking_prefix.en
drwxr-xr-x 4 root root      4096 Apr  3 15:53 onmt
-rw-r--r-- 1 root root      5977 Apr  3 15:07 preprocess.py
-rwxr-xr-x 1 root root       464 Apr  3 15:52 preprocess.sh
-rw-r--r-- 1 root root     16790 Apr  3 15:53 tokenizer.perl
-rw-r--r-- 1 root root     14316 Apr  3 15:07 train.py
-rw-r--r-- 1 root root         0 Apr  3 15:44 train.sh
-rw-r--r-- 1 root root      4774 Apr  3 15:07 translate.py
```

So I do not see the ` multi30k_model_e13_*.pt` model file there.

**Comment by guillaumekln** [comment]
You have to replace `multi30k_model_e13_*.pt` by an actual file: `multi30k_model_acc_70.02_ppl_5.65_e13.pt`.

**Comment by loretoparisi** [comment]
@guillaumekln Thanks it worked!!!

```
python translate.py -gpu 0 -model multi30k_model_acc_70.02_ppl_5.72_e13.pt -src data/multi30k/test.en.atok -tgt data/multi30k/test.de.atok -replace_unk -verbose -output multi30k.test.pred.atok
```
