### ISSUE TITLE
Bug with feature sorting

### ISSUE THREAD

**Issue by Henry-E** [OpenNMT/OpenNMT-py#298]
https://github.com/OpenNMT/OpenNMT-py/blob/d748ad1a9adf6260de9ed3b386ff4f71086608cb/onmt/IO.py#L76-L77

Causes the error `RuntimeError: bool value of Variable objects containing non-empty torch.cuda.ByteTensor is ambiguous
Uncaught exception.`

I broke apart the different steps and it appears that applying `sorted()` to the matrices themselves, rather than presumably the names, is what's causing the issue. I'm not going to submit a pull request yet in case there's some important reason for the sorting. And also quite embarrassingly I can't get the loop working as a list comprehension because of variable scoping or something. 

Stack trace
```
Traceback (most recent call last):
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/ipdb/__main__.py", line 198, in main
    pdb._runscript(mainpyfile)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/henrye/downloads/OpenNMT-py/train.py", line 1, in <module>
    from __future__ import division
  File "/home/henrye/downloads/OpenNMT-py/train.py", line 284, in main
    train_model(model, train, valid, fields, optim)
  File "/home/henrye/downloads/OpenNMT-py/train.py", line 144, in train_model
    train_stats = trainer.train(epoch, report_func)
  File "/home/henrye/downloads/OpenNMT-py/onmt/Trainer.py", line 108, in train
    src = onmt.IO.make_features(batch, 'src')
  File "/home/henrye/downloads/OpenNMT-py/onmt/IO.py", line 77, in make_features
    for k in batch.__dict__ if feat_start in k)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autograd/variable.py", line 123, in __bool__
    torch.typename(self.data) + " is ambiguous")
RuntimeError: bool value of Variable objects containing non-empty torch.cuda.ByteTensor is ambiguous
```

**Comment by srush** [comment]
@bpopeters what is this code? I honestly kind of hate whatever trick this is. Are you trying to sort by the values of tensors somehow? Why do you need to do any sorting in this function?

**Comment by srush** [comment]
oh, I guess it is trying to sort by the string of the key?

**Comment by bpopeters** [comment]
I would guess that's what it's supposed to do, but I don't know if it'll
succeed; it's sorting the values in the comprehension, not the keys of
`batch.__dict__`. But the documentation of what `batch` is does not appear
to be correct. I don't like this code either; it's one of several things in
IO.py that are fairly objectionable.

I'll have a closer look this evening CEST.

**Comment by srush** [comment]
Oh, haha thought you may have written it. Guess it was someone else. I'll take a look then.

**Comment by bpopeters** [comment]
I *kind of* wrote it, in the sense that I extended it to target features (and apparently added the `sorted`; I wish I'd left a comment), but the stuff with `__dict__` was there before me.

**Comment by srush** [comment]
did this get fixed in the io.py refactor?

**Comment by bpopeters** [comment]
This'll be in the next round of commits.
