### ISSUE TITLE
Error on validation with `-copy_attn`

### ISSUE THREAD

**Issue by pltrdy** [OpenNMT/OpenNMT-py#313]
The validation is failing when training using `-copy_attn`. The first epoch is ok but validation raises:
```
Traceback (most recent call last):
  File "train.py", line 288, in <module>
    main()
  File "train.py", line 284, in main
    train_model(model, train, valid, fields, optim)
  File "train.py", line 149, in train_model
    valid_stats = trainer.validate()
  File "/home/pltrdy/pytorchwork/OpenNMT-py/onmt/Trainer.py", line 161, in validate
    _, batch_stats = self.valid_loss(batch, **gen_state)
  File "/home/pltrdy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pltrdy/pytorchwork/OpenNMT-py/onmt/Loss.py", line 39, in forward
    return self.compute_loss(batch, output, target, **kwargs)
TypeError: compute_loss() got an unexpected keyword argument 'coverage'
```

I'm on the last commit

**Comment by sebastianGehrmann** [comment]
There is a workaround in #305 you can use.

**Comment by pltrdy** [comment]
Just also found it locally. I think things like this shouldn't be present on master tho. It's hard to find a code base we can trust here. 

Thx tho

**Comment by pltrdy** [comment]
there's another small thing related to the `validation_loss` call in Trainer. I've submitted a patch.

**Comment by srush** [comment]
Thanks, accepted.
