### ISSUE TITLE
About MultiGPU Usage

### ISSUE THREAD

**Issue by StillKeepTry** [OpenNMT/OpenNMT-py#34]
When i use Opennmt-py with MultiGPU, it will report the follow error:

> Traceback (most recent call last):
  File "train.py", line 356, in <module>
    main()
  File "train.py", line 352, in main
    trainModel(model, trainData, validData, dataset, optim)
  File "train.py", line 234, in trainModel
    train_loss, train_acc = trainEpoch(epoch)
  File "train.py", line 198, in trainEpoch
    outputs = model(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 61, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 71, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/parallel_apply.py", line 45, in parallel_apply
    raise output
ValueError: lengths array has incorrect size

But in Single GPU, it has no problem, is it a bug or other problem?

**Comment by guillaumekln** [comment]
It should be fixed on master.
