### ISSUE TITLE
typeError when trying to iterate on OrderedIterator class in Python 3.5

### ISSUE THREAD

**Issue by moonlightlane** [OpenNMT/OpenNMT-py#352]
In python3, ubuntu 16.04, I tried to load some text in command line, create the OrderedIterator object, and iterate through it. Got the following error:

`Traceback (most recent call last):`
 ` File "<stdin>", line 1, in <module>`
 ` File "/usr/local/lib/python3.5/dist-packages/torchtext-0.2.0b0-py3.5.egg/torchtext/data/iterator.py", line 164, in __iter__`
 ` File "/usr/local/lib/python3.5/dist-packages/torchtext-0.2.0b0-py3.5.egg/torchtext/data/batch.py", line 23, in __init__`
 ` File "/usr/local/lib/python3.5/dist-packages/torchtext-0.2.0b0-py3.5.egg/torchtext/data/field.py", line 227, in numericalize`
`  File "/usr/local/lib/python3.5/dist-packages/torchtext-0.2.0b0-py3.5.egg/torchtext/data/field.py", line 227, in <listcomp>`
`TypeError: float() argument must be a string or a number, not 'torch.LongTensor'`

I did the following that produced the above error:
`data = onmt.IO.ONMTDataset(opt.src, opt.tgt, translator.fields, None)`
`test_data = onmt.IO.OrderedIterator(
        dataset=data, device=opt.gpu,
        batch_size=opt.batch_size, train=False, sort=False,
        shuffle=False)`
`from itertools import takewhile, count`
`counter = count(1)`
`for i, batch in enumerate(test_data):`
`    batch_tmp = batch`

In python2 there is no such error.

**Comment by moonlightlane** [comment]
OK, I think this might because my training scrip is using python2.7 and I am trying to use python3 to load model and data for generating sequences.
