### ISSUE TITLE
SRU doesn't support multi-gpu

### ISSUE THREAD

**Issue by sriniiyer** [OpenNMT/OpenNMT-py#379]
If i run with SRUs and gpuid 0, it runs fine, but when I change it to 1, it gives the following error.

```
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    main()
  File "train.py", line 286, in main
    train_model(model, train, valid, fields, optim)
  File "train.py", line 146, in train_model
    train_stats = trainer.train(epoch, report_func)
  File "/home/sviyer/onmt-fresh/onmt/Trainer.py", line 119, in train
    self.model(src, tgt, src_lengths, dec_state, src_chars=batch.src_chars)
  File "/home/sviyer/.conda/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sviyer/onmt-fresh/onmt/Models.py", line 429, in forward
    enc_hidden, context = self.encoder(src, lengths, src_chars=src_chars)
  File "/home/sviyer/.conda/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sviyer/onmt-fresh/onmt/Models.py", line 96, in forward
    outputs, hidden_t = self.rnn(packed_emb, hidden)
  File "/home/sviyer/.conda/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sviyer/onmt-fresh/onmt/modules/SRU.py", line 601, in forward
    h, c = rnn(prevx, c0[i])
  File "/home/sviyer/.conda/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sviyer/onmt-fresh/onmt/modules/SRU.py", line 535, in forward
    u, input, self.bias, c0, mask_h
  File "/home/sviyer/onmt-fresh/onmt/modules/SRU.py", line 410, in forward
    stream=SRU_STREAM
  File "cupy/cuda/function.pyx", line 129, in cupy.cuda.function.Function.__call__ (cupy/cuda/function.cpp:3963)
  File "cupy/cuda/function.pyx", line 111, in cupy.cuda.function._launch (cupy/cuda/function.cpp:3600)
  File "cupy/cuda/driver.pyx", line 127, in cupy.cuda.driver.launchKernel (cupy/cuda/driver.cpp:2541)
  File "cupy/cuda/driver.pyx", line 62, in cupy.cuda.driver.check_status (cupy/cuda/driver.cpp:1446)
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_HANDLE: invalid resource handle
```

It runs fine with CUDA_VISIBLE_DEVICES=1 and then using gpuid=0, but this is a problem when im uding DataParallel. 

Is there any easy fix to this? Thanks!

**Comment by IdiosyncraticDragon** [comment]
Yes, SRU can only use one gpu, you can check the issue here https://github.com/taolei87/sru/issues/8

**Comment by sriniiyer** [comment]
Thanks! I'll follow up with them.
