### ISSUE TITLE
translate.py error with -n_best option (n > 1)

### ISSUE THREAD

**Issue by orina1123** [OpenNMT/OpenNMT-py#479]
This happens with **-n_best, n> 1** and **-verbose**.
```
$ python translate.py -model model.pt -src source.txt -n_best 10 -output pred10best.txt -replace_unk -verbose
Loading model parameters.
PRED SCORE: -6.3616

BEST HYP:
Traceback (most recent call last):
  File "translate.py", line 116, in <module>
    main()
  File "translate.py", line 97, in main
    output = trans.log(sent_number)
  File "/home/user/OpenNMT-py/onmt/translate/Translation.py", line 116, in log
    for score, sent in zip(self.pred_score, self.pred_sents):
AttributeError: 'Translation' object has no attribute 'pred_score'
```

**Comment by srush** [comment]
Good catch. Merged.
