### ISSUE TITLE
Sizes don't match error

### ISSUE THREAD

**Issue by HendrikStrobelt** [OpenNMT/OpenNMT-py#497]
using version: 1695edca82f35fc30c7d56904b903cef36528e58
Using python 3.6
using pytorch 0.1.12.post1

I was trying to train a simple model using defaults:
`python train.py -save_model data/model  -data data/data`
and ended up with (independent from using GPUs):

```
Traceback (most recent call last):
  File "train.py", line 348, in <module>
    main()
  File "train.py", line 344, in main
    train_model(model, train_dataset, valid_dataset, fields, optim, model_opt)
  File "train.py", line 168, in train_model
    train_stats = trainer.train(epoch, report_func)
  File "/data/hen/S2S/OpenNMT-py/onmt/Trainer.py", line 151, in train
    self.model(src, tgt, src_lengths, dec_state)
  File "/home/hen/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/hen/S2S/OpenNMT-py/onmt/Models.py", line 553, in forward
    context_lengths=lengths)
  File "/home/hen/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/hen/S2S/OpenNMT-py/onmt/Models.py", line 259, in forward
    input, context, state, context_lengths=context_lengths)
  File "/data/hen/S2S/OpenNMT-py/onmt/Models.py", line 463, in _run_forward_pass
    context_lengths=context_lengths)
  File "/home/hen/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/hen/S2S/OpenNMT-py/onmt/modules/GlobalAttention.py", line 172, in forward
    mask = sequence_mask(context_lengths)
  File "/data/hen/S2S/OpenNMT-py/onmt/Utils.py", line 23, in sequence_mask
    .lt(lengths.unsqueeze(1)))
RuntimeError: sizes do not match at /opt/conda/conda-bld/pytorch_1501971235237/work/pytorch-0.1.12/torch/lib/THC/generated/../THCTensorMathCompareT.cuh:65
```

**Comment by HendrikStrobelt** [comment]
used a way too old pytorch version -- sorry
