### ISSUE TITLE
Error in translation using trained model.

### ISSUE THREAD

**Issue by atebbifakhr** [OpenNMT/OpenNMT-py#505]
I trained the model successfully and run the command `python translate.py -model demo-model_epochX_PPL.pt -src data/src-test.txt -output pred.txt -replace_unk -verbose` for translation, but it occurred the following error:

<pre>Traceback (most recent call last):
  File "translate.py", line 141, in <module>
    main()
  File "translate.py", line 104, in main
    for batch in data_iter:
  File "/root/anaconda3/lib/python3.6/site-packages/torchtext/data/iterator.py", line 178, in __iter__
    self.train)
  File "/root/anaconda3/lib/python3.6/site-packages/torchtext/data/batch.py", line 22, in __init__
    setattr(self, name, field.process(batch, device=device, train=train))
  File "/root/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py", line 184, in process
    tensor = self.numericalize(padded, device=device, train=train)
  File "/root/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py", line 294, in numericalize
    arr = [numericalization_func(x) for x in arr]
  File "/root/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py", line 294, in <listcomp>
    arr = [numericalization_func(x) for x in arr]
  File "/root/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 389, in __float__
    raise TypeError("only 1-element tensors can be converted "
TypeError: only 1-element tensors can be converted to Python scalars</pre>
I guess this issue is related to torchtext 0.2.0 version, but if I downgrade my torchtext I couldn't train the model.

**Comment by JianyuZhan** [comment]
Yep, exactly, this line

```
arr = [numericalization_func(x) for x in arr]
```

did cause another problem that was a hindrance for us to upgrade to `0.2.0`, but it is fixed in `0.2.1`, I assume your problem should also be fixed. Please upgrade to `torchtext 0.2.1` and try again.

**Comment by atebbifakhr** [comment]
Yes, it works. Thanks!

**Comment by LeenaShekhar** [comment]
Hello @atebbifakhr 

I used the pre-trained model already provided but that throws the following error (it may be because the model and code are incompatible due to version issues):

python translate.py -model ../demo.rnn__acc_47.64_ppl_20.48_e13.pt -src data/src-test.txt -output pred.txt -replace_unk -verbose
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Loading model parameters.
Traceback (most recent call last):
  File "translate.py", line 141, in <module>
    main()
  File "translate.py", line 62, in main
    onmt.ModelConstructor.load_test_model(opt, dummy_opt.__dict__)
  File "/home/leena/Downloads/NMT/OpenNMT-py-master/onmt/ModelConstructor.py", line 124, in load_test_model
    use_gpu(opt), checkpoint)
  File "/home/leena/Downloads/NMT/OpenNMT-py-master/onmt/ModelConstructor.py", line 199, in make_base_model
    model.load_state_dict(checkpoint['model'])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 490, in load_state_dict
    .format(name))
KeyError: 'unexpected key "decoder.embeddings.emb_luts.0.weight" in state_dict'

Do you think you can share your model with me? It would be a great help. Also, how much time did it take you to train this model? Please mention your system specs as well.
