### ISSUE TITLE
error after epoch 1

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/OpenNMT-py#516]
not sure whether this is due to last commits or wrong version of torchtext (0.2.0 instead of 0.2.1 ?)

Epoch  1,  1400/   61; acc:  60.49; ppl:   7.92; 5325 src tok/s; 6375 tgt tok/s;   3592 s elapsed
Epoch  1,  1450/   61; acc:  60.85; ppl:   7.71; 5233 src tok/s; 6262 tgt tok/s;   3721 s elapsed
Train perplexity: 26.2815
Train accuracy: 46.1831
Loading valid dataset from baseline-1M.en-fr.valid.pt, number of examples: 987
Traceback (most recent call last):
  File "train.py", line 406, in <module>
    main()
  File "train.py", line 402, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 228, in train_model
    valid_stats = trainer.validate(valid_iter)
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/Trainer.py", line 246, in validate
    for batch in valid_iter:
  File "train.py", line 129, in __iter__
    for batch in self.cur_iter:
  File "/usr/local/lib/python3.5/dist-packages/torchtext/data/iterator.py", line 162, in __iter__
    self.init_epoch()
  File "/usr/local/lib/python3.5/dist-packages/torchtext/data/iterator.py", line 140, in init_epoch
    self.create_batches()
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/io/IO.py", line 337, in create_batches
    self.batch_size_fn):
  File "/usr/local/lib/python3.5/dist-packages/torchtext/data/iterator.py", line 274, in batch
    size_so_far = batch_size_fn(ex, len(minibatch), size_so_far)
TypeError: 'NoneType' object is not callable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook

**Comment by srush** [comment]
Yeah, could you try upgrading. The current code looks correct to me.

**Comment by srush** [comment]
Yeah, annoyingly they changed this behavior. 

In 0.2:

`def batch(data, batch_size, batch_size_fn=lambda new, count, sofar: count):`

In 0.2.1 

def batch(data, batch_size, batch_size_fn=None):

We pass in None thinking it's the default. We could hack around if you really really need 0.2.

**Comment by vince62s** [comment]
no, I upgraded and it's fine now.
