### ISSUE TITLE
preprocess failed on linux

### ISSUE THREAD

**Issue by cswhjiang** [OpenNMT/OpenNMT-py#521]
````
 python3.6 preprocess.py -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo

Extracting features...
 * number of source features: 0.
 * number of target features: 0.
Loading Fields object...
Building & saving training data...
 * divide corpus into shards and build dataset separately(shard_size = 0 bytes).
 * saving train data shard to data/demo.train.1.pt.
Building & saving vocabulary...
 * reloading data/demo.train.1.pt
Traceback (most recent call last):
  File "preprocess.py", line 188, in <module>
    main()
  File "preprocess.py", line 181, in main
    build_save_vocab(train_dataset_files, fields, opt)
  File "preprocess.py", line 158, in build_save_vocab
    opt.tgt_words_min_frequency)
  File "/data1/home/wenhaojiang/OpenNMT-py-master/onmt/io/IO.py", line 262, in build_vocab
    min_freq=tgt_words_min_frequency)
  File "/data1/home/wenhaojiang/OpenNMT-py-master/onmt/io/IO.py", line 221, in _build_field_vocab
    tok for tok in [field.unk_token, field.pad_token, field.init_token,
AttributeError: 'Field' object has no attribute 'unk_token'
````

**Comment by KelleyYin** [comment]
Which version of torchtext are you using ? I think you can update the torchtext  .

**Comment by cswhjiang** [comment]
0.1.1.

**Comment by KelleyYin** [comment]
Are you sure the same source code of OpenNMT-py in between mac and linux ? 
The nearly version is required torchtext >= 0.2.1, which can find from requirements.txt.

**Comment by cswhjiang** [comment]
Installing torchtext-0.2.0 solves this problem. Thanks!
