### ISSUE TITLE
KeyError: 'src_map' when using the 'train_from' option

### ISSUE THREAD

**Issue by ykasimov** [OpenNMT/OpenNMT-py#529]
Hello,
when I try to continue training I get the following error:

```
Traceback (most recent call last):
  File "./train.py", line 408, in <module>
    main()
  File "./train.py", line 402, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "./train.py", line 219, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/username/PycharmProjects/OpenNMT_PyTorch/onmt/Trainer.py", line 199, in train
    for i, batch_ in enumerate(train_iter):
  File "./train.py", line 129, in __iter__
    for batch in self.cur_iter:
  File "/home/username/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchtext/data/iterator.py", line 180, in __iter__
    self.train)
  File "/home/username/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchtext/data/batch.py", line 21, in __init__
    batch = [x.__dict__[name] for x in data]
  File "/home/username/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchtext/data/batch.py", line 21, in <listcomp>
    batch = [x.__dict__[name] for x in data]
KeyError: 'src_map'
```

This is the command I use to start training:
`./train.py -encoder_type brnn -decoder_type rnn -layers 10 -rnn_size 800 -rnn_type SRU -data my_data/corpus -save_model model/model_1.6 -gpuid 0 -epochs 14 -optim adam -report_every 1000 -exp 2 -word_vec_size 500 -learning_rate 0.001 -global_attention mlp -input_feed 0 -start_epoch 2 -train_from model/model_1.6_acc_63.48_ppl_6.59_e1.pt`

I use the same data as before. Could you help me with it, please?

**Comment by Hellokitty8** [comment]
I got the same error (KeyError: 'src_map') when continuous training the model.

File "train.py", line 406, in <module>
    main()
  File "train.py", line 402, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 219, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/Users/jiawang/Downloads/OpenNMT-py-master/onmt/Trainer.py", line 199, in train
    for i, batch_ in enumerate(train_iter):
  File "train.py", line 129, in __iter__
    for batch in self.cur_iter:
  File "/Users/jiawang/anaconda2/envs/python_3_5/lib/python3.5/site-packages/torchtext/data/iterator.py", line 180, in __iter__
    self.train)
  File "/Users/jiawang/anaconda2/envs/python_3_5/lib/python3.5/site-packages/torchtext/data/batch.py", line 21, in __init__
    batch = [x.__dict__[name] for x in data]
  File "/Users/jiawang/anaconda2/envs/python_3_5/lib/python3.5/site-packages/torchtext/data/batch.py", line 21, in <listcomp>
    batch = [x.__dict__[name] for x in data]
KeyError: 'src_map'


This is my command of the training: python train.py **-train_from** en-es-model_acc_83.47_ppl_1.61_e9.pt **-data** data/en-es **-save_model** en-es-model **-epochs** 10  
 Could you help me with it, please!

**Comment by ykasimov** [comment]
I am not sure if this is a correct fix, but I have created a pull request: https://github.com/OpenNMT/OpenNMT-py/pull/530

**Comment by srush** [comment]
Merged.
