### ISSUE TITLE
Translation error 

### ISSUE THREAD

**Issue by Tina-19** [OpenNMT/OpenNMT-py#555]
I get the following error during translation, for text summarization after printing the first two predictions:

`python translate.py -model model/model_acc_32.21_ppl_46.51_e16.pt -src data/src-test.txt -output pred.txt -beam_size 10 -replace_unk -dynamic_dict -share_vocab -verbose -gpu 0`
 
Traceback (most recent call last):
  File "translate.py", line 141, in <module>
    main()
  File "translate.py", line 104, in main
    for batch in data_iter:
  File "/home/altaml/anaconda3/lib/python3.6/site-packages/torchtext/data/iterator.py", line 180, in __iter__
    self.train)
  File "/home/altaml/anaconda3/lib/python3.6/site-packages/torchtext/data/batch.py", line 22, in __init__
    setattr(self, name, field.process(batch, device=device, train=train))
  File "/home/altaml/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py", line 187, in process
    tensor = self.numericalize(padded, device=device, train=train)
  File "/home/altaml/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py", line 309, in numericalize
    arr = self.tensor_type(arr)
RuntimeError: given sequence has an invalid size of dimension 2: 0

Is translate.py compatible with torchtext version 0.2.1?

**Comment by vardaan123** [comment]
@Tina-19 Could you please tell how did you resolve this? I am using PyTorch 0.3.1 with Torchtext 0.2.3
