### ISSUE TITLE
Overriding loss compute

### ISSUE THREAD

**Issue by thecortex** [OpenNMT/OpenNMT-py#558]
I am getting this error which is apparently because I have written my own hierarchical softmax class.

```
$ python train.py -data data/demo -save_model demo-model -ext-hsm True
Loading train dataset from data/demo.train.1.pt, number of examples: 100
 * vocabulary size. source = 541; target = 104
Building model...
  Progress Huffman Coding: |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% Complete
Huffman Coding Completed in 0 Seconds
Intializing model parameters.
NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(541, 500, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(500, 500, num_layers=2, dropout=0.3)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(104, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(1000, 500)
        (1): LSTMCell(500, 500)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=500, out_features=500)
      (linear_out): Linear(in_features=1000, out_features=500)
      (sm): Softmax()
      (tanh): Tanh()
    )
  )
  (generator): Sequential(
    (0): HierarchicalSoftmax(
      (linear): Linear(in_features=500, out_features=99)
      (output): Linear(in_features=99, out_features=1)
    )
  )
)
* number of parameters: 10138199
encoder:  4278500
decoder:  5859699
Making optimizer for training.

Start training...
 * number of epochs: 13, starting from Epoch 1
 * batch size: 64

Loading train dataset from data/demo.train.1.pt, number of examples: 100
/Users/mac/Documents/GitHub/OpenNMT-py/onmt/modules/GlobalAttention.py:177: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  align_vectors = self.sm(align.view(batch*targetL, sourceL))
Traceback (most recent call last):
  File "train.py", line 404, in <module>
    main()
  File "train.py", line 400, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 223, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/onmt/Trainer.py", line 165, in train
    report_stats, normalization)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/onmt/Trainer.py", line 296, in _gradient_accumulation
    trunc_size, self.shard_size, normalization)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/onmt/Loss.py", line 122, in sharded_compute_loss
    loss, stats = self._compute_loss(batch, **shard)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/onmt/Loss.py", line 187, in _compute_loss
    scores = self.generator(self._bottle(output))
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/extensions/hierarchical_softmax.py", line 63, in forward
    cls = self.output(ret_tensor)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 835, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: addmm(): argument 'mat1' (position 1) must be Variable, not torch.DoubleTensor
```

**Comment by thecortex** [comment]
I can trace it back up to here:
```
    def _compute_loss(self, batch, output, target):
        print(self._bottle(output))
        scores = self.generator(self._bottle(output))
```
However, I am not sure what is the best way to go about this. Moreover, I can see dimensions passes to self.genertor to be 72 x 500 where 500 is RNN Hidden Output fed into my HSMClass, and 72 is number of Internal Nodes in HSM and this gets mapped to 1 for Class Output.
```
$ python train.py -data data/demo -save_model demo-model -ext-hsm True
Loading train dataset from data/demo.train.1.pt, number of examples: 100
 * vocabulary size. source = 541; target = 104
Building model...
  Progress Huffman Coding: |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% Complete
Huffman Coding Completed in 0 Seconds
Intializing model parameters.
NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(541, 500, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(500, 500, num_layers=2, dropout=0.3)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(104, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(1000, 500)
        (1): LSTMCell(500, 500)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=500, out_features=500)
      (linear_out): Linear(in_features=1000, out_features=500)
      (sm): Softmax()
      (tanh): Tanh()
    )
  )
  (generator): Sequential(
    (0): HierarchicalSoftmax(
      (linear): Linear(in_features=500, out_features=99)
      (output): Linear(in_features=99, out_features=1)
    )
  )
)
* number of parameters: 10138199
encoder:  4278500
decoder:  5859699
Making optimizer for training.

Start training...
 * number of epochs: 13, starting from Epoch 1
 * batch size: 64

Loading train dataset from data/demo.train.1.pt, number of examples: 100
/Users/mac/Documents/GitHub/OpenNMT-py/onmt/modules/GlobalAttention.py:177: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  align_vectors = self.sm(align.view(batch*targetL, sourceL))
Variable containing:
-0.2668  0.0636 -0.1920  ...  -0.1077  0.2285  0.0000
-0.0000  0.0000 -0.0000  ...  -0.0000  0.2408  0.0000
-0.0000  0.1071 -0.1588  ...  -0.0785  0.2479  0.0000
          ...             ⋱             ...          
-0.3020  0.0000 -0.0000  ...  -0.0562  0.1615  0.0154
-0.2117  0.1906 -0.1606  ...   0.0354  0.0679  0.0842
-0.2934  0.1914 -0.1620  ...   0.0497  0.1165  0.0691
[torch.FloatTensor of size 72x500]

Traceback (most recent call last):
  File "train.py", line 406, in <module>
    main()
  File "train.py", line 402, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 224, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/onmt/Trainer.py", line 165, in train
    report_stats, normalization)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/onmt/Trainer.py", line 296, in _gradient_accumulation
    trunc_size, self.shard_size, normalization)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/onmt/Loss.py", line 122, in sharded_compute_loss
    loss, stats = self._compute_loss(batch, **shard)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/onmt/Loss.py", line 188, in _compute_loss
    scores = self.generator(self._bottle(output))
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/extensions/hierarchical_softmax.py", line 63, in forward
    cls = self.output(ret_tensor)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 835, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: addmm(): argument 'mat1' (position 1) must be Variable, not torch.DoubleTensor

```

**Comment by thecortex** [comment]
I have traced over to here:
```
            self.criterion = nn.NLLLoss(weight, size_average=False)
```
I have also reviewed loss.py and it doesn't indicate how to make make_compute_less read my new loss, or is it overridden by simply customizing in make_compute_loss? Do I still have to? I apparently want to keep the default behavior.

**Comment by thecortex** [comment]
The error hs become:

```
$ python train.py -data data/demo -save_model demo-model -ext-hsm True
Loading train dataset from data/demo.train.1.pt, number of examples: 100
 * vocabulary size. source = 541; target = 104
Building model...
  Progress Huffman Coding: |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% Complete
Huffman Coding Completed in 0 Seconds
500 <torchtext.vocab.Vocab object at 0x113dd6dd8>
Intializing model parameters.
NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(541, 500, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(500, 500, num_layers=2, dropout=0.3)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(104, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(1000, 500)
        (1): LSTMCell(500, 500)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=500, out_features=500)
      (linear_out): Linear(in_features=1000, out_features=500)
      (sm): Softmax()
      (tanh): Tanh()
    )
  )
  (generator): Sequential(
    (0): HierarchicalSoftmax(
      (linear): Linear(in_features=500, out_features=99)
      (output): Linear(in_features=99, out_features=104)
    )
  )
)
* number of parameters: 10148499
encoder:  4278500
decoder:  5869999
Making optimizer for training.

Start training...
 * number of epochs: 13, starting from Epoch 1
 * batch size: 64

Loading train dataset from data/demo.train.1.pt, number of examples: 100
/Users/mac/Documents/GitHub/OpenNMT-py/onmt/modules/GlobalAttention.py:177: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  align_vectors = self.sm(align.view(batch*targetL, sourceL))
Traceback (most recent call last):
  File "train.py", line 406, in <module>
    main()
  File "train.py", line 402, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 224, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/onmt/Trainer.py", line 165, in train
    report_stats, normalization)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/onmt/Trainer.py", line 296, in _gradient_accumulation
    trunc_size, self.shard_size, normalization)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/onmt/Loss.py", line 122, in sharded_compute_loss
    loss, stats = self._compute_loss(batch, **shard)
  File "/Users/mac/Documents/GitHub/OpenNMT-py/onmt/Loss.py", line 204, in _compute_loss
    loss = self.criterion(scores, gtruth)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 147, in forward
    self.ignore_index, self.reduce)
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1049, in nll_loss
    return torch._C._nn.nll_loss(input, target, weight, size_average, ignore_index, reduce)
RuntimeError: weight tensor should be defined either for all 1 classes or no classes but got weight tensor of shape: [104] at /Users/soumith/minicondabuild3/conda-bld/pytorch_1512381214802/work/torch/lib/THNN/generic/ClassNLLCriterion.c:30
```

**Comment by thecortex** [comment]
Why am I getting this error?
```
  File "/Users/mac/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1049, in nll_loss
    return torch._C._nn.nll_loss(input, target, weight, size_average, ignore_index, reduce)
RuntimeError: weight tensor should be defined either for all 1 classes or no classes but got weight tensor of shape: [104] at /Users/soumith/minicondabuild3/conda-bld/pytorch_1512381214802/work/torch/lib/THNN/generic/ClassNLLCriterion.c:30
```

**Comment by thecortex** [comment]
Finally I have managed to override the Loss Compute, but I see something weird that's causing a bad error for me that I am still debugging for hours:
```
        print(scores.size(), gtruth.size())
        exit(0)
        loss = self.criterion(scores, gtruth)
```
So I try to print the scores and gtruth, but their dimensions are not in accordanc at all ...
```
torch.Size([104, 1]) torch.Size([72])
```

**Comment by srush** [comment]
Hi, 

Looks like you figured most of it out. However it is hard for me to help without more detail.

Could you let us know what scores and gtruth are supposed to represent?

**Comment by thecortex** [comment]
That's how I have overriden compute loss:
```
def make_loss_compute(model, tgt_vocab, opt):
    """
    This returns user-defined LossCompute object, which is used to
    compute loss in train/validate process. You can implement your
    own *LossCompute class, by subclassing LossComputeBase.
    """
    if opt.copy_attn:
        compute = onmt.modules.CopyGeneratorLossCompute(
            model.generator, tgt_vocab, opt.copy_attn_force)
    if opt.ext_hsm:
        compute = HSMLossCompute(
            model.generator, tgt_vocab
        )
    else:
        compute = onmt.Loss.NMTLossCompute(
            model.generator, tgt_vocab,
            label_smoothing=opt.label_smoothing)

    if use_gpu(opt):
        compute.cuda()

    return compute
```

**Comment by thecortex** [comment]
> Could you let us know what scores and gtruth are supposed to represent?
scores are outputs from forward in my Module Layers
and gtruth is target y and by the way that's the default naming using in default NMTLoss:
```
        loss = self.criterion(scores, gtruth)
```
https://github.com/OpenNMT/OpenNMT-py/blob/5db22421b78e5832795f4ac2137d174a3229d2cf/onmt/Loss.py#L202

**Comment by thecortex** [comment]
However, I have found out that the problem is that forward returns dimensions as per the input training dictionary while compute less works on dimensions depending on batch size targets ground truth, so I believe there should be  way to work only on the shard size inside forward.
