### ISSUE TITLE
KeyError: 'alignment' when retrain models using -train_from

### ISSUE THREAD

**Issue by qfzhu** [OpenNMT/OpenNMT-py#559]
here is my train command:
python train.py -train_from demo_acc_9.11_ppl_1617.95_e3.pt -save_model pre -gpu
id 1 -data data/demo

Then i got this error:
```
Loading train dataset from data/demo.train.1.pt, number of examples: 10000
Traceback (most recent call last):
  File "train.py", line 406, in <module>
    main()
  File "train.py", line 402, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 219, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/users2/qfzhu/nlg/exp/master/onmt/Trainer.py", line 199, in train
    for i, batch_ in enumerate(train_iter):
  File "train.py", line 129, in __iter__
    for batch in self.cur_iter:
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/torchtext/data/iterator.py", line 180, in __iter__
    self.train)
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/torchtext/data/batch.py", line 21, in __init__
    batch = [x.__dict__[name] for x in data]
KeyError: 'alignment'
```

**Comment by JianyuZhan** [comment]
Did you use the same codebase before/after the `train_from`?  Pls update the code and try it again.
