### ISSUE TITLE
Error in replicating the example 

### ISSUE THREAD

**Issue by datduong** [OpenNMT/OpenNMT-py#564]
Hi, I am replicating the example posted in the README, 

I was able to run the pre-processing step. But I got the error (see below) in training step. It seems this is problem with pytorch library. I am using pytorch 0.1.1. Please let me know how to fix this problem. Thanks. 

python train.py -gpuid 0 -data data/demo -save_model data/demo-model

Loading train dataset from data\demo.train.1.pt, number of examples: 10000
 * vocabulary size. source = 24997; target = 35820
Building model...
Intializing model parameters.
NMTModel (
  (encoder): RNNEncoder (
    (embeddings): Embeddings (
      (make_embedding): Sequential (
        (emb_luts): Elementwise (
          (0): Embedding(24997, 500, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(500, 500, num_layers=2, dropout=0.3)
  )
  (decoder): InputFeedRNNDecoder (
    (embeddings): Embeddings (
      (make_embedding): Sequential (
        (emb_luts): Elementwise (
          (0): Embedding(35820, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout (p = 0.3)
    (rnn): StackedLSTM (
      (dropout): Dropout (p = 0.3)
      (layers): ModuleList (
        (0): LSTMCell(1000, 500)
        (1): LSTMCell(500, 500)
      )
    )
    (attn): GlobalAttention (
      (linear_in): Linear (500 -> 500)
      (linear_out): Linear (1000 -> 500)
      (sm): Softmax ()
      (tanh): Tanh ()
    )
  )
  (generator): Sequential (
    (0): Linear (500 -> 35820)
    (1): LogSoftmax ()
  )
)
* number of parameters: 58120320
encoder:  16506500
decoder:  41613820
Making optimizer for training.

Start training...
 * number of epochs: 13, starting from Epoch 1
 * batch size: 64

Loading train dataset from data\demo.train.1.pt, number of examples: 10000
Traceback (most recent call last):
  File "train.py", line 417, in <module>
    main()
  File "train.py", line 409, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 231, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "C:\Users\dat\Desktop\OpenNMT-py\onmt\Trainer.py", line 174, in train
    report_stats, normalization)
  File "C:\Users\dat\Desktop\OpenNMT-py\onmt\Trainer.py", line 300, in _gradient_accumulation
    self.model(src, tgt, src_lengths, dec_state)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\dat\Desktop\OpenNMT-py\onmt\Models.py", line 557, in forward
    context_lengths=lengths)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\dat\Desktop\OpenNMT-py\onmt\Models.py", line 262, in forward
    input, context, state, context_lengths=context_lengths)
  File "C:\Users\dat\Desktop\OpenNMT-py\onmt\Models.py", line 466, in _run_forward_pass
    context_lengths=context_lengths)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\dat\Desktop\OpenNMT-py\onmt\modules\GlobalAttention.py", line 172, in forward
    mask = sequence_mask(context_lengths)
  File "C:\Users\dat\Desktop\OpenNMT-py\onmt\Utils.py", line 23, in sequence_mask
    .lt(lengths.unsqueeze(1)))
RuntimeError: sizes do not match at d:\downloads\pytorch-master-1\torch\lib\thc\generated\../THCTensorMathCompareT.cuh:65

**Comment by srush** [comment]
Unfortunately we no longer support below 0.2 . Pytorch has been changing quite rapidly. 

Sorry about that.
