### ISSUE TITLE
preprocess wmt15 (news-commentary v10) gives assertion error (no. of lines)

### ISSUE THREAD

**Issue by xforceco** [OpenNMT/OpenNMT-py#569]
`wc -l data/wmt15-de-en/news-commentary-v10.de-en.en`
216190 data/wmt15-de-en/news-commentary-v10.de-en.en
`wc -l data/wmt15-de-en/news-commentary-v10.de-en.de`
216190 data/wmt15-de-en/news-commentary-v10.de-en.de

`python preprocess.py -train_src data/wmt15-de-en/news-commentary-v10.de-en.en -train_tgt data/wmt15-de-en/news-commentary-v10.de-en.de -valid_src data/wmt15-de-en/newstest2013.en -valid_tgt data/wmt15-de-en/newstest2013.de -save_data data/preprocess`

Error log:
> Extracting features...
number of source features: 0.
number of target features: 0.
Building `Fields` object...
Building & saving training data...
Warning. The corpus data/wmt15-de-en/news-commentary-v10.de-en.en is larger than 10M bytes, you can set '-max_shard_size' to process it by small shards to use less memory.
Traceback (most recent call last):
  File "preprocess.py", line 193, in <module>
    main()
  File "preprocess.py", line 183, in main
    train_dataset_files = build_save_dataset('train', fields, opt)
  File "preprocess.py", line 128, in build_save_dataset
    corpus_type, opt)
  File "preprocess.py", line 99, in build_save_text_dataset_in_shards
    dynamic_dict=opt.dynamic_dict)
  File "/ssdisk/hlfungaa/OpenNMT-py/onmt/io/TextDataset.py", line 56, in __init__
    zip(src_examples_iter, tgt_examples_iter))
  File "/ssdisk/hlfungaa/OpenNMT-py/onmt/io/TextDataset.py", line 329, in __iter__
    "Two corpuses must have same number of lines!")
AssertionError: Two corpuses must have same number of lines!

**Comment by xforceco** [comment]
trying tokenizer before preprocess.
