### ISSUE TITLE
TypeError: 'Example' object does not support indexing in tools/embeddings_to_torch.py

### ISSUE THREAD

**Issue by ttpro1995** [OpenNMT/OpenNMT-py#631]
- I use [Glove](https://github.com/stanfordnlp/GloVe) official code to create word vector small_train.src.wordvector.txt 
- embedding was directory intended for output
- demo.train.1.pt was create by [preprocess.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/preprocess.py) as I follow Quickstart guide in README.md

```
 python tools/embeddings_to_torch.py  -emb_file small_train.src.wordvector.txt -output_file embedding -dict_file demo.train.1.pt
You are using pip version 9.0.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 9.0.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "tools/embeddings_to_torch.py", line 124, in <module>
    main()
  File "tools/embeddings_to_torch.py", line 87, in main
    enc_vocab, dec_vocab = get_vocabs(opt.dict_file)
  File "tools/embeddings_to_torch.py", line 20, in get_vocabs
    if vocab[0] == 'src':
TypeError: 'Example' object does not support indexing

```

**Comment by vince62s** [comment]
I think this is fixed
