### ISSUE TITLE
How to use the -tgt flag?

### ISSUE THREAD

**Issue by nikhilweee** [OpenNMT/OpenNMT-py#656]
The `-tgt` flag is broken. The following arguments work perfectly fine without the `-tgt` flag.

```
$ python3 translate.py -model data/model_attn_best.pt -src data/test.cm -output data/pred.cm -replace_unk -verbose -attn_debug -tgt data/test.nl
Loading model parameters.
average src size 7.1683168316831685 606
/data/projects/opennmt-py/onmt/modules/GlobalAttention.py:176: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to inc
lude dim=X as an argument.
  align_vectors = self.sm(align.view(batch*targetL, sourceL))
/data/projects/opennmt-py/onmt/modules/CopyGenerator.py:91: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to includ
e dim=X as an argument.
  prob = F.softmax(logits)
Traceback (most recent call last):
  File "translate.py", line 166, in <module>
    main()
  File "translate.py", line 114, in main
    batch_data = translator.translate_batch(batch, data)
  File "/data/projects/opennmt-py/onmt/translate/Translator.py", line 172, in translate_batch
    ret["gold_score"] = self._run_target(batch, data)
  File "/data/projects/opennmt-py/onmt/translate/Translator.py", line 217, in _run_target
    out = self.model.generator.forward(dec)
TypeError: forward() missing 2 required positional arguments: 'attn' and 'src_map'
```

**Comment by sebastianGehrmann** [comment]
The flag is currently not implemented for models with `copy_attention` since it is not obvious how to calculate the correct scores. However, you can still translate without that flag.

**Comment by eeric** [comment]
make OpenNMT project audio list and sentences text list, as following:
https://github.com/eeric/OpenNMT-py-make-tgt-train.txt/blob/master/openNMT_make_label.py
