### ISSUE TITLE
SRU cupy.cuda error

### ISSUE THREAD

**Issue by JustinLin610** [OpenNMT/OpenNMT-py#665]
I run the model with SRU, and I have already passed the check_sru_requirements, but I met this problem:

`Traceback (most recent call last):
  File "train.py", line 438, in <module>
    main()
  File "train.py", line 430, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 252, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/linjunyang/OpenNMT-py/onmt/Trainer.py", line 178, in train
    report_stats, normalization)
  File "/home/linjunyang/OpenNMT-py/onmt/Trainer.py", line 306, in _gradient_accumulation
    self.model(src, tgt, src_lengths, dec_state)
  File "/home/linjunyang/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/linjunyang/OpenNMT-py/onmt/Models.py", line 587, in forward
    enc_final, memory_bank = self.encoder(src, lengths)
  File "/home/linjunyang/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/linjunyang/OpenNMT-py/onmt/Models.py", line 150, in forward
    memory_bank, encoder_final = self.rnn(packed_emb, encoder_state)
  File "/home/linjunyang/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/linjunyang/OpenNMT-py/onmt/modules/SRU.py", line 620, in forward
    h, c = rnn(prevx, c0[i])
  File "/home/linjunyang/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/linjunyang/OpenNMT-py/onmt/modules/SRU.py", line 534, in forward
    u, input, self.bias, c0, mask_h
  File "/home/linjunyang/OpenNMT-py/onmt/modules/SRU.py", line 409, in forward
    stream=SRU_STREAM
  File "cupy/cuda/function.pyx", line 143, in cupy.cuda.function.Function.__call__
  File "cupy/cuda/function.pyx", line 125, in cupy.cuda.function._launch
  File "cupy/cuda/driver.pyx", line 184, in cupy.cuda.driver.launchKernel
  File "cupy/cuda/driver.pyx", line 72, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_HANDLE: invalid resource handle`

Is there any solution to this problem? Thanks!

**Comment by vince62s** [comment]
closing, reopen if needed.
