### ISSUE TITLE
Need help, getting RuntimeError

### ISSUE THREAD

**Issue by yelwinsoe** [OpenNMT/OpenNMT-py#683]
I am trying image to text, trying to create my own dataset and train it, in training state I am getting an error.
Do I need a lot of data to be able to test?
Because I only have like 10 image and just want to make sure I can train it first before collecting lots of data.

RuntimeError: Given groups=1, weight[64, 3, 3, 3], so expected input[4, 4, 47, 347] to have 3 channels, but got 4 channels instead

My machine.

Ubuntu 16.04
Python 3.6.3
torch (0.3.0.post4)

The command I use.
python train.py -model_type img -data data/im2text/shn/test -save_model data/im2text/shn/demo-model -gpuid 0

Thanks.

**Comment by da03** [comment]
Thanks for reporting this bug! Can you post more detailed error message? (which line gives the error) And it'll be great if you can share the data with me, I'll be able to directly debug then.

**Comment by yelwinsoe** [comment]
Here's the full error message.

Start training...
 * number of epochs: 13, starting from Epoch 1
 * batch size: 20

Loading train dataset from data/im2text/shn/test.train.pt, number of examples: 4
Traceback (most recent call last):
  File "train.py", line 502, in <module>
    main()
  File "train.py", line 494, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 257, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/evvo/Desktop/OpenNMT-py/onmt/Trainer.py", line 178, in train
    report_stats, normalization)
  File "/home/evvo/Desktop/OpenNMT-py/onmt/Trainer.py", line 306, in _gradient_accumulation
    self.model(src, tgt, src_lengths, dec_state)
  File "/home/evvo/Desktop/virt_env/py3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/evvo/Desktop/OpenNMT-py/onmt/Models.py", line 585, in forward
    enc_final, memory_bank = self.encoder(src, lengths)
  File "/home/evvo/Desktop/virt_env/py3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/evvo/Desktop/OpenNMT-py/onmt/modules/ImageEncoder.py", line 58, in forward
    input = F.relu(self.layer1(input[:, :, :, :]-0.5), True)
  File "/home/evvo/Desktop/virt_env/py3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/evvo/Desktop/virt_env/py3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 277, in forward
    self.padding, self.dilation, self.groups)
  File "/home/evvo/Desktop/virt_env/py3/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: Given groups=1, weight[64, 3, 3, 3], so expected input[4, 4, 47, 347] to have 3 channels, but got 4 channels instead

**Comment by shantanu778** [comment]
Loading train dataset from data/demo.train.1.pt, number of examples: 10000
/home/shantu/Downloads/OpenNMT-py-master/onmt/Optim.py:125: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  clip_grad_norm(self.params, self.max_grad_norm)
Traceback (most recent call last):
  File "train.py", line 502, in <module>
    main()
  File "train.py", line 494, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 257, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/shantu/Downloads/OpenNMT-py-master/onmt/Trainer.py", line 178, in train
    report_stats, normalization)
  File "/home/shantu/Downloads/OpenNMT-py-master/onmt/Trainer.py", line 311, in _gradient_accumulation
    trunc_size, self.shard_size, normalization)
  File "/home/shantu/Downloads/OpenNMT-py-master/onmt/Loss.py", line 124, in sharded_compute_loss
    loss.div(normalization).backward(retain_graph=True)
  File "/home/shantu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/shantu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: $ Torch: not enough memory: you tried to allocate 0GB. Buy new RAM! at /opt/conda/conda-bld/pytorch_1524577177097/work/aten/src/TH/THGeneral.c:218

...................I also facing this kind of problem.......................

**Comment by steveatgit** [comment]
I also meet this issue when I translate image to text, my command is：
`python translate.py -data_type img -model models_image/demo-model_step_25000.pt -src_dir data/im2text/images -src data/im2text/src-test.txt -output testout/image/pred.txt -max_length 150 -beam_size 5 -gpu 0 -verbose`

**the error log is:**
Traceback (most recent call last):
  File "translate.py", line 37, in <module>
    main(opt)
  File "translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/data1/minisearch/upload/quwei3/OpenNMT-py/onmt/translate/translator.py", line 191, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/data1/minisearch/upload/quwei3/OpenNMT-py/onmt/translate/translator.py", line 295, in translate_batch
    return self._translate_batch(batch, data)
  File "/data1/minisearch/upload/quwei3/OpenNMT-py/onmt/translate/translator.py", line 595, in _translate_batch
    batch, data_type)
  File "/data1/minisearch/upload/quwei3/OpenNMT-py/onmt/translate/translator.py", line 305, in _run_encoder
    src, src_lengths)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/minisearch/upload/quwei3/OpenNMT-py/onmt/encoders/image_encoder.py", line 60, in forward
    src = F.relu(self.layer1(src[:, :, :, :] - 0.5), True)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 1, 3, 3], expected input[30, 3, 160, 600] to have 1 channels, but got 3 channels instead
