### ISSUE TITLE
got an unexpected keyword argument 'dim'

### ISSUE THREAD

**Issue by gaoshan2006** [OpenNMT/OpenNMT-py#691]
I got this error when running the demo:   " python train.py -data data/demo -save_model demo-model" 
Who can help me ? Thanks!!!

Loading train dataset from data/demo.train.1.pt, number of examples: 10000
 * vocabulary size. source = 24997; target = 35820
Building model...
Traceback (most recent call last):
  File "train.py", line 502, in <module>
    main()
  File "train.py", line 486, in main
    model = build_model(model_opt, opt, fields, checkpoint)
  File "train.py", line 369, in build_model
    use_gpu(opt), checkpoint)
  File "/opt/DL/OpenNMT-py/onmt/ModelConstructor.py", line 184, in make_base_model
    decoder = make_decoder(model_opt, tgt_embeddings)
  File "/opt/DL/OpenNMT-py/onmt/ModelConstructor.py", line 104, in make_decoder
    opt.reuse_copy_attn)
  File "/opt/DL/OpenNMT-py/onmt/Models.py", line 272, in __init__
    attn_type=attn_type
  File "/opt/DL/OpenNMT-py/onmt/modules/GlobalAttention.py", line 79, in __init__
    self.sm = nn.Softmax(dim=-1)
TypeError: __init__() got an unexpected keyword argument 'dim'

**Comment by gaoshan2006** [comment]
My OS is Ubuntu 16.04,   and pytorch is : 0.1.12,    CUDA 8,  cudnn: 5.1.5

**Comment by gaoshan2006** [comment]
I find there are some changes in the latest code.  I compare  the present OpenNMT-py/onmt/modules/GlobalAttention.py with the file of 2 weeks ago, where "self.sm = nn.Softmax()" was used in the past. And I verify the version of 2 week ago could work.  Thanks

**Comment by sebastianGehrmann** [comment]
Please update your pytorch version, then it should run again.

**Comment by gaoshan2006** [comment]
pytorch is : 0.1.12.    The OpenNMT-py that I downloaded 2 weeks ago could work now
