### ISSUE TITLE
Set different hidden sizes for encoder and decoder

### ISSUE THREAD

**Issue by freesunshine0316** [OpenNMT/OpenNMT-py#701]
Hi, 

   I tried to build an attention-based seq-to-seq model, which has a bidirectional LSTM encoder with 500 hidden units for both directions and an LSTM decoder with 500 hidden units. I tried using the "-encoder_type brnn -brnn_merge sum -hidden_size 500" options, but the resulting bidirectional LSTM encoder only has 250 hidden units.

**Comment by srush** [comment]
Do you mean that it has 250 forward and 250 backwards?

**Comment by freesunshine0316** [comment]
Yes, the resulting model is exactly as you described. However, I want one that has 500 for both forward and backward, respectively. How can I get that?

**Comment by freesunshine0316** [comment]
I asked a person who used it before. He mentioned to me that one previous version of OpenNMT does support the configuration I want, but the current version seems not.

**Comment by da03** [comment]
Sorry I'm a little confused. Why not set encoder rnn size to 1000? Then you'll get 500 for forward and 500 for backward.

**Comment by freesunshine0316** [comment]
But the decoder will have 1000 units, while I want the decoder to have 500 units too. For fair comparison.

**Comment by freesunshine0316** [comment]
@da03 I can't find a way to set separate size for encoder and decoder now. It seems that the current OpenNMT does not support that.

**Comment by da03** [comment]
I see, now we don't support using different encoder and decoder rnn sizes. I haven't tested the below workaround, but i think you can hard code that in a similar way: https://github.com/OpenNMT/OpenNMT-py/blob/0ecec8b4c16fdec7d8ce2646a0ea47ab6535d308/onmt/ModelConstructor.py#L97 to pass 500 instead of opt.rnn_size, and https://github.com/OpenNMT/OpenNMT-py/blob/0ecec8b4c16fdec7d8ce2646a0ea47ab6535d308/onmt/Models.py#L168 to be `500 * num_layers` and https://github.com/OpenNMT/OpenNMT-py/blob/0ecec8b4c16fdec7d8ce2646a0ea47ab6535d308/onmt/Models.py#L182 to be `return F.relu(result).view(size[0], size[1], -1)`. For training pass rnn size to be `1000` and add flag `-use_bridge.`

**Comment by freesunshine0316** [comment]
Traceback (most recent call last):
  File "train.py", line 502, in <module>
    main()
  File "train.py", line 494, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 257, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/mnt/disk0/linfeng/OpenNMT-py/onmt/Trainer.py", line 178, in train
    report_stats, normalization)
  File "/mnt/disk0/linfeng/OpenNMT-py/onmt/Trainer.py", line 306, in _gradient_accumulation
    self.model(src, tgt, src_lengths, dec_state)
  File "/home/linfeng/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/disk0/linfeng/OpenNMT-py/onmt/Models.py", line 592, in forward
    memory_lengths=lengths)
  File "/home/linfeng/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/disk0/linfeng/OpenNMT-py/onmt/Models.py", line 313, in forward
    tgt, memory_bank, state, memory_lengths=memory_lengths)
  File "/mnt/disk0/linfeng/OpenNMT-py/onmt/Models.py", line 494, in _run_forward_pass
    rnn_output, hidden = self.rnn(decoder_input, hidden)
  File "/home/linfeng/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/disk0/linfeng/OpenNMT-py/onmt/modules/StackedRNN.py", line 24, in forward
    h_1_i, c_1_i = layer(input, (h_0[i], c_0[i]))
  File "/home/linfeng/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/linfeng/anaconda2/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 615, in forward
    self.bias_ih, self.bias_hh,
  File "/home/linfeng/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 27, in LSTMCell
    hgates = F.linear(hidden[0], w_hh)
  File "/home/linfeng/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 837, in linear
    output = input.matmul(weight.t())
  File "/home/linfeng/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 386, in matmul
    return torch.matmul(self, other)
  File "/home/linfeng/anaconda2/lib/python2.7/site-packages/torch/functional.py", line 173, in matmul
    return torch.mm(tensor1, tensor2)
RuntimeError: size mismatch at /opt/conda/conda-bld/pytorch_1513363039688/work/torch/lib/THC/generic/THCTensorMathBlas.cu:243

**Comment by da03** [comment]
Hmm we need to modify attention as well. Here I just implemented a very hacky workaround: https://github.com/da03/OpenNMT-py/tree/hack . Run with command `python train.py -data data/demo -save_model demo-model -rnn_size 1000 -bridge -brnn_merge sum -encoder_type brnn` should work, although it's super hacky.

**Comment by freesunshine0316** [comment]
@da03 Thanks! Please take a look at the output. It seems not quite right. Sorry for bordering. I don't understand PyTorch very well. 

NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(8282, 500, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(500, 500, dropout=0.2, bidirectional=True)
    (bridge): ModuleList(
      (0): Linear(in_features=500, out_features=500)
      (1): Linear(in_features=500, out_features=500)
    )
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(8281, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.2)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.2)
      (layers): ModuleList(
        (0): LSTMCell(1500, 1000)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=1000, out_features=1000)
      (linear_out): Linear(in_features=2000, out_features=1000)
      (sm): Softmax()
      (tanh): Tanh()
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=1000, out_features=8281)
    (1): LogSoftmax()
  )
)
