### ISSUE TITLE
random cudnn error

### ISSUE THREAD

**Issue by Henry-E** [OpenNMT/OpenNMT-py#707]
Yesterday morning all my models stopped being able to train or evaluate due to a cudnn error. It was pretty random and I haven't been able to figure out what caused it. Models still in process of training were able to finish their training but any new models that tried to train, or when the currently training models tried to switch to their evaluation step, they all broke. Tried reinstalling pytorch and the code for OpenNMT has not changed. Kind of at a loss trying to figure out what changed. It's probably a path error as most things are. But I can't figure out what caused it and hence how to fix it.

```
Loading model parameters.
Traceback (most recent call last):
  File "/home/henrye/downloads/OpenNMT-py/translate.py", line 29, in <module>
    main(opt)
  File "/home/henrye/downloads/OpenNMT-py/translate.py", line 16, in main
    translator = make_translator(opt, report_score=True)
  File "/home/henrye/downloads/OpenNMT-py/onmt/translate/Translator.py", line 28, in make_translator
    onmt.ModelConstructor.load_test_model(opt, dummy_opt.__dict__)
  File "/home/henrye/downloads/OpenNMT-py/onmt/ModelConstructor.py", line 129, in load_test_model
    use_gpu(opt), checkpoint)
  File "/home/henrye/downloads/OpenNMT-py/onmt/ModelConstructor.py", line 233, in make_base_model
    model.cuda()
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 85, in flatten_parameters
    handle = cudnn.get_handle()
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 296, in get_handle
    handle = CuDNNHandle()
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 110, in __init__
    check_error(lib.cudnnCreate(ctypes.byref(ptr)))
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 283, in check_error
    raise CuDNNError(status)
torch.backends.cudnn.CuDNNError: 4: b'CUDNN_STATUS_INTERNAL_ERROR'
Exception ignored in: <bound method CuDNNHandle.__del__ of <torch.backends.cudnn.CuDNNHandle object at 0x2b821b52a780>>
Traceback (most recent call last):
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 114, in __del__
    check_error(lib.cudnnDestroy(self))
ctypes.ArgumentError: argument 1: <class 'TypeError'>: Don't know how to convert parameter 1
```

**Comment by Henry-E** [comment]
As random as solution was found as the problem that appeared. Basically all I had to do was delete the `.nv` folder in my home directory. https://github.com/pytorch/pytorch/issues/5700#issuecomment-372449325
