### ISSUE TITLE
Is mean encoder still supported?

### ISSUE THREAD

**Issue by Henry-E** [OpenNMT/OpenNMT-py#716]
Just getting an error when trying to use mean encoder. All the model options appear to be correct but when looking at architecture print out it's seemingly missing the encoder.

The top half is from a similar model using an RNN encoder and bottom half is using the mean encoder option. When stepping through the error it appears that there's no matrix multiplication to resize the 349 dimensional concatenated word and feature embeddings into the 450 dimensional RNN vector size.
![screen shot 2018-05-03 at 21 08 43](https://user-images.githubusercontent.com/12613144/39600479-c8634152-4f16-11e8-984b-a56e6b502eb6.png)

```

Loading train dataset from preprocess/dorsey_12h32m_Thu_03-05-2018/mostly.train.1.pt, number of examples: 654936
Traceback (most recent call last):
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/ipdb/__main__.py", line 198, in main
    pdb._runscript(mainpyfile)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/henrye/downloads/OpenNMT-py/train.py", line 3, in <module>
    from __future__ import division
  File "/home/henrye/downloads/OpenNMT-py/train.py", line 494, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "/home/henrye/downloads/OpenNMT-py/train.py", line 257, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/henrye/downloads/OpenNMT-py/onmt/Trainer.py", line 178, in train
    report_stats, normalization)
  File "/home/henrye/downloads/OpenNMT-py/onmt/Trainer.py", line 306, in _gradient_accumulation
    self.model(src, tgt, src_lengths, dec_state)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/henrye/downloads/OpenNMT-py/onmt/Models.py", line 592, in forward
    memory_lengths=lengths)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/henrye/downloads/OpenNMT-py/onmt/Models.py", line 313, in forward
    tgt, memory_bank, state, memory_lengths=memory_lengths)
  File "/home/henrye/downloads/OpenNMT-py/onmt/Models.py", line 494, in _run_forward_pass
    rnn_output, hidden = self.rnn(decoder_input, hidden)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/henrye/downloads/OpenNMT-py/onmt/modules/StackedRNN.py", line 24, in forward
    h_1_i, c_1_i = layer(input, (h_0[i], c_0[i]))
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 655, in forward
    self.bias_ih, self.bias_hh,
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 27, in LSTMCell
    hgates = F.linear(hidden[0], w_hh)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 837, in linear
    output = input.matmul(weight.t())
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autograd/variable.py", line 386, in matmul
    return torch.matmul(self, other)
  File "/home/henrye/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/functional.py", line 174, in matmul
    return torch.mm(tensor1, tensor2)
RuntimeError: size mismatch at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCTensorMathBlas.cu:247
```

**Comment by vince62s** [comment]
did you retry it since the refactoring ? I must admit I never tested it.

**Comment by Henry-E** [comment]
I tried using the mean encoder a while back and it wouldn't run. But it
wasn't such a high priority that I looked deeper into what the exact bug or
issue was

**Comment by vince62s** [comment]
ok closing for now, not really a high priority we can always reopen later if someone looks into it.
