### ISSUE TITLE
AttributeError: 'Translator' object has no attribute 'translator'

### ISSUE THREAD

**Issue by ziorufus** [OpenNMT/OpenNMT-py#719]
Hello!
I'm trying to use the `dump_beam` parameter in the [translate.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/translate.py) file, but I get this error:

```
Traceback (most recent call last):
  File "translate.py", line 29, in <module>
    main(opt)
  File "translate.py", line 18, in main
    opt.batch_size, opt.attn_debug)
  File "/kore-ns-groups/dh/aprosio/simp/OpenNMT-py-master/onmt/translate/Translator.py", line 210, in translate
    json.dump(self.translator.beam_accum,
AttributeError: 'Translator' object has no attribute 'translator'
```

By looking at the code, it seems that [line 210 of Translator.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/Translator.py#L210) should be modified from `json.dump(self.translator.beam_accum` to `json.dump(self.beam_accum`, but it still does not work. No error is thrown now, but the beam file only contains: `{"predicted_ids": [], "beam_parent_ids": [], "log_probs": [], "scores": []}`. How can I get the correct output?
Note that the output file is correct.

Thank you!

**Comment by bpopeters** [comment]
I'll give it a look.

**Comment by vince62s** [comment]
@bpopeters di you have time to work on this ?

**Comment by vince62s** [comment]
kind reminder if you have time.

**Comment by vince62s** [comment]
@ziorufus do you have time to test #1240 ?

**Comment by William-N-Havard** [comment]
Kind reminder if you have time.
