### ISSUE TITLE
Encounter problem when using transformer

### ISSUE THREAD

**Issue by Embedding** [OpenNMT/OpenNMT-py#737]
I ran the following command:
python3 train.py -data data/squad-nqg/demo -save_model squad-nqg/demo-model -gpuid 0 -encoder_type transformer -decoder_type transformer -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512

But got the error :              Traceback (most recent call last):
  File "train.py", line 502, in <module>
    main()
  File "train.py", line 494, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 257, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/zhaozhe/Desktop/opennmt/OpenNMT-py-master/onmt/Trainer.py", line 178, in train
    report_stats, normalization)
  File "/home/zhaozhe/Desktop/opennmt/OpenNMT-py-master/onmt/Trainer.py", line 311, in _gradient_accumulation
    trunc_size, self.shard_size, normalization)
  File "/home/zhaozhe/Desktop/opennmt/OpenNMT-py-master/onmt/Loss.py", line 122, in sharded_compute_loss
    for shard in shards(shard_state, shard_size):
  File "/home/zhaozhe/Desktop/opennmt/OpenNMT-py-master/onmt/Loss.py", line 266, in shards
    torch.autograd.backward(inputs, grads)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
         RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

Could you tell me how to solve it? Thank you very much!

**Comment by vince62s** [comment]
the current repo is not pytorch 0.4 compatible yet.
If you want to test the transformer with pytorch 0.4 and multi gpu, give a try here:
https://github.com/Ubiqus/OpenNMT-py
