### ISSUE TITLE
Size mismatch error when word_vec_size differs from rnn_size

### ISSUE THREAD

**Issue by abhishek0318** [OpenNMT/OpenNMT-py#753]
I am getting size mismatch error when I use different word_vec_size from rnn_size. I am using PyTorch 0.3.1. 

Steps to reproduce:

```
python preprocess.py -train_src ./data/train.src -train_tgt ./data/train.tgt -valid_src ./data/val.src -valid_tgt ./data/val.tgt -save_data ./data/out -share_vocab
```

Setting `word_vec_size` to 300 and `rnn_size` to 100, gives an error.

```
python train.py -word_vec_size 300 -share_decoder_embeddings -share_embeddings -encoder_type brnn -layers 1 -rnn_size 100 -data ./data/out -save_model ./data/out -gpuid 0 -batch_size 32`
```

```
Loading train dataset from ./data/out.train.1.pt, number of examples: XXXX
 * vocabulary size. source = 51; target = 51
Building model...
Intializing model parameters.
NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(51, 300, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(300, 50, dropout=0.3, bidirectional=True)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(51, 300, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(400, 100)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=100, out_features=100, bias=False)
      (linear_out): Linear(in_features=200, out_features=100, bias=False)
      (sm): Softmax()
      (tanh): Tanh()
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=100, out_features=51, bias=True)
    (1): LogSoftmax()
  )
)
* number of parameters: 386951
encoder:  156100
decoder:  230851
Making optimizer for training.
Stage 1: Keys after executing optim.set_parameters(model.parameters())
optim.optimizer.state_dict()['state'] keys: 
optim.optimizer.state_dict()['param_groups'] elements: 
optim.optimizer.state_dict()['param_groups'] element: {'lr': 1.0, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'params': [139702669493736, 139702669494056, 139702669494136, 139702669494216, 139702669494296, 139702669494376, 139702669494456, 139702669494536, 139702669494616, 139702669495336, 139702669495416, 139702669495496, 139702669495576, 139702669495816, 139702669495976, 139702668435688]}

Start training...
 * number of epochs: 13, starting from Epoch 1
 * batch size: 32

Loading train dataset from ./data/out.train.1.pt, number of examples: XXXX
Traceback (most recent call last):
  File "train.py", line 502, in <module>
    main()
  File "train.py", line 494, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 257, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/abhisha/OpenNMT-py/onmt/Trainer.py", line 178, in train
    report_stats, normalization)
  File "/home/abhisha/OpenNMT-py/onmt/Trainer.py", line 311, in _gradient_accumulation
    trunc_size, self.shard_size, normalization)
  File "/home/abhisha/OpenNMT-py/onmt/Loss.py", line 123, in sharded_compute_loss
    loss, stats = self._compute_loss(batch, **shard)
  File "/home/abhisha/OpenNMT-py/onmt/Loss.py", line 186, in _compute_loss
    scores = self.generator(self._bottle(output))
  File "/home/abhisha/anaconda3/envs/opennmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/abhisha/anaconda3/envs/opennmt/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/abhisha/anaconda3/envs/opennmt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/abhisha/anaconda3/envs/opennmt/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/abhisha/anaconda3/envs/opennmt/lib/python3.6/site-packages/torch/nn/functional.py", line 835, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCTensorMathBlas.cu:247

```

When `word_vec_size` and `nn_size` are same, I get no error.
```
python train.py -word_vec_size 100 -share_decoder_embeddings -share_embeddings -encoder_type brnn -layers 1 -rnn_size 100 -data ./data/out -save_model ./data/out -gpuid 0 -batch_size 32
```
Is this intended?

**Comment by da03** [comment]
Thanks for reporting! The reason is that `-share_decoder_embeddings` would share the target embedding matrix (which is word_vec_size*vocab_size) with the generator projection matrix (which is rnn_size*vocab_size), so in case which word_vec_size \ne rnn_size, we would see a size mismatch error. We'll add an error message to be this more clear.

**Comment by abhishek0318** [comment]
Thanks! I understand the problem now. If you don't mind I could make a PR. I guess I would've to add a few lines in `train.py`.
