### ISSUE TITLE
how to solve the problem: RuntimeError: expected Variable as element 1 in argument 0, but got list

### ISSUE THREAD

**Issue by jacklee8** [OpenNMT/OpenNMT-py#757]
When I run : 
python train.py -data data/demo -save_model demo-model -gpuid 1

I got the problem:

Start training...
 * number of epochs: 13, starting from Epoch 1
 * batch size: 64

Loading train dataset from data/demo.train.1.pt, number of examples: 10000
Traceback (most recent call last):
  File "train.py", line 502, in <module>
    main()
  File "train.py", line 494, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 257, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/media/automation/a158e51e-f082-467d-8909-c218d7c8ff40/Group_Liu/LiWenHao/chongfu/OpenNMT-py/onmt/Trainer.py", line 178, in train
    report_stats, normalization)
  File "/media/automation/a158e51e-f082-467d-8909-c218d7c8ff40/Group_Liu/LiWenHao/chongfu/OpenNMT-py/onmt/Trainer.py", line 306, in _gradient_accumulation
    self.model(src, tgt, src_lengths, dec_state)
  File "/home/automation/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/automation/a158e51e-f082-467d-8909-c218d7c8ff40/Group_Liu/LiWenHao/chongfu/OpenNMT-py/onmt/Models.py", line 593, in forward
    memory_lengths=lengths)
  File "/home/automation/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/automation/a158e51e-f082-467d-8909-c218d7c8ff40/Group_Liu/LiWenHao/chongfu/OpenNMT-py/onmt/Models.py", line 312, in forward
    tgt, memory_bank, state, memory_lengths=memory_lengths)
  File "/media/automation/a158e51e-f082-467d-8909-c218d7c8ff40/Group_Liu/LiWenHao/chongfu/OpenNMT-py/onmt/Models.py", line 493, in _run_forward_pass
    decoder_input = torch.cat([emb_t, input_feed], 1)
RuntimeError: expected Variable as element 1 in argument 0, but got list

**Comment by da03** [comment]
What's the version of pytorch? (import torch; print(torch.__version__) )

**Comment by jacklee8** [comment]
@da03  The previous version is 0.3.Now,I update the version to 0.4 and it works well.Thanks!

**Comment by da03** [comment]
Glad to hear that! Closing the issue now.
