### ISSUE TITLE
Error in translate.py

### ISSUE THREAD

**Issue by sbmaruf** [OpenNMT/OpenNMT-py#772]
While doing translation I got the following error,
command: 

> python translate.py -model ./first_model_acc_60.41_ppl_7.98_e13.pt -src ../temp/all_dataset/GNOME_KDE4_OpenSubtitles2016_OpenSubtitles2018_Ubuntu_alt_amara/test.en-ms.en -output pred.txt -replace_unk -verbose

> [Traceback (most recent call last):
>   File "translate.py", line 33, in <module>
>     main(opt)
>   File "translate.py", line 21, in main
>     opt.batch_size, opt.attn_debug)
>   File "/home/sbmaruf/Documents/Translation-Project/OpenNMT-py/onmt/translate/Translator.py", line 161, in translate
>     for batch in data_iter:
>   File "/home/sbmaruf/anaconda3/envs/sbmaruf/lib/python3.6/site-packages/torchtext/data/iterator.py", line 151, in __iter__
>     self.train)
>   File "/home/sbmaruf/anaconda3/envs/sbmaruf/lib/python3.6/site-packages/torchtext/data/batch.py", line 27, in __init__
>     setattr(self, name, field.process(batch, device=device, train=train))
>   File "/home/sbmaruf/anaconda3/envs/sbmaruf/lib/python3.6/site-packages/torchtext/data/field.py", line 188, in process
>     tensor = self.numericalize(padded, device=device, train=train)
>   File "/home/sbmaruf/anaconda3/envs/sbmaruf/lib/python3.6/site-packages/torchtext/data/field.py", line 308, in numericalize
>     arr = self.postprocessing(arr, None, train)
>   File "/home/sbmaruf/Documents/Translation-Project/OpenNMT-py/onmt/io/TextDataset.py", line 220, in make_src
>     src_vocab_size = max([t.max() for t in data]) + 1
>   File "/home/sbmaruf/Documents/Translation-Project/OpenNMT-py/onmt/io/TextDataset.py", line 220, in <listcomp>
>     src_vocab_size = max([t.max() for t in data]) + 1
> RuntimeError: invalid argument 1: tensor must have one dimension at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/TH/generic/THTensorMath.c:733

I know probably it is a pytorch issue. But anyone having this issue?

my pytorch version is `0.4.0`.

And at first it was predicting fine. This is an error occured after predicting a lot of lines.

Another question, when I give the test-set to the `translate.py` as input, do I need to tokenize that test-set before giving input to the `translate.py`?

**Comment by lianghong** [comment]
+1 
same issue

**Comment by da03** [comment]
Hmm thanks for reporting! Can you post one example which caused the crash? (Or share the test set). Regrading tokenization, yes it should be tokenized before translating.

**Comment by sbmaruf** [comment]
Hi @da03 !
To reproduce the same error I have uploded the model and testset. Please download them from the following google drive folder. 
https://drive.google.com/drive/folders/10MztbJmJkdSxmmF0doYvv1FSxvF9b218?usp=sharing

**Comment by da03** [comment]
sorry for the delay, looking into that now

**Comment by da03** [comment]
Oh I think Line 1704 in dummy.en is blank? That caused the issue since the source feature tensor is empty.

**Comment by sbmaruf** [comment]
Thanks for the help. yes you are right. 
Is there any workaround here to process that empty line or it could not be done.

**Comment by da03** [comment]
Hmm I think the simplest way would be deleting blank lines, or using <pad> as a placeholder.

**Comment by mayhewsw** [comment]
I had the same issue, same solution. Super easy way of removing blank lines: 
`awk NF infile > outfile`
