### ISSUE TITLE
Conv2Conv bug when running translate.py

### ISSUE THREAD

**Issue by 1400012780** [OpenNMT/OpenNMT-py#792]
I trained a conv2conv model and test it using translate.py.
command line is shown as below.
``python translate.py -model models/ROC_conv/model_acc_33.46_ppl_42.63_e50.pt -src data/ROC/test_x.txt -tgt data/ROC/test_y.txt -output models/ROC_conv/pred_e50.txt -report_bleu -report_rouge -share_vocab -beam_size 8 -verbose -n_best 4 -gpu 7 ``
but there was a bug.
``
Traceback (most recent call last):
  File "translate.py", line 36, in <module>
    main(opt)
  File "translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/data6/OpenNMT-py/onmt/translate/translator.py", line 210, in translate
    batch_data = self.translate_batch(batch, data)
  File "/data6/OpenNMT-py/onmt/translate/translator.py", line 302, in translate_batch
    return self._translate_batch(batch, data)
  File "/data6/OpenNMT-py/onmt/translate/translator.py", line 385, in _translate_batch
    step=i)
  File "/usr/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'step'
``
A variable is missing in the onmt/decoders/cnn_decoder.py CNNDecoder.forward. 
I tried to add step=None in it and fixed it.
I don't know whether there are some unseen bugs if I doing so?

**Comment by guillaumekln** [comment]
That's the fix. Do you mind sending a PR with that?

**Comment by 1400012780** [comment]
my pleasure.

**Comment by vince62s** [comment]
@1400012780 during my refactoring work I tested CNN but not extensively.
In particular I found that results where not as good as fairseq.
If you have some good benchmark, would be good to share.
BTW: is your task audio or text ?
