### ISSUE TITLE
TypeError: _compute_loss() missing 1 required positional argument: 'copy_attn'

### ISSUE THREAD

**Issue by pushpankar** [OpenNMT/OpenNMT-py#809]
Type error while using -copy_attn during training.

**Comment by vince62s** [comment]
Please post your command line

**Comment by pushpankar** [comment]
python train.py -data data/finetune -save_model finetune -train_from original_model_same_vocab_acc_89.88_ppl_3.09_e11.pt  -epochs 150 -layers 4 -encoder_type transformer -decoder_type transformer  -adagrad_accumulator_init 0.1 -copy_attn -copy_loss_by_seqlength  -bridge

Traceback (most recent call last):
  File "train.py", line 141, in <module>
    main(opt)
  File "train.py", line 125, in main
    trainer.train(train_iter_fct, valid_iter_fct, opt.start_epoch, opt.epochs)
  File "/home/pushpankar-k/OpenNMT-py/onmt/trainer.py", line 132, in train
    train_stats = self.train_epoch(train_iter, epoch)
  File "/home/pushpankar-k/OpenNMT-py/onmt/trainer.py", line 190, in train_epoch
    report_stats, normalization)
  File "/home/pushpankar-k/OpenNMT-py/onmt/trainer.py", line 321, in _gradient_accumulation
    trunc_size, self.shard_size, normalization)
  File "/home/pushpankar-k/OpenNMT-py/onmt/utils/loss.py", line 144, in sharded_compute_loss
    loss, stats = self._compute_loss(batch, **shard)
TypeError: _compute_loss() missing 1 required positional argument: 'copy_attn'

**Comment by vince62s** [comment]
you are not on master, git pull and try again.

**Comment by pushpankar** [comment]
Did pull still getting the same error.
`python train.py -data data/finetune -save_model finetune -train_from original_model_same_vocab_acc_89.88_ppl_3.09_e11.pt  -train_steps 150000 -layers 4 -encoder_type transformer -decoder_type transformer  -copy_attn`

Traceback (most recent call last):
  File "train.py", line 40, in <module>
    main(opt)
  File "train.py", line 27, in main
    single_main(opt)
  File "/home/pushpankar-k/OpenNMT-py/onmt/train_single.py", line 128, in main
    opt.valid_steps)
  File "/home/pushpankar-k/OpenNMT-py/onmt/trainer.py", line 175, in train
    report_stats)
  File "/home/pushpankar-k/OpenNMT-py/onmt/trainer.py", line 287, in _gradient_accumulation
    trunc_size, self.shard_size, normalization)
  File "/home/pushpankar-k/OpenNMT-py/onmt/utils/loss.py", line 143, in sharded_compute_loss
    loss, stats = self._compute_loss(batch, **shard)
TypeError: _compute_loss() missing 1 required positional argument: 'copy_attn'

**Comment by pltrdy** [comment]
It only happens when you set `-train_from` right?

Could you provide the command you used for the initial training so we can reproduce. Thx.

**Comment by pushpankar** [comment]
`python train.py -data data/original_data -save_model original_model` for original training



`python preprocess.py -train_src data/new_headline.train -train_tgt data/new_title.train -valid_src data/new_headline.test -valid_tgt data/title.test -share_vocab -dynamic_dict -save_data data/finetune -src_vocab data/vocab.txt` for preprocessing the data.

**Comment by vince62s** [comment]
you did not specify an encoder / decoder type to start with ? => it was a rnn by default.
