### ISSUE TITLE
Met some problems when using server

### ISSUE THREAD

**Issue by FernandoSailing** [OpenNMT/OpenNMT-py#810]
I tried to use server.py, but met some problems.
I follow the tutorial at  https://github.com/OpenNMT/OpenNMT-py/pull/619
But I got 404 error. 

the input:
curl http://0.0.0.0:5000/models

the output:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

Could you give me advice? Thank you very much!

**Comment by vince62s** [comment]
Obviously you can't put 0.0.0.0 as an IP address when using curl.

**Comment by vince62s** [comment]
Post your server command line and the json file.

**Comment by FernandoSailing** [comment]
The server.py:
```
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="OpenNMT-py REST Server")
    parser.add_argument("--ip", type=str, default="11.185.210.2")
    parser.add_argument("--port", type=int, default="5000")
    parser.add_argument("--url_root", type=str, default="/translator")
    parser.add_argument("--debug", "-d", action="store_true")
    parser.add_argument("--config", "-c", type=str,
                        default="./available_models/conf.json")
    args = parser.parse_args()
    start(args.config, url_root=args.url_root, host=args.ip, port=args.port,
          debug=args.debug)
```

the config file:
```
{
    "models_root": "./available_models",
    "models": [
        {
            "id": 100,
            "model": "model_0.pt",
            "timeout": 600,
            "on_timeout": "to_cpu",
            "load": true,
            "opt": {
                "gpu": 0,
                "beam_size": 5
            },
            "tokenizer": {
                "type": "sentencepiece",
                "model": "m.model"
            }
        },{
            "model": "model_0.light.pt",
            "timeout": -1,
            "on_timeout": "unload",
            "model_root": "../other_models",
            "opt": {
                "batch_size": 1,
                "beam_size": 10
            }
        }
    ]
}

```
           

The command is just `python server.py   ` 

It could be great if some guideline for server is provided. Thank you very much

**Comment by vince62s** [comment]
did you put these two files
model_0.pt
m.model
in ./available_models ?

in server.py do not put the ip address, leave it to 0.0.0.0

**Comment by FernandoSailing** [comment]
I have model_0.pt and m.model in ./available_models
And I change server.py, leaving it to 0.0.0.0

The returned result is:

```
Pre-loading model 100
[2018-07-09 15:48:49,842 INFO] Loading model 100
[2018-07-09 15:48:55,712 INFO] Loading tokenizer
Pre-loading model 0
 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
[2018-07-09 15:48:55,760 INFO]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2018-07-09 15:48:55,760 INFO]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2018-07-09 15:49:04,061 INFO] 11.185.210.2 - - [09/Jul/2018 15:49:04] "GET /models HTTP/1.1" 404 -
[2018-07-09 15:49:04,061 INFO] 11.185.210.2 - - [09/Jul/2018 15:49:04] "GET /models HTTP/1.1" 404 -
[2018-07-09 15:49:47,905 INFO] 11.185.210.2 - - [09/Jul/2018 15:49:47] "GET /models HTTP/1.1" 404 -
[2018-07-09 15:49:47,905 INFO] 11.185.210.2 - - [09/Jul/2018 15:49:47] "GET /models HTTP/1.1" 404 -

```

**Comment by vince62s** [comment]
remove the second items of you json file.
remove this:
,{
            "model": "model_0.light.pt",
            "timeout": -1,
            "on_timeout": "unload",
            "model_root": "../other_models",
            "opt": {
                "batch_size": 1,
                "beam_size": 10
            }
        }

**Comment by pltrdy** [comment]
There's a set parameter `--url_root` that is set to `/translator`, therefore urls are e.g. `http://<ip_address>:<port>/translator/models`.

**Comment by FernandoSailing** [comment]
@vince62s Thank you very much for your kind suggestions!
@pltrdy  It works out. Thanks!
I met another problem.
`curl http://127.0.0.1:5000/translator/models` works well, but the following two command still have 404 problem.

`curl -i -X POST -H "Content-Type: application/json" -d '{"model": "model_0.pt"}' http://127.0.0.1:5000/translator/load_model`


`curl -i -X POST -H "Content-Type: application/json" -d '{"text": "// txt to translate, separated with \n"}' http://127.0.0.1:5000/translator/translate/100`

**Comment by FernandoSailing** [comment]
Sorry for bothering you again. I got the 500 error:
```
$python server.py
Pre-loading model 100
[2018-07-09 17:01:31,415 INFO] Loading model 100
[2018-07-09 17:01:37,399 INFO] Loading tokenizer
 * Serving Flask app "server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
[2018-07-09 17:01:37,449 INFO]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2018-07-09 17:01:38,109 INFO] 127.0.0.1 - - [09/Jul/2018 17:01:38] "GET /translator/models HTTP/1.1" 200 -
[2018-07-09 17:01:44,992 ERROR] Exception on /translator/translate [POST]
Traceback (most recent call last):
  File "/home/zhezhao.zz/Env/zz_env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zhezhao.zz/Env/zz_env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zhezhao.zz/Env/zz_env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zhezhao.zz/Env/zz_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/zhezhao.zz/Env/zz_env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zhezhao.zz/Env/zz_env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 72, in translate
    translation, scores, n_best, times = translation_server.run(inputs)
  File "/home/zhezhao.zz/NQG/OpenNMT-py-0709/onmt/translate/translation_server.py", line 123, in run
    model_id = inputs[0].get("id", 0)
KeyError: 0
[2018-07-09 17:01:44,993 INFO] 11.185.210.2 - - [09/Jul/2018 17:01:44] "POST /translator/translate HTTP/1.1" 500 -
```

the command line is 
`curl -i -X POST -H "Content-Type: application/json" -d '{"text": "// txt to translate, separated with \n"}' http://127.0.0.1:5000/translator/translate`
 Could you give me some suggestions? thank you very much!

**Comment by vince62s** [comment]
You need to read the post from Paul.
at the end of the url (after translate) you need to put the id of the model
100 in your case

**Comment by hpulfc** [comment]
@FernandoSailing 
like this 
` curl -i -X POST -H "Content-Type: application/json" -d '[{"src": "hello wold ", "id": model_id_in_your_conf }]' http://127.0.0.1:5000/translator/translate `

also ,if you have an unicode char to return ,you should change the translator.py 
`self.out_file.write('\n'.join(n_best_preds) + '\n')`
just encode the unicode str  to utf-8
like this:
`
n_best_preds_block = '\n'.join(n_best_preds) + '\n'
self.out_file.write(n_best_preds_block.encode("utf-8"))
`
may be this have to be fixed ! @pltrdy 
this does work!

**Comment by vince62s** [comment]
@pltrdy can you please check the very last point, otherwise I'll close this. thanks.

**Comment by vince62s** [comment]
@hpulfc can you please be more specific about the requirement of the .encode("utf-8") fix ?
We are using it for language like French with special characters "éèàç" and it works fine.

**Comment by vince62s** [comment]
closing.
