### ISSUE TITLE
Assertion error: assert len(self) == len(inputs_)

### ISSUE THREAD

**Issue by Lawhy** [OpenNMT/OpenNMT-py#834]
Hi,

I have two data text files in which each word has a feature, I use the '￨' to annotate the word, so as to specify its cluster. 
The training process went well but something got wrong in the translation step:

`python /disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/translate.py -src en_dev_2 cls.txt -model model_step_350.pt -output rrr.txt -verbose -replace_unk -gpu 1
Traceback (most recent call last):
  File "/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/translate.py", line 36, in <module>
    main(opt)
  File "/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/translate/translator.py", line 213, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/translate/translator.py", line 314, in translate_batch
    return self._translate_batch(batch, data)
  File "/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/translate/translator.py", line 559, in _translate_batch
    step=i)
  File "/disk/ocean/lhe/condaPytorch/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/decoders/decoder.py", line 136, in forward
    tgt, memory_bank, state, memory_lengths=memory_lengths)
  File "/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/decoders/decoder.py", line 314, in _run_forward_pass
    emb = self.embeddings(tgt)
  File "/disk/ocean/lhe/condaPytorch/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/modules/embeddings.py", line 184, in forward
    emb = self.make_embedding(source)
  File "/disk/ocean/lhe/condaPytorch/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk/ocean/lhe/condaPytorch/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/disk/ocean/lhe/condaPytorch/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/modules/util_class.py", line 42, in forward
    assert len(self) == len(inputs_)
AssertionError`

Please help me with that. Everything is fine for the original data without word features.

**Comment by vince62s** [comment]
did you use the pipe symbol or the one mentioned here: http://opennmt.net/OpenNMT/data/word_features/

**Comment by Lawhy** [comment]
The details of how I got the errors:

Here is a MWE for something I am getting an error for.

There are four files, as usual for preprocess.py:

en_tra_2cls.txt contains:

g￨1 o￨0 o￨0 r￨0 t￨0 y￨0
w￨1 h￨0 i￨0 t￨0 t￨0 e￨0 r￨0 i￨0 d￨0 g￨0 e￨0

en_dev_2cls.txt contains:

h￨1 u￨0 b￨0 e￨0 r￨0
l￨1 a￨0 p￨0 a￨0 d￨0 i￨0 s￨0

ch_tra_2cls.txt contains:
古￨1 尔￨1 蒂￨0
惠￨1 特￨1 里￨1 奇￨0

ch_dev_2cls.txt contains:
休￨1 伯￨0
拉￨1 帕￨1 迪￨1 斯￨0

Then I run preprocess.py:

python nmt-py/OpenNMT-py/preprocess.py -train_src en_tra_2cls.txt -train_tgt ch_tra_2cls.txt -valid_src en_dev_2cls.txt -valid_tgt ch_dev_2cls.txt -save_data 2cls

all goes well.

Then I run train.py:

python nmt-py/OpenNMT-py/train.py -data 2cls -save_model 2cls -train_steps 10 -seed 7 -start_decay_step 5000 -save_checkpoint_steps 5 -keep_checkpoint 5 -decay_steps 1000 -gpuid 1

all goes well.

however, when I run:

python nmt-py/OpenNMT-py/translate.py -src en_dev_2cls.txt -model 2cls_step_5.pt -output rrr.txt -verbose -replace_unk -gpu 1

I get the error

Traceback (most recent call last):
File “/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/translate.py”, line 36, in 
main(opt)
File “/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/translate.py”, line 24, in main
attn_debug=opt.attn_debug)
File “/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/translate/translator.py”, line 213, in translate
batch_data = self.translate_batch(batch, data, fast=self.fast)
File “/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/translate/translator.py”, line 314, in translate_batch
return self._translate_batch(batch, data)
File “/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/translate/translator.py”, line 559, in _translate_batch
step=i)
File “/disk/ocean/lhe/condaPytorch/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py”, line 491, in call
result = self.forward(*input, **kwargs)
File “/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/decoders/decoder.py”, line 136, in forward
tgt, memory_bank, state, memory_lengths=memory_lengths)
File “/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/decoders/decoder.py”, line 314, in run_forward_pass
emb = self.embeddings(tgt)
File “/disk/ocean/lhe/condaPytorch/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py”, line 491, in call
result = self.forward(*input, **kwargs)
File “/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/modules/embeddings.py”, line 184, in forward
emb = self.make_embedding(source)
File “/disk/ocean/lhe/condaPytorch/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py”, line 491, in call
result = self.forward(*input, **kwargs)
File “/disk/ocean/lhe/condaPytorch/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/container.py”, line 91, in forward
input = module(input)
File “/disk/ocean/lhe/condaPytorch/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py”, line 491, in call
result = self.forward(*input, **kwargs)
File “/disk/ocean/lhe/transliteration/nmt-py/OpenNMT-py/onmt/modules/util_class.py”, line 42, in forward
assert len(self) == len(inputs)
AssertionError

any ideas why?

I am using the latest version of pytorch as of date (using “pip install”) and I believe the latest version of OpenNMT.

If I remove the “word features” (from both source and target), everything works well.

**Comment by Lawhy** [comment]
Can someone help please, I am really struggling with this bug.

**Comment by zhezhaoa** [comment]
I think the reason of the error is from delimiter. Try to use this u"￨" to concatenate word and features, and add # coding: utf-8 at the beginning of file. I also suggest you to print data to see if the word and features are correctly split by u"￨" . According to your error, I think you did not split the word and features correctly.

**Comment by Lawhy** [comment]
Thanks for your response, but I don't think the problem is the delimiter because I indeed use u"￨" and every data file is in 'UTF-8'.

Do you have any sample data that has word features and can be translated successfully?

Even when I use the simplest example with:
src_data: 
a￨1 b￨2 
a￨1 c￨2 
a￨1 b￨2 a￨1 b￨2
tgt_data:
a￨1 b￨2 
a￨1 b￨2 
a￨1 b￨2 

Everything is fine in preprocess/train steps, but the same assertion error still happens in translation.

This leads me to doubt that something is wrong with the implementation of word features in the source code.

**Comment by Lawhy** [comment]
I have just tested another sample data set, it seems that if I removed word features from the target side, everything works well, so does OpenNMT-py only support word features from the source side?

**Comment by vince62s** [comment]
only source features. it's on the README page.

**Comment by Lawhy** [comment]
Many thanks.

**Comment by eduamf** [comment]
The error occurs using the translation service too. And I'm sending the feature is extracted using the tokenizer pyonmttok (segment_case). 

This is the error:

`[2019-04-03 08:55:03,297 INFO] Running translation using 101
[2019-04-03 08:55:03,300 ERROR] Error:
[2019-04-03 08:55:03,300 ERROR] repr(text_to_translate): ['B￭ r￭ a￭ s￭ i￭ l é u￭ m p￭ a￭ í￭ s']
[2019-04-03 08:55:03,300 ERROR] model: #101
[2019-04-03 08:55:03,300 ERROR] model opt: {'models': ['./models/Celex-CF88_96-Fapesp-GPU-sgmnt500_2019_04_01-09_58__step_25000.pt'], 'avg_raw_probs': False, 'data_type': 'text', 'src': 'dummy_src', 'src_dir': '', 'tgt': None, 'output': 'pred.txt', 'report_bleu': False, 'report_rouge': False, 'dynamic_dict': True, 'share_vocab': True, 'fast': True, 'beam_size': 1, 'min_length': 0, 'max_length': 700, 'max_sent_length': None, 'stepwise_penalty': False, 'length_penalty': 'none', 'coverage_penalty': 'none', 'alpha': 0.0, 'beta': -0.0, 'block_ngram_repeat': 0, 'ignore_when_blocking': [], 'replace_unk': True, 'verbose': True, 'log_file': '', 'log_file_level': '0', 'attn_debug': False, 'dump_beam': '', 'n_best': 1, 'batch_size': 16, 'gpu': -1, 'sample_rate': 16000, 'window_size': 0.02, 'window_stride': 0.01, 'window': 'hamming', 'image_channel_size': 3, 'cuda': False}
[2019-04-03 08:55:03,318 ERROR] Traceback (most recent call last):
  File "/Projetos/OpenNMT-py/onmt/translate/translation_server.py", line 409, in run
    batch_size=self.opt.batch_size)
  File "/Projetos/OpenNMT/eduamf/OpenNMT-py/onmt/translate/translator.py", line 200, in translate
    batch, data, attn_debug, fast=self.fast
  File "/Projetos/OpenNMT/eduamf/OpenNMT-py/onmt/translate/translator.py", line 302, in translate_batch
    return_attention=attn_debug or self.replace_unk)
  File "/Projetos/OpenNMT/eduamf/OpenNMT-py/onmt/translate/translator.py", line 407, in _fast_translate_batch
    batch, data.data_type)
  File "/Projetos/OpenNMT/eduamf/OpenNMT-py/onmt/translate/translator.py", line 314, in _run_encoder
    src, src_lengths)
  File "/opt/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/Projetos/OpenNMT/eduamf/OpenNMT-py/onmt/encoders/rnn_encoder.py", line 55, in forward
    emb = self.embeddings(src)
  File "/opt/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/Projetos/OpenNMT/eduamf/OpenNMT-py/onmt/modules/embeddings.py", line 205, in forward
    source = self.make_embedding(source)
  File "/opt/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/opt/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/Projetos/OpenNMT/eduamf/OpenNMT-py/onmt/modules/util_class.py", line 25, in forward
    assert len(self) == len(inputs_)
AssertionError
`

**Comment by eduamf** [comment]
My conf.json has the following tokenizer parameters:

...
            "tokenizer": {
                "type": "pyonmttok",
                "mode": "aggressive",
                "params": {
                    "no_substitution": false,
                    "segment_case": true,
                    "segment_numbers": true,
                    "joiner_annotate": true,
                    "segment_alphabet": ["Latin"]
                }
            }
        }

**Comment by guillaumekln** [comment]
It's `case_feature` (not `segment_case`) that extracts the case components. However, this extra feature is currently ignored by the OpenNMT-py translation server (second output of `tokenize`):

https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/translation_server.py#L524

**Comment by eduamf** [comment]
You're right. Otherwise, the feature is created when using tools/tokenize.lua with `segment_case` to tokenize the original files.

**Comment by eduamf** [comment]
The same error with `case_feature` and last version:
```
  File "/home/cosev/Projetos/OpenNMT/Master/OpenNMT-py-0.8.2/onmt/modules/util_class.py", line 25, in forward
    assert len(self) == len(inputs_)
AssertionError
```

**Comment by eduamf** [comment]
I`m using the same case feature separator used by OpenNMT (lua version). 

I know that there a lot of symbols alike "￨":
U+01C0		ǀ	letter pipe or Latin dental click
U+2223		∣	divides
U+2502		│	box drawings light vertical (used by OpenNMT to replace U+FFE8)
U+2503		┃	box drawings heavy vertical
U+2758 ‭ 	❘  	light vertical bar
U+2759		❙	medium vertical bar
U+275A‭		❚	heavy vertical bar
U+FF5C		｜	fullwidth vertical line.
U+FFE8		￨	halfwidth light vertical (used by OpenNMT as feature separator symbol)

But when I use the service in Flask, I send the text not tokenized. And, the same error happens with the translate.py command sending only source.

**Comment by eduamf** [comment]
In the util_class.py module the length values are:
self: 2
inputs: 8
inputs_: 1

It is ignoring some conf.json parameters:
```
...
        }, {
            "id": 102,
            "name": "PT-EN-Case",
            "model": "Celex-CF88_96-Fapesp_2019_04_20-12_17__step_145000.pt",
            "dynamic_dict": true,
            "timeout": 5000,
            "on_timeout": "to_cpu",
            "model_root": "/opt/models",
            "load": true,
            "opt": {
                "gpu": -1,
                "beam_size": 5,
                "dynamic_dict": true,
                "share_vocab": false,
                "max_length": 500,
                "batch_size": 16,
                "replace_unk": false,
                "fast": true,
                "verbose": false
            }
            ,  
            "tokenizer": {
                "type": "pyonmttok",
                "mode": "aggressive",
                "params": {
                    "no_substitution": false,
                    "case_feature": true,
                    "segment_case": true,
                    "segment_numbers": true,
                    "joiner_annotate": true
                }
            }
        }
...
```

**Comment by eduamf** [comment]
I tried not sending target file, but with error. 

Has anyone ever succeeded with any version of translate.py using features?

**Comment by anderleich** [comment]
Has someone solved this error?

Do we need to train the model just using case features on source?

**Comment by vmujadia** [comment]
@anderleich , I tried only with a source feature, translate.py worked on that .. not sure about exact problem though.
