### ISSUE TITLE
text_dataset get_fields method throws a TypeError

### ISSUE THREAD

**Issue by kustom666** [OpenNMT/OpenNMT-py#836]
Hello,

## Environment
Python 3.6.4 Anaconda
OpenNMT-py master
Pytorch 0.4.0
torchtext 0.2.3

## The issue
When using the server.py script with loading=True, the script crashes on [line 23](https://github.com/OpenNMT/OpenNMT-py/blob/master/server.py#L23)

The full error stack is as follows:

```
Traceback (most recent call last):
  File "server.py", line 114, in <module>
    debug=args.debug)
  File "server.py", line 23, in start
    translation_server.start(config_file)
  File "/Users/pforti/Projects/onmt-canned-prediction-api/onmt/translate/translation_server.py", line 76, in start
    self.preload_model(opt, model_id=model_id, **kwargs)
  File "/Users/pforti/Projects/onmt-canned-prediction-api/onmt/translate/translation_server.py", line 112, in preload_model
    model = ServerModel(opt, model_id, **model_kwargs)
  File "/Users/pforti/Projects/onmt-canned-prediction-api/onmt/translate/translation_server.py", line 182, in __init__
    self.load()
  File "/Users/pforti/Projects/onmt-canned-prediction-api/onmt/translate/translation_server.py", line 221, in load
    out_file=open(os.devnull, "w"))
  File "/Users/pforti/Projects/onmt-canned-prediction-api/onmt/translate/translator.py", line 32, in build_translator
    onmt.model_builder.load_test_model(opt, dummy_opt.__dict__)
  File "/Users/pforti/Projects/onmt-canned-prediction-api/onmt/model_builder.py", line 132, in load_test_model
    checkpoint['vocab'], data_type=opt.data_type)
  File "/Users/pforti/Projects/onmt-canned-prediction-api/onmt/inputters/inputter.py", line 64, in load_fields_from_vocab
    fields = get_fields(data_type, n_src_features, n_tgt_features)
  File "/Users/pforti/Projects/onmt-canned-prediction-api/onmt/inputters/inputter.py", line 48, in get_fields
    return TextDataset.get_fields(n_src_features, n_tgt_features)
  File "/Users/pforti/Projects/onmt-canned-prediction-api/onmt/inputters/text_dataset.py", line 244, in get_fields
    postprocessing=make_src, sequential=False)
TypeError: __init__() got an unexpected keyword argument 'dtype'
```

## Steps for reproducing
Simply run server.py with a correct config file that points to any valid checkpoint file generated from a training under the aforementioned environment.

## Possible solution

I have already identified the issue as a breaking change introduced by pytorch 0.4 / torchtext 0.2.3: the    torchtext.data.Field class doesn't accept a dtype argument in its constructor anymore, hence this will fail:
```python
fields["src_map"] = torchtext.data.Field(
            use_vocab=False, dtype=torch.float,
            postprocessing=make_src, sequential=False)
``` 
(excerpt from [text_dataset.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/inputters/text_dataset.py#L242)

It seems that simply removing the dtype argument solves the issue, I have prepared a patch and will submit a pull request shortly.

**Comment by vince62s** [comment]
read the requirements, torchtext 0.3.0 is needed.

**Comment by kustom666** [comment]
My apologies, I did not notice any specific mention to torchtext 0.3.0 being needed. This issue is moot.

**Comment by vince62s** [comment]
no pb, you can close it.

**Comment by RogerXT** [comment]
May I ask a dumb question? How to install torchtext 0.3.0? I cannot find this version.

**Comment by alphadl** [comment]
if you use the latest pyTorch (0.4) then you have to remove that parameter
