### ISSUE TITLE
AttributeError: 'Field' object has no attribute 'vocab'

### ISSUE THREAD

**Issue by xiadingZ** [OpenNMT/OpenNMT-py#842]
torchtext: 0.3
train is ok, but problem occurs in translate:

```
Traceback (most recent call last):
  File "translate.py", line 36, in <module>
    main(opt)
  File "translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/home/dingxia/code/OpenNMT-py/onmt/translate/translator.py", line 212, in translate
    for batch in data_iter:
  File "/home/dingxia/anaconda3/lib/python3.6/site-packages/torchtext/data/iterator.py", line 157, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "/home/dingxia/anaconda3/lib/python3.6/site-packages/torchtext/data/batch.py", line 27, in __init__
    setattr(self, name, field.process(batch, device=device))
  File "/home/dingxia/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py", line 186, in process
    tensor = self.numericalize(padded, device=device)
  File "/home/dingxia/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py", line 285, in numericalize
    arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
  File "/home/dingxia/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py", line 285, in <listcomp>
    arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
  File "/home/dingxia/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py", line 285, in <listcomp>
    arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
AttributeError: 'Field' object has no attribute 'vocab'
```

**Comment by LeeeeoLiu** [comment]
Hi xiadingZ, I meet this problem in training. How do you fix it?

**Comment by pencoa** [comment]
How do you solve it?
