### ISSUE TITLE
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by susht3** [OpenNMT/OpenNMT-py#846]
when i run python train.py -data data/demo -save_model demo-model -gpuid 2
i got cuda error, but i can use gpu2 in other code by CUDA_VISIBLE_DEVICES=2 python train.py

Traceback (most recent call last):
  File "train.py", line 40, in <module>
    main(opt)
  File "train.py", line 27, in main
    single_main(opt)
  File "/home/work/sushuting/opennmt/onmt/train_single.py", line 129, in main
    opt.valid_steps)
  File "/home/work/sushuting/opennmt/onmt/trainer.py", line 176, in train
    report_stats)
  File "/home/work/sushuting/opennmt/onmt/trainer.py", line 284, in _gradient_accumulation
    self.model(src, tgt, src_lengths, dec_state)
  File "/home/work/anaconda3/envs/susht/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/work/sushuting/opennmt/onmt/models/model.py", line 45, in forward
    enc_final, memory_bank = self.encoder(src, lengths)
  File "/home/work/anaconda3/envs/susht/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/work/sushuting/opennmt/onmt/encoders/rnn_encoder.py", line 66, in forward
    memory_bank, encoder_final = self.rnn(packed_emb)
  File "/home/work/anaconda3/envs/susht/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/work/anaconda3/envs/susht/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 192, in forward
    output, hidden = func(input, self.all_weights, hx, batch_sizes)
  File "/home/work/anaconda3/envs/susht/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 323, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/work/anaconda3/envs/susht/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 275, in forward
    train, dropout_seed, dropout_state)
  File "/home/work/anaconda3/envs/susht/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 44, in init_dropout_state
    if dropout_p != 0 else None

**Comment by vince62s** [comment]
see this https://github.com/OpenNMT/OpenNMT-py/issues/840
