### ISSUE TITLE
Context gate runtime error

### ISSUE THREAD

**Issue by geovedi** [OpenNMT/OpenNMT-py#85]
How to properly use newly committed `-context_gate` feature as I couldn't make it works. I keep getting the following error.

```
$ python ../OpenNMT/train.py -gpus 0 -log_interval 100 -rnn_size 2048 -word_vec_size 1024 -context_gate both -optim adam -learning_rate 0.0001 -data data.000.000.train.pt
Namespace(batch_size=64, brnn=False, brnn_merge='concat', context_gate='both', curriculum=False, data='data.000.000.train.pt', dropout=0.3, encoder_type='text', epochs=13, extra_shuffle=False, gpus=[0], input_fe
ed=1, layers=2, learning_rate=0.0001, learning_rate_decay=0.5, log_interval=100, max_generator_batches=32, max_grad_norm=5, optim='adam', param_init=0.1, pre_word_vecs_dec=None, pre_word_vecs_enc=None, rnn_size=2048, rnn_type='LSTM', save_model='model', seed=-1, start_decay_at=8, start_epoch=1, train_from='', train_from_state_dict='', word_vec_size=1024)
Loading data from 'data.000.000.train.pt'
 * vocabulary size. source = 10004; target = 10004
 * number of training sentences. 2000000
 * maximum batch size. 64
Building model...
* number of parameters: 208830228
NMTModel (
  (encoder): Encoder (
    (word_lut): Embedding(10004, 1024, padding_idx=0)
    (rnn): LSTM(1024, 2048, num_layers=2, dropout=0.3)
  ) 
  (decoder): Decoder (
    (word_lut): Embedding(10004, 1024, padding_idx=0)
    (rnn): StackedLSTM (
      (dropout): Dropout (p = 0.3)
      (layers): ModuleList (
        (0): LSTMCell(3072, 2048)
        (1): LSTMCell(2048, 2048)
      ) 
    ) 
    (attn): GlobalAttention (
      (linear_in): Linear (2048 -> 2048)
      (sm): Softmax ()
      (linear_out): Linear (4096 -> 2048)
      (tanh): Tanh ()
    ) 
    (context_gate): BothContextGate (
      (context_gate): ContextGate (
        (gate): Linear (5120 -> 2048)
        (sig): Sigmoid ()
        (source_proj): Linear (2048 -> 2048)
        (target_proj): Linear (3072 -> 2048)
      ) 
      (tanh): Tanh ()
    )  
    (dropout): Dropout (p = 0.3)
  )
  (generator): Sequential (
    (0): Linear (2048 -> 10004)
    (1): LogSoftmax ()
  )
)

Traceback (most recent call last):
  File "../OpenNMT/train.py", line 415, in <module>
    main()
  File "../OpenNMT/train.py", line 411, in main
    trainModel(model, trainData, validData, dataset, optim)
  File "../OpenNMT/train.py", line 268, in trainModel
    train_loss, train_acc = trainEpoch(epoch)
  File "../OpenNMT/train.py", line 229, in trainEpoch
    outputs = model(batch)
  File "/XXX/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/beritagar/workdir/src/OpenNMT-py/onmt/Models.py", line 198, in forward
    context, init_output)
  File "/XXX/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/beritagar/workdir/src/OpenNMT-py/onmt/Models.py", line 152, in forward
    emb_t.squeeze(0), rnn_output, attn_output
  File "/XXX/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/beritagar/workdir/src/OpenNMT-py/onmt/modules/Gate.py", line 89, in forward
    z, source, target = self.context_gate(prev_emb, dec_state, attn_state)
  File "/XXX/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/beritagar/workdir/src/OpenNMT-py/onmt/modules/Gate.py", line 39, in forward
    input_tensor = torch.cat((prev_emb, dec_state, attn_state), dim=2)
  File "/XXX/lib/python3.6/site-packages/torch/autograd/variable.py", line 841, in cat
    return Concat(dim)(*iterable)
  File "/XXX/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 309, in forward
    self.input_sizes = [i.size(self.dim) for i in inputs]
  File "/XXX/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 309, in <listcomp>
    self.input_sizes = [i.size(self.dim) for i in inputs]
RuntimeError: out of range at /py/conda-bld/pytorch_1493681908901/work/torch/lib/THC/generic/THCTensor.c:23
```

**Comment by mattiadg** [comment]
Assuming that you still have the version prior the last merge, you should modify the code like this:

https://github.com/mattiadg/OpenNMT-py/blob/2f0533c2ef7f2dc0c281f408dbe1e7bce45b1171/onmt/modules/Gate.py#L39-L43

just set dim=1 instead of dim=2 in both lines.

For the new version, I still need to study the code.

**Comment by srush** [comment]
@mattiadg can you join our giter channel? https://gitter.im/OpenNMT/openmt . I can help fix this.

**Comment by srush** [comment]
Oh I see the issue. It will be fixed in my next PR.
