### ISSUE TITLE
translate.py throws error after a few sentences

### ISSUE THREAD

**Issue by jbecke** [OpenNMT/OpenNMT-py#860]
translate.py throws this after 60, 90 or 120 sentences. Note that it is not always after a specific number of sentences, which makes me think it's not a problem with the validation data. I'm also running translate.py over the same validation file I used for training, and it had no problem during training.

```
Traceback (most recent call last):
  File "translate.py", line 36, in <module>
    main(opt)
  File "translate.py", line 24, in main
    attn_debug=opt.attn_debug)
  File "/home/Jacob/OpenNMT-py/onmt/translate/translator.py", line 213, in translate
    batch_data = self.translate_batch(batch, data, fast=self.fast)
  File "/home/Jacob/OpenNMT-py/onmt/translate/translator.py", line 314, in translate_batch
    return self._translate_batch(batch, data)
  File "/home/Jacob/OpenNMT-py/onmt/translate/translator.py", line 590, in _translate_batch
    ret = self._from_beam(beam)
  File "/home/Jacob/OpenNMT-py/onmt/translate/translator.py", line 604, in _from_beam
    scores, ks = b.sort_finished(minimum=n_best)
  File "/home/Jacob/OpenNMT-py/onmt/translate/beam.py", line 160, in sort_finished
    s = global_scores[i]
IndexError: index 5 is out of bounds for dimension 0 with size 5
```

These are the args I'm using:
```
python translate.py -model retry_step_40000.pt -src ../super_src_valid.txt -output pred.txt -replace_unk -verbose -n_best 20 -gpu 0
```

**Comment by vince62s** [comment]
what kind of model ?
try:
- without n_best
- without replace_unk
- with python3
trying to narrow down the issue

**Comment by jbecke** [comment]
...I was out of disk space.
