### ISSUE TITLE
Inconsistent tensor types when using average attn in Transformer

### ISSUE THREAD

**Issue by vikrantsharma7** [OpenNMT/OpenNMT-py#880]
Commit ID: `6b93582`
I'm trying to train a transformer model using the following command:
```
python train.py -data data/data -save_model data/model \
-layers 2 -rnn_size 256 -word_vec_size 256 \
-encoder_type transformer -decoder_type transformer \
-position_encoding -max_generator_batches 32 -dropout 0.2 \
-batch_type tokens -normalization tokens -accum_count 4 \
-optim adam -adam_beta2 0.99 -decay_method noam \
-warmup_steps 8000 -learning_rate 2 -max_grad_norm 0 \
-param_init 0 -param_init_glorot -label_smoothing 0.1 \
-batch_size 8192 -report_every 1 -save_checkpoint_steps 5 \
-self_attn_type average
```
I get the following traceback:
```
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    main(opt)
  File "train.py", line 24, in main
    single_main(opt)
  File "/home/vikrant/src/OpenNMT-py/onmt/train_single.py", line 128, in main
    opt.valid_steps)
  File "/home/vikrant/src/OpenNMT-py/onmt/trainer.py", line 175, in train
    report_stats)
  File "/home/vikrant/src/OpenNMT-py/onmt/trainer.py", line 282, in _gradient_accumulation
    self.model(src, tgt, src_lengths, dec_state)
  File "/home/vikrant/src/OpenNMT-py/.env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vikrant/src/OpenNMT-py/onmt/models/model.py", line 52, in forward
    memory_lengths=lengths)
  File "/home/vikrant/src/OpenNMT-py/.env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vikrant/src/OpenNMT-py/onmt/decoders/transformer.py", line 217, in forward
    step=step)
  File "/home/vikrant/src/OpenNMT-py/.env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vikrant/src/OpenNMT-py/onmt/decoders/transformer.py", line 86, in forward
    layer_cache=layer_cache, step=step)
  File "/home/vikrant/src/OpenNMT-py/.env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vikrant/src/OpenNMT-py/onmt/modules/average_attn.py", line 97, in forward
    if layer_cache is None else step, layer_cache=layer_cache)
  File "/home/vikrant/src/OpenNMT-py/onmt/modules/average_attn.py", line 47, in cumulative_average_mask
    weights = torch.ones((1, inputs_len)) / torch.arange(1, inputs_len + 1)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'other'
```

The command works fine with `-self_attn_type` set to `scaled-dot` or omitted (as it's the default).
I do not have a GPU on my machine, if that helps.
Am I using it wrong?
Thanks in advance.

**Comment by bpopeters** [comment]
My guess is what happened is that the default return type of `torch.arange` changed from `torch.FloatTensor` to `torch.LongTensor` between 0.4.0 and 0.4.1. To fix it, you can change line 47 of average_attn.py to `weights = torch.ones((1, inputs_len)) / torch.arange(1, inputs_len + 1).float()`. I'll see if there are any similar bugs elsewhere in the code too.

**Comment by bpopeters** [comment]
#884

**Comment by vikrantsharma7** [comment]
Yes, thanks. That does it.

**Comment by vince62s** [comment]
@vikrantsharma7 if you have time to test even further with 0.4.1, that would be great.

**Comment by vikrantsharma7** [comment]
@vince62s sure, I'll check the complete flow anyway.
Closing this for now.
