### ISSUE TITLE
Seems that Transformer does't support multi_gpu

### ISSUE THREAD

**Issue by chengduoZH** [OpenNMT/OpenNMT-py#887]
When I use multi-gpu to train Transformer, I encountered the following error.
```
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    main(opt)
  File "train.py", line 22, in main
    multi_main(opt)
  File "/paddle/OpenNMT-py/onmt/train_multi.py", line 45, in main
    p.join()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 121, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.5/multiprocessing/popen_forkserver.py", line 62, in poll
    if not wait([self.sentinel], timeout):
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/paddle/OpenNMT-py/onmt/train_multi.py", line 94, in signal_handler
    raise Exception(msg)
Exception:

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/paddle/OpenNMT-py/onmt/train_multi.py", line 52, in run
    single_main(opt)
  File "/paddle/OpenNMT-py/onmt/train_single.py", line 128, in main
    opt.valid_steps)
  File "/paddle/OpenNMT-py/onmt/trainer.py", line 171, in train
    (normalization))
RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:234
```
The script is:
```
python3 train.py -data data/wmt16.en-de.share -save_model wmt16-en-de-t2t -gpuid 4 5 6 7 -layers 6 -rnn_size 512 -word_vec_size 512 -encoder_type transformer -decoder_type transformer -position_encoding -train_steps 100000 -max_generator_batches 32 -dropout 0.1 -batch_size 4096 -batch_type tokens -normalization tokens
```

**Comment by chrishokamp** [comment]
Hi, I think you need to use pytorch `0.4.0`, not `0.4.1` or later

**Comment by alphadl** [comment]
same questions with you ~  you can change the batch_type from tokens to sents, which could ensure you run well. however, if you use tokens , this question is inevitable just now~

**Comment by vince62s** [comment]
You just need to set gpuid 0 1 2 3
And make sure you set cuda visible devices to what you want.

**Comment by alphadl** [comment]
@vince62s  nope , your suggestion is working if batch_type is sents rather than tokens ~

**Comment by alphadl** [comment]
@chrishokamp I just tried PyTorch 0.4.0 ,however , it shows that that version doesn't support NCCL
 
RuntimeError: the distributed NCCL backend is not available; try to recompile the THD package with CUDA and NCCL 2+ support at /opt/conda/conda-bld/pytorch_1525812548180/work/torch/lib/THD/process_group/General.cpp:17

**Comment by alphadl** [comment]
https://github.com/OpenNMT/OpenNMT-py/blob/6b93582884a6df6417e5b9cda4e5cd3445fe1a91/onmt/trainer.py#L154-L156

I guess this code snippet are most likely to cause problems

**Comment by chrishokamp** [comment]
@alphadl there could be other issues with your setup. I had the same error and I downgraded from `0.4.1` to `0.4.0` for Ubuntu 16.04 (https://pytorch.org/previous-versions/) in a conda environment and it just worked.

**Comment by alphadl** [comment]
I think the only difference between us is that My cuda version is 8 instead of 9 , and under the environment of Pytorch0.4.0+cuda8 , I still met error like I mentioned earlier (NCCL backend is not available)

**Comment by chrishokamp** [comment]
@alphadl, not sure what the issue(s) could be, but can confirm that it works for me with `CUDA Version 9.2.148`, nvidia `Driver Version: 396.37`, and pytorch `0.4.0` from [this link](http://download.pytorch.org/whl/cu91/torch-0.4.0-cp36-cp36m-linux_x86_64.whl)

**Comment by alphadl** [comment]
thank you, I will update my cuda to the latest version~ @chrishokamp

**Comment by chengduoZH** [comment]
@chrishokamp @alphadl Thank you for your reply.
I followed @chrishokamp's advice and multi-gpu can work now.
But what is the cause of this problem?

**Comment by vince62s** [comment]
@chengduoZH if you set gpuid 0 1 2 3, instead of 4 5 6 7, are you getting the same error as your first post with pytorch 0.4.1 ?
I think we are mixing different issues in this thread.

**Comment by shhshn** [comment]
The same happened with PyTorch 0.4.1 before downgrading it to 0.4.0
So this is	just another 0.4.1 compatibility issue similar to #880

**Comment by vince62s** [comment]
closing this for now until we tackle the 0.4.1 compatibility.

**Comment by chengduoZH** [comment]
@vince62s 
> if you set gpuid 0 1 2 3, instead of 4 5 6 7, are you getting the same error as your first post with pytorch 0.4.1 ?

Yes.

Another issue is that, when I use pytorch 0.4.0 and set gpuid 0 1 2 3 4 5 6 7, I get the same error as my first post. And if I decrease the number of GPU, it can work. 
It seems that pytorch 0.4.0 doesn't support 8 pieces GPU to train model. I am not sure whether it is normal.

**Comment by vince62s** [comment]
hmm weird. does it work up to 7 ? 6 ?
waht is your CUDA_VISIBLE_DEVICES when you run the train ?
can you post your nvidia-smi ?

**Comment by chengduoZH** [comment]
Yes, it can work up when the number of GPU is less 8.
I don't set CUDA_VISIBLE_DEVICES when I run the train.
And I use Pytorch in the docker container(nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04). I'm not sure if it's because I use Pytorch in docker. 
nvidia-smi:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           On   | 00000000:00:0A.0 Off |                    0 |
| N/A   43C    P0    51W / 250W |  0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           On   | 00000000:00:0B.0 Off |                    0 |
| N/A   25C    P8     9W / 250W |      0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           On   | 00000000:00:0C.0 Off |                    0 |
| N/A   23C    P8     9W / 250W |      0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           On   | 00000000:00:0D.0 Off |                    0 |
| N/A   24C    P8     9W / 250W |      0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P40           On   | 00000000:00:0E.0 Off |                    0 |
| N/A   24C    P8     8W / 250W |      0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P40           On   | 00000000:00:0F.0 Off |                    0 |
| N/A   24C    P8    10W / 250W |      0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P40           On   | 00000000:00:10.0 Off |                    0 |
| N/A   28C    P8    10W / 250W |      0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P40           On   | 00000000:00:11.0 Off |                    0 |
| N/A   20C    P8     9W / 250W |      0MiB / 22912MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

**Comment by vince62s** [comment]
please retry using -gpu_verbose_level 2
post your command line and the log before it crashes.
thanks.

**Comment by chengduoZH** [comment]
@vince62s the command line is:
```
python3  train.py -data $DATA/wmt16.en-de.share -save_model wmt16-en-de-t2t -gpuid  0 1 2 3 4 5 6 7  -gpu_verbose_level 2\
        -layers 6 -rnn_size 512 -word_vec_size 512   \
        -encoder_type transformer -decoder_type transformer -position_encoding \
        -train_steps 100000  -max_generator_batches 32 -dropout 0.1 \
        -batch_size 2048 -batch_type tokens -normalization tokens  -accum_count 4 \
        -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 2 \
        -max_grad_norm 0 -param_init 0  -param_init_glorot \
        -label_smoothing 0.1
```
And the log:
```
[2018-08-22 15:40:13,070 INFO] Loading train dataset from /home/OpenNMT_data/data/wmt16.en-de.share.train.1.pt, number of examples: 3873788
[2018-08-22 15:40:13,566 INFO]  * vocabulary size. source = 35372; target = 35372
[2018-08-22 15:40:13,566 INFO] Building model...
[2018-08-22 15:40:30,080 INFO] NMTModel(
   ......
)
[2018-08-22 15:40:30,093 INFO] encoder: 37025792
[2018-08-22 15:40:30,093 INFO] decoder: 61481516
[2018-08-22 15:40:30,093 INFO] * number of parameters: 98507308
[2018-08-22 15:40:30,099 INFO] Start training...
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    main(opt)
  File "train.py", line 22, in main
    multi_main(opt)
  File "/home/OpenNMT-py/onmt/train_multi.py", line 38, in main
    p.join()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 121, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/OpenNMT-py/onmt/train_multi.py", line 87, in signal_handler
    raise Exception(msg)
Exception:

-- Tracebacks above this line can probably
                 be ignored --

Traceback (most recent call last):
  File "/home/OpenNMT-py/onmt/train_multi.py", line 45, in run
    single_main(opt)
  File "/home/OpenNMT-py/onmt/train_single.py", line 128, in main
    opt.valid_steps)
  File "/home/OpenNMT-py/onmt/trainer.py", line 134, in train
    train_iter = train_iter_fct()
  File "/home/OpenNMT-py/onmt/train_single.py", line 121, in train_iter_fct
    lazily_load_dataset("train", opt), fields, opt)
  File "/home/OpenNMT-py/onmt/inputters/inputter.py", line 503, in build_dataset_iter
    device, is_train)
  File "/home/OpenNMT-py/onmt/inputters/inputter.py", line 425, in __init__
    self.cur_iter = self._next_dataset_iterator(datasets)
  File "/home/OpenNMT-py/onmt/inputters/inputter.py", line 449, in _next_dataset_iterator
    self.cur_dataset = next(dataset_iter)
  File "/home/OpenNMT-py/onmt/inputters/inputter.py", line 528, in lazily_load_dataset
    yield _lazy_dataset_loader(pt, corpus_type)
  File "/home/OpenNMT-py/onmt/inputters/inputter.py", line 519, in _lazy_dataset_loader
    dataset = torch.load(pt_file)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
MemoryError

```

**Comment by vince62s** [comment]
this is not the same error at all .....
this one is easy, MemoryError.
you need to shard in pieces that will create about 1 Milion sentences. You have 3.8 Millions here.
you're going OOM.

**Comment by vince62s** [comment]
@chengduoZH can you test the change from #923 and let me know if it works for you too (0.4.1) ?
