### ISSUE TITLE
Encountering RuntimeError when I loading pre-trained model to translate

### ISSUE THREAD

**Issue by alphadl** [OpenNMT/OpenNMT-py#902]
>>python translate.py -model ./transformer-model/bpe_t2t_en_to_cn_lr_2_layers_6_dropout_0.1_step_30000.pt -src ../data/dev.en.bpe -tgt ../data/dev.cn.bpe -output ../data/pred_t2t_bpe.cn -verbose -gpu 0 -report_bleu

---

Traceback (most recent call last):
  File "onmt/translate/translator.py", line 46, in build_translator
    onmt.modules.Ensemble.load_test_model(opt, dummy_opt.__dict__)
  File "onmt/modules/Ensemble.py", line 159, in load_test_model
    model_path=model_path)
  File "onmt/model_builder.py", line 133, in load_test_model
    map_location=lambda storage, loc: storage)
  File "/lib/python2.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/lib/python2.7/site-packages/torch/serialization.py", line 549, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 4328856626966500654 got 512

**Comment by alphadl** [comment]
has anybody met this problem before?

**Comment by alphadl** [comment]
@vince62s I assume that you can help me ~ many thanks

**Comment by vince62s** [comment]
Looks like an encoding issue can you please try with python3?

**Comment by alphadl** [comment]
that training and translation process are just trained with python3

**Comment by alphadl** [comment]
>>File ".../onmt/model_builder.py", line 133, in load_test_model
>>    map_location=lambda storage, loc: storage)
>>  File ".../lib/python3.6/site-packages/torch/serialization.py", line 358, in load
>>    return _load(f, map_location, pickle_module)
>>  File ".../lib/python3.6/site-packages/torch/serialization.py", line 549, in _load
>>    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
>> RuntimeError: storage has wrong size: expected 4328856626966500654 got 512

same error as python2 when I switch to python3

**Comment by guillaumekln** [comment]
The checkpoint is likely corrupted. Try to regenerate or redownload it.

**Comment by alphadl** [comment]
okay , I will try to re-train it

**Comment by alphadl** [comment]
I am sure that I have got complete checkpoint and use it as the translation model, however I still received that error~ 

>>[2018-08-17 16:59:56,860 INFO] Saving checkpoint /home/dingliang/experiment/e2c_exp/s2s/transformer-model/10w_sents_bpe_t2t_en_to_cn_lr_2_layers_6_dropout_0.1_step_5000.pt
---
>>python .../tools/OpenNMT-py/translate.py -model ./transformer-model/10w_sents_bpe_t2t_en_to_cn_lr_2_layers_6_dropout_0.1_step_5000.pt -src ../data/dev.en.bpe -tgt ../data/dev.cn.bpe -output ../data/pred_t2t_bpe_10w.cn -gpu 7 -verbose -report_bleu

and the result is :  
RuntimeError: storage has wrong size: expected -4834500515474013996 got 512

**Comment by vince62s** [comment]
why are we seeing this on your first log:
File "onmt/modules/Ensemble.py", line 159, in load_test_model
You are not on master, are you ?

**Comment by SONG-ziyue** [comment]
have you solved your problem? seem to meet the same problem "pt storage has wrong size: expected ... got 512" as  yours.
