### ISSUE TITLE
multiple-GPUs is broken

### ISSUE THREAD

**Issue by nicolabertoldi** [OpenNMT/OpenNMT-py#91]
with the latest commit (285f5495513d19a6a25935d0769e239e6cc3ee3f)

Multiple-GPU training fails,
while single-GPU training works properly.

PROCESSING succeeds:
python preprocess.py -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data debugging/model
Building source vocabulary...
Created dictionary of size 24999 (pruned from 24999)
()
Building target vocabulary...
Created dictionary of size 35820 (pruned from 35820)
()
Preparing training ...
Processing data/src-train.txt & data/tgt-train.txt ...
... shuffling sentences
... sorting sentences by size
Prepared 10000 sentences (0 ignored due to length == 0 or src len > 50 or tgt len > 50)
Preparing validation ...
Processing data/src-val.txt & data/tgt-val.txt ...
... shuffling sentences
... sorting sentences by size
Prepared 2819 sentences (181 ignored due to length == 0 or src len > 50 or tgt len > 50)
Saving source vocabulary to 'debugging/model.src.dict'...
Saving target vocabulary to 'debugging/model.tgt.dict'...
Saving data to 'debugging/model.train.pt'...

TRAINING fails:
python train.py -data debugging/model.train.pt -save_model debugging/model -gpus 0 1 -batch_size 64
Namespace(batch_size=64, brnn=False, brnn_merge='concat', context_gate=None, copy_attn=False, coverage_attn=False, curriculum=False, data='debugging/model.train.pt', decay_method='', decoder_layer='rnn', dropout=0.3, encoder_layer='rnn', encoder_type='text', epochs=13, experiment_name='', extra_shuffle=False, feature_vec_size=100, gpus=[0, 1], input_feed=1, layers=2, learning_rate=1.0, learning_rate_decay=0.5, log_interval=50, log_server='', max_generator_batches=32, max_grad_norm=5, optim='sgd', param_init=0.1, position_encoding=False, pre_word_vecs_dec=None, pre_word_vecs_enc=None, rnn_size=500, rnn_type='LSTM', save_model='debugging/model', seed=-1, share_decoder_embeddings=False, start_checkpoint_at=0, start_decay_at=8, start_epoch=1, train_from='', train_from_state_dict='', truncated_decoder=0, warmup_steps=4000, word_vec_size=500)
Loading data from 'debugging/model.train.pt'
 * vocabulary size. source = 24999; target = 35820
 * number of training sentences. 10000
 * maximum batch size. 64
Building model...
Intializing params
* number of parameters: 58121320

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 22, in _worker
    var_input = var_input[0]
TypeError: 'Batch' object does not support indexing
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 22, in _worker
    var_input = var_input[0]
TypeError: 'Batch' object does not support indexing

Traceback (most recent call last):
  File "train.py", line 565, in <module>
    main()
  File "train.py", line 561, in main
    trainModel(model, trainData, validData, dataset, optim)
  File "train.py", line 398, in trainModel
    train_loss, train_acc = trainEpoch(epoch)
  File "train.py", line 342, in trainEpoch
    if dec_hidden else None)
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 61, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 71, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 44, in parallel_apply
    output = results[i]
KeyError: 0

**Comment by srush** [comment]
Looking into it.
