### ISSUE TITLE
StopIteration Error when using Python 3.7

### ISSUE THREAD

**Issue by ZeweiChu** [OpenNMT/OpenNMT-py#911]
When I use Python 3.7 to run preprocess.py, I got the following error. The same error does not occur when I use Python 3.6. 

```
Traceback (most recent call last):
  File "/mnt/cephfs2/asr/users/zewei.chu/SQuAD/round-trip-translation/OpenNMT-py/onmt/inputters/text_dataset.py", line 384, in __iter__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 211, in <module>
    main()
  File "preprocess.py", line 201, in main
    train_dataset_files = build_save_dataset('train', fields, opt)
  File "preprocess.py", line 138, in build_save_dataset
    corpus_type, opt)
  File "preprocess.py", line 107, in build_save_in_shards
    dynamic_dict=opt.dynamic_dict)
  File "/mnt/cephfs2/asr/users/zewei.chu/SQuAD/round-trip-translation/OpenNMT-py/onmt/inputters/text_dataset.py", line 79, in __init__
    for ex_values in example_values:
  File "/mnt/cephfs2/asr/users/zewei.chu/SQuAD/round-trip-translation/OpenNMT-py/onmt/inputters/text_dataset.py", line 71, in <genexpr>
    example_values = ([ex[k] for k in keys] for ex in examples_iter)
  File "/mnt/cephfs2/asr/users/zewei.chu/SQuAD/round-trip-translation/OpenNMT-py/onmt/inputters/text_dataset.py", line 57, in <genexpr>
    examples_iter = (self._join_dicts(src, tgt) for src, tgt in
RuntimeError: generator raised StopIteration
```

**Comment by bpopeters** [comment]
I think I know where this one is coming from: there's a kind of weird generator function that manually raises `StopIteration`. This is an error in 3.7, whereas in older versions of python it was simply something you shouldn't ever need to do. A quick fix might just be to replace the `raise StopIteration` lines with `return`.

In the longer term, I'm working on simplifying the preprocessing code and the method that causes this problem is already on my list.

**Comment by tavin** [comment]
Hi @bpopeters, why was it made an error in 3.7? I've also got a broken generator as a result. And I think mine raises StopIteration for a very good reason :)

**Comment by bpopeters** [comment]
Hi @tavin, the proposal is discussed [here](https://www.python.org/dev/peps/pep-0479/).

Is this a problem you're having with OpenNMT-py? I thought we solved this bug last year, but I've been away from OpenNMT-py development for a while so it's possible it could have come up again.

**Comment by tavin** [comment]
Thanks for the reference @bpopeters. No it's nothing to do with OpenNMT-py. I just came across this thread as the top google result for my issue and you seemed to know the details.
