### ISSUE TITLE
Getting TypeError on model building

### ISSUE THREAD

**Issue by alpoktem** [OpenNMT/OpenNMT-py#913]
Hi,

I'm trying to train on the multi30k dataset but keep getting this error:
`[2018-08-21 14:40:56,794 INFO] Loading train dataset from data/multi30k.atok.low.train.1.pt, number of examples: 29000
[2018-08-21 14:40:56,817 INFO]  * vocabulary size. source = 10841; target = 18563
[2018-08-21 14:40:56,817 INFO] Building model...
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    main(opt)
  File "train.py", line 24, in main
    single_main(opt)
  File "/Users/alp/phdCloud/playground/OpenNMT-py/onmt/train_single.py", line 104, in main
    model = build_model(model_opt, opt, fields, checkpoint)
  File "/Users/alp/phdCloud/playground/OpenNMT-py/onmt/model_builder.py", line 246, in build_model
    use_gpu(opt), checkpoint)
  File "/Users/alp/phdCloud/playground/OpenNMT-py/onmt/model_builder.py", line 192, in build_base_model
    decoder = build_decoder(model_opt, tgt_embeddings)
  File "/Users/alp/phdCloud/playground/OpenNMT-py/onmt/model_builder.py", line 114, in build_decoder
    opt.reuse_copy_attn)
  File "/Users/alp/phdCloud/playground/OpenNMT-py/onmt/decoders/decoder.py", line 79, in __init__
    dropout=dropout)
  File "/Users/alp/phdCloud/playground/OpenNMT-py/onmt/decoders/decoder.py", line 370, in _build_rnn
    hidden_size, dropout)
  File "/Users/alp/phdCloud/playground/OpenNMT-py/onmt/models/stacked_rnn.py", line 19, in __init__
    self.layers.append(nn.LSTMCell(input_size, rnn_size))
  File "/Users/alp/extSW/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 662, in __init__
    self.weight_ih = Parameter(torch.Tensor(4 * hidden_size, input_size))
TypeError: an integer is required (got type method)`

I am using Python 3.6, torchtext 0.3.0 on mac.

**Comment by vince62s** [comment]
post your command line.

**Comment by alpoktem** [comment]
Here it goes:
`python train.py -data data/multi30k.atok.low -save_model models/multi30k`

**Comment by vince62s** [comment]
are you using pytorch 0.4.0 ? are you on master for OpenNMT-py ?
