### ISSUE TITLE
RuntimeError:

### ISSUE THREAD

**Issue by TB-SeChaJia** [OpenNMT/OpenNMT-py#930]
Traceback (most recent call last):
  File "train.py", line 476, in <module>
    main()
  File "train.py", line 469, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 243, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/bsichrb/Documents/CODE/OpenNMT/onmt/Trainer.py", line 163, in train
    report_stats, normalization)
  File "/home/bsichrb/Documents/CODE/OpenNMT/onmt/Trainer.py", line 291, in _gradient_accumulation
    batch, outputs, attns, j, trunc_size, self.shard_size, normalization)
  File "/home/bsichrb/Documents/CODE/OpenNMT/onmt/Loss.py", line 107, in sharded_compute_loss
    for shard in shards(shard_state, shard_size):
  File "/home/bsichrb/Documents/CODE/OpenNMT/onmt/Loss.py", line 260, in shards
    torch.autograd.backward(inputs, grads)
  File "/home/bsichrb/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

**Comment by vince62s** [comment]
new issue same question:
Please provide your pytorch + torchtext version and the command line you used

**Comment by TB-SeChaJia** [comment]
torchtext version=="0.2.3"
python3 train.py -data ./output/pre-data/demo

**Comment by vince62s** [comment]
look at the requirements, you need torchtext 0.3.0

**Comment by TB-SeChaJia** [comment]
The latest version is only 0.2.3

**Comment by vince62s** [comment]
yes but if you follow the instructions you will see this:
pip install -r requirements.txt
which has this:
six
tqdm
torch>=0.4.0
git+https://github.com/pytorch/text
future

it will take torchtext on master which is 0.3
