### ISSUE TITLE
New torchtext version breaks preprocessing

### ISSUE THREAD

**Issue by amulder** [OpenNMT/OpenNMT-py#935]
When I install the latest OpenNMT-py and `pip install -r requirements.txt`, I get the following error when I run preprocess.py:

```
Traceback (most recent call last):
  File "OpenNMT-py/preprocess.py", line 195, in <module>
    main()
  File "OpenNMT-py/preprocess.py", line 182, in main
    fields = onmt.io.get_fields(opt.data_type, src_nfeats, tgt_nfeats)
  File "OpenNMT-py/onmt/io/IO.py", line 44, in get_fields
    return TextDataset.get_fields(n_src_features, n_tgt_features)
  File "OpenNMT-py/onmt/io/TextDataset.py", line 231, in get_fields
    postprocessing=make_src, sequential=False)
TypeError: __init__() got an unexpected keyword argument 'tensor_type'
```

The current requirements.txt file pulls the latest torchtext, which is currently 0.3.0.

I can resolve the issue and run preprocess.py by regressing torchtext to 0.2.3.

```
# pip uninstall torchtext
Uninstalling torchtext-0.3.0:
  Would remove:
    /data/virtualenvs/opennmt021/lib/python3.6/site-packages/test/common/*
    /data/virtualenvs/opennmt021/lib/python3.6/site-packages/test/data/*
    /data/virtualenvs/opennmt021/lib/python3.6/site-packages/torchtext-0.3.0.dist-info/*
    /data/virtualenvs/opennmt021/lib/python3.6/site-packages/torchtext/*
Proceed (y/n)? y
  Successfully uninstalled torchtext-0.3.0

# pip install torchtext==0.2.3
Collecting torchtext
Requirement already satisfied: tqdm in /data/virtualenvs/opennmt021/lib/python3.6/site-packages (from torchtext) (4.25.0)
Requirement already satisfied: requests in /data/virtualenvs/opennmt021/lib/python3.6/site-packages (from torchtext) (2.19.1)
Requirement already satisfied: idna<2.8,>=2.5 in /data/virtualenvs/opennmt021/lib/python3.6/site-packages (from requests->torchtext) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /data/virtualenvs/opennmt021/lib/python3.6/site-packages (from requests->torchtext) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /data/virtualenvs/opennmt021/lib/python3.6/site-packages (from requests->torchtext) (2018.8.24)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /data/virtualenvs/opennmt021/lib/python3.6/site-packages (from requests->torchtext) (1.23)
Installing collected packages: torchtext
Successfully installed torchtext-0.2.3
```

**Comment by vince62s** [comment]
you need to be on master for OpenNMT-py

**Comment by amulder** [comment]
That fixed it. Thanks.
