### ISSUE TITLE
preprocess error, torch pickle is broken?

### ISSUE THREAD

**Issue by Henry-E** [OpenNMT/OpenNMT-py#937]
Ran into a strange preprocessing bug, not really sure. Based on the comment it looks like this has already been flagged as an issue. Any idea what to do?

```
[2018-09-02 17:03:59,102 INFO] Extracting features...
[2018-09-02 17:03:59,102 INFO]  * number of source features: 0.
[2018-09-02 17:03:59,102 INFO]  * number of target features: 0.
[2018-09-02 17:03:59,102 INFO] Building `Fields` object...
[2018-09-02 17:03:59,102 INFO] Building & saving training data...
[2018-09-02 17:03:59,102 INFO] Warning. The corpus create_source_and_target/data/train_self_original_no_cands_source.txt is larger than 10M bytes, you can set '-max_shard_size' to process it by small shards to use less memory.
[2018-09-02 17:04:17,656 INFO]  * saving train data shard to preprocess/basic_test/normal_data.train.1.pt.
Traceback (most recent call last):
  File "/home/henry/anaconda3/envs/pytorch/lib/python3.7/site-packages/ipdb/__main__.py", line 169, in main
    pdb._runscript(mainpyfile)
  File "/home/henry/anaconda3/envs/pytorch/lib/python3.7/pdb.py", line 1566, in _runscript
    self.run(statement)
  File "/home/henry/anaconda3/envs/pytorch/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/henry/downloads/OpenNMT-py/preprocess.py", line 5, in <module>
    """
  File "/home/henry/downloads/OpenNMT-py/preprocess.py", line 201, in main
    train_dataset_files = build_save_dataset('train', fields, opt)
  File "/home/henry/downloads/OpenNMT-py/preprocess.py", line 138, in build_save_dataset
    corpus_type, opt)
  File "/home/henry/downloads/OpenNMT-py/preprocess.py", line 116, in build_save_in_shards
    torch.save(dataset, pt_file)
  File "/home/henry/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py", line 209, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/henry/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py", line 134, in _with_file_like
    return body(f)
  File "/home/henry/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py", line 209, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/henry/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py", line 282, in _save
    pickler.dump(obj)
  File "/home/henry/downloads/OpenNMT-py/onmt/inputters/dataset_base.py", line 39, in __reduce_ex__
    return super(DatasetBase, self).__reduce_ex__()
TypeError: __reduce_ex__() takes exactly one argument (0 given)
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/henry/downloads/OpenNMT-py/onmt/inputters/dataset_base.py(39)__reduce_ex__()
     38         "This is a hack. Something is broken with torch pickle."
---> 39         return super(DatasetBase, self).__reduce_ex__()
     40
```

**Comment by Henry-E** [comment]
oh i didn't realise it was using python 3.7. Sorry, on a new computer. Reinstalling everything in a 3.6 env ought to fix it. Thanks very much
