### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'list'

### ISSUE THREAD

**Issue by xjtu-zeng** [OpenNMT/OpenNMT-py#94]
when I use translate with ```-src``` and ```-tgt```, it happens
```
Traceback (most recent call last):
  File "translate.py", line 171, in <module>
    main()
  File "translate.py", line 110, in main
    = translator.translate(srcBatch, tgtBatch)
  File "/home/zeng/github/OpenNMT-py/onmt/Translator.py", line 279, in translate
    dataset = self.buildData(srcBatch, goldBatch)
  File "/home/zeng/github/OpenNMT-py/onmt/Translator.py", line 87, in buildData
    tgtData += [tgtD]
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'list'
```
But it's ok without ```-tgt```.

**Comment by srush** [comment]
This should be fixed now.
