### ISSUE TITLE
im2text issue

### ISSUE THREAD

**Issue by ailurus1991** [OpenNMT/OpenNMT-py#943]
I was just following the tutorial in http://opennmt.net/OpenNMT-py/im2text.html. When I tried to train ,  `RuntimeError: hidden[0] has inconsistent hidden_size: got 1000, expected 500`. 

any suggestion? or just change to encoder type to rnn?

**Comment by vince62s** [comment]
I cannot reproduce.
Please post your command line.

**Comment by ailurus1991** [comment]
I just literally followed the tutorial http://opennmt.net/OpenNMT-py/im2text.html:
1. preprocess: `python preprocess.py -data_type img -src_dir data/im2text/images/ -train_src data/im2text/src-train.txt \
                     -train_tgt data/im2text/tgt-train.txt -valid_src data/im2text/src-val.txt \
                     -valid_tgt data/im2text/tgt-val.txt -save_data data/im2text/demo \
                     -tgt_seq_length 150 -tgt_words_min_frequency 2`
2. train: `python train.py -model_type img -data data/im2text/demo -save_model demo-model -gpuid 0 -batch_size 20 \
                -max_grad_norm 20 -learning_rate 0.1 -word_vec_size 80 -encoder_type brnn`

**Comment by vince62s** [comment]
are you on master ? it works like a charm for me.

**Comment by ailurus1991** [comment]
@vince62s Yeah on OpenNMT-py master with PyTorch 0.4.1

here's the full log:
```
Traceback (most recent call last):
  File "train.py", line 40, in <module>
    main(opt)
  File "train.py", line 27, in main
    single_main(opt)
  File "/home/guokr/open_NMT_dev/OpenNMT-py/onmt/train_single.py", line 128, in main
    opt.valid_steps)
  File "/home/guokr/open_NMT_dev/OpenNMT-py/onmt/trainer.py", line 172, in train
    report_stats)
  File "/home/guokr/open_NMT_dev/OpenNMT-py/onmt/trainer.py", line 276, in _gradient_accumulation
    self.model(src, tgt, src_lengths, dec_state)
  File "/home/guokr/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/guokr/open_NMT_dev/OpenNMT-py/onmt/models/model.py", line 52, in forward
    memory_lengths=lengths)
  File "/home/guokr/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/guokr/open_NMT_dev/OpenNMT-py/onmt/decoders/decoder.py", line 136, in forward
    tgt, memory_bank, state, memory_lengths=memory_lengths)
  File "/home/guokr/open_NMT_dev/OpenNMT-py/onmt/decoders/decoder.py", line 328, in _run_forward_pass
    rnn_output, hidden = self.rnn(decoder_input, hidden)
  File "/home/guokr/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/guokr/open_NMT_dev/OpenNMT-py/onmt/models/stacked_rnn.py", line 26, in forward
    h_1_i, c_1_i = layer(input_feed, (h_0[i], c_0[i]))
  File "/home/guokr/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/guokr/.local/lib/python3.5/site-packages/torch/nn/modules/rnn.py", line 708, in forward
    self.check_forward_hidden(input, hx[0], '[0]')
  File "/home/guokr/.local/lib/python3.5/site-packages/torch/nn/modules/rnn.py", line 537, in check_forward_hidden
    hidden_label, hx.size(1), self.hidden_size))
RuntimeError: hidden[0] has inconsistent hidden_size: got 1000, expected 500
```

**Comment by vince62s** [comment]
ok I messed up with the data, you are correct there is an error.
in fact there is a PR that fixes it and add some new stuff.
What you can try is just to fix this line
https://github.com/OpenNMT/OpenNMT-py/pull/889/files#diff-5688c2c667ac1cec66cd8235d994122aL43

**Comment by ailurus1991** [comment]
@vince62s Oh nice, brnn encoder is ok now. this PR should be merged. lol

**Comment by vince62s** [comment]
Unfortunately there are some other unfixed issues.
