### ISSUE TITLE
attention mask error during translation

### ISSUE THREAD

**Issue by mattiadg** [OpenNMT/OpenNMT-py#95]
I have tried to train models with different settings:
```bash
python train.py -log_interval 100 -context_gate both -optim adam -learning_rate 0.0001 -data data/demo.train.pt -epochs=1 -rnn_size 100 -word_vec_size 100 -optim adam -brnn -rnn_type GRU
```
```bash
python train.py -log_interval 100  -optim adam -learning_rate 0.0001 -data data/demo.train.pt -epochs=1 -rnn_size 100 -word_vec_size 100 -optim adam -brnn -rnn_type LSTM -gpus 3
```
```bash
python train.py -log_interval 100 -context_gate both -optim adam -learning_rate 0.0001 -data data/demo.train.pt -epochs=1 -rnn_size 100 -word_vec_size 100 -optim adam  -brnn -rnn_type LSTM -gpus 3
```

but then, when I try to translate with 
```bash
python translate.py -model model_XXX.pt -src data/src-test.txt -output pred.txt -replace_unk -verbose
```

I get always the following error
```bash
Traceback (most recent call last):
  File "translate.py", line 171, in <module>
    main()
  File "translate.py", line 110, in main
    = translator.translate(srcBatch, tgtBatch)
  File "/hltsrv0/digangi/OpenNMT-py/onmt/Translator.py", line 250, in translate
    pred, predScore, attn, goldScore = self.translateBatch(batch)
  File "/hltsrv0/digangi/OpenNMT-py/onmt/Translator.py", line 164, in translateBatch
    context, decStates)
  File "/hltsrv0/digangi/bin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/hltsrv0/digangi/OpenNMT-py/onmt/Models.py", line 306, in forward
    context.transpose(0, 1))
  File "/hltsrv0/digangi/bin/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/hltsrv0/digangi/OpenNMT-py/onmt/modules/GlobalAttention.py", line 81, in forward
    batch_, sourceL_ = self.mask.size()
ValueError: too many values to unpack (expected 2)
```

**Comment by mattiadg** [comment]
As we are talking about attention, why is the default attention "dotprod" and not "mlp"? 
For what I know the second is better in most of the cases.

**Comment by sebastianGehrmann** [comment]
Sorry, my bad. -  #96 should fix this.

**Comment by srush** [comment]
OpenNMT has always used DotProd. Different papers assert one is better or worse than the other.
