### ISSUE TITLE
error When use transform

### ISSUE THREAD

**Issue by ruidongtd** [OpenNMT/OpenNMT-py#961]
I use that
`
> python train.py -data data/cnndm/CNNDM \
					  -save_model models/cnndm_transform \
				        -layers 6 \
				      -rnn_size 512 \
				      -word_vec_size 300 \
					  -transformer_ff 2048 \
					  -heads 8  \
					  -encoder_type transformer \
					  -decoder_type transformer \
					  -position_encoding \
					  -train_steps 200000 \
					  -max_generator_batches 2 \
					  -dropout 0.1 \
					  -batch_size 4096 \
					  -batch_type tokens \
					  -normalization tokens \
					  -accum_count 2 \
					  -optim adam -adam_beta2 0.998 \
					  -decay_method noam \
					  -warmup_steps 8000 \
					  -learning_rate 2 \
					  -max_grad_norm 0 \
					  -param_init 0 -param_init_glorot -label_smoothing 0.1 -valid_steps 10000 \
					  -save_checkpoint_steps 10000 \
					  -pre_word_vecs_enc cnndm.vocab.dec.pt \
					  -pre_word_vecs_dec cnndm.vocab.enc.pt \
					  -gpuid 0
`

and I use the Pretrained embeddings(dim=300). and the error is 
`
> Traceback (most recent call last):
  File "train.py", line 38, in <module>
    main(opt)
  File "train.py", line 24, in main
    single_main(opt)
  File "/home/ruiy/disk_86/OpenNMT-py/onmt/train_single.py", line 128, in main
    opt.valid_steps)
  File "/home/ruiy/disk_86/OpenNMT-py/onmt/trainer.py", line 177, in train
    report_stats)
  File "/home/ruiy/disk_86/OpenNMT-py/onmt/trainer.py", line 290, in _gradient_accumulation
    self.model(src, tgt, src_lengths, dec_state)
  File "/home/ruiy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ruiy/disk_86/OpenNMT-py/onmt/models/model.py", line 45, in forward
    enc_final, memory_bank = self.encoder(src, lengths)
  File "/home/ruiy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ruiy/disk_86/OpenNMT-py/onmt/encoders/transformer.py", line 112, in forward
    out = self.transformer[i](out, mask)
  File "/home/ruiy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ruiy/disk_86/OpenNMT-py/onmt/encoders/transformer.py", line 48, in forward
    input_norm = self.layer_norm(inputs)
  File "/home/ruiy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ruiy/disk_86/OpenNMT-py/onmt/modules/util_class.py", line 20, in forward
    return self.a_2 * (x - mean) / (std + self.eps) + self.b_2
RuntimeError: The size of tensor a (512) must match the size of tensor b (300) at non-singleton dimension 2
`

**Comment by vince62s** [comment]
transformer requires word_vec_size and rnn_size to be the same

**Comment by ruidongtd** [comment]
ok, I think that `OpenNMT` should add a layer that can transform `word_vec_size` to `rnn_size`. It's convenient to add `GloVe` and `word2vec`.
