### ISSUE TITLE
Error with preprocessing procedure

### ISSUE THREAD

**Issue by pikaliov** [OpenNMT/OpenNMT-py#973]
OS: Linux Mint 19
Preinstalled libraries: torch==0.4.1, torchtext==0.2.3, torchvision==0.2.1, last version of OpenNMT-py
Version of python: used python3.6 and python2.7

Description of problem:
Can not preprocess data. I'm using data for summarization task http://opennmt.net/OpenNMT-py/Summarization.html (also tried run with files from folder data/)
`python preprocess.py -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo`
Getting output with error:
```
[2018-09-29 17:13:32,188 INFO] Extracting features...
[2018-09-29 17:13:32,192 INFO]  * number of source features: 0.
[2018-09-29 17:13:32,192 INFO]  * number of target features: 0.
[2018-09-29 17:13:32,192 INFO] Building `Fields` object...
Traceback (most recent call last):
  File "preprocess.py", line 286, in <module>
    main()
  File "preprocess.py", line 273, in main
    fields = inputters.get_fields(opt.data_type, src_nfeats, tgt_nfeats)
  File "/home/pikaliov/TODO/Libs/OpenNMT_new/onmt/inputters/inputter.py", line 50, in get_fields
    return TextDataset.get_fields(n_src_features, n_tgt_features)
  File "/home/pikaliov/TODO/Libs/OpenNMT_new/onmt/inputters/text_dataset.py", line 244, in get_fields
    postprocessing=make_src, sequential=False)
TypeError: __init__() got an unexpected keyword argument 'dtype'
```

**Comment by pikaliov** [comment]
I solved error. Installed git-version torchtext
