### ISSUE TITLE
error in loading existing vocabulary in the preprocess step

### ISSUE THREAD

**Issue by PersianNLPer** [OpenNMT/OpenNMT-py#989]
Hi,
There seem to be an error in loading existing vocabularies from the .pt files.
Well, I just tried with the toy example, preprocessed the data and obtained the three .pt files (demo.train.pt, demo.valid.pt, and demo.vocab.pt).
Now, if I re-call preprocess.py but with the extra arguments for existing source and target vocabularies (-src_vocab, and -tgt_vocab both pointing to the same file, demo.vocab.pt) I get the following error:
`python preprocess.py -train_src data/src-train.txt -train_tgt data/tgt-train.txt -valid_src data/src-val.txt -valid_tgt data/tgt-val.txt -save_data data/demo1 -shard_size 0 -src_vocab data/demo.vocab.pt -tgt_vocab data/demo.vocab.pt`

`2018-10-18 10:51:35,054 INFO Extracting features...`
`2018-10-18 10:51:35,056 INFO  * number of source features: 0.`
`2018-10-18 10:51:35,056 INFO  * number of target features: 0.`
`2018-10-18 10:51:35,056 INFO Building 'Fields' object...`
`2018-10-18 10:51:35,056 INFO Building & saving training data...`
`2018-10-18 10:51:35,829 INFO  * saving train dataset to data/demo1.train.pt.`
`2018-10-18 10:51:36,154 INFO Building & saving validation data...`
`2018-10-18 10:51:36,390 INFO  * saving valid dataset to data/demo1.valid.pt.`
`2018-10-18 10:51:36,472 INFO Building & saving vocabulary...`
`2018-10-18 10:51:36,472 INFO Loading source vocabulary from data/demo.vocab.pt`
`Traceback (most recent call last):`
 ` File "preprocess.py", line 235, in <module>`
 `  main()`
 ` File "preprocess.py", line 231, in main`
 `  build_save_vocab(train_dataset_files, fields, opt)`
 ` File "preprocess.py", line 197, in build_save_vocab`
 `   opt.tgt_words_min_frequency)`
 ` File "/Users/amin/NLP/projects/NMT/anmt/onmt/inputters/inputter.py", line 306, in build_vocab`
 `   src_vocab = load_vocabulary(src_vocab_path, tag="source")`
 ` File "/Users/amin/NLP/projects/NMT/anmt/onmt/inputters/inputter.py", line 393, in load_vocabulary`
  `  for line in f:`
 ` File "/Users/amin/anaconda3/lib/python3.6/codecs.py", line 321, in decode`
  `  (result, consumed) = self._buffer_decode(data, self.errors, final)`
` UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`

By looking at the code, I understood that in `preprocess.py` we save the vocabulary using `torch.save()` method which writes the file in the binary format, but then when reading the existing vocabularies (`inputter.py` line 389) we open them not in the binary format and then parse them line by line. So, I think this should be the source of the error.

Unfortunately, I am new with ONMT and don't have a clear idea about `torchtext` and how it stores the vocabularies. So, I couldn't get that much into the details. Any hint for solving the issue is appreciated.

**Comment by PersianNLPer** [comment]
I just realised that in the case of "adapting an existing model to a new domain" we don't need to modify the existing vocabulary, or even give some vocabularies with `-src_vocab` and `tgt_vocab` arguments. The only thing that is required is to prepare the new data (create `adap.train.pt` and `adapt.valid.pt`), make a copy of the original vocabulary (say `adapt.vocab.pt`) and continue the training using  the desired checkpoint!
Is it true or I am missing something in the process?
If so, may I ask you what is the reason behind introducing additional vocabularies with `-src_vocab` and `tgt_vocab` arguments?  

Thank you very much!
